Sensor de vibração MQTT - Trabalho de conclusão de curso: flash_l4.c File Reference
flash_l4.c File Reference
Management of the L4 internal flash memory.
#include "main.h"
#include "flash.h"
#include <string.h>
#include <stdbool.h>
Macros
#define ROUND_DOWN(a, b) (((a) / (b)) * (b))
#define MIN(a, b) (((a) < (b)) ? (a) : (b))
Functions
static int FLASH_get_pageInBank (uint32_t addr)
Get the page of a given address within its FLASH bank.
static uint32_t FLASH_Init (void)
Unlocks Flash for write access.
static int FLASH_write_at (uint32_t address, uint64_t *pData, uint32_t len_bytes)
Write to FLASH memory.
static int FLASH_unlock_erase (uint32_t address, uint32_t len_bytes)
Erase FLASH memory page(s) at address.
static uint32_t FLASH_get_bank (uint32_t addr)
Get the bank of a given address.
int FLASH_update (uint32_t dst_addr, const void *data, uint32_t size)
Update a chunk of the FLASH memory.
static uint32_t GetPage (uint32_t uAddr)
Gets the page of a given address.
static uint32_t GetBank (uint32_t uAddr)
Gets the bank of a given address.
uint32_t FLASH_Erase_Size (uint32_t uStart, uint32_t uLength)
This function erases bytes in user flash area.
uint32_t FLASH_Write (uint32_t uDestination, uint32_t *pSource, uint32_t uLength)
This function writes a data buffer in flash (data are 32-bit aligned).
Detailed Description
Management of the L4 internal flash memory.
Author
MCD Application Team
Attention
© Copyright (c) 2017 STMicroelectronics International N.V. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted, provided that the following conditions are met:
Redistribution of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of STMicroelectronics nor the names of other contributors to this software may be used to endorse or promote products derived from this software without specific written permission.
This software, including modifications and/or derivative works of this software, must execute solely and exclusively on microcontroller or microprocessor devices manufactured by or for STMicroelectronics.
Redistribution and use of this software other than as permitted under this license is void and will automatically terminate your rights under this license.
THIS SOFTWARE IS PROVIDED BY STMICROELECTRONICS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS, IMPLIED OR STATUTORY WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT OF THIRD PARTY INTELLECTUAL PROPERTY RIGHTS ARE DISCLAIMED TO THE FULLEST EXTENT PERMITTED BY LAW. IN NO EVENT SHALL STMICROELECTRONICS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Function Documentation
FLASH_Erase_Size()
uint32_t FLASH_Erase_Size (uint32_t uStart, uint32_t uLength)
This function erases bytes in user flash area.
Parameters
Start Start of user flash area
uLength number of bytes.
Return values
HAL status.
FLASH_get_bank()
uint32_t FLASH_get_bank (uint32_t addr) static
Get the bank of a given address.
Parameters
In addr Address in the FLASH Memory.
Return values
Bank identifier. FLASH_BANK_1 FLASH_BANK_2
Referenced by FLASH_unlock_erase().
FLASH_get_pageInBank()
static int FLASH_get_pageInBank (uint32_t addr) static
Get the page of a given address within its FLASH bank.
Parameters
In addr Address in the FLASH memory.
Return values
>=0 Success: Page number. <0 Failure: The address in not mapped in the internal FLASH memory.
References FLASH_BASE, and FLASH_SIZE.
Referenced by FLASH_unlock_erase().
FLASH_Init()
uint32_t FLASH_Init (void) static
Unlocks Flash for write access.
Parameters
None
Return values
HAL Status.
FLASH_unlock_erase()
int FLASH_unlock_erase (uint32_t address, uint32_t len_bytes) static
Erase FLASH memory page(s) at address.
Note
The range to erase shall not cross the bank boundary.
Parameters
In address Start address to erase from.
In len_bytes Length to be erased.
Return values
0 Success. -1: Failure.
References FLASH_EraseInitTypeDef::Banks, FLASH_get_bank(), FLASH_get_pageInBank(), FLASH_TYPEERASE_PAGES, FLASH_EraseInitTypeDef::NbPages, FLASH_EraseInitTypeDef::Page, and FLASH_EraseInitTypeDef::TypeErase.
FLASH_update()
int FLASH_update (uint32_t dst_addr, const void * data, uint32_t size)
Update a chunk of the FLASH memory.
Note
The FLASH chunk must no cross a FLASH bank boundary.
The source and destination buffers have no specific alignment constraints.
Parameters
In dst_addr Destination address in the FLASH memory.
In data Source address.
In size Number of bytes to update.
Return values
0 Success. <0: Failure.
Referenced by setIoTDeviceConfig().
FLASH_Write()
uint32_t FLASH_Write (uint32_t uDestination, uint32_t * pSource, uint32_t uLength)
This function writes a data buffer in flash (data are 32-bit aligned).
Note
After writing data buffer, the flash content is checked.
Parameters
uDestination Start address for target location
pSource pointer on buffer with data to write
uLength Length of data buffer in byte. It has to be 64-bit aligned.
Return values
uint32_t 0: Data successfully written to Flash memory 1: Error occurred while writing data in Flash memory 2: Written Data in flash memory is different from expected one
FLASH_write_at()
static int FLASH_write_at (uint32_t address, uint64_t * pData, uint32_t len_bytes) static
Write to FLASH memory.
Parameters
In address Destination address.
In pData Data to be programmed: Must be 8 byte aligned.
In len_bytes Number of bytes to be programmed.
Return values
0 Success. -1: Failure.
References __disable_irq().
GetBank()
static uint32_t GetBank (uint32_t uAddr) static
Gets the bank of a given address.
Parameters
uAddr Address of the FLASH Memory
Return values
The bank of a given address
GetPage()
static uint32_t GetPage (uint32_t uAddr) static
Gets the page of a given address.
Parameters
uAddr Address of the FLASH Memory
Return values
The page of a given address
References FLASH_BASE.