Sensor de vibração MQTT - Trabalho de conclusão de curso: /Inactivity_detection
/Inactivity_detection
BSP » Component » LSM6DSL
This section groups all the functions concerning activity/inactivity detection.
Functions
int32_t lsm6dsl_gy_sleep_mode_set (stmdev_ctx_t *ctx, uint8_t val)
Enables gyroscope Sleep mode.[set].
int32_t lsm6dsl_gy_sleep_mode_get (stmdev_ctx_t *ctx, uint8_t *val)
Enables gyroscope Sleep mode.[get].
int32_t lsm6dsl_act_mode_set (stmdev_ctx_t *ctx, lsm6dsl_inact_en_t val)
Enable inactivity function.[set].
int32_t lsm6dsl_act_mode_get (stmdev_ctx_t *ctx, lsm6dsl_inact_en_t *val)
Enable inactivity function.[get].
int32_t lsm6dsl_act_sleep_dur_set (stmdev_ctx_t *ctx, uint8_t val)
Duration to go in sleep mode.1 LSb = 512 / ODR[set].
int32_t lsm6dsl_act_sleep_dur_get (stmdev_ctx_t *ctx, uint8_t *val)
Duration to go in sleep mode. 1 LSb = 512 / ODR[get].
Detailed Description
This section groups all the functions concerning activity/inactivity detection.
Function Documentation
lsm6dsl_act_mode_get()
int32_t lsm6dsl_act_mode_get (stmdev_ctx_t * ctx, lsm6dsl_inact_en_t * val)
Enable inactivity function.[get].
Parameters
ctx Read / write interface definitions
val Get the values of inact_en in reg TAP_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_act_mode_set()
int32_t lsm6dsl_act_mode_set (stmdev_ctx_t * ctx, lsm6dsl_inact_en_t val)
Enable inactivity function.[set].
Parameters
ctx Read / write interface definitions
val Change the values of inact_en in reg TAP_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_act_sleep_dur_get()
int32_t lsm6dsl_act_sleep_dur_get (stmdev_ctx_t * ctx, uint8_t * val)
Duration to go in sleep mode. 1 LSb = 512 / ODR[get].
Parameters
ctx Read / write interface definitions
val Change the values of sleep_dur in reg WAKE_UP_DUR
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_act_sleep_dur_set()
int32_t lsm6dsl_act_sleep_dur_set (stmdev_ctx_t * ctx, uint8_t val)
Duration to go in sleep mode.1 LSb = 512 / ODR[set].
Parameters
ctx Read / write interface definitions
val Change the values of sleep_dur in reg WAKE_UP_DUR
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Set_Sleep_Duration().
lsm6dsl_gy_sleep_mode_get()
int32_t lsm6dsl_gy_sleep_mode_get (stmdev_ctx_t * ctx, uint8_t * val)
Enables gyroscope Sleep mode.[get].
Parameters
ctx Read / write interface definitions
val Change the values of sleep in reg CTRL4_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_gy_sleep_mode_set()
int32_t lsm6dsl_gy_sleep_mode_set (stmdev_ctx_t * ctx, uint8_t val)
Enables gyroscope Sleep mode.[set].
Parameters
ctx Read / write interface definitions
val Change the values of sleep in reg CTRL4_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().