Sensor de vibração MQTT - Trabalho de conclusão de curso: LSM6DSL_Wake_Up_event
LSM6DSL_Wake_Up_event
BSP » Component » LSM6DSL
This section groups all the functions that manage the Wake Up event generation.
Functions
int32_t lsm6dsl_wkup_threshold_set (stmdev_ctx_t *ctx, uint8_t val)
Threshold for wakeup.1 LSB = FS_XL / 64.[set].
int32_t lsm6dsl_wkup_threshold_get (stmdev_ctx_t *ctx, uint8_t *val)
Threshold for wakeup.1 LSB = FS_XL / 64.[get].
int32_t lsm6dsl_wkup_dur_set (stmdev_ctx_t *ctx, uint8_t val)
Wake up duration event.1LSb = 1 / ODR[set].
int32_t lsm6dsl_wkup_dur_get (stmdev_ctx_t *ctx, uint8_t *val)
Wake up duration event.1LSb = 1 / ODR[get].
Detailed Description
This section groups all the functions that manage the Wake Up event generation.
Function Documentation
lsm6dsl_wkup_dur_get()
int32_t lsm6dsl_wkup_dur_get (stmdev_ctx_t * ctx, uint8_t * val)
Wake up duration event.1LSb = 1 / ODR[get].
Parameters
ctx Read / write interface definitions
val Change the values of wake_dur in reg WAKE_UP_DUR
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_wkup_dur_set()
int32_t lsm6dsl_wkup_dur_set (stmdev_ctx_t * ctx, uint8_t val)
Wake up duration event.1LSb = 1 / ODR[set].
Parameters
ctx Read / write interface definitions
val Change the values of wake_dur in reg WAKE_UP_DUR
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Set_Wake_Up_Duration().
lsm6dsl_wkup_threshold_get()
int32_t lsm6dsl_wkup_threshold_get (stmdev_ctx_t * ctx, uint8_t * val)
Threshold for wakeup.1 LSB = FS_XL / 64.[get].
Parameters
ctx Read / write interface definitions
val Change the values of wk_ths in reg WAKE_UP_THS
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_wkup_threshold_set()
int32_t lsm6dsl_wkup_threshold_set (stmdev_ctx_t * ctx, uint8_t val)
Threshold for wakeup.1 LSB = FS_XL / 64.[set].
Parameters
ctx Read / write interface definitions
val Change the values of wk_ths in reg WAKE_UP_THS
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Set_Wake_Up_Threshold().