Sensor de vibração MQTT - Trabalho de conclusão de curso: LSM6DSL Private Functions
LSM6DSL Private Functions
BSP » Component » LSM6DSL
Functions
static int32_t LSM6DSL_ACC_SetOutputDataRate_When_Enabled (LSM6DSL_Object_t *pObj, float Odr)
Set the LSM6DSL accelerometer sensor output data rate when enabled.
static int32_t LSM6DSL_ACC_SetOutputDataRate_When_Disabled (LSM6DSL_Object_t *pObj, float Odr)
Set the LSM6DSL accelerometer sensor output data rate when disabled.
static int32_t LSM6DSL_GYRO_SetOutputDataRate_When_Enabled (LSM6DSL_Object_t *pObj, float Odr)
Set the LSM6DSL gyroscope sensor output data rate when enabled.
static int32_t LSM6DSL_GYRO_SetOutputDataRate_When_Disabled (LSM6DSL_Object_t *pObj, float Odr)
Set the LSM6DSL gyroscope sensor output data rate when disabled.
static int32_t ReadRegWrap (void *Handle, uint8_t Reg, uint8_t *pData, uint16_t Length)
Wrap Read register component function to Bus IO function.
static int32_t WriteRegWrap (void *Handle, uint8_t Reg, uint8_t *pData, uint16_t Length)
Wrap Write register component function to Bus IO function.
Detailed Description
Function Documentation
LSM6DSL_ACC_SetOutputDataRate_When_Disabled()
static int32_t LSM6DSL_ACC_SetOutputDataRate_When_Disabled (LSM6DSL_Object_t * pObj, float Odr) static
Set the LSM6DSL accelerometer sensor output data rate when disabled.
Parameters
pObj the device pObj
Odr the functional output data rate to be set
Return values
0 in case of success, an error code otherwise
Referenced by LSM6DSL_ACC_SetOutputDataRate().
LSM6DSL_ACC_SetOutputDataRate_When_Enabled()
static int32_t LSM6DSL_ACC_SetOutputDataRate_When_Enabled (LSM6DSL_Object_t * pObj, float Odr) static
Set the LSM6DSL accelerometer sensor output data rate when enabled.
Parameters
pObj the device pObj
Odr the functional output data rate to be set
Return values
0 in case of success, an error code otherwise
Referenced by LSM6DSL_ACC_SetOutputDataRate().
LSM6DSL_GYRO_SetOutputDataRate_When_Disabled()
static int32_t LSM6DSL_GYRO_SetOutputDataRate_When_Disabled (LSM6DSL_Object_t * pObj, float Odr) static
Set the LSM6DSL gyroscope sensor output data rate when disabled.
Parameters
pObj the device pObj
Odr the functional output data rate to be set
Return values
0 in case of success, an error code otherwise
Referenced by LSM6DSL_GYRO_SetOutputDataRate().
LSM6DSL_GYRO_SetOutputDataRate_When_Enabled()
static int32_t LSM6DSL_GYRO_SetOutputDataRate_When_Enabled (LSM6DSL_Object_t * pObj, float Odr) static
Set the LSM6DSL gyroscope sensor output data rate when enabled.
Parameters
pObj the device pObj
Odr the functional output data rate to be set
Return values
0 in case of success, an error code otherwise
Referenced by LSM6DSL_GYRO_SetOutputDataRate().
ReadRegWrap()
static int32_t ReadRegWrap (void * Handle, uint8_t Reg, uint8_t * pData, uint16_t Length) static
Wrap Read register component function to Bus IO function.
Parameters
Handle the device handler
Reg the register address
pData the stored data pointer
Length the length
Return values
0 in case of success, an error code otherwise
WriteRegWrap()
static int32_t WriteRegWrap (void * Handle, uint8_t Reg, uint8_t * pData, uint16_t Length) static
Wrap Write register component function to Bus IO function.
Parameters
Handle the device handler
Reg the register address
pData the stored data pointer
Length the length
Return values
0 in case of success, an error code otherwise