Sensor de vibração MQTT - Trabalho de conclusão de curso: LSM6DSL_interfaces_functions
LSM6DSL_interfaces_functions
BSP » Component » LSM6DSL
This section provide a set of functions used to read and write a generic register of the device. MANDATORY: return 0 -> no Error.
Functions
int32_t lsm6dsl_read_reg (stmdev_ctx_t *ctx, uint8_t reg, uint8_t *data, uint16_t len)
Read generic device register.
int32_t lsm6dsl_write_reg (stmdev_ctx_t *ctx, uint8_t reg, uint8_t *data, uint16_t len)
Write generic device register.
Detailed Description
This section provide a set of functions used to read and write a generic register of the device. MANDATORY: return 0 -> no Error.
Function Documentation
lsm6dsl_read_reg()
int32_t lsm6dsl_read_reg (stmdev_ctx_t * ctx, uint8_t reg, uint8_t * data, uint16_t len)
Read generic device register.
Parameters
ctx read / write interface definitions(ptr)
reg register to read
data pointer to buffer that store the data read(ptr)
len number of consecutive register to read
Return values
interface status (MANDATORY: return 0 -> no Error)
References stmdev_ctx_t::handle.
Referenced by lsm6dsl_4d_mode_get(), lsm6dsl_4d_mode_set(), lsm6dsl_6d_feed_data_get(), lsm6dsl_6d_feed_data_set(), lsm6dsl_6d_threshold_get(), lsm6dsl_6d_threshold_set(), LSM6DSL_ACC_Get_6D_Orientation_XH(), LSM6DSL_ACC_Get_6D_Orientation_XL(), LSM6DSL_ACC_Get_6D_Orientation_YH(), LSM6DSL_ACC_Get_6D_Orientation_YL(), LSM6DSL_ACC_Get_6D_Orientation_ZH(), LSM6DSL_ACC_Get_6D_Orientation_ZL(), LSM6DSL_ACC_Get_Event_Status(), LSM6DSL_ACC_Get_Step_Count(), lsm6dsl_acceleration_raw_get(), lsm6dsl_act_mode_get(), lsm6dsl_act_mode_set(), lsm6dsl_act_sleep_dur_get(), lsm6dsl_act_sleep_dur_set(), lsm6dsl_all_on_int1_get(), lsm6dsl_all_on_int1_set(), lsm6dsl_all_sources_get(), lsm6dsl_angular_rate_raw_get(), lsm6dsl_auto_increment_get(), lsm6dsl_auto_increment_set(), lsm6dsl_block_data_update_get(), lsm6dsl_block_data_update_set(), lsm6dsl_boot_get(), lsm6dsl_boot_set(), lsm6dsl_data_format_get(), lsm6dsl_data_format_set(), lsm6dsl_data_ready_mode_get(), lsm6dsl_data_ready_mode_set(), lsm6dsl_den_enable_get(), lsm6dsl_den_enable_set(), lsm6dsl_den_mark_axis_x_get(), lsm6dsl_den_mark_axis_x_set(), lsm6dsl_den_mark_axis_y_get(), lsm6dsl_den_mark_axis_y_set(), lsm6dsl_den_mark_axis_z_get(), lsm6dsl_den_mark_axis_z_set(), lsm6dsl_den_mode_get(), lsm6dsl_den_mode_set(), lsm6dsl_den_polarity_get(), lsm6dsl_den_polarity_set(), lsm6dsl_device_id_get(), lsm6dsl_ff_dur_get(), lsm6dsl_ff_dur_set(), lsm6dsl_ff_threshold_get(), lsm6dsl_ff_threshold_set(), lsm6dsl_fifo_data_level_get(), lsm6dsl_fifo_data_rate_get(), lsm6dsl_fifo_data_rate_set(), lsm6dsl_fifo_dataset_3_batch_get(), lsm6dsl_fifo_dataset_3_batch_set(), lsm6dsl_fifo_dataset_4_batch_get(), lsm6dsl_fifo_dataset_4_batch_set(), LSM6DSL_FIFO_Get_Data(), LSM6DSL_FIFO_Get_Full_Status(), lsm6dsl_fifo_gy_batch_get(), lsm6dsl_fifo_gy_batch_set(), lsm6dsl_fifo_mode_get(), lsm6dsl_fifo_mode_set(), lsm6dsl_fifo_pattern_get(), lsm6dsl_fifo_pedo_and_timestamp_batch_get(), lsm6dsl_fifo_pedo_and_timestamp_batch_set(), lsm6dsl_fifo_raw_data_get(), LSM6DSL_FIFO_Set_INT1_FIFO_Full(), lsm6dsl_fifo_stop_on_wtm_get(), lsm6dsl_fifo_stop_on_wtm_set(), lsm6dsl_fifo_temp_batch_get(), lsm6dsl_fifo_temp_batch_set(), lsm6dsl_fifo_watermark_get(), lsm6dsl_fifo_watermark_set(), lsm6dsl_fifo_write_trigger_get(), lsm6dsl_fifo_write_trigger_set(), lsm6dsl_fifo_wtm_flag_get(), lsm6dsl_fifo_xl_batch_get(), lsm6dsl_fifo_xl_batch_set(), lsm6dsl_fifo_xl_gy_8bit_format_get(), lsm6dsl_fifo_xl_gy_8bit_format_set(), lsm6dsl_filter_settling_mask_get(), lsm6dsl_filter_settling_mask_set(), lsm6dsl_func_en_set(), lsm6dsl_gy_band_pass_get(), lsm6dsl_gy_band_pass_set(), lsm6dsl_gy_data_rate_get(), lsm6dsl_gy_data_rate_set(), lsm6dsl_gy_flag_data_ready_get(), lsm6dsl_gy_full_scale_get(), lsm6dsl_gy_full_scale_set(), lsm6dsl_gy_power_mode_get(), lsm6dsl_gy_power_mode_set(), lsm6dsl_gy_self_test_get(), lsm6dsl_gy_self_test_set(), lsm6dsl_gy_sleep_mode_get(), lsm6dsl_gy_sleep_mode_set(), lsm6dsl_i2c_interface_get(), lsm6dsl_i2c_interface_set(), lsm6dsl_int_notification_get(), lsm6dsl_int_notification_set(), lsm6dsl_mag_calibrated_raw_get(), lsm6dsl_mag_hard_iron_get(), lsm6dsl_mag_hard_iron_set(), lsm6dsl_mag_soft_iron_get(), lsm6dsl_mag_soft_iron_set(), lsm6dsl_mem_bank_get(), lsm6dsl_mem_bank_set(), lsm6dsl_motion_sens_get(), lsm6dsl_motion_sens_set(), lsm6dsl_pedo_sens_get(), lsm6dsl_pedo_sens_set(), lsm6dsl_pedo_step_reset_get(), lsm6dsl_pedo_step_reset_set(), lsm6dsl_pin_int1_route_get(), lsm6dsl_pin_int1_route_set(), lsm6dsl_pin_int2_route_get(), lsm6dsl_pin_int2_route_set(), lsm6dsl_pin_mode_get(), lsm6dsl_pin_mode_set(), lsm6dsl_pin_polarity_get(), lsm6dsl_pin_polarity_set(), LSM6DSL_Read_Reg(), lsm6dsl_reset_get(), lsm6dsl_reset_set(), lsm6dsl_rounding_mode_get(), lsm6dsl_rounding_mode_set(), lsm6dsl_rounding_on_status_get(), lsm6dsl_rounding_on_status_set(), lsm6dsl_sh_cmd_sens_sync_get(), lsm6dsl_sh_cmd_sens_sync_set(), lsm6dsl_sh_drdy_on_int1_get(), lsm6dsl_sh_drdy_on_int1_set(), lsm6dsl_sh_master_get(), lsm6dsl_sh_master_set(), lsm6dsl_sh_pass_through_get(), lsm6dsl_sh_pass_through_set(), lsm6dsl_sh_pin_mode_get(), lsm6dsl_sh_pin_mode_set(), lsm6dsl_sh_read_data_raw_get(), lsm6dsl_sh_spi_sync_error_get(), lsm6dsl_sh_spi_sync_error_set(), lsm6dsl_sh_sync_sens_frame_get(), lsm6dsl_sh_sync_sens_frame_set(), lsm6dsl_sh_sync_sens_ratio_get(), lsm6dsl_sh_sync_sens_ratio_set(), lsm6dsl_sh_syncro_mode_get(), lsm6dsl_sh_syncro_mode_set(), lsm6dsl_spi_mode_get(), lsm6dsl_spi_mode_set(), lsm6dsl_status_reg_get(), lsm6dsl_tap_detection_on_x_get(), lsm6dsl_tap_detection_on_x_set(), lsm6dsl_tap_detection_on_y_get(), lsm6dsl_tap_detection_on_y_set(), lsm6dsl_tap_detection_on_z_get(), lsm6dsl_tap_detection_on_z_set(), lsm6dsl_tap_dur_get(), lsm6dsl_tap_dur_set(), lsm6dsl_tap_mode_get(), lsm6dsl_tap_mode_set(), lsm6dsl_tap_quiet_get(), lsm6dsl_tap_quiet_set(), lsm6dsl_tap_shock_get(), lsm6dsl_tap_shock_set(), lsm6dsl_tap_src_get(), lsm6dsl_tap_threshold_x_get(), lsm6dsl_tap_threshold_x_set(), lsm6dsl_temp_flag_data_ready_get(), lsm6dsl_temperature_raw_get(), lsm6dsl_tilt_sens_get(), lsm6dsl_tilt_sens_set(), lsm6dsl_timestamp_get(), lsm6dsl_timestamp_res_get(), lsm6dsl_timestamp_res_set(), lsm6dsl_timestamp_set(), lsm6dsl_wkup_dur_get(), lsm6dsl_wkup_dur_set(), lsm6dsl_wkup_threshold_get(), lsm6dsl_wkup_threshold_set(), lsm6dsl_wrist_tilt_sens_get(), lsm6dsl_wrist_tilt_sens_set(), lsm6dsl_xl_data_rate_get(), lsm6dsl_xl_data_rate_set(), lsm6dsl_xl_filter_analog_get(), lsm6dsl_xl_filter_analog_set(), lsm6dsl_xl_flag_data_ready_get(), lsm6dsl_xl_full_scale_get(), lsm6dsl_xl_full_scale_set(), lsm6dsl_xl_hp_bandwidth_get(), lsm6dsl_xl_hp_bandwidth_set(), lsm6dsl_xl_hp_path_internal_get(), lsm6dsl_xl_hp_path_internal_set(), lsm6dsl_xl_lp1_bandwidth_get(), lsm6dsl_xl_lp1_bandwidth_set(), lsm6dsl_xl_lp2_bandwidth_get(), lsm6dsl_xl_lp2_bandwidth_set(), lsm6dsl_xl_offset_weight_get(), lsm6dsl_xl_offset_weight_set(), lsm6dsl_xl_power_mode_get(), lsm6dsl_xl_power_mode_set(), lsm6dsl_xl_reference_mode_get(), lsm6dsl_xl_reference_mode_set(), lsm6dsl_xl_self_test_get(), lsm6dsl_xl_self_test_set(), and lsm6dsl_xl_usr_offset_get().
lsm6dsl_write_reg()
int32_t lsm6dsl_write_reg (stmdev_ctx_t * ctx, uint8_t reg, uint8_t * data, uint16_t len)
Write generic device register.
Parameters
ctx read / write interface definitions(ptr)
reg register to write
data pointer to data to write in register reg(ptr)
len number of consecutive register to write
Return values
interface status (MANDATORY: return 0 -> no Error)
References stmdev_ctx_t::handle, and stmdev_ctx_t::write_reg.
Referenced by LSM6DSL_Write_Reg(), and lsm6dsl_xl_usr_offset_set().