Sensor de vibração MQTT - Trabalho de conclusão de curso: LSM6DSL_serial_interface
LSM6DSL_serial_interface
BSP » Component » LSM6DSL
This section groups all the functions concerning serial interface management.
Functions
int32_t lsm6dsl_spi_mode_set (stmdev_ctx_t *ctx, lsm6dsl_sim_t val)
SPI Serial Interface Mode selection.[set].
int32_t lsm6dsl_spi_mode_get (stmdev_ctx_t *ctx, lsm6dsl_sim_t *val)
SPI Serial Interface Mode selection.[get].
int32_t lsm6dsl_i2c_interface_set (stmdev_ctx_t *ctx, lsm6dsl_i2c_disable_t val)
Disable / Enable I2C interface.[set].
int32_t lsm6dsl_i2c_interface_get (stmdev_ctx_t *ctx, lsm6dsl_i2c_disable_t *val)
Disable / Enable I2C interface.[get].
Detailed Description
This section groups all the functions concerning serial interface management.
Function Documentation
lsm6dsl_i2c_interface_get()
int32_t lsm6dsl_i2c_interface_get (stmdev_ctx_t * ctx, lsm6dsl_i2c_disable_t * val)
Disable / Enable I2C interface.[get].
Parameters
ctx Read / write interface definitions
val Get the values of i2c_disable in reg CTRL4_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_i2c_interface_set()
int32_t lsm6dsl_i2c_interface_set (stmdev_ctx_t * ctx, lsm6dsl_i2c_disable_t val)
Disable / Enable I2C interface.[set].
Parameters
ctx Read / write interface definitions
val Change the values of i2c_disable in reg CTRL4_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_spi_mode_get()
int32_t lsm6dsl_spi_mode_get (stmdev_ctx_t * ctx, lsm6dsl_sim_t * val)
SPI Serial Interface Mode selection.[get].
Parameters
ctx Read / write interface definitions
val Get the values of sim in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_spi_mode_set()
int32_t lsm6dsl_spi_mode_set (stmdev_ctx_t * ctx, lsm6dsl_sim_t val)
SPI Serial Interface Mode selection.[set].
Parameters
ctx Read / write interface definitions
val Change the values of sim in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().