Sensor de vibração MQTT - Trabalho de conclusão de curso: LSM6DSL_data_generation
LSM6DSL_data_generation
BSP » Component » LSM6DSL
This section groups all the functions concerning data generation.
Functions
int32_t lsm6dsl_xl_full_scale_set (stmdev_ctx_t *ctx, lsm6dsl_fs_xl_t val)
Accelerometer full-scale selection.[set].
int32_t lsm6dsl_xl_full_scale_get (stmdev_ctx_t *ctx, lsm6dsl_fs_xl_t *val)
Accelerometer full-scale selection.[get].
int32_t lsm6dsl_xl_data_rate_set (stmdev_ctx_t *ctx, lsm6dsl_odr_xl_t val)
Accelerometer data rate selection.[set].
int32_t lsm6dsl_xl_data_rate_get (stmdev_ctx_t *ctx, lsm6dsl_odr_xl_t *val)
Accelerometer data rate selection.[get].
int32_t lsm6dsl_gy_full_scale_set (stmdev_ctx_t *ctx, lsm6dsl_fs_g_t val)
Gyroscope chain full-scale selection.[set].
int32_t lsm6dsl_gy_full_scale_get (stmdev_ctx_t *ctx, lsm6dsl_fs_g_t *val)
Gyroscope chain full-scale selection.[get].
int32_t lsm6dsl_gy_data_rate_set (stmdev_ctx_t *ctx, lsm6dsl_odr_g_t val)
Gyroscope data rate selection.[set].
int32_t lsm6dsl_gy_data_rate_get (stmdev_ctx_t *ctx, lsm6dsl_odr_g_t *val)
Gyroscope data rate selection.[get].
int32_t lsm6dsl_block_data_update_set (stmdev_ctx_t *ctx, uint8_t val)
Block data update.[set].
int32_t lsm6dsl_block_data_update_get (stmdev_ctx_t *ctx, uint8_t *val)
Block data update.[get].
int32_t lsm6dsl_xl_offset_weight_set (stmdev_ctx_t *ctx, lsm6dsl_usr_off_w_t val)
Weight of XL user offset bits of registers X_OFS_USR(73h), Y_OFS_USR(74h), Z_OFS_USR(75h).[set].
int32_t lsm6dsl_xl_offset_weight_get (stmdev_ctx_t *ctx, lsm6dsl_usr_off_w_t *val)
Weight of XL user offset bits of registers X_OFS_USR(73h), Y_OFS_USR(74h), Z_OFS_USR(75h).[get].
int32_t lsm6dsl_xl_power_mode_set (stmdev_ctx_t *ctx, lsm6dsl_xl_hm_mode_t val)
High-performance operating mode for accelerometer[set].
int32_t lsm6dsl_xl_power_mode_get (stmdev_ctx_t *ctx, lsm6dsl_xl_hm_mode_t *val)
High-performance operating mode for accelerometer.[get].
int32_t lsm6dsl_rounding_on_status_set (stmdev_ctx_t *ctx, lsm6dsl_rounding_status_t val)
Source register rounding function on WAKE_UP_SRC (1Bh), TAP_SRC (1Ch), D6D_SRC (1Dh), STATUS_REG (1Eh) and FUNC_SRC1 (53h) registers in the primary interface.[set].
int32_t lsm6dsl_rounding_on_status_get (stmdev_ctx_t *ctx, lsm6dsl_rounding_status_t *val)
Source register rounding function on WAKE_UP_SRC (1Bh), TAP_SRC (1Ch), D6D_SRC (1Dh), STATUS_REG (1Eh) and FUNC_SRC1 (53h) registers in the primary interface.[get].
int32_t lsm6dsl_gy_power_mode_set (stmdev_ctx_t *ctx, lsm6dsl_g_hm_mode_t val)
High-performance operating mode disable for gyroscope.[set].
int32_t lsm6dsl_gy_power_mode_get (stmdev_ctx_t *ctx, lsm6dsl_g_hm_mode_t *val)
High-performance operating mode disable for gyroscope.[get].
int32_t lsm6dsl_all_sources_get (stmdev_ctx_t *ctx, lsm6dsl_all_sources_t *val)
Read all the interrupt/status flag of the device.[get].
int32_t lsm6dsl_status_reg_get (stmdev_ctx_t *ctx, lsm6dsl_status_reg_t *val)
The STATUS_REG register is read by the primary interface[get].
int32_t lsm6dsl_xl_flag_data_ready_get (stmdev_ctx_t *ctx, uint8_t *val)
Accelerometer new data available.[get].
int32_t lsm6dsl_gy_flag_data_ready_get (stmdev_ctx_t *ctx, uint8_t *val)
Gyroscope new data available.[get].
int32_t lsm6dsl_temp_flag_data_ready_get (stmdev_ctx_t *ctx, uint8_t *val)
Temperature new data available.[get].
int32_t lsm6dsl_xl_usr_offset_set (stmdev_ctx_t *ctx, uint8_t *buff)
Accelerometer axis user offset correction expressed in two’s complement, weight depends on USR_OFF_W in CTRL6_C. The value must be in the range [-127 127].[set].
int32_t lsm6dsl_xl_usr_offset_get (stmdev_ctx_t *ctx, uint8_t *buff)
Accelerometer axis user offset correction xpressed in two’s complement, weight depends on USR_OFF_W in CTRL6_C. The value must be in the range [-127 127].[get].
Detailed Description
This section groups all the functions concerning data generation.
Function Documentation
lsm6dsl_all_sources_get()
int32_t lsm6dsl_all_sources_get (stmdev_ctx_t * ctx, lsm6dsl_all_sources_t * val)
Read all the interrupt/status flag of the device.[get].
Parameters
ctx Read / write interface definitions
val WAKE_UP_SRC, TAP_SRC, D6D_SRC, STATUS_REG, FUNC_SRC1, FUNC_SRC2, WRIST_TILT_IA, A_WRIST_TILT_Mask
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_block_data_update_get()
int32_t lsm6dsl_block_data_update_get (stmdev_ctx_t * ctx, uint8_t * val)
Block data update.[get].
Parameters
ctx Read / write interface definitions
val Change the values of bdu in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_block_data_update_set()
int32_t lsm6dsl_block_data_update_set (stmdev_ctx_t * ctx, uint8_t val)
Block data update.[set].
Parameters
ctx Read / write interface definitions
val Change the values of bdu in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_gy_data_rate_get()
int32_t lsm6dsl_gy_data_rate_get (stmdev_ctx_t * ctx, lsm6dsl_odr_g_t * val)
Gyroscope data rate selection.[get].
Parameters
ctx Read / write interface definitions
val Get the values of odr_g in reg CTRL2_G
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_gy_data_rate_set()
int32_t lsm6dsl_gy_data_rate_set (stmdev_ctx_t * ctx, lsm6dsl_odr_g_t val)
Gyroscope data rate selection.[set].
Parameters
ctx Read / write interface definitions
val Change the values of odr_g in reg CTRL2_G
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_gy_flag_data_ready_get()
int32_t lsm6dsl_gy_flag_data_ready_get (stmdev_ctx_t * ctx, uint8_t * val)
Gyroscope new data available.[get].
Parameters
ctx Read / write interface definitions
val Change the values of gda in reg STATUS_REG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_GYRO_Get_DRDY_Status().
lsm6dsl_gy_full_scale_get()
int32_t lsm6dsl_gy_full_scale_get (stmdev_ctx_t * ctx, lsm6dsl_fs_g_t * val)
Gyroscope chain full-scale selection.[get].
Parameters
ctx Read / write interface definitions
val Get the values of fs_g in reg CTRL2_G
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_gy_full_scale_set()
int32_t lsm6dsl_gy_full_scale_set (stmdev_ctx_t * ctx, lsm6dsl_fs_g_t val)
Gyroscope chain full-scale selection.[set].
Parameters
ctx Read / write interface definitions
val Change the values of fs_g in reg CTRL2_G
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_gy_power_mode_get()
int32_t lsm6dsl_gy_power_mode_get (stmdev_ctx_t * ctx, lsm6dsl_g_hm_mode_t * val)
High-performance operating mode disable for gyroscope.[get].
Parameters
ctx Read / write interface definitions
val Get the values of g_hm_mode in reg CTRL7_G
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_gy_power_mode_set()
int32_t lsm6dsl_gy_power_mode_set (stmdev_ctx_t * ctx, lsm6dsl_g_hm_mode_t val)
High-performance operating mode disable for gyroscope.[set].
Parameters
ctx Read / write interface definitions
val Change the values of g_hm_mode in reg CTRL7_G
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_rounding_on_status_get()
int32_t lsm6dsl_rounding_on_status_get (stmdev_ctx_t * ctx, lsm6dsl_rounding_status_t * val)
Source register rounding function on WAKE_UP_SRC (1Bh), TAP_SRC (1Ch), D6D_SRC (1Dh), STATUS_REG (1Eh) and FUNC_SRC1 (53h) registers in the primary interface.[get].
Parameters
ctx Read / write interface definitions
val Get the values of rounding_status in reg CTRL7_G
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_rounding_on_status_set()
int32_t lsm6dsl_rounding_on_status_set (stmdev_ctx_t * ctx, lsm6dsl_rounding_status_t val)
Source register rounding function on WAKE_UP_SRC (1Bh), TAP_SRC (1Ch), D6D_SRC (1Dh), STATUS_REG (1Eh) and FUNC_SRC1 (53h) registers in the primary interface.[set].
Parameters
ctx Read / write interface definitions
val Change the values of rounding_status in reg CTRL7_G
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_status_reg_get()
int32_t lsm6dsl_status_reg_get (stmdev_ctx_t * ctx, lsm6dsl_status_reg_t * val)
The STATUS_REG register is read by the primary interface[get].
Parameters
ctx Read / write interface definitions
val Registers STATUS_REG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_temp_flag_data_ready_get()
int32_t lsm6dsl_temp_flag_data_ready_get (stmdev_ctx_t * ctx, uint8_t * val)
Temperature new data available.[get].
Parameters
ctx Read / write interface definitions
val Change the values of tda in reg STATUS_REG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_data_rate_get()
int32_t lsm6dsl_xl_data_rate_get (stmdev_ctx_t * ctx, lsm6dsl_odr_xl_t * val)
Accelerometer data rate selection.[get].
Parameters
ctx Read / write interface definitions
val Get the values of odr_xl in reg CTRL1_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_data_rate_set()
int32_t lsm6dsl_xl_data_rate_set (stmdev_ctx_t * ctx, lsm6dsl_odr_xl_t val)
Accelerometer data rate selection.[set].
Parameters
ctx Read / write interface definitions
val Change the values of odr_xl in reg CTRL1_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_flag_data_ready_get()
int32_t lsm6dsl_xl_flag_data_ready_get (stmdev_ctx_t * ctx, uint8_t * val)
Accelerometer new data available.[get].
Parameters
ctx Read / write interface definitions
val Change the values of xlda in reg STATUS_REG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Get_DRDY_Status().
lsm6dsl_xl_full_scale_get()
int32_t lsm6dsl_xl_full_scale_get (stmdev_ctx_t * ctx, lsm6dsl_fs_xl_t * val)
Accelerometer full-scale selection.[get].
Parameters
ctx Read / write interface definitions
val Get the values of fs_xl in reg CTRL1_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_full_scale_set()
int32_t lsm6dsl_xl_full_scale_set (stmdev_ctx_t * ctx, lsm6dsl_fs_xl_t val)
Accelerometer full-scale selection.[set].
Parameters
ctx Read / write interface definitions
val Change the values of fs_xl in reg CTRL1_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_offset_weight_get()
int32_t lsm6dsl_xl_offset_weight_get (stmdev_ctx_t * ctx, lsm6dsl_usr_off_w_t * val)
Weight of XL user offset bits of registers X_OFS_USR(73h), Y_OFS_USR(74h), Z_OFS_USR(75h).[get].
Parameters
ctx Read / write interface definitions
val Get the values of usr_off_w in reg CTRL6_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_offset_weight_set()
int32_t lsm6dsl_xl_offset_weight_set (stmdev_ctx_t * ctx, lsm6dsl_usr_off_w_t val)
Weight of XL user offset bits of registers X_OFS_USR(73h), Y_OFS_USR(74h), Z_OFS_USR(75h).[set].
Parameters
ctx Read / write interface definitions
val Change the values of usr_off_w in reg CTRL6_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_power_mode_get()
int32_t lsm6dsl_xl_power_mode_get (stmdev_ctx_t * ctx, lsm6dsl_xl_hm_mode_t * val)
High-performance operating mode for accelerometer.[get].
Parameters
ctx Read / write interface definitions
val Get the values of xl_hm_mode in reg CTRL6_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_power_mode_set()
int32_t lsm6dsl_xl_power_mode_set (stmdev_ctx_t * ctx, lsm6dsl_xl_hm_mode_t val)
High-performance operating mode for accelerometer[set].
Parameters
ctx Read / write interface definitions
val Change the values of xl_hm_mode in reg CTRL6_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_usr_offset_get()
int32_t lsm6dsl_xl_usr_offset_get (stmdev_ctx_t * ctx, uint8_t * buff)
Accelerometer axis user offset correction xpressed in two’s complement, weight depends on USR_OFF_W in CTRL6_C. The value must be in the range [-127 127].[get].
Parameters
ctx Read / write interface definitions
buff Buffer that stores data read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_usr_offset_set()
int32_t lsm6dsl_xl_usr_offset_set (stmdev_ctx_t * ctx, uint8_t * buff)
Accelerometer axis user offset correction expressed in two’s complement, weight depends on USR_OFF_W in CTRL6_C. The value must be in the range [-127 127].[set].
Parameters
ctx Read / write interface definitions
buff Buffer that contains data to write
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_write_reg().