Sensor de vibração MQTT - Trabalho de conclusão de curso: LSM6DSL_tap_generator
LSM6DSL_tap_generator
BSP » Component » LSM6DSL
This section groups all the functions that manage the tap and double tap event generation.
Functions
int32_t lsm6dsl_tap_src_get (stmdev_ctx_t *ctx, lsm6dsl_tap_src_t *val)
Read the tap / double tap source register.[get].
int32_t lsm6dsl_tap_detection_on_z_set (stmdev_ctx_t *ctx, uint8_t val)
Enable Z direction in tap recognition.[set].
int32_t lsm6dsl_tap_detection_on_z_get (stmdev_ctx_t *ctx, uint8_t *val)
Enable Z direction in tap recognition.[get].
int32_t lsm6dsl_tap_detection_on_y_set (stmdev_ctx_t *ctx, uint8_t val)
Enable Y direction in tap recognition.[set].
int32_t lsm6dsl_tap_detection_on_y_get (stmdev_ctx_t *ctx, uint8_t *val)
Enable Y direction in tap recognition.[get].
int32_t lsm6dsl_tap_detection_on_x_set (stmdev_ctx_t *ctx, uint8_t val)
Enable X direction in tap recognition.[set].
int32_t lsm6dsl_tap_detection_on_x_get (stmdev_ctx_t *ctx, uint8_t *val)
Enable X direction in tap recognition.[get].
int32_t lsm6dsl_tap_threshold_x_set (stmdev_ctx_t *ctx, uint8_t val)
Threshold for tap recognition.[set].
int32_t lsm6dsl_tap_threshold_x_get (stmdev_ctx_t *ctx, uint8_t *val)
Threshold for tap recognition.[get].
int32_t lsm6dsl_tap_shock_set (stmdev_ctx_t *ctx, uint8_t val)
Maximum duration is the maximum time of an overthreshold signal detection to be recognized as a tap event. The default value of these bits is 00b which corresponds to 4*ODR_XL time. If the SHOCK[1:0] bits are set to a different value, 1LSB corresponds to 8*ODR_XL time.[set].
int32_t lsm6dsl_tap_shock_get (stmdev_ctx_t *ctx, uint8_t *val)
Maximum duration is the maximum time of an overthreshold signal detection to be recognized as a tap event. The default value of these bits is 00b which corresponds to 4*ODR_XL time. If the SHOCK[1:0] bits are set to a different value, 1LSB corresponds to 8*ODR_XL time.[get].
int32_t lsm6dsl_tap_quiet_set (stmdev_ctx_t *ctx, uint8_t val)
Quiet time is the time after the first detected tap in which there must not be any overthreshold event. The default value of these bits is 00b which corresponds to 2*ODR_XL time. If the QUIET[1:0] bits are set to a different value, 1LSB corresponds to 4*ODR_XL time.[set].
int32_t lsm6dsl_tap_quiet_get (stmdev_ctx_t *ctx, uint8_t *val)
Quiet time is the time after the first detected tap in which there must not be any overthreshold event. The default value of these bits is 00b which corresponds to 2*ODR_XL time. If the QUIET[1:0] bits are set to a different value, 1LSB corresponds to 4*ODR_XL time.[get].
int32_t lsm6dsl_tap_dur_set (stmdev_ctx_t *ctx, uint8_t val)
When double tap recognition is enabled, this register expresses the maximum time between two consecutive detected taps to determine a double tap event. The default value of these bits is 0000b which corresponds to 16*ODR_XL time. If the DUR[3:0] bits are set to a different value,1LSB corresponds to 32*ODR_XL time.[set].
int32_t lsm6dsl_tap_dur_get (stmdev_ctx_t *ctx, uint8_t *val)
When double tap recognition is enabled, this register expresses the maximum time between two consecutive detected taps to determine a double tap event. The default value of these bits is 0000b which corresponds to 16*ODR_XL time. If the DUR[3:0] bits are set to a different value,1LSB corresponds to 32*ODR_XL time.[get].
int32_t lsm6dsl_tap_mode_set (stmdev_ctx_t *ctx, lsm6dsl_single_double_tap_t val)
Single/double-tap event enable/disable.[set].
int32_t lsm6dsl_tap_mode_get (stmdev_ctx_t *ctx, lsm6dsl_single_double_tap_t *val)
Single/double-tap event enable/disable.[get].
Detailed Description
This section groups all the functions that manage the tap and double tap event generation.
Function Documentation
lsm6dsl_tap_detection_on_x_get()
int32_t lsm6dsl_tap_detection_on_x_get (stmdev_ctx_t * ctx, uint8_t * val)
Enable X direction in tap recognition.[get].
Parameters
ctx Read / write interface definitions
val Change the values of tap_x_en in reg TAP_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_detection_on_x_set()
int32_t lsm6dsl_tap_detection_on_x_set (stmdev_ctx_t * ctx, uint8_t val)
Enable X direction in tap recognition.[set].
Parameters
ctx Read / write interface definitions
val Change the values of tap_x_en in reg TAP_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_detection_on_y_get()
int32_t lsm6dsl_tap_detection_on_y_get (stmdev_ctx_t * ctx, uint8_t * val)
Enable Y direction in tap recognition.[get].
Parameters
ctx Read / write interface definitions
val Change the values of tap_y_en in reg TAP_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_detection_on_y_set()
int32_t lsm6dsl_tap_detection_on_y_set (stmdev_ctx_t * ctx, uint8_t val)
Enable Y direction in tap recognition.[set].
Parameters
ctx Read / write interface definitions
val Change the values of tap_y_en in reg TAP_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_detection_on_z_get()
int32_t lsm6dsl_tap_detection_on_z_get (stmdev_ctx_t * ctx, uint8_t * val)
Enable Z direction in tap recognition.[get].
Parameters
ctx Read / write interface definitions
val Change the values of tap_z_en in reg TAP_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_detection_on_z_set()
int32_t lsm6dsl_tap_detection_on_z_set (stmdev_ctx_t * ctx, uint8_t val)
Enable Z direction in tap recognition.[set].
Parameters
ctx Read / write interface definitions
val Change the values of tap_z_en in reg TAP_CFG
References lsm6dsl_read_reg().
lsm6dsl_tap_dur_get()
int32_t lsm6dsl_tap_dur_get (stmdev_ctx_t * ctx, uint8_t * val)
When double tap recognition is enabled, this register expresses the maximum time between two consecutive detected taps to determine a double tap event. The default value of these bits is 0000b which corresponds to 16*ODR_XL time. If the DUR[3:0] bits are set to a different value,1LSB corresponds to 32*ODR_XL time.[get].
Parameters
ctx Read / write interface definitions
val Change the values of dur in reg INT_DUR2
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_dur_set()
int32_t lsm6dsl_tap_dur_set (stmdev_ctx_t * ctx, uint8_t val)
When double tap recognition is enabled, this register expresses the maximum time between two consecutive detected taps to determine a double tap event. The default value of these bits is 0000b which corresponds to 16*ODR_XL time. If the DUR[3:0] bits are set to a different value,1LSB corresponds to 32*ODR_XL time.[set].
Parameters
ctx Read / write interface definitions
val Change the values of dur in reg INT_DUR2
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Set_Tap_Duration_Time().
lsm6dsl_tap_mode_get()
int32_t lsm6dsl_tap_mode_get (stmdev_ctx_t * ctx, lsm6dsl_single_double_tap_t * val)
Single/double-tap event enable/disable.[get].
Parameters
ctx Read / write interface definitions
val Get the values of single_double_tap in reg WAKE_UP_THS
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_mode_set()
int32_t lsm6dsl_tap_mode_set (stmdev_ctx_t * ctx, lsm6dsl_single_double_tap_t val)
Single/double-tap event enable/disable.[set].
Parameters
ctx Read / write interface definitions
val Change the values of single_double_tap in reg WAKE_UP_THS
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_quiet_get()
int32_t lsm6dsl_tap_quiet_get (stmdev_ctx_t * ctx, uint8_t * val)
Quiet time is the time after the first detected tap in which there must not be any overthreshold event. The default value of these bits is 00b which corresponds to 2*ODR_XL time. If the QUIET[1:0] bits are set to a different value, 1LSB corresponds to 4*ODR_XL time.[get].
Parameters
ctx Read / write interface definitions
val Change the values of quiet in reg INT_DUR2
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_quiet_set()
int32_t lsm6dsl_tap_quiet_set (stmdev_ctx_t * ctx, uint8_t val)
Quiet time is the time after the first detected tap in which there must not be any overthreshold event. The default value of these bits is 00b which corresponds to 2*ODR_XL time. If the QUIET[1:0] bits are set to a different value, 1LSB corresponds to 4*ODR_XL time.[set].
Parameters
ctx Read / write interface definitions
val Change the values of quiet in reg INT_DUR2
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Set_Tap_Quiet_Time().
lsm6dsl_tap_shock_get()
int32_t lsm6dsl_tap_shock_get (stmdev_ctx_t * ctx, uint8_t * val)
Maximum duration is the maximum time of an overthreshold signal detection to be recognized as a tap event. The default value of these bits is 00b which corresponds to 4*ODR_XL time. If the SHOCK[1:0] bits are set to a different value, 1LSB corresponds to 8*ODR_XL time.[get].
Parameters
ctx Read / write interface definitions
val Change the values of shock in reg INT_DUR2
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_shock_set()
int32_t lsm6dsl_tap_shock_set (stmdev_ctx_t * ctx, uint8_t val)
Maximum duration is the maximum time of an overthreshold signal detection to be recognized as a tap event. The default value of these bits is 00b which corresponds to 4*ODR_XL time. If the SHOCK[1:0] bits are set to a different value, 1LSB corresponds to 8*ODR_XL time.[set].
Parameters
ctx Read / write interface definitions
val Change the values of shock in reg INT_DUR2
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Set_Tap_Shock_Time().
lsm6dsl_tap_src_get()
int32_t lsm6dsl_tap_src_get (stmdev_ctx_t * ctx, lsm6dsl_tap_src_t * val)
Read the tap / double tap source register.[get].
Parameters
ctx Read / write interface definitions
val Structure of registers from TAP_SRC
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_threshold_x_get()
int32_t lsm6dsl_tap_threshold_x_get (stmdev_ctx_t * ctx, uint8_t * val)
Threshold for tap recognition.[get].
Parameters
ctx Read / write interface definitions
val Change the values of tap_ths in reg TAP_THS_6D
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_threshold_x_set()
int32_t lsm6dsl_tap_threshold_x_set (stmdev_ctx_t * ctx, uint8_t val)
Threshold for tap recognition.[set].
Parameters
ctx Read / write interface definitions
val Change the values of tap_ths in reg TAP_THS_6D
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Set_Tap_Threshold().