Sensor de vibração MQTT - Trabalho de conclusão de curso: LSM6DSL_Pedometer
LSM6DSL_Pedometer
BSP » Component » LSM6DSL
This section groups all the functions that manage pedometer.
Functions
int32_t lsm6dsl_pedo_step_reset_set (stmdev_ctx_t *ctx, uint8_t val)
Reset pedometer step counter.[set].
int32_t lsm6dsl_pedo_step_reset_get (stmdev_ctx_t *ctx, uint8_t *val)
Reset pedometer step counter.[get].
int32_t lsm6dsl_pedo_sens_set (stmdev_ctx_t *ctx, uint8_t val)
Enable pedometer algorithm.[set].
int32_t lsm6dsl_pedo_sens_get (stmdev_ctx_t *ctx, uint8_t *val)
pedo_sens: Enable pedometer algorithm.[get]
int32_t lsm6dsl_pedo_threshold_set (stmdev_ctx_t *ctx, uint8_t val)
Minimum threshold to detect a peak. Default is 10h.[set].
int32_t lsm6dsl_pedo_threshold_get (stmdev_ctx_t *ctx, uint8_t *val)
Minimum threshold to detect a peak. Default is 10h.[get].
int32_t lsm6dsl_pedo_full_scale_set (stmdev_ctx_t *ctx, lsm6dsl_pedo_fs_t val)
pedo_full_scale: Pedometer data range.[set]
int32_t lsm6dsl_pedo_full_scale_get (stmdev_ctx_t *ctx, lsm6dsl_pedo_fs_t *val)
Pedometer data range.[get].
int32_t lsm6dsl_pedo_debounce_steps_set (stmdev_ctx_t *ctx, uint8_t val)
Pedometer debounce configuration register (r/w).[set].
int32_t lsm6dsl_pedo_debounce_steps_get (stmdev_ctx_t *ctx, uint8_t *val)
Pedometer debounce configuration register (r/w).[get].
int32_t lsm6dsl_pedo_timeout_set (stmdev_ctx_t *ctx, uint8_t val)
Debounce time. If the time between two consecutive steps is greater than DEB_TIME*80ms, the debouncer is reactivated. Default value: 01101[set].
int32_t lsm6dsl_pedo_timeout_get (stmdev_ctx_t *ctx, uint8_t *val)
Debounce time. If the time between two consecutive steps is greater than DEB_TIME*80ms, the debouncer is reactivated. Default value: 01101[get].
int32_t lsm6dsl_pedo_steps_period_set (stmdev_ctx_t *ctx, uint8_t *buff)
Time period register for step detection on delta time (r/w).[set].
int32_t lsm6dsl_pedo_steps_period_get (stmdev_ctx_t *ctx, uint8_t *buff)
Time period register for step detection on delta time (r/w).[get].
Detailed Description
This section groups all the functions that manage pedometer.
Function Documentation
lsm6dsl_pedo_debounce_steps_get()
int32_t lsm6dsl_pedo_debounce_steps_get (stmdev_ctx_t * ctx, uint8_t * val)
Pedometer debounce configuration register (r/w).[get].
Parameters
ctx Read / write interface definitions
val Change the values of deb_step in reg PEDO_DEB_REG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_pedo_debounce_steps_set()
int32_t lsm6dsl_pedo_debounce_steps_set (stmdev_ctx_t * ctx, uint8_t val)
Pedometer debounce configuration register (r/w).[set].
Parameters
ctx Read / write interface definitions
val Change the values of deb_step in reg PEDO_DEB_REG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_pedo_full_scale_get()
int32_t lsm6dsl_pedo_full_scale_get (stmdev_ctx_t * ctx, lsm6dsl_pedo_fs_t * val)
Pedometer data range.[get].
Parameters
ctx Read / write interface definitions
val Get the values of pedo_fs in reg CONFIG_PEDO_THS_MIN
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_pedo_full_scale_set()
int32_t lsm6dsl_pedo_full_scale_set (stmdev_ctx_t * ctx, lsm6dsl_pedo_fs_t val)
pedo_full_scale: Pedometer data range.[set]
Parameters
ctx Read / write interface definitions
val Change the values of pedo_fs in reg CONFIG_PEDO_THS_MIN
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_pedo_sens_get()
int32_t lsm6dsl_pedo_sens_get (stmdev_ctx_t * ctx, uint8_t * val)
pedo_sens: Enable pedometer algorithm.[get]
Parameters
ctx Read / write interface definitions
val Change the values of pedo_en in reg CTRL10_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_pedo_sens_set()
int32_t lsm6dsl_pedo_sens_set (stmdev_ctx_t * ctx, uint8_t val)
Enable pedometer algorithm.[set].
Parameters
ctx Read / write interface definitions
val Change the values of pedo_en in reg CTRL10_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_pedo_step_reset_get()
int32_t lsm6dsl_pedo_step_reset_get (stmdev_ctx_t * ctx, uint8_t * val)
Reset pedometer step counter.[get].
Parameters
ctx Read / write interface definitions
val Change the values of pedo_rst_step in reg CTRL10_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_pedo_step_reset_set()
int32_t lsm6dsl_pedo_step_reset_set (stmdev_ctx_t * ctx, uint8_t val)
Reset pedometer step counter.[set].
Parameters
ctx Read / write interface definitions
val Change the values of pedo_rst_step in reg CTRL10_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Disable_Step_Counter_Reset(), and LSM6DSL_ACC_Enable_Step_Counter_Reset().
lsm6dsl_pedo_steps_period_get()
int32_t lsm6dsl_pedo_steps_period_get (stmdev_ctx_t * ctx, uint8_t * buff)
Time period register for step detection on delta time (r/w).[get].
Parameters
ctx Read / write interface definitions
buff Buffer that stores data read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_pedo_steps_period_set()
int32_t lsm6dsl_pedo_steps_period_set (stmdev_ctx_t * ctx, uint8_t * buff)
Time period register for step detection on delta time (r/w).[set].
Parameters
ctx Read / write interface definitions
buff Buffer that contains data to write
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_pedo_threshold_get()
int32_t lsm6dsl_pedo_threshold_get (stmdev_ctx_t * ctx, uint8_t * val)
Minimum threshold to detect a peak. Default is 10h.[get].
Parameters
ctx Read / write interface definitions
val Change the values of ths_min in reg CONFIG_PEDO_THS_MIN
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_pedo_threshold_set()
int32_t lsm6dsl_pedo_threshold_set (stmdev_ctx_t * ctx, uint8_t val)
Minimum threshold to detect a peak. Default is 10h.[set].
Parameters
ctx Read / write interface definitions
val Change the values of ths_min in reg CONFIG_PEDO_THS_MIN
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
Referenced by LSM6DSL_ACC_Set_Pedometer_Threshold().
lsm6dsl_pedo_timeout_get()
int32_t lsm6dsl_pedo_timeout_get (stmdev_ctx_t * ctx, uint8_t * val)
Debounce time. If the time between two consecutive steps is greater than DEB_TIME*80ms, the debouncer is reactivated. Default value: 01101[get].
Parameters
ctx Read / write interface definitions
val Change the values of deb_time in reg PEDO_DEB_REG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_pedo_timeout_set()
int32_t lsm6dsl_pedo_timeout_set (stmdev_ctx_t * ctx, uint8_t val)
Debounce time. If the time between two consecutive steps is greater than DEB_TIME*80ms, the debouncer is reactivated. Default value: 01101[set].
Parameters
ctx Read / write interface definitions
val Change the values of deb_time in reg PEDO_DEB_REG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().