Sensor de vibração MQTT - Trabalho de conclusão de curso: LSM6DSL_Dataoutput
LSM6DSL_Dataoutput
BSP » Component » LSM6DSL
This section groups all the data output functions.
Functions
int32_t lsm6dsl_rounding_mode_set (stmdev_ctx_t *ctx, lsm6dsl_rounding_t val)
Circular burst-mode (rounding) read from output registers through the primary interface.[set].
int32_t lsm6dsl_rounding_mode_get (stmdev_ctx_t *ctx, lsm6dsl_rounding_t *val)
Circular burst-mode (rounding) read from output registers through the primary interface.[get].
int32_t lsm6dsl_temperature_raw_get (stmdev_ctx_t *ctx, int16_t *val)
Temperature data output register (r). L and H registers together express a 16-bit word in two’s complement.[get].
int32_t lsm6dsl_angular_rate_raw_get (stmdev_ctx_t *ctx, int16_t *val)
Angular rate sensor. The value is expressed as a 16-bit word in two’s complement.[get].
int32_t lsm6dsl_acceleration_raw_get (stmdev_ctx_t *ctx, int16_t *val)
Linear acceleration output register. The value is expressed as a 16-bit word in two’s complement.[get].
int32_t lsm6dsl_mag_calibrated_raw_get (stmdev_ctx_t *ctx, int16_t *val)
External magnetometer raw data.[get].
int32_t lsm6dsl_fifo_raw_data_get (stmdev_ctx_t *ctx, uint8_t *buffer, uint8_t len)
Read data in FIFO.[get].
Detailed Description
This section groups all the data output functions.
Function Documentation
lsm6dsl_acceleration_raw_get()
int32_t lsm6dsl_acceleration_raw_get (stmdev_ctx_t * ctx, int16_t * val)
Linear acceleration output register. The value is expressed as a 16-bit word in two’s complement.[get].
Parameters
ctx Read / write interface definitions
buff Buffer that stores data read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_GetAxes(), and LSM6DSL_ACC_GetAxesRaw().
lsm6dsl_angular_rate_raw_get()
int32_t lsm6dsl_angular_rate_raw_get (stmdev_ctx_t * ctx, int16_t * val)
Angular rate sensor. The value is expressed as a 16-bit word in two’s complement.[get].
Parameters
ctx Read / write interface definitions
buff Buffer that stores data read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_GYRO_GetAxes(), and LSM6DSL_GYRO_GetAxesRaw().
lsm6dsl_fifo_raw_data_get()
int32_t lsm6dsl_fifo_raw_data_get (stmdev_ctx_t * ctx, uint8_t * buffer, uint8_t len)
Read data in FIFO.[get].
Parameters
ctx Read / write interface definitions
buffer Data buffer to store FIFO data.
len Number of data to read from FIFO.
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_mag_calibrated_raw_get()
int32_t lsm6dsl_mag_calibrated_raw_get (stmdev_ctx_t * ctx, int16_t * val)
External magnetometer raw data.[get].
Parameters
ctx Read / write interface definitions
buff Buffer that stores data read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_rounding_mode_get()
int32_t lsm6dsl_rounding_mode_get (stmdev_ctx_t * ctx, lsm6dsl_rounding_t * val)
Circular burst-mode (rounding) read from output registers through the primary interface.[get].
Parameters
ctx Read / write interface definitions
val Get the values of rounding in reg CTRL5_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_rounding_mode_set()
int32_t lsm6dsl_rounding_mode_set (stmdev_ctx_t * ctx, lsm6dsl_rounding_t val)
Circular burst-mode (rounding) read from output registers through the primary interface.[set].
Parameters
ctx Read / write interface definitions
val Change the values of rounding in reg CTRL5_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_temperature_raw_get()
int32_t lsm6dsl_temperature_raw_get (stmdev_ctx_t * ctx, int16_t * val)
Temperature data output register (r). L and H registers together express a 16-bit word in two’s complement.[get].
Parameters
ctx Read / write interface definitions
buff Buffer that stores data read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().