Sensor de vibração MQTT - Trabalho de conclusão de curso: LSM6DSL_filters
LSM6DSL_filters
BSP » Component » LSM6DSL
This section group all the functions concerning the filters configuration that impact both accelerometer and gyro.
Functions
int32_t lsm6dsl_filter_settling_mask_set (stmdev_ctx_t *ctx, uint8_t val)
Mask DRDY on pin (both XL & Gyro) until filter settling ends (XL and Gyro independently masked).[set].
int32_t lsm6dsl_filter_settling_mask_get (stmdev_ctx_t *ctx, uint8_t *val)
Mask DRDY on pin (both XL & Gyro) until filter settling ends (XL and Gyro independently masked).[get].
int32_t lsm6dsl_xl_hp_path_internal_set (stmdev_ctx_t *ctx, lsm6dsl_slope_fds_t val)
HPF or SLOPE filter selection on wake-up and Activity/Inactivity functions.[set].
int32_t lsm6dsl_xl_hp_path_internal_get (stmdev_ctx_t *ctx, lsm6dsl_slope_fds_t *val)
HPF or SLOPE filter selection on wake-up and Activity/Inactivity functions.[get].
Detailed Description
This section group all the functions concerning the filters configuration that impact both accelerometer and gyro.
Function Documentation
lsm6dsl_filter_settling_mask_get()
int32_t lsm6dsl_filter_settling_mask_get (stmdev_ctx_t * ctx, uint8_t * val)
Mask DRDY on pin (both XL & Gyro) until filter settling ends (XL and Gyro independently masked).[get].
Parameters
ctx Read / write interface definitions
val Change the values of drdy_mask in reg CTRL4_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_filter_settling_mask_set()
int32_t lsm6dsl_filter_settling_mask_set (stmdev_ctx_t * ctx, uint8_t val)
Mask DRDY on pin (both XL & Gyro) until filter settling ends (XL and Gyro independently masked).[set].
Parameters
ctx Read / write interface definitions
val Change the values of drdy_mask in reg CTRL4_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_hp_path_internal_get()
int32_t lsm6dsl_xl_hp_path_internal_get (stmdev_ctx_t * ctx, lsm6dsl_slope_fds_t * val)
HPF or SLOPE filter selection on wake-up and Activity/Inactivity functions.[get].
Parameters
ctx Read / write interface definitions
val Get the values of slope_fds in reg TAP_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_hp_path_internal_set()
int32_t lsm6dsl_xl_hp_path_internal_set (stmdev_ctx_t * ctx, lsm6dsl_slope_fds_t val)
HPF or SLOPE filter selection on wake-up and Activity/Inactivity functions.[set].
Parameters
ctx Read / write interface definitions
val Change the values of slope_fds in reg TAP_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().