Sensor de vibração MQTT - Trabalho de conclusão de curso: LSM6DSL_significant_motion
LSM6DSL_significant_motion
BSP » Component » LSM6DSL
This section groups all the functions that manage the significant motion detection.
Functions
int32_t lsm6dsl_motion_sens_set (stmdev_ctx_t *ctx, uint8_t val)
Enable significant motion detection function.[set].
int32_t lsm6dsl_motion_sens_get (stmdev_ctx_t *ctx, uint8_t *val)
Enable significant motion detection function.[get].
int32_t lsm6dsl_motion_threshold_set (stmdev_ctx_t *ctx, uint8_t *buff)
Significant motion threshold.[set].
int32_t lsm6dsl_motion_threshold_get (stmdev_ctx_t *ctx, uint8_t *buff)
Significant motion threshold.[get].
Detailed Description
This section groups all the functions that manage the significant motion detection.
Function Documentation
lsm6dsl_motion_sens_get()
int32_t lsm6dsl_motion_sens_get (stmdev_ctx_t * ctx, uint8_t * val)
Enable significant motion detection function.[get].
Parameters
ctx Read / write interface definitions
val Change the values of sign_motion_en in reg CTRL10_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_motion_sens_set()
int32_t lsm6dsl_motion_sens_set (stmdev_ctx_t * ctx, uint8_t val)
Enable significant motion detection function.[set].
Parameters
ctx Read / write interface definitions
val Change the values of sign_motion_en in reg CTRL10_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_motion_threshold_get()
int32_t lsm6dsl_motion_threshold_get (stmdev_ctx_t * ctx, uint8_t * buff)
Significant motion threshold.[get].
Parameters
ctx Read / write interface definitions
buff Buffer that store significant motion threshold.
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_motion_threshold_set()
int32_t lsm6dsl_motion_threshold_set (stmdev_ctx_t * ctx, uint8_t * buff)
Significant motion threshold.[set].
Parameters
ctx Read / write interface definitions
buff Buffer that store significant motion threshold.
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().