Sensor de vibração MQTT - Trabalho de conclusão de curso: LSM6DSL_accelerometer_filters
LSM6DSL_accelerometer_filters
BSP » Component » LSM6DSL
This section group all the functions concerning the filters configuration that impact accelerometer in every mode.
Functions
int32_t lsm6dsl_xl_filter_analog_set (stmdev_ctx_t *ctx, lsm6dsl_bw0_xl_t val)
Accelerometer analog chain bandwidth selection (only for accelerometer ODR ≥ 1.67 kHz).[set].
int32_t lsm6dsl_xl_filter_analog_get (stmdev_ctx_t *ctx, lsm6dsl_bw0_xl_t *val)
Accelerometer analog chain bandwidth selection (only for accelerometer ODR ≥ 1.67 kHz).[get].
int32_t lsm6dsl_xl_lp1_bandwidth_set (stmdev_ctx_t *ctx, lsm6dsl_lpf1_bw_sel_t val)
Accelerometer digital LPF (LPF1) bandwidth selection LPF2 is not used.[set].
int32_t lsm6dsl_xl_lp1_bandwidth_get (stmdev_ctx_t *ctx, lsm6dsl_lpf1_bw_sel_t *val)
Accelerometer digital LPF (LPF1) bandwidth selection LPF2 is not used.[get].
int32_t lsm6dsl_xl_lp2_bandwidth_set (stmdev_ctx_t *ctx, lsm6dsl_input_composite_t val)
LPF2 on outputs[set].
int32_t lsm6dsl_xl_lp2_bandwidth_get (stmdev_ctx_t *ctx, lsm6dsl_input_composite_t *val)
LPF2 on outputs[get].
int32_t lsm6dsl_xl_reference_mode_set (stmdev_ctx_t *ctx, uint8_t val)
Enable HP filter reference mode.[set].
int32_t lsm6dsl_xl_reference_mode_get (stmdev_ctx_t *ctx, uint8_t *val)
Enable HP filter reference mode.[get].
int32_t lsm6dsl_xl_hp_bandwidth_set (stmdev_ctx_t *ctx, lsm6dsl_hpcf_xl_t val)
High pass/Slope on outputs.[set].
int32_t lsm6dsl_xl_hp_bandwidth_get (stmdev_ctx_t *ctx, lsm6dsl_hpcf_xl_t *val)
High pass/Slope on outputs.[get].
Detailed Description
This section group all the functions concerning the filters configuration that impact accelerometer in every mode.
This section group all the functions concerning the filters configuration that impact accelerometer.
Function Documentation
lsm6dsl_xl_filter_analog_get()
int32_t lsm6dsl_xl_filter_analog_get (stmdev_ctx_t * ctx, lsm6dsl_bw0_xl_t * val)
Accelerometer analog chain bandwidth selection (only for accelerometer ODR ≥ 1.67 kHz).[get].
Parameters
ctx Read / write interface definitions
val Get the values of bw0_xl in reg CTRL1_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_filter_analog_set()
int32_t lsm6dsl_xl_filter_analog_set (stmdev_ctx_t * ctx, lsm6dsl_bw0_xl_t val)
Accelerometer analog chain bandwidth selection (only for accelerometer ODR ≥ 1.67 kHz).[set].
Parameters
ctx Read / write interface definitions
val Change the values of bw0_xl in reg CTRL1_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_hp_bandwidth_get()
int32_t lsm6dsl_xl_hp_bandwidth_get (stmdev_ctx_t * ctx, lsm6dsl_hpcf_xl_t * val)
High pass/Slope on outputs.[get].
Parameters
ctx Read / write interface definitions
val Get the values of hpcf_xl in reg CTRL8_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_hp_bandwidth_set()
int32_t lsm6dsl_xl_hp_bandwidth_set (stmdev_ctx_t * ctx, lsm6dsl_hpcf_xl_t val)
High pass/Slope on outputs.[set].
Parameters
ctx Read / write interface definitions
val Change the values of hpcf_xl in reg CTRL8_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_lp1_bandwidth_get()
int32_t lsm6dsl_xl_lp1_bandwidth_get (stmdev_ctx_t * ctx, lsm6dsl_lpf1_bw_sel_t * val)
Accelerometer digital LPF (LPF1) bandwidth selection LPF2 is not used.[get].
Parameters
ctx Read / write interface definitions
val Get the values of lpf1_bw_sel in reg CTRL1_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_lp1_bandwidth_set()
int32_t lsm6dsl_xl_lp1_bandwidth_set (stmdev_ctx_t * ctx, lsm6dsl_lpf1_bw_sel_t val)
Accelerometer digital LPF (LPF1) bandwidth selection LPF2 is not used.[set].
Parameters
ctx Read / write interface definitions
val Change the values of lpf1_bw_sel in reg CTRL1_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_lp2_bandwidth_get()
int32_t lsm6dsl_xl_lp2_bandwidth_get (stmdev_ctx_t * ctx, lsm6dsl_input_composite_t * val)
LPF2 on outputs[get].
Parameters
ctx Read / write interface definitions
val Get the values of input_composite in reg CTRL8_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_lp2_bandwidth_set()
int32_t lsm6dsl_xl_lp2_bandwidth_set (stmdev_ctx_t * ctx, lsm6dsl_input_composite_t val)
LPF2 on outputs[set].
Parameters
ctx Read / write interface definitions
val Change the values of input_composite in reg CTRL8_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_reference_mode_get()
int32_t lsm6dsl_xl_reference_mode_get (stmdev_ctx_t * ctx, uint8_t * val)
Enable HP filter reference mode.[get].
Parameters
ctx Read / write interface definitions
val Change the values of hp_ref_mode in reg CTRL8_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_reference_mode_set()
int32_t lsm6dsl_xl_reference_mode_set (stmdev_ctx_t * ctx, uint8_t val)
Enable HP filter reference mode.[set].
Parameters
ctx Read / write interface definitions
val Change the values of hp_ref_mode in reg CTRL8_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().