Sensor de vibração MQTT - Trabalho de conclusão de curso: LSM6DSL Exported Functions
LSM6DSL Exported Functions
BSP » Component » LSM6DSL
Functions
int32_t LSM6DSL_RegisterBusIO (LSM6DSL_Object_t *pObj, LSM6DSL_IO_t *pIO)
Register Component Bus IO operations.
int32_t LSM6DSL_Init (LSM6DSL_Object_t *pObj)
Initialize the LSM6DSL sensor.
int32_t LSM6DSL_DeInit (LSM6DSL_Object_t *pObj)
Deinitialize the LSM6DSL sensor.
int32_t LSM6DSL_ReadID (LSM6DSL_Object_t *pObj, uint8_t *Id)
Read component ID.
int32_t LSM6DSL_GetCapabilities (LSM6DSL_Object_t *pObj, LSM6DSL_Capabilities_t *Capabilities)
Get LSM6DSL sensor capabilities.
int32_t LSM6DSL_ACC_Enable (LSM6DSL_Object_t *pObj)
Enable the LSM6DSL accelerometer sensor.
int32_t LSM6DSL_ACC_Disable (LSM6DSL_Object_t *pObj)
Disable the LSM6DSL accelerometer sensor.
int32_t LSM6DSL_ACC_GetSensitivity (LSM6DSL_Object_t *pObj, float *Sensitivity)
Get the LSM6DSL accelerometer sensor sensitivity.
int32_t LSM6DSL_ACC_GetOutputDataRate (LSM6DSL_Object_t *pObj, float *Odr)
Get the LSM6DSL accelerometer sensor output data rate.
int32_t LSM6DSL_ACC_SetOutputDataRate (LSM6DSL_Object_t *pObj, float Odr)
Set the LSM6DSL accelerometer sensor output data rate.
int32_t LSM6DSL_ACC_GetFullScale (LSM6DSL_Object_t *pObj, int32_t *FullScale)
Get the LSM6DSL accelerometer sensor full scale.
int32_t LSM6DSL_ACC_SetFullScale (LSM6DSL_Object_t *pObj, int32_t FullScale)
Set the LSM6DSL accelerometer sensor full scale.
int32_t LSM6DSL_ACC_GetAxesRaw (LSM6DSL_Object_t *pObj, LSM6DSL_AxesRaw_t *Value)
Get the LSM6DSL accelerometer sensor raw axes.
int32_t LSM6DSL_ACC_GetAxes (LSM6DSL_Object_t *pObj, LSM6DSL_Axes_t *Acceleration)
Get the LSM6DSL accelerometer sensor axes.
int32_t LSM6DSL_GYRO_Enable (LSM6DSL_Object_t *pObj)
Enable the LSM6DSL gyroscope sensor.
int32_t LSM6DSL_GYRO_Disable (LSM6DSL_Object_t *pObj)
Disable the LSM6DSL gyroscope sensor.
int32_t LSM6DSL_GYRO_GetSensitivity (LSM6DSL_Object_t *pObj, float *Sensitivity)
Get the LSM6DSL gyroscope sensor sensitivity.
int32_t LSM6DSL_GYRO_GetOutputDataRate (LSM6DSL_Object_t *pObj, float *Odr)
Get the LSM6DSL gyroscope sensor output data rate.
int32_t LSM6DSL_GYRO_SetOutputDataRate (LSM6DSL_Object_t *pObj, float Odr)
Set the LSM6DSL gyroscope sensor output data rate.
int32_t LSM6DSL_GYRO_GetFullScale (LSM6DSL_Object_t *pObj, int32_t *FullScale)
Get the LSM6DSL gyroscope sensor full scale.
int32_t LSM6DSL_GYRO_SetFullScale (LSM6DSL_Object_t *pObj, int32_t FullScale)
Set the LSM6DSL gyroscope sensor full scale.
int32_t LSM6DSL_GYRO_GetAxesRaw (LSM6DSL_Object_t *pObj, LSM6DSL_AxesRaw_t *Value)
Get the LSM6DSL gyroscope sensor raw axes.
int32_t LSM6DSL_GYRO_GetAxes (LSM6DSL_Object_t *pObj, LSM6DSL_Axes_t *AngularRate)
Get the LSM6DSL gyroscope sensor axes.
int32_t LSM6DSL_Read_Reg (LSM6DSL_Object_t *pObj, uint8_t Reg, uint8_t *Data)
Get the LSM6DSL register value.
int32_t LSM6DSL_Write_Reg (LSM6DSL_Object_t *pObj, uint8_t Reg, uint8_t Data)
Set the LSM6DSL register value.
int32_t LSM6DSL_Set_Interrupt_Latch (LSM6DSL_Object_t *pObj, uint8_t Status)
Set the interrupt latch.
int32_t LSM6DSL_ACC_Enable_Free_Fall_Detection (LSM6DSL_Object_t *pObj, LSM6DSL_SensorIntPin_t IntPin)
Enable free fall detection.
int32_t LSM6DSL_ACC_Disable_Free_Fall_Detection (LSM6DSL_Object_t *pObj)
Disable free fall detection.
int32_t LSM6DSL_ACC_Set_Free_Fall_Threshold (LSM6DSL_Object_t *pObj, uint8_t Threshold)
Set free fall threshold.
int32_t LSM6DSL_ACC_Set_Free_Fall_Duration (LSM6DSL_Object_t *pObj, uint8_t Duration)
Set free fall duration.
int32_t LSM6DSL_ACC_Enable_Pedometer (LSM6DSL_Object_t *pObj)
Enable pedometer.
int32_t LSM6DSL_ACC_Disable_Pedometer (LSM6DSL_Object_t *pObj)
Disable pedometer.
int32_t LSM6DSL_ACC_Get_Step_Count (LSM6DSL_Object_t *pObj, uint16_t *StepCount)
Get step count.
int32_t LSM6DSL_ACC_Enable_Step_Counter_Reset (LSM6DSL_Object_t *pObj)
Enable step counter reset.
int32_t LSM6DSL_ACC_Disable_Step_Counter_Reset (LSM6DSL_Object_t *pObj)
Disable step counter reset.
int32_t LSM6DSL_ACC_Set_Pedometer_Threshold (LSM6DSL_Object_t *pObj, uint8_t Threshold)
Set pedometer threshold.
int32_t LSM6DSL_ACC_Enable_Tilt_Detection (LSM6DSL_Object_t *pObj, LSM6DSL_SensorIntPin_t IntPin)
Enable tilt detection.
int32_t LSM6DSL_ACC_Disable_Tilt_Detection (LSM6DSL_Object_t *pObj)
Disable tilt detection.
int32_t LSM6DSL_ACC_Enable_Wake_Up_Detection (LSM6DSL_Object_t *pObj, LSM6DSL_SensorIntPin_t IntPin)
Enable wake up detection.
int32_t LSM6DSL_ACC_Disable_Wake_Up_Detection (LSM6DSL_Object_t *pObj)
Disable wake up detection.
int32_t LSM6DSL_ACC_Set_Wake_Up_Threshold (LSM6DSL_Object_t *pObj, uint8_t Threshold)
Set wake up threshold.
int32_t LSM6DSL_ACC_Set_Wake_Up_Duration (LSM6DSL_Object_t *pObj, uint8_t Duration)
Set wake up duration.
int32_t LSM6DSL_ACC_Enable_Inactivity_Detection (LSM6DSL_Object_t *pObj, LSM6DSL_SensorIntPin_t IntPin)
Enable inactivity detection.
int32_t LSM6DSL_ACC_Disable_Inactivity_Detection (LSM6DSL_Object_t *pObj)
Disable inactivity detection.
int32_t LSM6DSL_ACC_Set_Sleep_Duration (LSM6DSL_Object_t *pObj, uint8_t Duration)
Set sleep duration.
int32_t LSM6DSL_ACC_Enable_Single_Tap_Detection (LSM6DSL_Object_t *pObj, LSM6DSL_SensorIntPin_t IntPin)
Enable single tap detection.
int32_t LSM6DSL_ACC_Disable_Single_Tap_Detection (LSM6DSL_Object_t *pObj)
Disable single tap detection.
int32_t LSM6DSL_ACC_Enable_Double_Tap_Detection (LSM6DSL_Object_t *pObj, LSM6DSL_SensorIntPin_t IntPin)
Enable double tap detection.
int32_t LSM6DSL_ACC_Disable_Double_Tap_Detection (LSM6DSL_Object_t *pObj)
Disable double tap detection.
int32_t LSM6DSL_ACC_Set_Tap_Threshold (LSM6DSL_Object_t *pObj, uint8_t Threshold)
Set tap threshold.
int32_t LSM6DSL_ACC_Set_Tap_Shock_Time (LSM6DSL_Object_t *pObj, uint8_t Time)
Set tap shock time.
int32_t LSM6DSL_ACC_Set_Tap_Quiet_Time (LSM6DSL_Object_t *pObj, uint8_t Time)
Set tap quiet time.
int32_t LSM6DSL_ACC_Set_Tap_Duration_Time (LSM6DSL_Object_t *pObj, uint8_t Time)
Set tap duration time.
int32_t LSM6DSL_ACC_Enable_6D_Orientation (LSM6DSL_Object_t *pObj, LSM6DSL_SensorIntPin_t IntPin)
Enable 6D orientation detection.
int32_t LSM6DSL_ACC_Disable_6D_Orientation (LSM6DSL_Object_t *pObj)
Disable 6D orientation detection.
int32_t LSM6DSL_ACC_Set_6D_Orientation_Threshold (LSM6DSL_Object_t *pObj, uint8_t Threshold)
Set 6D orientation threshold.
int32_t LSM6DSL_ACC_Get_6D_Orientation_XL (LSM6DSL_Object_t *pObj, uint8_t *XLow)
Get the status of XLow orientation.
int32_t LSM6DSL_ACC_Get_6D_Orientation_XH (LSM6DSL_Object_t *pObj, uint8_t *XHigh)
Get the status of XHigh orientation.
int32_t LSM6DSL_ACC_Get_6D_Orientation_YL (LSM6DSL_Object_t *pObj, uint8_t *YLow)
Get the status of YLow orientation.
int32_t LSM6DSL_ACC_Get_6D_Orientation_YH (LSM6DSL_Object_t *pObj, uint8_t *YHigh)
Get the status of YHigh orientation.
int32_t LSM6DSL_ACC_Get_6D_Orientation_ZL (LSM6DSL_Object_t *pObj, uint8_t *ZLow)
Get the status of ZLow orientation.
int32_t LSM6DSL_ACC_Get_6D_Orientation_ZH (LSM6DSL_Object_t *pObj, uint8_t *ZHigh)
Get the status of ZHigh orientation.
int32_t LSM6DSL_ACC_Get_Event_Status (LSM6DSL_Object_t *pObj, LSM6DSL_Event_Status_t *Status)
Get the status of all hardware events.
int32_t LSM6DSL_ACC_Set_SelfTest (LSM6DSL_Object_t *pObj, uint8_t Val)
Set self test.
int32_t LSM6DSL_ACC_Get_DRDY_Status (LSM6DSL_Object_t *pObj, uint8_t *Status)
Get the LSM6DSL ACC data ready bit value.
int32_t LSM6DSL_ACC_Get_Init_Status (LSM6DSL_Object_t *pObj, uint8_t *Status)
Get the LSM6DSL ACC initialization status.
int32_t LSM6DSL_ACC_Set_INT1_DRDY (LSM6DSL_Object_t *pObj, uint8_t Val)
Set DRDY on INT1.
int32_t LSM6DSL_GYRO_Set_SelfTest (LSM6DSL_Object_t *pObj, uint8_t Val)
Set self test.
int32_t LSM6DSL_GYRO_Get_DRDY_Status (LSM6DSL_Object_t *pObj, uint8_t *Status)
Get the LSM6DSL GYRO data ready bit value.
int32_t LSM6DSL_GYRO_Get_Init_Status (LSM6DSL_Object_t *pObj, uint8_t *Status)
Get the LSM6DSL GYRO initialization status.
int32_t LSM6DSL_GYRO_Set_INT1_DRDY (LSM6DSL_Object_t *pObj, uint8_t Val)
Set DRDY on INT1.
int32_t LSM6DSL_Set_DRDY_Mode (LSM6DSL_Object_t *pObj, uint8_t Val)
Set DRDY mode.
int32_t LSM6DSL_FIFO_Get_Num_Samples (LSM6DSL_Object_t *pObj, uint16_t *NumSamples)
Get the LSM6DSL FIFO number of samples.
int32_t LSM6DSL_FIFO_Get_Full_Status (LSM6DSL_Object_t *pObj, uint8_t *Status)
Get the LSM6DSL FIFO full status.
int32_t LSM6DSL_FIFO_Set_ODR_Value (LSM6DSL_Object_t *pObj, float Odr)
Set the LSM6DSL FIFO ODR value.
int32_t LSM6DSL_FIFO_Set_INT1_FIFO_Full (LSM6DSL_Object_t *pObj, uint8_t Status)
Set the LSM6DSL FIFO full interrupt on INT1 pin.
int32_t LSM6DSL_FIFO_Set_Watermark_Level (LSM6DSL_Object_t *pObj, uint16_t Watermark)
Set the LSM6DSL FIFO watermark level.
int32_t LSM6DSL_FIFO_Set_Stop_On_Fth (LSM6DSL_Object_t *pObj, uint8_t Status)
Set the LSM6DSL FIFO stop on watermark.
int32_t LSM6DSL_FIFO_Set_Mode (LSM6DSL_Object_t *pObj, uint8_t Mode)
Set the LSM6DSL FIFO mode.
int32_t LSM6DSL_FIFO_Get_Pattern (LSM6DSL_Object_t *pObj, uint16_t *Pattern)
Get the LSM6DSL FIFO pattern.
int32_t LSM6DSL_FIFO_Get_Data (LSM6DSL_Object_t *pObj, uint8_t *Data)
Get the LSM6DSL FIFO raw data.
int32_t LSM6DSL_FIFO_ACC_Set_Decimation (LSM6DSL_Object_t *pObj, uint8_t Decimation)
Set the LSM6DSL FIFO accelero decimation.
int32_t LSM6DSL_FIFO_ACC_Get_Axis (LSM6DSL_Object_t *pObj, int32_t *Acceleration)
Get the LSM6DSL FIFO accelero single sample (16-bit data) and calculate acceleration [mg].
int32_t LSM6DSL_FIFO_GYRO_Set_Decimation (LSM6DSL_Object_t *pObj, uint8_t Decimation)
Set the LSM6DSL FIFO gyro decimation.
int32_t LSM6DSL_FIFO_GYRO_Get_Axis (LSM6DSL_Object_t *pObj, int32_t *AngularVelocity)
Get the LSM6DSL FIFO gyro single sample (16-bit data) and calculate angular velocity [mDPS].
int32_t LSM6DSL_FIFO_Get_Empty_Status (LSM6DSL_Object_t *pObj, uint8_t *Status)
int32_t LSM6DSL_FIFO_Get_Overrun_Status (LSM6DSL_Object_t *pObj, uint8_t *Status)
Detailed Description
Function Documentation
LSM6DSL_ACC_Disable()
int32_t LSM6DSL_ACC_Disable (LSM6DSL_Object_t * pObj)
Disable the LSM6DSL accelerometer sensor.
Parameters
pObj the device pObj
Return values
0 in case of success, an error code otherwise
Referenced by LSM6DSL_DeInit().
LSM6DSL_ACC_Disable_6D_Orientation()
int32_t LSM6DSL_ACC_Disable_6D_Orientation (LSM6DSL_Object_t * pObj)
Disable 6D orientation detection.
Parameters
pObj the device pObj
Return values
0 in case of success, an error code otherwise
References lsm6dsl_pin_int1_route_get().
LSM6DSL_ACC_Disable_Double_Tap_Detection()
int32_t LSM6DSL_ACC_Disable_Double_Tap_Detection (LSM6DSL_Object_t * pObj)
Disable double tap detection.
Parameters
pObj the device pObj
Return values
0 in case of success, an error code otherwise
References lsm6dsl_pin_int1_route_get().
LSM6DSL_ACC_Disable_Free_Fall_Detection()
int32_t LSM6DSL_ACC_Disable_Free_Fall_Detection (LSM6DSL_Object_t * pObj)
Disable free fall detection.
Parameters
pObj the device pObj
Return values
0 in case of success, an error code otherwise
References lsm6dsl_pin_int1_route_get().
LSM6DSL_ACC_Disable_Inactivity_Detection()
int32_t LSM6DSL_ACC_Disable_Inactivity_Detection (LSM6DSL_Object_t * pObj)
Disable inactivity detection.
Parameters
pObj the device pObj
Return values
0 in case of success, an error code otherwise
References lsm6dsl_pin_int1_route_get().
LSM6DSL_ACC_Disable_Pedometer()
int32_t LSM6DSL_ACC_Disable_Pedometer (LSM6DSL_Object_t * pObj)
Disable pedometer.
Parameters
pObj the device pObj
Return values
0 in case of success, an error code otherwise
References lsm6dsl_pin_int1_route_get().
LSM6DSL_ACC_Disable_Single_Tap_Detection()
int32_t LSM6DSL_ACC_Disable_Single_Tap_Detection (LSM6DSL_Object_t * pObj)
Disable single tap detection.
Parameters
pObj the device pObj
Return values
0 in case of success, an error code otherwise
References lsm6dsl_pin_int1_route_get().
LSM6DSL_ACC_Disable_Step_Counter_Reset()
int32_t LSM6DSL_ACC_Disable_Step_Counter_Reset (LSM6DSL_Object_t * pObj)
Disable step counter reset.
Parameters
pObj the device pObj
Return values
0 in case of success, an error code otherwise
References lsm6dsl_pedo_step_reset_set().
LSM6DSL_ACC_Disable_Tilt_Detection()
int32_t LSM6DSL_ACC_Disable_Tilt_Detection (LSM6DSL_Object_t * pObj)
Disable tilt detection.
Parameters
pObj the device pObj
Return values
0 in case of success, an error code otherwise
References lsm6dsl_pin_int1_route_get().
LSM6DSL_ACC_Disable_Wake_Up_Detection()
int32_t LSM6DSL_ACC_Disable_Wake_Up_Detection (LSM6DSL_Object_t * pObj)
Disable wake up detection.
Parameters
pObj the device pObj
Return values
0 in case of success, an error code otherwise
References lsm6dsl_pin_int1_route_get().
LSM6DSL_ACC_Enable()
int32_t LSM6DSL_ACC_Enable (LSM6DSL_Object_t * pObj)
Enable the LSM6DSL accelerometer sensor.
Parameters
pObj the device pObj
Return values
0 in case of success, an error code otherwise
LSM6DSL_ACC_Enable_6D_Orientation()
int32_t LSM6DSL_ACC_Enable_6D_Orientation (LSM6DSL_Object_t * pObj, LSM6DSL_SensorIntPin_t IntPin)
Enable 6D orientation detection.
Parameters
pObj the device pObj
IntPin interrupt pin line to be used
Return values
0 in case of success, an error code otherwise
LSM6DSL_ACC_Enable_Double_Tap_Detection()
int32_t LSM6DSL_ACC_Enable_Double_Tap_Detection (LSM6DSL_Object_t * pObj, LSM6DSL_SensorIntPin_t IntPin)
Enable double tap detection.
Parameters
pObj the device pObj
IntPin interrupt pin line to be used
Return values
0 in case of success, an error code otherwise
LSM6DSL_ACC_Enable_Free_Fall_Detection()
int32_t LSM6DSL_ACC_Enable_Free_Fall_Detection (LSM6DSL_Object_t * pObj, LSM6DSL_SensorIntPin_t IntPin)
Enable free fall detection.
Parameters
pObj the device pObj
IntPin interrupt pin line to be used
Return values
0 in case of success, an error code otherwise
LSM6DSL_ACC_Enable_Inactivity_Detection()
int32_t LSM6DSL_ACC_Enable_Inactivity_Detection (LSM6DSL_Object_t * pObj, LSM6DSL_SensorIntPin_t IntPin)
Enable inactivity detection.
Parameters
pObj the device pObj
IntPin interrupt pin line to be used
Return values
0 in case of success, an error code otherwise
LSM6DSL_ACC_Enable_Pedometer()
int32_t LSM6DSL_ACC_Enable_Pedometer (LSM6DSL_Object_t * pObj)
Enable pedometer.
Parameters
pObj the device pObj
Return values
0 in case of success, an error code otherwise
References LSM6DSL_ACC_SetOutputDataRate().
LSM6DSL_ACC_Enable_Single_Tap_Detection()
int32_t LSM6DSL_ACC_Enable_Single_Tap_Detection (LSM6DSL_Object_t * pObj, LSM6DSL_SensorIntPin_t IntPin)
Enable single tap detection.
Parameters
pObj the device pObj
IntPin interrupt pin line to be used
Return values
0 in case of success, an error code otherwise
LSM6DSL_ACC_Enable_Step_Counter_Reset()
int32_t LSM6DSL_ACC_Enable_Step_Counter_Reset (LSM6DSL_Object_t * pObj)
Enable step counter reset.
Parameters
pObj the device pObj
Return values
0 in case of success, an error code otherwise
References lsm6dsl_pedo_step_reset_set().
LSM6DSL_ACC_Enable_Tilt_Detection()
int32_t LSM6DSL_ACC_Enable_Tilt_Detection (LSM6DSL_Object_t * pObj, LSM6DSL_SensorIntPin_t IntPin)
Enable tilt detection.
Parameters
pObj the device pObj
IntPin interrupt pin line to be used
Return values
0 in case of success, an error code otherwise
LSM6DSL_ACC_Enable_Wake_Up_Detection()
int32_t LSM6DSL_ACC_Enable_Wake_Up_Detection (LSM6DSL_Object_t * pObj, LSM6DSL_SensorIntPin_t IntPin)
Enable wake up detection.
Parameters
pObj the device pObj
IntPin interrupt pin line to be used
Return values
0 in case of success, an error code otherwise
LSM6DSL_ACC_Get_6D_Orientation_XH()
int32_t LSM6DSL_ACC_Get_6D_Orientation_XH (LSM6DSL_Object_t * pObj, uint8_t * XHigh)
Get the status of XHigh orientation.
Parameters
pObj the device pObj
XHigh the status of XHigh orientation
Return values
0 in case of success, an error code otherwise
References lsm6dsl_read_reg().
LSM6DSL_ACC_Get_6D_Orientation_XL()
int32_t LSM6DSL_ACC_Get_6D_Orientation_XL (LSM6DSL_Object_t * pObj, uint8_t * XLow)
Get the status of XLow orientation.
Parameters
pObj the device pObj
XLow the status of XLow orientation
Return values
0 in case of success, an error code otherwise
References lsm6dsl_read_reg().
LSM6DSL_ACC_Get_6D_Orientation_YH()
int32_t LSM6DSL_ACC_Get_6D_Orientation_YH (LSM6DSL_Object_t * pObj, uint8_t * YHigh)
Get the status of YHigh orientation.
Parameters
pObj the device pObj
YHigh the status of YHigh orientation
Return values
0 in case of success, an error code otherwise
References lsm6dsl_read_reg().
LSM6DSL_ACC_Get_6D_Orientation_YL()
int32_t LSM6DSL_ACC_Get_6D_Orientation_YL (LSM6DSL_Object_t * pObj, uint8_t * YLow)
Get the status of YLow orientation.
Parameters
pObj the device pObj
YLow the status of YLow orientation
Return values
0 in case of success, an error code otherwise
References lsm6dsl_read_reg().
LSM6DSL_ACC_Get_6D_Orientation_ZH()
int32_t LSM6DSL_ACC_Get_6D_Orientation_ZH (LSM6DSL_Object_t * pObj, uint8_t * ZHigh)
Get the status of ZHigh orientation.
Parameters
pObj the device pObj
ZHigh the status of ZHigh orientation
Return values
0 in case of success, an error code otherwise
References lsm6dsl_read_reg().
LSM6DSL_ACC_Get_6D_Orientation_ZL()
int32_t LSM6DSL_ACC_Get_6D_Orientation_ZL (LSM6DSL_Object_t * pObj, uint8_t * ZLow)
Get the status of ZLow orientation.
Parameters
pObj the device pObj
ZLow the status of ZLow orientation
Return values
0 in case of success, an error code otherwise
References lsm6dsl_read_reg().
LSM6DSL_ACC_Get_DRDY_Status()
int32_t LSM6DSL_ACC_Get_DRDY_Status (LSM6DSL_Object_t * pObj, uint8_t * Status)
Get the LSM6DSL ACC data ready bit value.
Parameters
pObj the device pObj
Status the status of data ready bit
Return values
0 in case of success, an error code otherwise
References lsm6dsl_xl_flag_data_ready_get().
LSM6DSL_ACC_Get_Event_Status()
int32_t LSM6DSL_ACC_Get_Event_Status (LSM6DSL_Object_t * pObj, LSM6DSL_Event_Status_t * Status)
Get the status of all hardware events.
Parameters
pObj the device pObj
Status the status of all hardware events
Return values
0 in case of success, an error code otherwise
References lsm6dsl_read_reg().
LSM6DSL_ACC_Get_Init_Status()
int32_t LSM6DSL_ACC_Get_Init_Status (LSM6DSL_Object_t * pObj, uint8_t * Status)
Get the LSM6DSL ACC initialization status.
Parameters
pObj the device pObj
Status 1 if initialized, 0 otherwise
Return values
0 in case of success, an error code otherwise
LSM6DSL_ACC_Get_Step_Count()
int32_t LSM6DSL_ACC_Get_Step_Count (LSM6DSL_Object_t * pObj, uint16_t * StepCount)
Get step count.
Parameters
pObj the device pObj
StepCount step counter
Return values
0 in case of success, an error code otherwise
References lsm6dsl_read_reg().
LSM6DSL_ACC_GetAxes()
int32_t LSM6DSL_ACC_GetAxes (LSM6DSL_Object_t * pObj, LSM6DSL_Axes_t * Acceleration)
Get the LSM6DSL accelerometer sensor axes.
Parameters
pObj the device pObj
Acceleration pointer where the values of the axes are written
Return values
0 in case of success, an error code otherwise
References lsm6dsl_acceleration_raw_get().
LSM6DSL_ACC_GetAxesRaw()
int32_t LSM6DSL_ACC_GetAxesRaw (LSM6DSL_Object_t * pObj, LSM6DSL_AxesRaw_t * Value)
Get the LSM6DSL accelerometer sensor raw axes.
Parameters
pObj the device pObj
Value pointer where the raw values of the axes are written
Return values
0 in case of success, an error code otherwise
References lsm6dsl_acceleration_raw_get().
LSM6DSL_ACC_GetFullScale()
int32_t LSM6DSL_ACC_GetFullScale (LSM6DSL_Object_t * pObj, int32_t * FullScale)
Get the LSM6DSL accelerometer sensor full scale.
Parameters
pObj the device pObj
FullScale pointer where the full scale is written
Return values
0 in case of success, an error code otherwise
LSM6DSL_ACC_GetOutputDataRate()
int32_t LSM6DSL_ACC_GetOutputDataRate (LSM6DSL_Object_t * pObj, float * Odr)
Get the LSM6DSL accelerometer sensor output data rate.
Parameters
pObj the device pObj
Odr pointer where the output data rate is written
Return values
0 in case of success, an error code otherwise
LSM6DSL_ACC_GetSensitivity()
int32_t LSM6DSL_ACC_GetSensitivity (LSM6DSL_Object_t * pObj, float * Sensitivity)
Get the LSM6DSL accelerometer sensor sensitivity.
Parameters
pObj the device pObj
Sensitivity pointer
Return values
0 in case of success, an error code otherwise
LSM6DSL_ACC_Set_6D_Orientation_Threshold()
int32_t LSM6DSL_ACC_Set_6D_Orientation_Threshold (LSM6DSL_Object_t * pObj, uint8_t Threshold)
Set 6D orientation threshold.
Parameters
pObj the device pObj
Threshold 6D Orientation detection threshold
Return values
0 in case of success, an error code otherwise
References lsm6dsl_6d_threshold_set().
LSM6DSL_ACC_Set_Free_Fall_Duration()
int32_t LSM6DSL_ACC_Set_Free_Fall_Duration (LSM6DSL_Object_t * pObj, uint8_t Duration)
Set free fall duration.
Parameters
pObj the device pObj
Duration free fall detection duration
Return values
0 in case of success, an error code otherwise
References lsm6dsl_ff_dur_set().
LSM6DSL_ACC_Set_Free_Fall_Threshold()
int32_t LSM6DSL_ACC_Set_Free_Fall_Threshold (LSM6DSL_Object_t * pObj, uint8_t Threshold)
Set free fall threshold.
Parameters
pObj the device pObj
Threshold free fall detection threshold
Return values
0 in case of success, an error code otherwise
References lsm6dsl_ff_threshold_set().
LSM6DSL_ACC_Set_INT1_DRDY()
int32_t LSM6DSL_ACC_Set_INT1_DRDY (LSM6DSL_Object_t * pObj, uint8_t Val)
Set DRDY on INT1.
Parameters
pObj the device pObj
Val the value of int1_drdy_xl in reg INT1_CTRL
Return values
0 in case of success, an error code otherwise
References lsm6dsl_pin_int1_route_get().
LSM6DSL_ACC_Set_Pedometer_Threshold()
int32_t LSM6DSL_ACC_Set_Pedometer_Threshold (LSM6DSL_Object_t * pObj, uint8_t Threshold)
Set pedometer threshold.
Parameters
pObj the device pObj
Threshold pedometer threshold
Return values
0 in case of success, an error code otherwise
References lsm6dsl_pedo_threshold_set().
LSM6DSL_ACC_Set_SelfTest()
int32_t LSM6DSL_ACC_Set_SelfTest (LSM6DSL_Object_t * pObj, uint8_t Val)
Set self test.
Parameters
pObj the device pObj
Val the value of st_xl in reg CTRL5_C
Return values
0 in case of success, an error code otherwise
LSM6DSL_ACC_Set_Sleep_Duration()
int32_t LSM6DSL_ACC_Set_Sleep_Duration (LSM6DSL_Object_t * pObj, uint8_t Duration)
Set sleep duration.
Parameters
pObj the device pObj
Duration wake up detection duration
Return values
0 in case of success, an error code otherwise
References lsm6dsl_act_sleep_dur_set().
LSM6DSL_ACC_Set_Tap_Duration_Time()
int32_t LSM6DSL_ACC_Set_Tap_Duration_Time (LSM6DSL_Object_t * pObj, uint8_t Time)
Set tap duration time.
Parameters
pObj the device pObj
Time tap duration time
Return values
0 in case of success, an error code otherwise
References lsm6dsl_tap_dur_set().
LSM6DSL_ACC_Set_Tap_Quiet_Time()
int32_t LSM6DSL_ACC_Set_Tap_Quiet_Time (LSM6DSL_Object_t * pObj, uint8_t Time)
Set tap quiet time.
Parameters
pObj the device pObj
Time tap quiet time
Return values
0 in case of success, an error code otherwise
References lsm6dsl_tap_quiet_set().
LSM6DSL_ACC_Set_Tap_Shock_Time()
int32_t LSM6DSL_ACC_Set_Tap_Shock_Time (LSM6DSL_Object_t * pObj, uint8_t Time)
Set tap shock time.
Parameters
pObj the device pObj
Time tap shock time
Return values
0 in case of success, an error code otherwise
References lsm6dsl_tap_shock_set().
LSM6DSL_ACC_Set_Tap_Threshold()
int32_t LSM6DSL_ACC_Set_Tap_Threshold (LSM6DSL_Object_t * pObj, uint8_t Threshold)
Set tap threshold.
Parameters
pObj the device pObj
Threshold tap threshold
Return values
0 in case of success, an error code otherwise
References lsm6dsl_tap_threshold_x_set().
LSM6DSL_ACC_Set_Wake_Up_Duration()
int32_t LSM6DSL_ACC_Set_Wake_Up_Duration (LSM6DSL_Object_t * pObj, uint8_t Duration)
Set wake up duration.
Parameters
pObj the device pObj
Duration wake up detection duration
Return values
0 in case of success, an error code otherwise
References lsm6dsl_wkup_dur_set().
LSM6DSL_ACC_Set_Wake_Up_Threshold()
int32_t LSM6DSL_ACC_Set_Wake_Up_Threshold (LSM6DSL_Object_t * pObj, uint8_t Threshold)
Set wake up threshold.
Parameters
pObj the device pObj
Threshold wake up detection threshold
Return values
0 in case of success, an error code otherwise
References lsm6dsl_wkup_threshold_set().
LSM6DSL_ACC_SetFullScale()
int32_t LSM6DSL_ACC_SetFullScale (LSM6DSL_Object_t * pObj, int32_t FullScale)
Set the LSM6DSL accelerometer sensor full scale.
Parameters
pObj the device pObj
FullScale the functional full scale to be set
Return values
0 in case of success, an error code otherwise
LSM6DSL_ACC_SetOutputDataRate()
int32_t LSM6DSL_ACC_SetOutputDataRate (LSM6DSL_Object_t * pObj, float Odr)
Set the LSM6DSL accelerometer sensor output data rate.
Parameters
pObj the device pObj
Odr the output data rate value to be set
Return values
0 in case of success, an error code otherwise
References LSM6DSL_ACC_SetOutputDataRate_When_Disabled(), and LSM6DSL_ACC_SetOutputDataRate_When_Enabled().
Referenced by LSM6DSL_ACC_Enable_Pedometer().
LSM6DSL_DeInit()
int32_t LSM6DSL_DeInit (LSM6DSL_Object_t * pObj)
Deinitialize the LSM6DSL sensor.
Parameters
pObj the device pObj
Return values
0 in case of success, an error code otherwise
References LSM6DSL_ACC_Disable().
LSM6DSL_FIFO_ACC_Get_Axis()
int32_t LSM6DSL_FIFO_ACC_Get_Axis (LSM6DSL_Object_t * pObj, int32_t * Acceleration)
Get the LSM6DSL FIFO accelero single sample (16-bit data) and calculate acceleration [mg].
Parameters
pObj the device pObj
Acceleration FIFO single accelero axis [mg]
Return values
0 in case of success, an error code otherwise
References LSM6DSL_FIFO_Get_Data().
LSM6DSL_FIFO_ACC_Set_Decimation()
int32_t LSM6DSL_FIFO_ACC_Set_Decimation (LSM6DSL_Object_t * pObj, uint8_t Decimation)
Set the LSM6DSL FIFO accelero decimation.
Parameters
pObj the device pObj
Decimation FIFO accelero decimation
Return values
0 in case of success, an error code otherwise
LSM6DSL_FIFO_Get_Data()
int32_t LSM6DSL_FIFO_Get_Data (LSM6DSL_Object_t * pObj, uint8_t * Data)
Get the LSM6DSL FIFO raw data.
Parameters
pObj the device pObj
Data FIFO raw data array [2]
Return values
0 in case of success, an error code otherwise
References lsm6dsl_read_reg().
Referenced by LSM6DSL_FIFO_ACC_Get_Axis(), and LSM6DSL_FIFO_GYRO_Get_Axis().
LSM6DSL_FIFO_Get_Full_Status()
int32_t LSM6DSL_FIFO_Get_Full_Status (LSM6DSL_Object_t * pObj, uint8_t * Status)
Get the LSM6DSL FIFO full status.
Parameters
pObj the device pObj
Status FIFO full status
Return values
0 in case of success, an error code otherwise
References lsm6dsl_read_reg().
LSM6DSL_FIFO_Get_Num_Samples()
int32_t LSM6DSL_FIFO_Get_Num_Samples (LSM6DSL_Object_t * pObj, uint16_t * NumSamples)
Get the LSM6DSL FIFO number of samples.
Parameters
pObj the device pObj
NumSamples number of samples
Return values
0 in case of success, an error code otherwise
References lsm6dsl_fifo_data_level_get().
LSM6DSL_FIFO_Get_Pattern()
int32_t LSM6DSL_FIFO_Get_Pattern (LSM6DSL_Object_t * pObj, uint16_t * Pattern)
Get the LSM6DSL FIFO pattern.
Parameters
pObj the device pObj
Pattern FIFO pattern
Return values
0 in case of success, an error code otherwise
References lsm6dsl_fifo_pattern_get().
LSM6DSL_FIFO_GYRO_Get_Axis()
int32_t LSM6DSL_FIFO_GYRO_Get_Axis (LSM6DSL_Object_t * pObj, int32_t * AngularVelocity)
Get the LSM6DSL FIFO gyro single sample (16-bit data) and calculate angular velocity [mDPS].
Parameters
pObj the device pObj
AngularVelocity FIFO single gyro axis [mDPS]
Return values
0 in case of success, an error code otherwise
References LSM6DSL_FIFO_Get_Data().
LSM6DSL_FIFO_GYRO_Set_Decimation()
int32_t LSM6DSL_FIFO_GYRO_Set_Decimation (LSM6DSL_Object_t * pObj, uint8_t Decimation)
Set the LSM6DSL FIFO gyro decimation.
Parameters
pObj the device pObj
Decimation FIFO gyro decimation
Return values
0 in case of success, an error code otherwise
LSM6DSL_FIFO_Set_INT1_FIFO_Full()
int32_t LSM6DSL_FIFO_Set_INT1_FIFO_Full (LSM6DSL_Object_t * pObj, uint8_t Status)
Set the LSM6DSL FIFO full interrupt on INT1 pin.
Parameters
pObj the device pObj
Status FIFO full interrupt on INT1 pin status
Return values
0 in case of success, an error code otherwise
References lsm6dsl_read_reg().
LSM6DSL_FIFO_Set_Mode()
int32_t LSM6DSL_FIFO_Set_Mode (LSM6DSL_Object_t * pObj, uint8_t Mode)
Set the LSM6DSL FIFO mode.
Parameters
pObj the device pObj
Mode FIFO mode
Return values
0 in case of success, an error code otherwise
LSM6DSL_FIFO_Set_ODR_Value()
int32_t LSM6DSL_FIFO_Set_ODR_Value (LSM6DSL_Object_t * pObj, float Odr)
Set the LSM6DSL FIFO ODR value.
Parameters
pObj the device pObj
Odr FIFO ODR value
Return values
0 in case of success, an error code otherwise
LSM6DSL_FIFO_Set_Stop_On_Fth()
int32_t LSM6DSL_FIFO_Set_Stop_On_Fth (LSM6DSL_Object_t * pObj, uint8_t Status)
Set the LSM6DSL FIFO stop on watermark.
Parameters
pObj the device pObj
Status FIFO stop on watermark status
Return values
0 in case of success, an error code otherwise
References lsm6dsl_fifo_stop_on_wtm_set().
LSM6DSL_FIFO_Set_Watermark_Level()
int32_t LSM6DSL_FIFO_Set_Watermark_Level (LSM6DSL_Object_t * pObj, uint16_t Watermark)
Set the LSM6DSL FIFO watermark level.
Parameters
pObj the device pObj
Watermark FIFO watermark level
Return values
0 in case of success, an error code otherwise
References lsm6dsl_fifo_watermark_set().
LSM6DSL_GetCapabilities()
int32_t LSM6DSL_GetCapabilities (LSM6DSL_Object_t * pObj, LSM6DSL_Capabilities_t * Capabilities)
Get LSM6DSL sensor capabilities.
Parameters
pObj Component object pointer
Capabilities pointer to LSM6DSL sensor capabilities
Return values
0 in case of success, an error code otherwise
LSM6DSL_GYRO_Disable()
int32_t LSM6DSL_GYRO_Disable (LSM6DSL_Object_t * pObj)
Disable the LSM6DSL gyroscope sensor.
Parameters
pObj the device pObj
Return values
0 in case of success, an error code otherwise
LSM6DSL_GYRO_Enable()
int32_t LSM6DSL_GYRO_Enable (LSM6DSL_Object_t * pObj)
Enable the LSM6DSL gyroscope sensor.
Parameters
pObj the device pObj
Return values
0 in case of success, an error code otherwise
LSM6DSL_GYRO_Get_DRDY_Status()
int32_t LSM6DSL_GYRO_Get_DRDY_Status (LSM6DSL_Object_t * pObj, uint8_t * Status)
Get the LSM6DSL GYRO data ready bit value.
Parameters
pObj the device pObj
Status the status of data ready bit
Return values
0 in case of success, an error code otherwise
References lsm6dsl_gy_flag_data_ready_get().
LSM6DSL_GYRO_Get_Init_Status()
int32_t LSM6DSL_GYRO_Get_Init_Status (LSM6DSL_Object_t * pObj, uint8_t * Status)
Get the LSM6DSL GYRO initialization status.
Parameters
pObj the device pObj
Status 1 if initialized, 0 otherwise
Return values
0 in case of success, an error code otherwise
LSM6DSL_GYRO_GetAxes()
int32_t LSM6DSL_GYRO_GetAxes (LSM6DSL_Object_t * pObj, LSM6DSL_Axes_t * AngularRate)
Get the LSM6DSL gyroscope sensor axes.
Parameters
pObj the device pObj
AngularRate pointer where the values of the axes are written
Return values
0 in case of success, an error code otherwise
References lsm6dsl_angular_rate_raw_get().
LSM6DSL_GYRO_GetAxesRaw()
int32_t LSM6DSL_GYRO_GetAxesRaw (LSM6DSL_Object_t * pObj, LSM6DSL_AxesRaw_t * Value)
Get the LSM6DSL gyroscope sensor raw axes.
Parameters
pObj the device pObj
Value pointer where the raw values of the axes are written
Return values
0 in case of success, an error code otherwise
References lsm6dsl_angular_rate_raw_get().
LSM6DSL_GYRO_GetFullScale()
int32_t LSM6DSL_GYRO_GetFullScale (LSM6DSL_Object_t * pObj, int32_t * FullScale)
Get the LSM6DSL gyroscope sensor full scale.
Parameters
pObj the device pObj
FullScale pointer where the full scale is written
Return values
0 in case of success, an error code otherwise
LSM6DSL_GYRO_GetOutputDataRate()
int32_t LSM6DSL_GYRO_GetOutputDataRate (LSM6DSL_Object_t * pObj, float * Odr)
Get the LSM6DSL gyroscope sensor output data rate.
Parameters
pObj the device pObj
Odr pointer where the output data rate is written
Return values
0 in case of success, an error code otherwise
LSM6DSL_GYRO_GetSensitivity()
int32_t LSM6DSL_GYRO_GetSensitivity (LSM6DSL_Object_t * pObj, float * Sensitivity)
Get the LSM6DSL gyroscope sensor sensitivity.
Parameters
pObj the device pObj
Sensitivity pointer
Return values
0 in case of success, an error code otherwise
LSM6DSL_GYRO_Set_INT1_DRDY()
int32_t LSM6DSL_GYRO_Set_INT1_DRDY (LSM6DSL_Object_t * pObj, uint8_t Val)
Set DRDY on INT1.
Parameters
pObj the device pObj
Val the value of int1_drdy_g in reg INT1_CTRL
Return values
0 in case of success, an error code otherwise
References lsm6dsl_pin_int1_route_get().
LSM6DSL_GYRO_Set_SelfTest()
int32_t LSM6DSL_GYRO_Set_SelfTest (LSM6DSL_Object_t * pObj, uint8_t Val)
Set self test.
Parameters
pObj the device pObj
Val the value of st_xl in reg CTRL5_C
Return values
0 in case of success, an error code otherwise
LSM6DSL_GYRO_SetFullScale()
int32_t LSM6DSL_GYRO_SetFullScale (LSM6DSL_Object_t * pObj, int32_t FullScale)
Set the LSM6DSL gyroscope sensor full scale.
Parameters
pObj the device pObj
FullScale the functional full scale to be set
Return values
0 in case of success, an error code otherwise
LSM6DSL_GYRO_SetOutputDataRate()
int32_t LSM6DSL_GYRO_SetOutputDataRate (LSM6DSL_Object_t * pObj, float Odr)
Set the LSM6DSL gyroscope sensor output data rate.
Parameters
pObj the device pObj
Odr the output data rate value to be set
Return values
0 in case of success, an error code otherwise
References LSM6DSL_GYRO_SetOutputDataRate_When_Disabled(), and LSM6DSL_GYRO_SetOutputDataRate_When_Enabled().
LSM6DSL_Init()
int32_t LSM6DSL_Init (LSM6DSL_Object_t * pObj)
Initialize the LSM6DSL sensor.
Parameters
pObj the device pObj
Return values
0 in case of success, an error code otherwise
References lsm6dsl_auto_increment_set().
LSM6DSL_Read_Reg()
int32_t LSM6DSL_Read_Reg (LSM6DSL_Object_t * pObj, uint8_t Reg, uint8_t * Data)
Get the LSM6DSL register value.
Parameters
pObj the device pObj
Reg address to be read
Data pointer where the value is written
Return values
0 in case of success, an error code otherwise
References lsm6dsl_read_reg().
LSM6DSL_ReadID()
int32_t LSM6DSL_ReadID (LSM6DSL_Object_t * pObj, uint8_t * Id)
Read component ID.
Parameters
pObj the device pObj
Id the WHO_AM_I value
Return values
0 in case of success, an error code otherwise
References lsm6dsl_device_id_get().
LSM6DSL_RegisterBusIO()
int32_t LSM6DSL_RegisterBusIO (LSM6DSL_Object_t * pObj, LSM6DSL_IO_t * pIO)
Register Component Bus IO operations.
Parameters
pObj the device pObj
Return values
0 in case of success, an error code otherwise
LSM6DSL_Set_DRDY_Mode()
int32_t LSM6DSL_Set_DRDY_Mode (LSM6DSL_Object_t * pObj, uint8_t Val)
Set DRDY mode.
Parameters
pObj the device pObj
Val the value of drdy_pulsed in reg LSM6DSL_DRDY_PULSE_CFG_G
Return values
0 in case of success, an error code otherwise
LSM6DSL_Set_Interrupt_Latch()
int32_t LSM6DSL_Set_Interrupt_Latch (LSM6DSL_Object_t * pObj, uint8_t Status)
Set the interrupt latch.
Parameters
pObj the device pObj
Status value to be written
Return values
0 in case of success, an error code otherwise
LSM6DSL_Write_Reg()
int32_t LSM6DSL_Write_Reg (LSM6DSL_Object_t * pObj, uint8_t Reg, uint8_t Data)
Set the LSM6DSL register value.
Parameters
pObj the device pObj
Reg address to be written
Data value to be written
Return values
0 in case of success, an error code otherwise
References lsm6dsl_write_reg().