Sensor de vibração MQTT - Trabalho de conclusão de curso: LSM6DSL_free_fall
LSM6DSL_free_fall
BSP » Component » LSM6DSL
This section group all the functions concerning the free fall detection.
Functions
int32_t lsm6dsl_ff_dur_set (stmdev_ctx_t *ctx, uint8_t val)
Free-fall duration event. 1LSb = 1 / ODR[set].
int32_t lsm6dsl_ff_dur_get (stmdev_ctx_t *ctx, uint8_t *val)
Free-fall duration event. 1LSb = 1 / ODR[get].
int32_t lsm6dsl_ff_threshold_set (stmdev_ctx_t *ctx, lsm6dsl_ff_ths_t val)
Free fall threshold setting.[set].
int32_t lsm6dsl_ff_threshold_get (stmdev_ctx_t *ctx, lsm6dsl_ff_ths_t *val)
Free fall threshold setting.[get].
Detailed Description
This section group all the functions concerning the free fall detection.
Function Documentation
lsm6dsl_ff_dur_get()
int32_t lsm6dsl_ff_dur_get (stmdev_ctx_t * ctx, uint8_t * val)
Free-fall duration event. 1LSb = 1 / ODR[get].
Parameters
ctx Read / write interface definitions
val Change the values of ff_dur in reg WAKE_UP_DUR
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_ff_dur_set()
int32_t lsm6dsl_ff_dur_set (stmdev_ctx_t * ctx, uint8_t val)
Free-fall duration event. 1LSb = 1 / ODR[set].
Parameters
ctx Read / write interface definitions
val Change the values of ff_dur in reg WAKE_UP_DUR
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Set_Free_Fall_Duration().
lsm6dsl_ff_threshold_get()
int32_t lsm6dsl_ff_threshold_get (stmdev_ctx_t * ctx, lsm6dsl_ff_ths_t * val)
Free fall threshold setting.[get].
Parameters
ctx Read / write interface definitions
val Get the values of ff_ths in reg FREE_FALL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_ff_threshold_set()
int32_t lsm6dsl_ff_threshold_set (stmdev_ctx_t * ctx, lsm6dsl_ff_ths_t val)
Free fall threshold setting.[set].
Parameters
ctx Read / write interface definitions
val Change the values of ff_ths in reg FREE_FALL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Set_Free_Fall_Threshold().