Sensor de vibração MQTT - Trabalho de conclusão de curso: LSM6DSL_Sensor_hub
LSM6DSL_Sensor_hub
BSP » Component » LSM6DSL
This section groups all the functions that manage the sensor hub functionality.
Functions
int32_t lsm6dsl_func_en_set (stmdev_ctx_t *ctx, uint8_t val)
Enable function.[set].
int32_t lsm6dsl_sh_sync_sens_frame_set (stmdev_ctx_t *ctx, uint8_t val)
Sensor synchronization time frame with the step of 500 ms and full range of 5s. Unsigned 8-bit.[set].
int32_t lsm6dsl_sh_sync_sens_frame_get (stmdev_ctx_t *ctx, uint8_t *val)
Sensor synchronization time frame with the step of 500 ms and full range of 5s. Unsigned 8-bit.[get].
int32_t lsm6dsl_sh_sync_sens_ratio_set (stmdev_ctx_t *ctx, lsm6dsl_rr_t val)
Resolution ratio of error code for sensor synchronization.[set].
int32_t lsm6dsl_sh_sync_sens_ratio_get (stmdev_ctx_t *ctx, lsm6dsl_rr_t *val)
Resolution ratio of error code for sensor synchronization.[get].
int32_t lsm6dsl_sh_master_set (stmdev_ctx_t *ctx, uint8_t val)
Sensor hub I2C master enable.[set].
int32_t lsm6dsl_sh_master_get (stmdev_ctx_t *ctx, uint8_t *val)
Sensor hub I2C master enable.[get].
int32_t lsm6dsl_sh_pass_through_set (stmdev_ctx_t *ctx, uint8_t val)
I2C interface pass-through.[set].
int32_t lsm6dsl_sh_pass_through_get (stmdev_ctx_t *ctx, uint8_t *val)
I2C interface pass-through.[get].
int32_t lsm6dsl_sh_pin_mode_set (stmdev_ctx_t *ctx, lsm6dsl_pull_up_en_t val)
Master I2C pull-up enable/disable.[set].
int32_t lsm6dsl_sh_pin_mode_get (stmdev_ctx_t *ctx, lsm6dsl_pull_up_en_t *val)
Master I2C pull-up enable/disable.[get].
int32_t lsm6dsl_sh_syncro_mode_set (stmdev_ctx_t *ctx, lsm6dsl_start_config_t val)
Sensor hub trigger signal selection.[set].
int32_t lsm6dsl_sh_syncro_mode_get (stmdev_ctx_t *ctx, lsm6dsl_start_config_t *val)
Sensor hub trigger signal selection.[get].
int32_t lsm6dsl_sh_drdy_on_int1_set (stmdev_ctx_t *ctx, uint8_t val)
Manage the Master DRDY signal on INT1 pad.[set].
int32_t lsm6dsl_sh_drdy_on_int1_get (stmdev_ctx_t *ctx, uint8_t *val)
Manage the Master DRDY signal on INT1 pad.[get].
int32_t lsm6dsl_sh_read_data_raw_get (stmdev_ctx_t *ctx, lsm6dsl_emb_sh_read_t *val)
Sensor hub output registers.[get].
int32_t lsm6dsl_sh_cmd_sens_sync_set (stmdev_ctx_t *ctx, uint8_t val)
Master command code used for stamping for sensor sync.[set].
int32_t lsm6dsl_sh_cmd_sens_sync_get (stmdev_ctx_t *ctx, uint8_t *val)
Master command code used for stamping for sensor sync.[get].
int32_t lsm6dsl_sh_spi_sync_error_set (stmdev_ctx_t *ctx, uint8_t val)
Error code used for sensor synchronization.[set].
int32_t lsm6dsl_sh_spi_sync_error_get (stmdev_ctx_t *ctx, uint8_t *val)
Error code used for sensor synchronization.[get].
int32_t lsm6dsl_sh_num_of_dev_connected_set (stmdev_ctx_t *ctx, lsm6dsl_aux_sens_on_t val)
Number of external sensors to be read by the sensor hub.[set].
int32_t lsm6dsl_sh_num_of_dev_connected_get (stmdev_ctx_t *ctx, lsm6dsl_aux_sens_on_t *val)
Number of external sensors to be read by the sensor hub.[get].
int32_t lsm6dsl_sh_cfg_write (stmdev_ctx_t *ctx, lsm6dsl_sh_cfg_write_t *val)
Configure slave 0 for perform a write.[set].
int32_t lsm6dsl_sh_slv0_cfg_read (stmdev_ctx_t *ctx, lsm6dsl_sh_cfg_read_t *val)
Configure slave 0 for perform a read.[get].
int32_t lsm6dsl_sh_slv1_cfg_read (stmdev_ctx_t *ctx, lsm6dsl_sh_cfg_read_t *val)
Configure slave 1 for perform a read.[get].
int32_t lsm6dsl_sh_slv2_cfg_read (stmdev_ctx_t *ctx, lsm6dsl_sh_cfg_read_t *val)
Configure slave 2 for perform a read.[get].
int32_t lsm6dsl_sh_slv3_cfg_read (stmdev_ctx_t *ctx, lsm6dsl_sh_cfg_read_t *val)
Configure slave 3 for perform a read.[get].
int32_t lsm6dsl_sh_slave_0_dec_set (stmdev_ctx_t *ctx, lsm6dsl_slave0_rate_t val)
Decimation of read operation on Slave 0 starting from the sensor hub trigger.[set].
int32_t lsm6dsl_sh_slave_0_dec_get (stmdev_ctx_t *ctx, lsm6dsl_slave0_rate_t *val)
Decimation of read operation on Slave 0 starting from the sensor hub trigger.[get].
int32_t lsm6dsl_sh_write_mode_set (stmdev_ctx_t *ctx, lsm6dsl_write_once_t val)
Slave 0 write operation is performed only at the first sensor hub cycle. This is effective if the Aux_sens_on[1:0] field in SLAVE0_CONFIG(04h) is set to a value other than 00.[set].
int32_t lsm6dsl_sh_write_mode_get (stmdev_ctx_t *ctx, lsm6dsl_write_once_t *val)
Slave 0 write operation is performed only at the first sensor hub cycle. This is effective if the Aux_sens_on[1:0] field in SLAVE0_CONFIG(04h) is set to a value other than 00.[get].
int32_t lsm6dsl_sh_slave_1_dec_set (stmdev_ctx_t *ctx, lsm6dsl_slave1_rate_t val)
Decimation of read operation on Slave 1 starting from the sensor hub trigger.[set].
int32_t lsm6dsl_sh_slave_1_dec_get (stmdev_ctx_t *ctx, lsm6dsl_slave1_rate_t *val)
Decimation of read operation on Slave 1 starting from the sensor hub trigger.[get].
int32_t lsm6dsl_sh_slave_2_dec_set (stmdev_ctx_t *ctx, lsm6dsl_slave2_rate_t val)
Decimation of read operation on Slave 2 starting from the sensor hub trigger.[set].
int32_t lsm6dsl_sh_slave_2_dec_get (stmdev_ctx_t *ctx, lsm6dsl_slave2_rate_t *val)
Decimation of read operation on Slave 2 starting from the sensor hub trigger.[get].
int32_t lsm6dsl_sh_slave_3_dec_set (stmdev_ctx_t *ctx, lsm6dsl_slave3_rate_t val)
Decimation of read operation on Slave 3 starting from the sensor hub trigger.[set].
int32_t lsm6dsl_sh_slave_3_dec_get (stmdev_ctx_t *ctx, lsm6dsl_slave3_rate_t *val)
Decimation of read operation on Slave 3 starting from the sensor hub trigger.[get].
Detailed Description
This section groups all the functions that manage the sensor hub functionality.
Function Documentation
lsm6dsl_func_en_set()
int32_t lsm6dsl_func_en_set (stmdev_ctx_t * ctx, uint8_t val)
Enable function.[set].
Parameters
ctx Read / write interface definitions
val Change the values func_en
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_cfg_write()
int32_t lsm6dsl_sh_cfg_write (stmdev_ctx_t * ctx, lsm6dsl_sh_cfg_write_t * val)
Configure slave 0 for perform a write.[set].
Parameters
ctx Read / write interface definitions
val Structure that contain:
uint8_t slv_add; 8 bit i2c device address
uint8_t slv_subadd; 8 bit register device address
uint8_t slv_data; 8 bit data to write
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_cmd_sens_sync_get()
int32_t lsm6dsl_sh_cmd_sens_sync_get (stmdev_ctx_t * ctx, uint8_t * val)
Master command code used for stamping for sensor sync.[get].
Parameters
ctx Read / write interface definitions
val Change the values of master_cmd_code in reg MASTER_CMD_CODE
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_cmd_sens_sync_set()
int32_t lsm6dsl_sh_cmd_sens_sync_set (stmdev_ctx_t * ctx, uint8_t val)
Master command code used for stamping for sensor sync.[set].
Parameters
ctx Read / write interface definitions
val Change the values of master_cmd_code in reg MASTER_CMD_CODE
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_drdy_on_int1_get()
int32_t lsm6dsl_sh_drdy_on_int1_get (stmdev_ctx_t * ctx, uint8_t * val)
Manage the Master DRDY signal on INT1 pad.[get].
Parameters
ctx Read / write interface definitions
val Change the values of drdy_on_int1 in reg MASTER_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_drdy_on_int1_set()
int32_t lsm6dsl_sh_drdy_on_int1_set (stmdev_ctx_t * ctx, uint8_t val)
Manage the Master DRDY signal on INT1 pad.[set].
Parameters
ctx Read / write interface definitions
val Change the values of drdy_on_int1 in reg MASTER_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_master_get()
int32_t lsm6dsl_sh_master_get (stmdev_ctx_t * ctx, uint8_t * val)
Sensor hub I2C master enable.[get].
Parameters
ctx Read / write interface definitions
val Change the values of master_on in reg MASTER_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_master_set()
int32_t lsm6dsl_sh_master_set (stmdev_ctx_t * ctx, uint8_t val)
Sensor hub I2C master enable.[set].
Parameters
ctx Read / write interface definitions
val Change the values of master_on in reg MASTER_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_num_of_dev_connected_get()
int32_t lsm6dsl_sh_num_of_dev_connected_get (stmdev_ctx_t * ctx, lsm6dsl_aux_sens_on_t * val)
Number of external sensors to be read by the sensor hub.[get].
Parameters
ctx Read / write interface definitions
val Get the values of aux_sens_on in reg SLAVE0_CONFIG.
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_num_of_dev_connected_set()
int32_t lsm6dsl_sh_num_of_dev_connected_set (stmdev_ctx_t * ctx, lsm6dsl_aux_sens_on_t val)
Number of external sensors to be read by the sensor hub.[set].
Parameters
ctx Read / write interface definitions
val Change the values of aux_sens_on in reg SLAVE0_CONFIG.
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_pass_through_get()
int32_t lsm6dsl_sh_pass_through_get (stmdev_ctx_t * ctx, uint8_t * val)
I2C interface pass-through.[get].
Parameters
ctx Read / write interface definitions
val Change the values of pass_through_mode in reg MASTER_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_pass_through_set()
int32_t lsm6dsl_sh_pass_through_set (stmdev_ctx_t * ctx, uint8_t val)
I2C interface pass-through.[set].
Parameters
ctx Read / write interface definitions
val Change the values of pass_through_mode in reg MASTER_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_pin_mode_get()
int32_t lsm6dsl_sh_pin_mode_get (stmdev_ctx_t * ctx, lsm6dsl_pull_up_en_t * val)
Master I2C pull-up enable/disable.[get].
Parameters
ctx Read / write interface definitions
val Get the values of pull_up_en in reg MASTER_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_pin_mode_set()
int32_t lsm6dsl_sh_pin_mode_set (stmdev_ctx_t * ctx, lsm6dsl_pull_up_en_t val)
Master I2C pull-up enable/disable.[set].
Parameters
ctx Read / write interface definitions
val Change the values of pull_up_en in reg MASTER_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_read_data_raw_get()
int32_t lsm6dsl_sh_read_data_raw_get (stmdev_ctx_t * ctx, lsm6dsl_emb_sh_read_t * val)
Sensor hub output registers.[get].
Parameters
ctx Read / write interface definitions
val Structure of registers from SENSORHUB1_REG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_slave_0_dec_get()
int32_t lsm6dsl_sh_slave_0_dec_get (stmdev_ctx_t * ctx, lsm6dsl_slave0_rate_t * val)
Decimation of read operation on Slave 0 starting from the sensor hub trigger.[get].
Parameters
ctx Read / write interface definitions
val Get the values of slave0_rate in reg SLAVE0_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_slave_0_dec_set()
int32_t lsm6dsl_sh_slave_0_dec_set (stmdev_ctx_t * ctx, lsm6dsl_slave0_rate_t val)
Decimation of read operation on Slave 0 starting from the sensor hub trigger.[set].
Parameters
ctx Read / write interface definitions
val Change the values of slave0_rate in reg SLAVE0_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_slave_1_dec_get()
int32_t lsm6dsl_sh_slave_1_dec_get (stmdev_ctx_t * ctx, lsm6dsl_slave1_rate_t * val)
Decimation of read operation on Slave 1 starting from the sensor hub trigger.[get].
Parameters
ctx Read / write interface definitions reg SLAVE1_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_slave_1_dec_set()
int32_t lsm6dsl_sh_slave_1_dec_set (stmdev_ctx_t * ctx, lsm6dsl_slave1_rate_t val)
Decimation of read operation on Slave 1 starting from the sensor hub trigger.[set].
Parameters
ctx Read / write interface definitions
val Change the values of slave1_rate in reg SLAVE1_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_slave_2_dec_get()
int32_t lsm6dsl_sh_slave_2_dec_get (stmdev_ctx_t * ctx, lsm6dsl_slave2_rate_t * val)
Decimation of read operation on Slave 2 starting from the sensor hub trigger.[get].
Parameters
ctx Read / write interface definitions
val Get the values of slave2_rate in reg SLAVE2_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_slave_2_dec_set()
int32_t lsm6dsl_sh_slave_2_dec_set (stmdev_ctx_t * ctx, lsm6dsl_slave2_rate_t val)
Decimation of read operation on Slave 2 starting from the sensor hub trigger.[set].
Parameters
ctx Read / write interface definitions
val Change the values of slave2_rate in reg SLAVE2_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_slave_3_dec_get()
int32_t lsm6dsl_sh_slave_3_dec_get (stmdev_ctx_t * ctx, lsm6dsl_slave3_rate_t * val)
Decimation of read operation on Slave 3 starting from the sensor hub trigger.[get].
Parameters
ctx Read / write interface definitions
val Get the values of slave3_rate in reg SLAVE3_CONFIG.
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_slave_3_dec_set()
int32_t lsm6dsl_sh_slave_3_dec_set (stmdev_ctx_t * ctx, lsm6dsl_slave3_rate_t val)
Decimation of read operation on Slave 3 starting from the sensor hub trigger.[set].
Parameters
ctx Read / write interface definitions
val Change the values of slave3_rate in reg SLAVE3_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_slv0_cfg_read()
int32_t lsm6dsl_sh_slv0_cfg_read (stmdev_ctx_t * ctx, lsm6dsl_sh_cfg_read_t * val)
Configure slave 0 for perform a read.[get].
Parameters
ctx Read / write interface definitions
val Structure that contain:
uint8_t slv_add; 8 bit i2c device address
uint8_t slv_subadd; 8 bit register device address
uint8_t slv_len; num of bit to read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_slv1_cfg_read()
int32_t lsm6dsl_sh_slv1_cfg_read (stmdev_ctx_t * ctx, lsm6dsl_sh_cfg_read_t * val)
Configure slave 1 for perform a read.[get].
Parameters
ctx Read / write interface definitions
val Structure that contain:
uint8_t slv_add; 8 bit i2c device address
uint8_t slv_subadd; 8 bit register device address
uint8_t slv_len; num of bit to read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_slv2_cfg_read()
int32_t lsm6dsl_sh_slv2_cfg_read (stmdev_ctx_t * ctx, lsm6dsl_sh_cfg_read_t * val)
Configure slave 2 for perform a read.[get].
Parameters
ctx Read / write interface definitions
val Structure that contain:
uint8_t slv_add; 8 bit i2c device address
uint8_t slv_subadd; 8 bit register device address
uint8_t slv_len; num of bit to read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_slv3_cfg_read()
int32_t lsm6dsl_sh_slv3_cfg_read (stmdev_ctx_t * ctx, lsm6dsl_sh_cfg_read_t * val)
Configure slave 3 for perform a read.[get].
Parameters
ctx Read / write interface definitions
val Structure that contain:
uint8_t slv_add; 8 bit i2c device address
uint8_t slv_subadd; 8 bit register device address
uint8_t slv_len; num of bit to read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_spi_sync_error_get()
int32_t lsm6dsl_sh_spi_sync_error_get (stmdev_ctx_t * ctx, uint8_t * val)
Error code used for sensor synchronization.[get].
Parameters
ctx Read / write interface definitions
val Change the values of error_code in reg SENS_SYNC_SPI_ERROR_CODE.
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_spi_sync_error_set()
int32_t lsm6dsl_sh_spi_sync_error_set (stmdev_ctx_t * ctx, uint8_t val)
Error code used for sensor synchronization.[set].
Parameters
ctx Read / write interface definitions
val Change the values of error_code in reg SENS_SYNC_SPI_ERROR_CODE.
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_sync_sens_frame_get()
int32_t lsm6dsl_sh_sync_sens_frame_get (stmdev_ctx_t * ctx, uint8_t * val)
Sensor synchronization time frame with the step of 500 ms and full range of 5s. Unsigned 8-bit.[get].
Parameters
ctx Read / write interface definitions
val Change the values of tph in reg SENSOR_SYNC_TIME_FRAME
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_sync_sens_frame_set()
int32_t lsm6dsl_sh_sync_sens_frame_set (stmdev_ctx_t * ctx, uint8_t val)
Sensor synchronization time frame with the step of 500 ms and full range of 5s. Unsigned 8-bit.[set].
Parameters
ctx Read / write interface definitions
val Change the values of tph in reg SENSOR_SYNC_TIME_FRAME
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_sync_sens_ratio_get()
int32_t lsm6dsl_sh_sync_sens_ratio_get (stmdev_ctx_t * ctx, lsm6dsl_rr_t * val)
Resolution ratio of error code for sensor synchronization.[get].
Parameters
ctx Read / write interface definitions
val Get the values of rr in reg SENSOR_SYNC_RES_RATIO
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_sync_sens_ratio_set()
int32_t lsm6dsl_sh_sync_sens_ratio_set (stmdev_ctx_t * ctx, lsm6dsl_rr_t val)
Resolution ratio of error code for sensor synchronization.[set].
Parameters
ctx Read / write interface definitions
val Change the values of rr in reg SENSOR_SYNC_RES_RATIO
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_syncro_mode_get()
int32_t lsm6dsl_sh_syncro_mode_get (stmdev_ctx_t * ctx, lsm6dsl_start_config_t * val)
Sensor hub trigger signal selection.[get].
Parameters
ctx Read / write interface definitions
val Get the values of start_config in reg MASTER_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_syncro_mode_set()
int32_t lsm6dsl_sh_syncro_mode_set (stmdev_ctx_t * ctx, lsm6dsl_start_config_t val)
Sensor hub trigger signal selection.[set].
Parameters
ctx Read / write interface definitions
val Change the values of start_config in reg MASTER_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_write_mode_get()
int32_t lsm6dsl_sh_write_mode_get (stmdev_ctx_t * ctx, lsm6dsl_write_once_t * val)
Slave 0 write operation is performed only at the first sensor hub cycle. This is effective if the Aux_sens_on[1:0] field in SLAVE0_CONFIG(04h) is set to a value other than 00.[get].
Parameters
ctx Read / write interface definitions
val Get the values of write_once in reg SLAVE1_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_write_mode_set()
int32_t lsm6dsl_sh_write_mode_set (stmdev_ctx_t * ctx, lsm6dsl_write_once_t val)
Slave 0 write operation is performed only at the first sensor hub cycle. This is effective if the Aux_sens_on[1:0] field in SLAVE0_CONFIG(04h) is set to a value other than 00.[set].
Parameters
ctx Read / write interface definitions
val Change the values of write_once in reg SLAVE1_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().