Sensor de vibração MQTT - Trabalho de conclusão de curso: LSM6DSL_common
LSM6DSL_common
BSP » Component » LSM6DSL
This section groups common useful functions.
Functions
int32_t lsm6dsl_mem_bank_set (stmdev_ctx_t *ctx, lsm6dsl_func_cfg_en_t val)
Enable access to the embedded functions/sensor hub configuration registers[set].
int32_t lsm6dsl_mem_bank_get (stmdev_ctx_t *ctx, lsm6dsl_func_cfg_en_t *val)
Enable access to the embedded functions/sensor hub configuration registers[get].
int32_t lsm6dsl_data_ready_mode_set (stmdev_ctx_t *ctx, lsm6dsl_drdy_pulsed_g_t val)
Data-ready pulsed / letched mode[set].
int32_t lsm6dsl_data_ready_mode_get (stmdev_ctx_t *ctx, lsm6dsl_drdy_pulsed_g_t *val)
Data-ready pulsed / letched mode[get].
int32_t lsm6dsl_device_id_get (stmdev_ctx_t *ctx, uint8_t *buff)
DeviceWhoamI.[get].
int32_t lsm6dsl_reset_set (stmdev_ctx_t *ctx, uint8_t val)
Software reset. Restore the default values in user registers[set].
int32_t lsm6dsl_reset_get (stmdev_ctx_t *ctx, uint8_t *val)
Software reset. Restore the default values in user registers[get].
int32_t lsm6dsl_data_format_set (stmdev_ctx_t *ctx, lsm6dsl_ble_t val)
Big/Little Endian Data selection.[set].
int32_t lsm6dsl_data_format_get (stmdev_ctx_t *ctx, lsm6dsl_ble_t *val)
Big/Little Endian Data selection.[get].
int32_t lsm6dsl_auto_increment_set (stmdev_ctx_t *ctx, uint8_t val)
Register address automatically incremented during a multiple byte access with a serial interface.[set].
int32_t lsm6dsl_auto_increment_get (stmdev_ctx_t *ctx, uint8_t *val)
Register address automatically incremented during a multiple byte access with a serial interface.[get].
int32_t lsm6dsl_boot_set (stmdev_ctx_t *ctx, uint8_t val)
Reboot memory content. Reload the calibration parameters.[set].
int32_t lsm6dsl_boot_get (stmdev_ctx_t *ctx, uint8_t *val)
Reboot memory content. Reload the calibration parameters.[get].
int32_t lsm6dsl_xl_self_test_set (stmdev_ctx_t *ctx, lsm6dsl_st_xl_t val)
Linear acceleration sensor self-test enable.[set].
int32_t lsm6dsl_xl_self_test_get (stmdev_ctx_t *ctx, lsm6dsl_st_xl_t *val)
Linear acceleration sensor self-test enable.[get].
int32_t lsm6dsl_gy_self_test_set (stmdev_ctx_t *ctx, lsm6dsl_st_g_t val)
Angular rate sensor self-test enable.[set].
int32_t lsm6dsl_gy_self_test_get (stmdev_ctx_t *ctx, lsm6dsl_st_g_t *val)
Angular rate sensor self-test enable.[get].
Detailed Description
This section groups common useful functions.
Function Documentation
lsm6dsl_auto_increment_get()
int32_t lsm6dsl_auto_increment_get (stmdev_ctx_t * ctx, uint8_t * val)
Register address automatically incremented during a multiple byte access with a serial interface.[get].
Parameters
ctx Read / write interface definitions
val Change the values of if_inc in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_auto_increment_set()
int32_t lsm6dsl_auto_increment_set (stmdev_ctx_t * ctx, uint8_t val)
Register address automatically incremented during a multiple byte access with a serial interface.[set].
Parameters
ctx Read / write interface definitions
val Change the values of if_inc in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_Init().
lsm6dsl_boot_get()
int32_t lsm6dsl_boot_get (stmdev_ctx_t * ctx, uint8_t * val)
Reboot memory content. Reload the calibration parameters.[get].
Parameters
ctx Read / write interface definitions
val Change the values of boot in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_boot_set()
int32_t lsm6dsl_boot_set (stmdev_ctx_t * ctx, uint8_t val)
Reboot memory content. Reload the calibration parameters.[set].
Parameters
ctx Read / write interface definitions
val Change the values of boot in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_data_format_get()
int32_t lsm6dsl_data_format_get (stmdev_ctx_t * ctx, lsm6dsl_ble_t * val)
Big/Little Endian Data selection.[get].
Parameters
ctx Read / write interface definitions
val Get the values of ble in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_data_format_set()
int32_t lsm6dsl_data_format_set (stmdev_ctx_t * ctx, lsm6dsl_ble_t val)
Big/Little Endian Data selection.[set].
Parameters
ctx Read / write interface definitions
val Change the values of ble in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_data_ready_mode_get()
int32_t lsm6dsl_data_ready_mode_get (stmdev_ctx_t * ctx, lsm6dsl_drdy_pulsed_g_t * val)
Data-ready pulsed / letched mode[get].
Parameters
ctx Read / write interface definitions
val Get the values of drdy_pulsed in reg DRDY_PULSE_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_data_ready_mode_set()
int32_t lsm6dsl_data_ready_mode_set (stmdev_ctx_t * ctx, lsm6dsl_drdy_pulsed_g_t val)
Data-ready pulsed / letched mode[set].
Parameters
ctx Read / write interface definitions
val Change the values of drdy_pulsed in reg DRDY_PULSE_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_device_id_get()
int32_t lsm6dsl_device_id_get (stmdev_ctx_t * ctx, uint8_t * buff)
DeviceWhoamI.[get].
Parameters
ctx Read / write interface definitions
buff Buffer that stores data read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ReadID().
lsm6dsl_gy_self_test_get()
int32_t lsm6dsl_gy_self_test_get (stmdev_ctx_t * ctx, lsm6dsl_st_g_t * val)
Angular rate sensor self-test enable.[get].
Parameters
ctx Read / write interface definitions
val Get the values of st_g in reg CTRL5_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_gy_self_test_set()
int32_t lsm6dsl_gy_self_test_set (stmdev_ctx_t * ctx, lsm6dsl_st_g_t val)
Angular rate sensor self-test enable.[set].
Parameters
ctx Read / write interface definitions
val Change the values of st_g in reg CTRL5_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_mem_bank_get()
int32_t lsm6dsl_mem_bank_get (stmdev_ctx_t * ctx, lsm6dsl_func_cfg_en_t * val)
Enable access to the embedded functions/sensor hub configuration registers[get].
Parameters
ctx Read / write interface definitions
val Get the values of func_cfg_en in reg FUNC_CFG_ACCESS
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_mem_bank_set()
int32_t lsm6dsl_mem_bank_set (stmdev_ctx_t * ctx, lsm6dsl_func_cfg_en_t val)
Enable access to the embedded functions/sensor hub configuration registers[set].
Parameters
ctx Read / write interface definitions
val Change the values of func_cfg_en in reg FUNC_CFG_ACCESS
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by lsm6dsl_mag_offset_get(), lsm6dsl_mag_offset_set(), lsm6dsl_mag_soft_iron_mat_get(), lsm6dsl_mag_soft_iron_mat_set(), lsm6dsl_motion_threshold_get(), lsm6dsl_motion_threshold_set(), lsm6dsl_pedo_debounce_steps_get(), lsm6dsl_pedo_debounce_steps_set(), lsm6dsl_pedo_full_scale_get(), lsm6dsl_pedo_full_scale_set(), lsm6dsl_pedo_steps_period_get(), lsm6dsl_pedo_steps_period_set(), lsm6dsl_pedo_threshold_get(), lsm6dsl_pedo_threshold_set(), lsm6dsl_pedo_timeout_get(), lsm6dsl_pedo_timeout_set(), lsm6dsl_sh_cfg_write(), lsm6dsl_sh_num_of_dev_connected_get(), lsm6dsl_sh_num_of_dev_connected_set(), lsm6dsl_sh_slave_0_dec_get(), lsm6dsl_sh_slave_0_dec_set(), lsm6dsl_sh_slave_1_dec_get(), lsm6dsl_sh_slave_1_dec_set(), lsm6dsl_sh_slave_2_dec_get(), lsm6dsl_sh_slave_2_dec_set(), lsm6dsl_sh_slave_3_dec_get(), lsm6dsl_sh_slave_3_dec_set(), lsm6dsl_sh_slv0_cfg_read(), lsm6dsl_sh_slv1_cfg_read(), lsm6dsl_sh_slv2_cfg_read(), lsm6dsl_sh_slv3_cfg_read(), lsm6dsl_sh_write_mode_get(), lsm6dsl_sh_write_mode_set(), lsm6dsl_tilt_latency_get(), lsm6dsl_tilt_latency_set(), lsm6dsl_tilt_src_get(), lsm6dsl_tilt_src_set(), lsm6dsl_tilt_threshold_get(), and lsm6dsl_tilt_threshold_set().
lsm6dsl_reset_get()
int32_t lsm6dsl_reset_get (stmdev_ctx_t * ctx, uint8_t * val)
Software reset. Restore the default values in user registers[get].
Parameters
ctx Read / write interface definitions
val Change the values of sw_reset in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_reset_set()
int32_t lsm6dsl_reset_set (stmdev_ctx_t * ctx, uint8_t val)
Software reset. Restore the default values in user registers[set].
Parameters
ctx Read / write interface definitions
val Change the values of sw_reset in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_self_test_get()
int32_t lsm6dsl_xl_self_test_get (stmdev_ctx_t * ctx, lsm6dsl_st_xl_t * val)
Linear acceleration sensor self-test enable.[get].
Parameters
ctx Read / write interface definitions
val Get the values of st_xl in reg CTRL5_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_self_test_set()
int32_t lsm6dsl_xl_self_test_set (stmdev_ctx_t * ctx, lsm6dsl_st_xl_t val)
Linear acceleration sensor self-test enable.[set].
Parameters
ctx Read / write interface definitions
val Change the values of st_xl in reg CTRL5_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().