Sensor de vibração MQTT - Trabalho de conclusão de curso: LSM6DSL_Timestamp
LSM6DSL_Timestamp
BSP » Component » LSM6DSL
This section groups all the functions that manage the timestamp generation.
Functions
int32_t lsm6dsl_timestamp_set (stmdev_ctx_t *ctx, uint8_t val)
Enable timestamp count. The count is saved in TIMESTAMP0_REG (40h), TIMESTAMP1_REG (41h) and TIMESTAMP2_REG (42h).[set].
int32_t lsm6dsl_timestamp_get (stmdev_ctx_t *ctx, uint8_t *val)
Enable timestamp count. The count is saved in TIMESTAMP0_REG (40h), TIMESTAMP1_REG (41h) and TIMESTAMP2_REG (42h).[get].
int32_t lsm6dsl_timestamp_res_set (stmdev_ctx_t *ctx, lsm6dsl_timer_hr_t val)
Timestamp register resolution setting. Configuration of this bit affects TIMESTAMP0_REG(40h), TIMESTAMP1_REG(41h), TIMESTAMP2_REG(42h), STEP_TIMESTAMP_L(49h), STEP_TIMESTAMP_H(4Ah) and STEP_COUNT_DELTA(15h) registers.[set].
int32_t lsm6dsl_timestamp_res_get (stmdev_ctx_t *ctx, lsm6dsl_timer_hr_t *val)
Timestamp register resolution setting. Configuration of this bit affects TIMESTAMP0_REG(40h), TIMESTAMP1_REG(41h), TIMESTAMP2_REG(42h), STEP_TIMESTAMP_L(49h), STEP_TIMESTAMP_H(4Ah) and STEP_COUNT_DELTA(15h) registers.[get].
Detailed Description
This section groups all the functions that manage the timestamp generation.
Function Documentation
lsm6dsl_timestamp_get()
int32_t lsm6dsl_timestamp_get (stmdev_ctx_t * ctx, uint8_t * val)
Enable timestamp count. The count is saved in TIMESTAMP0_REG (40h), TIMESTAMP1_REG (41h) and TIMESTAMP2_REG (42h).[get].
Parameters
ctx Read / write interface definitions
val Change the values of timer_en in reg CTRL10_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_timestamp_res_get()
int32_t lsm6dsl_timestamp_res_get (stmdev_ctx_t * ctx, lsm6dsl_timer_hr_t * val)
Timestamp register resolution setting. Configuration of this bit affects TIMESTAMP0_REG(40h), TIMESTAMP1_REG(41h), TIMESTAMP2_REG(42h), STEP_TIMESTAMP_L(49h), STEP_TIMESTAMP_H(4Ah) and STEP_COUNT_DELTA(15h) registers.[get].
Parameters
ctx Read / write interface definitions
val Get the values of timer_hr in reg WAKE_UP_DUR
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_timestamp_res_set()
int32_t lsm6dsl_timestamp_res_set (stmdev_ctx_t * ctx, lsm6dsl_timer_hr_t val)
Timestamp register resolution setting. Configuration of this bit affects TIMESTAMP0_REG(40h), TIMESTAMP1_REG(41h), TIMESTAMP2_REG(42h), STEP_TIMESTAMP_L(49h), STEP_TIMESTAMP_H(4Ah) and STEP_COUNT_DELTA(15h) registers.[set].
Parameters
ctx Read / write interface definitions
val Change the values of timer_hr in reg WAKE_UP_DUR
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_timestamp_set()
int32_t lsm6dsl_timestamp_set (stmdev_ctx_t * ctx, uint8_t val)
Enable timestamp count. The count is saved in TIMESTAMP0_REG (40h), TIMESTAMP1_REG (41h) and TIMESTAMP2_REG (42h).[set].
Parameters
ctx Read / write interface definitions
val Change the values of timer_en in reg CTRL10_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().