Sensor de vibração MQTT - Trabalho de conclusão de curso: LSM6DSL_interrupt_pins
LSM6DSL_interrupt_pins
BSP » Component » LSM6DSL
This section groups all the functions that manage interrupt pins.
Functions
int32_t lsm6dsl_pin_int1_route_set (stmdev_ctx_t *ctx, lsm6dsl_int1_route_t val)
Select the signal that need to route on int1 pad[set].
int32_t lsm6dsl_pin_int1_route_get (stmdev_ctx_t *ctx, lsm6dsl_int1_route_t *val)
Select the signal that need to route on int1 pad[get].
int32_t lsm6dsl_pin_int2_route_set (stmdev_ctx_t *ctx, lsm6dsl_int2_route_t val)
Select the signal that need to route on int2 pad[set].
int32_t lsm6dsl_pin_int2_route_get (stmdev_ctx_t *ctx, lsm6dsl_int2_route_t *val)
Select the signal that need to route on int2 pad[get].
int32_t lsm6dsl_pin_mode_set (stmdev_ctx_t *ctx, lsm6dsl_pp_od_t val)
Push-pull/open drain selection on interrupt pads.[set].
int32_t lsm6dsl_pin_mode_get (stmdev_ctx_t *ctx, lsm6dsl_pp_od_t *val)
Push-pull/open drain selection on interrupt pads.[get].
int32_t lsm6dsl_pin_polarity_set (stmdev_ctx_t *ctx, lsm6dsl_h_lactive_t val)
Interrupt active-high/low.[set].
int32_t lsm6dsl_pin_polarity_get (stmdev_ctx_t *ctx, lsm6dsl_h_lactive_t *val)
Interrupt active-high/low.[get].
int32_t lsm6dsl_all_on_int1_set (stmdev_ctx_t *ctx, uint8_t val)
All interrupt signals become available on INT1 pin.[set].
int32_t lsm6dsl_all_on_int1_get (stmdev_ctx_t *ctx, uint8_t *val)
All interrupt signals become available on INT1 pin.[get].
int32_t lsm6dsl_int_notification_set (stmdev_ctx_t *ctx, lsm6dsl_lir_t val)
Latched/pulsed interrupt.[set].
int32_t lsm6dsl_int_notification_get (stmdev_ctx_t *ctx, lsm6dsl_lir_t *val)
Latched/pulsed interrupt.[get].
Detailed Description
This section groups all the functions that manage interrupt pins.
Function Documentation
lsm6dsl_all_on_int1_get()
int32_t lsm6dsl_all_on_int1_get (stmdev_ctx_t * ctx, uint8_t * val)
All interrupt signals become available on INT1 pin.[get].
Parameters
ctx Read / write interface definitions
val Change the values of int2_on_int1 in reg CTRL4_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_all_on_int1_set()
int32_t lsm6dsl_all_on_int1_set (stmdev_ctx_t * ctx, uint8_t val)
All interrupt signals become available on INT1 pin.[set].
Parameters
ctx Read / write interface definitions
val Change the values of int2_on_int1 in reg CTRL4_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_int_notification_get()
int32_t lsm6dsl_int_notification_get (stmdev_ctx_t * ctx, lsm6dsl_lir_t * val)
Latched/pulsed interrupt.[get].
Parameters
ctx Read / write interface definitions
val Get the values of lir in reg TAP_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_int_notification_set()
int32_t lsm6dsl_int_notification_set (stmdev_ctx_t * ctx, lsm6dsl_lir_t val)
Latched/pulsed interrupt.[set].
Parameters
ctx Read / write interface definitions
val Change the values of lir in reg TAP_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_pin_int1_route_get()
int32_t lsm6dsl_pin_int1_route_get (stmdev_ctx_t * ctx, lsm6dsl_int1_route_t * val)
Select the signal that need to route on int1 pad[get].
Parameters
ctx Read / write interface definitions
val read INT1_CTRL, MD1_CFG, CTRL4_C(den_drdy_int1), MASTER_CONFIG(drdy_on_int1)
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Disable_6D_Orientation(), LSM6DSL_ACC_Disable_Double_Tap_Detection(), LSM6DSL_ACC_Disable_Free_Fall_Detection(), LSM6DSL_ACC_Disable_Inactivity_Detection(), LSM6DSL_ACC_Disable_Pedometer(), LSM6DSL_ACC_Disable_Single_Tap_Detection(), LSM6DSL_ACC_Disable_Tilt_Detection(), LSM6DSL_ACC_Disable_Wake_Up_Detection(), LSM6DSL_ACC_Set_INT1_DRDY(), and LSM6DSL_GYRO_Set_INT1_DRDY().
lsm6dsl_pin_int1_route_set()
int32_t lsm6dsl_pin_int1_route_set (stmdev_ctx_t * ctx, lsm6dsl_int1_route_t val)
Select the signal that need to route on int1 pad[set].
Parameters
ctx Read / write interface definitions
val configure INT1_CTRL, MD1_CFG, CTRL4_C(den_drdy_int1), MASTER_CONFIG(drdy_on_int1)
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_pin_int2_route_get()
int32_t lsm6dsl_pin_int2_route_get (stmdev_ctx_t * ctx, lsm6dsl_int2_route_t * val)
Select the signal that need to route on int2 pad[get].
Parameters
ctx Read / write interface definitions
val INT2_CTRL, DRDY_PULSE_CFG(int2_wrist_tilt), MD2_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_pin_int2_route_set()
int32_t lsm6dsl_pin_int2_route_set (stmdev_ctx_t * ctx, lsm6dsl_int2_route_t val)
Select the signal that need to route on int2 pad[set].
Parameters
ctx Read / write interface definitions
val INT2_CTRL, DRDY_PULSE_CFG(int2_wrist_tilt), MD2_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_pin_mode_get()
int32_t lsm6dsl_pin_mode_get (stmdev_ctx_t * ctx, lsm6dsl_pp_od_t * val)
Push-pull/open drain selection on interrupt pads.[get].
Parameters
ctx Read / write interface definitions
val Get the values of pp_od in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_pin_mode_set()
int32_t lsm6dsl_pin_mode_set (stmdev_ctx_t * ctx, lsm6dsl_pp_od_t val)
Push-pull/open drain selection on interrupt pads.[set].
Parameters
ctx Read / write interface definitions
val Change the values of pp_od in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_pin_polarity_get()
int32_t lsm6dsl_pin_polarity_get (stmdev_ctx_t * ctx, lsm6dsl_h_lactive_t * val)
Interrupt active-high/low.[get].
Parameters
ctx Read / write interface definitions
val Get the values of h_lactive in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_pin_polarity_set()
int32_t lsm6dsl_pin_polarity_set (stmdev_ctx_t * ctx, lsm6dsl_h_lactive_t val)
Interrupt active-high/low.[set].
Parameters
ctx Read / write interface definitions
val Change the values of h_lactive in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().