Sensor de vibração MQTT - Trabalho de conclusão de curso: LSM6DSL_DEN_functionality
LSM6DSL_DEN_functionality
BSP » Component » LSM6DSL
This section groups all the functions concerning DEN functionality.
Functions
int32_t lsm6dsl_den_polarity_set (stmdev_ctx_t *ctx, lsm6dsl_den_lh_t val)
DEN active level configuration.[set].
int32_t lsm6dsl_den_polarity_get (stmdev_ctx_t *ctx, lsm6dsl_den_lh_t *val)
DEN active level configuration.[get].
int32_t lsm6dsl_den_mode_set (stmdev_ctx_t *ctx, lsm6dsl_den_mode_t val)
DEN functionality marking mode[set].
int32_t lsm6dsl_den_mode_get (stmdev_ctx_t *ctx, lsm6dsl_den_mode_t *val)
DEN functionality marking mode[get].
int32_t lsm6dsl_den_enable_set (stmdev_ctx_t *ctx, lsm6dsl_den_xl_en_t val)
Extend DEN functionality to accelerometer sensor.[set].
int32_t lsm6dsl_den_enable_get (stmdev_ctx_t *ctx, lsm6dsl_den_xl_en_t *val)
Extend DEN functionality to accelerometer sensor. [get].
int32_t lsm6dsl_den_mark_axis_z_set (stmdev_ctx_t *ctx, uint8_t val)
DEN value stored in LSB of Z-axis.[set].
int32_t lsm6dsl_den_mark_axis_z_get (stmdev_ctx_t *ctx, uint8_t *val)
DEN value stored in LSB of Z-axis.[get].
int32_t lsm6dsl_den_mark_axis_y_set (stmdev_ctx_t *ctx, uint8_t val)
DEN value stored in LSB of Y-axis.[set].
int32_t lsm6dsl_den_mark_axis_y_get (stmdev_ctx_t *ctx, uint8_t *val)
DEN value stored in LSB of Y-axis.[get].
int32_t lsm6dsl_den_mark_axis_x_set (stmdev_ctx_t *ctx, uint8_t val)
DEN value stored in LSB of X-axis.[set].
int32_t lsm6dsl_den_mark_axis_x_get (stmdev_ctx_t *ctx, uint8_t *val)
DEN value stored in LSB of X-axis.[get].
Detailed Description
This section groups all the functions concerning DEN functionality.
Function Documentation
lsm6dsl_den_enable_get()
int32_t lsm6dsl_den_enable_get (stmdev_ctx_t * ctx, lsm6dsl_den_xl_en_t * val)
Extend DEN functionality to accelerometer sensor. [get].
Parameters
ctx Read / write interface definitions
val Get the values of den_xl_g in reg CTRL9_XL and den_xl_en in CTRL4_C.
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_den_enable_set()
int32_t lsm6dsl_den_enable_set (stmdev_ctx_t * ctx, lsm6dsl_den_xl_en_t val)
Extend DEN functionality to accelerometer sensor.[set].
Parameters
ctx Read / write interface definitions
val Change the values of den_xl_g in reg CTRL9_XL and den_xl_en in CTRL4_C.
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_den_mark_axis_x_get()
int32_t lsm6dsl_den_mark_axis_x_get (stmdev_ctx_t * ctx, uint8_t * val)
DEN value stored in LSB of X-axis.[get].
Parameters
ctx Read / write interface definitions
val Change the values of den_x in reg CTRL9_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_den_mark_axis_x_set()
int32_t lsm6dsl_den_mark_axis_x_set (stmdev_ctx_t * ctx, uint8_t val)
DEN value stored in LSB of X-axis.[set].
Parameters
ctx Read / write interface definitions
val Change the values of den_x in reg CTRL9_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_den_mark_axis_y_get()
int32_t lsm6dsl_den_mark_axis_y_get (stmdev_ctx_t * ctx, uint8_t * val)
DEN value stored in LSB of Y-axis.[get].
Parameters
ctx Read / write interface definitions
val Change the values of den_y in reg CTRL9_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_den_mark_axis_y_set()
int32_t lsm6dsl_den_mark_axis_y_set (stmdev_ctx_t * ctx, uint8_t val)
DEN value stored in LSB of Y-axis.[set].
Parameters
ctx Read / write interface definitions
val Change the values of den_y in reg CTRL9_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_den_mark_axis_z_get()
int32_t lsm6dsl_den_mark_axis_z_get (stmdev_ctx_t * ctx, uint8_t * val)
DEN value stored in LSB of Z-axis.[get].
Parameters
ctx Read / write interface definitions
val Change the values of den_z in reg CTRL9_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_den_mark_axis_z_set()
int32_t lsm6dsl_den_mark_axis_z_set (stmdev_ctx_t * ctx, uint8_t val)
DEN value stored in LSB of Z-axis.[set].
Parameters
ctx Read / write interface definitions
val Change the values of den_z in reg CTRL9_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_den_mode_get()
int32_t lsm6dsl_den_mode_get (stmdev_ctx_t * ctx, lsm6dsl_den_mode_t * val)
DEN functionality marking mode[get].
Parameters
ctx Read / write interface definitions
val Change the values of den_mode in reg CTRL6_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_den_mode_set()
int32_t lsm6dsl_den_mode_set (stmdev_ctx_t * ctx, lsm6dsl_den_mode_t val)
DEN functionality marking mode[set].
Parameters
ctx Read / write interface definitions
val Change the values of den_mode in reg CTRL6_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_den_polarity_get()
int32_t lsm6dsl_den_polarity_get (stmdev_ctx_t * ctx, lsm6dsl_den_lh_t * val)
DEN active level configuration.[get].
Parameters
ctx Read / write interface definitions
val Get the values of den_lh in reg CTRL5_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_den_polarity_set()
int32_t lsm6dsl_den_polarity_set (stmdev_ctx_t * ctx, lsm6dsl_den_lh_t val)
DEN active level configuration.[set].
Parameters
ctx Read / write interface definitions
val Change the values of den_lh in reg CTRL5_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().