Sensor de vibração MQTT - Trabalho de conclusão de curso: LSM6DSL_fifo
LSM6DSL_fifo
BSP » Component » LSM6DSL
This section group all the functions concerning the fifo usage.
Functions
int32_t lsm6dsl_fifo_watermark_set (stmdev_ctx_t *ctx, uint16_t val)
FIFO watermark level selection.[set].
int32_t lsm6dsl_fifo_watermark_get (stmdev_ctx_t *ctx, uint16_t *val)
FIFO watermark level selection.[get].
int32_t lsm6dsl_fifo_data_level_get (stmdev_ctx_t *ctx, uint16_t *val)
FIFO data level.[get].
int32_t lsm6dsl_fifo_wtm_flag_get (stmdev_ctx_t *ctx, uint8_t *val)
FIFO watermark.[get].
int32_t lsm6dsl_fifo_pattern_get (stmdev_ctx_t *ctx, uint16_t *val)
FIFO pattern.[get].
int32_t lsm6dsl_fifo_temp_batch_set (stmdev_ctx_t *ctx, uint8_t val)
Batching of temperature data[set].
int32_t lsm6dsl_fifo_temp_batch_get (stmdev_ctx_t *ctx, uint8_t *val)
Batching of temperature data[get].
int32_t lsm6dsl_fifo_write_trigger_set (stmdev_ctx_t *ctx, lsm6dsl_trigger_fifo_t val)
Trigger signal for FIFO write operation.[set].
int32_t lsm6dsl_fifo_write_trigger_get (stmdev_ctx_t *ctx, lsm6dsl_trigger_fifo_t *val)
Trigger signal for FIFO write operation.[get].
int32_t lsm6dsl_fifo_pedo_and_timestamp_batch_set (stmdev_ctx_t *ctx, uint8_t val)
Enable pedometer step counter and timestamp as 4th FIFO data set.[set].
int32_t lsm6dsl_fifo_pedo_and_timestamp_batch_get (stmdev_ctx_t *ctx, uint8_t *val)
Enable pedometer step counter and timestamp as 4th FIFO data set.[get].
int32_t lsm6dsl_fifo_xl_batch_set (stmdev_ctx_t *ctx, lsm6dsl_dec_fifo_xl_t val)
Selects Batching Data Rate (writing frequency in FIFO) for accelerometer data.[set].
int32_t lsm6dsl_fifo_xl_batch_get (stmdev_ctx_t *ctx, lsm6dsl_dec_fifo_xl_t *val)
Selects Batching Data Rate (writing frequency in FIFO) for accelerometer data.[get].
int32_t lsm6dsl_fifo_gy_batch_set (stmdev_ctx_t *ctx, lsm6dsl_dec_fifo_gyro_t val)
Selects Batching Data Rate (writing frequency in FIFO) for gyroscope data.[set].
int32_t lsm6dsl_fifo_gy_batch_get (stmdev_ctx_t *ctx, lsm6dsl_dec_fifo_gyro_t *val)
Selects Batching Data Rate (writing frequency in FIFO) for gyroscope data.[get].
int32_t lsm6dsl_fifo_dataset_3_batch_set (stmdev_ctx_t *ctx, lsm6dsl_dec_ds3_fifo_t val)
Selects Batching Data Rate (writing frequency in FIFO) for third data set.[set].
int32_t lsm6dsl_fifo_dataset_3_batch_get (stmdev_ctx_t *ctx, lsm6dsl_dec_ds3_fifo_t *val)
Selects Batching Data Rate (writing frequency in FIFO) for third data set.[get].
int32_t lsm6dsl_fifo_dataset_4_batch_set (stmdev_ctx_t *ctx, lsm6dsl_dec_ds4_fifo_t val)
Selects Batching Data Rate (writing frequency in FIFO) for fourth data set.[set].
int32_t lsm6dsl_fifo_dataset_4_batch_get (stmdev_ctx_t *ctx, lsm6dsl_dec_ds4_fifo_t *val)
Selects Batching Data Rate (writing frequency in FIFO) for fourth data set.[get].
int32_t lsm6dsl_fifo_xl_gy_8bit_format_set (stmdev_ctx_t *ctx, uint8_t val)
8-bit data storage in FIFO.[set]
int32_t lsm6dsl_fifo_xl_gy_8bit_format_get (stmdev_ctx_t *ctx, uint8_t *val)
8-bit data storage in FIFO.[get]
int32_t lsm6dsl_fifo_stop_on_wtm_set (stmdev_ctx_t *ctx, uint8_t val)
Sensing chain FIFO stop values memorization at threshold level.[set].
int32_t lsm6dsl_fifo_stop_on_wtm_get (stmdev_ctx_t *ctx, uint8_t *val)
Sensing chain FIFO stop values memorization at threshold level.[get].
int32_t lsm6dsl_fifo_mode_set (stmdev_ctx_t *ctx, lsm6dsl_fifo_mode_t val)
FIFO mode selection.[set].
int32_t lsm6dsl_fifo_mode_get (stmdev_ctx_t *ctx, lsm6dsl_fifo_mode_t *val)
FIFO mode selection.[get].
int32_t lsm6dsl_fifo_data_rate_set (stmdev_ctx_t *ctx, lsm6dsl_odr_fifo_t val)
FIFO ODR selection, setting FIFO_MODE also.[set].
int32_t lsm6dsl_fifo_data_rate_get (stmdev_ctx_t *ctx, lsm6dsl_odr_fifo_t *val)
FIFO ODR selection, setting FIFO_MODE also.[get].
Detailed Description
This section group all the functions concerning the fifo usage.
Function Documentation
lsm6dsl_fifo_data_level_get()
int32_t lsm6dsl_fifo_data_level_get (stmdev_ctx_t * ctx, uint16_t * val)
FIFO data level.[get].
Parameters
ctx Read / write interface definitions
val get the values of diff_fifo in reg FIFO_STATUS1 and FIFO_STATUS2(diff_fifo), it is recommended to set the BDU bit.
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_FIFO_Get_Num_Samples().
lsm6dsl_fifo_data_rate_get()
int32_t lsm6dsl_fifo_data_rate_get (stmdev_ctx_t * ctx, lsm6dsl_odr_fifo_t * val)
FIFO ODR selection, setting FIFO_MODE also.[get].
Parameters
ctx Read / write interface definitions
val Get the values of odr_fifo in reg FIFO_CTRL5
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_data_rate_set()
int32_t lsm6dsl_fifo_data_rate_set (stmdev_ctx_t * ctx, lsm6dsl_odr_fifo_t val)
FIFO ODR selection, setting FIFO_MODE also.[set].
Parameters
ctx Read / write interface definitions
val Change the values of odr_fifo in reg FIFO_CTRL5
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_dataset_3_batch_get()
int32_t lsm6dsl_fifo_dataset_3_batch_get (stmdev_ctx_t * ctx, lsm6dsl_dec_ds3_fifo_t * val)
Selects Batching Data Rate (writing frequency in FIFO) for third data set.[get].
Parameters
ctx Read / write interface definitions
val Get the values of dec_ds3_fifo in reg FIFO_CTRL4
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_dataset_3_batch_set()
int32_t lsm6dsl_fifo_dataset_3_batch_set (stmdev_ctx_t * ctx, lsm6dsl_dec_ds3_fifo_t val)
Selects Batching Data Rate (writing frequency in FIFO) for third data set.[set].
Parameters
ctx Read / write interface definitions
val Change the values of dec_ds3_fifo in reg FIFO_CTRL4
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_dataset_4_batch_get()
int32_t lsm6dsl_fifo_dataset_4_batch_get (stmdev_ctx_t * ctx, lsm6dsl_dec_ds4_fifo_t * val)
Selects Batching Data Rate (writing frequency in FIFO) for fourth data set.[get].
Parameters
ctx Read / write interface definitions
val Get the values of dec_ds4_fifo in reg FIFO_CTRL4
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_dataset_4_batch_set()
int32_t lsm6dsl_fifo_dataset_4_batch_set (stmdev_ctx_t * ctx, lsm6dsl_dec_ds4_fifo_t val)
Selects Batching Data Rate (writing frequency in FIFO) for fourth data set.[set].
Parameters
ctx Read / write interface definitions
val Change the values of dec_ds4_fifo in reg FIFO_CTRL4
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_gy_batch_get()
int32_t lsm6dsl_fifo_gy_batch_get (stmdev_ctx_t * ctx, lsm6dsl_dec_fifo_gyro_t * val)
Selects Batching Data Rate (writing frequency in FIFO) for gyroscope data.[get].
Parameters
ctx Read / write interface definitions
val Get the values of dec_fifo_gyro in reg FIFO_CTRL3
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_gy_batch_set()
int32_t lsm6dsl_fifo_gy_batch_set (stmdev_ctx_t * ctx, lsm6dsl_dec_fifo_gyro_t val)
Selects Batching Data Rate (writing frequency in FIFO) for gyroscope data.[set].
Parameters
ctx Read / write interface definitions
val Change the values of dec_fifo_gyro in reg FIFO_CTRL3
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_mode_get()
int32_t lsm6dsl_fifo_mode_get (stmdev_ctx_t * ctx, lsm6dsl_fifo_mode_t * val)
FIFO mode selection.[get].
Parameters
ctx Read / write interface definitions
val Get the values of fifo_mode in reg FIFO_CTRL5
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_mode_set()
int32_t lsm6dsl_fifo_mode_set (stmdev_ctx_t * ctx, lsm6dsl_fifo_mode_t val)
FIFO mode selection.[set].
Parameters
ctx Read / write interface definitions
val Change the values of fifo_mode in reg FIFO_CTRL5
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_pattern_get()
int32_t lsm6dsl_fifo_pattern_get (stmdev_ctx_t * ctx, uint16_t * val)
FIFO pattern.[get].
Parameters
ctx Read / write interface definitions
val get the values of fifo_pattern in reg FIFO_STATUS3 and FIFO_STATUS4, it is recommended to set the BDU bit
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_FIFO_Get_Pattern().
lsm6dsl_fifo_pedo_and_timestamp_batch_get()
int32_t lsm6dsl_fifo_pedo_and_timestamp_batch_get (stmdev_ctx_t * ctx, uint8_t * val)
Enable pedometer step counter and timestamp as 4th FIFO data set.[get].
Parameters
ctx Read / write interface definitions
val Change the values of timer_pedo_fifo_en in reg FIFO_CTRL2
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_pedo_and_timestamp_batch_set()
int32_t lsm6dsl_fifo_pedo_and_timestamp_batch_set (stmdev_ctx_t * ctx, uint8_t val)
Enable pedometer step counter and timestamp as 4th FIFO data set.[set].
Parameters
ctx Read / write interface definitions
val Change the values of timer_pedo_fifo_en in reg FIFO_CTRL2
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_stop_on_wtm_get()
int32_t lsm6dsl_fifo_stop_on_wtm_get (stmdev_ctx_t * ctx, uint8_t * val)
Sensing chain FIFO stop values memorization at threshold level.[get].
Parameters
ctx Read / write interface definitions
val Change the values of stop_on_fth in reg FIFO_CTRL4
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_stop_on_wtm_set()
int32_t lsm6dsl_fifo_stop_on_wtm_set (stmdev_ctx_t * ctx, uint8_t val)
Sensing chain FIFO stop values memorization at threshold level.[set].
Parameters
ctx Read / write interface definitions
val Change the values of stop_on_fth in reg FIFO_CTRL4
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_FIFO_Set_Stop_On_Fth().
lsm6dsl_fifo_temp_batch_get()
int32_t lsm6dsl_fifo_temp_batch_get (stmdev_ctx_t * ctx, uint8_t * val)
Batching of temperature data[get].
Parameters
ctx Read / write interface definitions
val Change the values of fifo_temp_en in reg FIFO_CTRL2
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_temp_batch_set()
int32_t lsm6dsl_fifo_temp_batch_set (stmdev_ctx_t * ctx, uint8_t val)
Batching of temperature data[set].
Parameters
ctx Read / write interface definitions
val Change the values of fifo_temp_en in reg FIFO_CTRL2
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_watermark_get()
int32_t lsm6dsl_fifo_watermark_get (stmdev_ctx_t * ctx, uint16_t * val)
FIFO watermark level selection.[get].
Parameters
ctx Read / write interface definitions
val Change the values of fth in reg FIFO_CTRL1
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_watermark_set()
int32_t lsm6dsl_fifo_watermark_set (stmdev_ctx_t * ctx, uint16_t val)
FIFO watermark level selection.[set].
Parameters
ctx Read / write interface definitions
val Change the values of fth in reg FIFO_CTRL1
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_FIFO_Set_Watermark_Level().
lsm6dsl_fifo_write_trigger_get()
int32_t lsm6dsl_fifo_write_trigger_get (stmdev_ctx_t * ctx, lsm6dsl_trigger_fifo_t * val)
Trigger signal for FIFO write operation.[get].
Parameters
ctx Read / write interface definitions
val act on FIFO_CTRL2(timer_pedo_fifo_drdy) and MASTER_CONFIG(data_valid_sel_fifo)
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_write_trigger_set()
int32_t lsm6dsl_fifo_write_trigger_set (stmdev_ctx_t * ctx, lsm6dsl_trigger_fifo_t val)
Trigger signal for FIFO write operation.[set].
Parameters
ctx Read / write interface definitions
val act on FIFO_CTRL2(timer_pedo_fifo_drdy) and MASTER_CONFIG(data_valid_sel_fifo)
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_wtm_flag_get()
int32_t lsm6dsl_fifo_wtm_flag_get (stmdev_ctx_t * ctx, uint8_t * val)
FIFO watermark.[get].
Parameters
ctx Read / write interface definitions
val get the values of watermark in reg FIFO_STATUS2 and
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_xl_batch_get()
int32_t lsm6dsl_fifo_xl_batch_get (stmdev_ctx_t * ctx, lsm6dsl_dec_fifo_xl_t * val)
Selects Batching Data Rate (writing frequency in FIFO) for accelerometer data.[get].
Parameters
ctx Read / write interface definitions
val Get the values of dec_fifo_xl in reg FIFO_CTRL3
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_xl_batch_set()
int32_t lsm6dsl_fifo_xl_batch_set (stmdev_ctx_t * ctx, lsm6dsl_dec_fifo_xl_t val)
Selects Batching Data Rate (writing frequency in FIFO) for accelerometer data.[set].
Parameters
ctx Read / write interface definitions
val Change the values of dec_fifo_xl in reg FIFO_CTRL3
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_xl_gy_8bit_format_get()
int32_t lsm6dsl_fifo_xl_gy_8bit_format_get (stmdev_ctx_t * ctx, uint8_t * val)
8-bit data storage in FIFO.[get]
Parameters
ctx Read / write interface definitions
val Change the values of only_high_data in reg FIFO_CTRL4
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_xl_gy_8bit_format_set()
int32_t lsm6dsl_fifo_xl_gy_8bit_format_set (stmdev_ctx_t * ctx, uint8_t val)
8-bit data storage in FIFO.[set]
Parameters
ctx Read / write interface definitions
val Change the values of only_high_data in reg FIFO_CTRL4
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().