Sensor de vibração MQTT - Trabalho de conclusão de curso: LSM6DSL_tilt_detection
LSM6DSL_tilt_detection
BSP » Component » LSM6DSL
This section groups all the functions that manage the tilt event detection.
Functions
int32_t lsm6dsl_tilt_sens_set (stmdev_ctx_t *ctx, uint8_t val)
Enable tilt calculation.[set].
int32_t lsm6dsl_tilt_sens_get (stmdev_ctx_t *ctx, uint8_t *val)
Enable tilt calculation.[get].
int32_t lsm6dsl_wrist_tilt_sens_set (stmdev_ctx_t *ctx, uint8_t val)
Enable tilt calculation.[set].
int32_t lsm6dsl_wrist_tilt_sens_get (stmdev_ctx_t *ctx, uint8_t *val)
Enable tilt calculation.[get].
int32_t lsm6dsl_tilt_latency_set (stmdev_ctx_t *ctx, uint8_t *buff)
Absolute Wrist Tilt latency register (r/w). Absolute wrist tilt latency parameters. 1 LSB = 40 ms. Default value: 0Fh (600 ms).[set].
int32_t lsm6dsl_tilt_latency_get (stmdev_ctx_t *ctx, uint8_t *buff)
Absolute Wrist Tilt latency register (r/w). Absolute wrist tilt latency parameters. 1 LSB = 40 ms. Default value: 0Fh (600 ms).[get].
int32_t lsm6dsl_tilt_threshold_set (stmdev_ctx_t *ctx, uint8_t *buff)
Absolute Wrist Tilt threshold register(r/w). Absolute wrist tilt threshold parameters. 1 LSB = 15.625 mg.Default value: 20h (500 mg).[set].
int32_t lsm6dsl_tilt_threshold_get (stmdev_ctx_t *ctx, uint8_t *buff)
Absolute Wrist Tilt threshold register(r/w). Absolute wrist tilt threshold parameters. 1 LSB = 15.625 mg.Default value: 20h (500 mg).[get].
int32_t lsm6dsl_tilt_src_set (stmdev_ctx_t *ctx, lsm6dsl_a_wrist_tilt_mask_t *val)
Absolute Wrist Tilt mask register (r/w).[set].
int32_t lsm6dsl_tilt_src_get (stmdev_ctx_t *ctx, lsm6dsl_a_wrist_tilt_mask_t *val)
Absolute Wrist Tilt mask register (r/w).[get].
Detailed Description
This section groups all the functions that manage the tilt event detection.
Function Documentation
lsm6dsl_tilt_latency_get()
int32_t lsm6dsl_tilt_latency_get (stmdev_ctx_t * ctx, uint8_t * buff)
Absolute Wrist Tilt latency register (r/w). Absolute wrist tilt latency parameters. 1 LSB = 40 ms. Default value: 0Fh (600 ms).[get].
Parameters
ctx Read / write interface definitions
buff Buffer that stores data read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_tilt_latency_set()
int32_t lsm6dsl_tilt_latency_set (stmdev_ctx_t * ctx, uint8_t * buff)
Absolute Wrist Tilt latency register (r/w). Absolute wrist tilt latency parameters. 1 LSB = 40 ms. Default value: 0Fh (600 ms).[set].
Parameters
ctx Read / write interface definitions
buff Buffer that contains data to write
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_tilt_sens_get()
int32_t lsm6dsl_tilt_sens_get (stmdev_ctx_t * ctx, uint8_t * val)
Enable tilt calculation.[get].
Parameters
ctx Read / write interface definitions
val Change the values of tilt_en in reg CTRL10_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tilt_sens_set()
int32_t lsm6dsl_tilt_sens_set (stmdev_ctx_t * ctx, uint8_t val)
Enable tilt calculation.[set].
Parameters
ctx Read / write interface definitions
val Change the values of tilt_en in reg CTRL10_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tilt_src_get()
int32_t lsm6dsl_tilt_src_get (stmdev_ctx_t * ctx, lsm6dsl_a_wrist_tilt_mask_t * val)
Absolute Wrist Tilt mask register (r/w).[get].
Parameters
ctx Read / write interface definitions
val Registers A_WRIST_TILT_MASK
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_tilt_src_set()
int32_t lsm6dsl_tilt_src_set (stmdev_ctx_t * ctx, lsm6dsl_a_wrist_tilt_mask_t * val)
Absolute Wrist Tilt mask register (r/w).[set].
Parameters
ctx Read / write interface definitions
val Registers A_WRIST_TILT_MASK
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_tilt_threshold_get()
int32_t lsm6dsl_tilt_threshold_get (stmdev_ctx_t * ctx, uint8_t * buff)
Absolute Wrist Tilt threshold register(r/w). Absolute wrist tilt threshold parameters. 1 LSB = 15.625 mg.Default value: 20h (500 mg).[get].
Parameters
ctx Read / write interface definitions
buff Buffer that stores data read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_tilt_threshold_set()
int32_t lsm6dsl_tilt_threshold_set (stmdev_ctx_t * ctx, uint8_t * buff)
Absolute Wrist Tilt threshold register(r/w). Absolute wrist tilt threshold parameters. 1 LSB = 15.625 mg.Default value: 20h (500 mg).[set].
Parameters
ctx Read / write interface definitions
buff Buffer that contains data to write
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_wrist_tilt_sens_get()
int32_t lsm6dsl_wrist_tilt_sens_get (stmdev_ctx_t * ctx, uint8_t * val)
Enable tilt calculation.[get].
Parameters
ctx Read / write interface definitions
val Change the values of tilt_en in reg CTRL10_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_wrist_tilt_sens_set()
int32_t lsm6dsl_wrist_tilt_sens_set (stmdev_ctx_t * ctx, uint8_t val)
Enable tilt calculation.[set].
Parameters
ctx Read / write interface definitions
val Change the values of tilt_en in reg CTRL10_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().