Sensor de vibração MQTT - Trabalho de conclusão de curso: LSM6DSL
LSM6DSL
BSP » Component
This file provides a set of functions needed to drive the lsm6dsl enanced inertial module.
Modules
LSM6DSL Exported Variables
LSM6DSL Private Function Prototypes
LSM6DSL Exported Functions
LSM6DSL Private Functions
LSM6DSL Exported Types
LSM6DSL Exported Constants
LSM6DSL_interfaces_functions
This section provide a set of functions used to read and write a generic register of the device. MANDATORY: return 0 -> no Error.
LSM6DSL_Sensitivity
These functions convert raw-data into engineering units.
LSM6DSL_data_generation
This section groups all the functions concerning data generation.
LSM6DSL_Timestamp
This section groups all the functions that manage the timestamp generation.
LSM6DSL_Dataoutput
This section groups all the data output functions.
LSM6DSL_common
This section groups common useful functions.
LSM6DSL_filters
This section group all the functions concerning the filters configuration that impact both accelerometer and gyro.
LSM6DSL_accelerometer_filters
This section group all the functions concerning the filters configuration that impact accelerometer in every mode.
LSM6DSL_gyroscope_filters
This section group all the functions concerning the filters configuration that impact gyroscope.
LSM6DSL_serial_interface
This section groups all the functions concerning serial interface management.
LSM6DSL_interrupt_pins
This section groups all the functions that manage interrupt pins.
LSM6DSL_Wake_Up_event
This section groups all the functions that manage the Wake Up event generation.
/Inactivity_detection
This section groups all the functions concerning activity/inactivity detection.
LSM6DSL_tap_generator
This section groups all the functions that manage the tap and double tap event generation.
Six_position_detection(6D/4D)
This section groups all the functions concerning six position detection (6D).
LSM6DSL_free_fall
This section group all the functions concerning the free fall detection.
LSM6DSL_fifo
This section group all the functions concerning the fifo usage.
LSM6DSL_DEN_functionality
This section groups all the functions concerning DEN functionality.
LSM6DSL_Pedometer
This section groups all the functions that manage pedometer.
LSM6DSL_significant_motion
This section groups all the functions that manage the significant motion detection.
LSM6DSL_tilt_detection
This section groups all the functions that manage the tilt event detection.
LSM6DSL_Sensor_hub
This section groups all the functions that manage the sensor hub functionality.
definitions
sensors common types
LSM6DSL_Infos
LSM6DSL_Register_Union
This union group all the registers that has a bit-field description. This union is useful but not need by the driver.
Data Structures
struct lsm6dsl_func_cfg_access_t
struct lsm6dsl_sensor_sync_time_frame_t
struct lsm6dsl_sensor_sync_res_ratio_t
struct lsm6dsl_fifo_ctrl1_t
struct lsm6dsl_fifo_ctrl2_t
struct lsm6dsl_fifo_ctrl3_t
struct lsm6dsl_fifo_ctrl4_t
struct lsm6dsl_fifo_ctrl5_t
struct lsm6dsl_drdy_pulse_cfg_g_t
struct lsm6dsl_int1_ctrl_t
struct lsm6dsl_int2_ctrl_t
struct lsm6dsl_ctrl1_xl_t
struct lsm6dsl_ctrl2_g_t
struct lsm6dsl_ctrl3_c_t
struct lsm6dsl_ctrl4_c_t
struct lsm6dsl_ctrl5_c_t
struct lsm6dsl_ctrl6_c_t
struct lsm6dsl_ctrl7_g_t
struct lsm6dsl_ctrl8_xl_t
struct lsm6dsl_ctrl9_xl_t
struct lsm6dsl_ctrl10_c_t
struct lsm6dsl_master_config_t
struct lsm6dsl_wake_up_src_t
struct lsm6dsl_tap_src_t
struct lsm6dsl_d6d_src_t
struct lsm6dsl_status_reg_t
struct lsm6dsl_sensorhub1_reg_t
struct lsm6dsl_sensorhub2_reg_t
struct lsm6dsl_sensorhub3_reg_t
struct lsm6dsl_sensorhub4_reg_t
struct lsm6dsl_sensorhub5_reg_t
struct lsm6dsl_sensorhub6_reg_t
struct lsm6dsl_sensorhub7_reg_t
struct lsm6dsl_sensorhub8_reg_t
struct lsm6dsl_sensorhub9_reg_t
struct lsm6dsl_sensorhub10_reg_t
struct lsm6dsl_sensorhub11_reg_t
struct lsm6dsl_sensorhub12_reg_t
struct lsm6dsl_fifo_status1_t
struct lsm6dsl_fifo_status2_t
struct lsm6dsl_fifo_status3_t
struct lsm6dsl_fifo_status4_t
struct lsm6dsl_sensorhub13_reg_t
struct lsm6dsl_sensorhub14_reg_t
struct lsm6dsl_sensorhub15_reg_t
struct lsm6dsl_sensorhub16_reg_t
struct lsm6dsl_sensorhub17_reg_t
struct lsm6dsl_sensorhub18_reg_t
struct lsm6dsl_func_src1_t
struct lsm6dsl_func_src2_t
struct lsm6dsl_wrist_tilt_ia_t
struct lsm6dsl_tap_cfg_t
struct lsm6dsl_tap_ths_6d_t
struct lsm6dsl_int_dur2_t
struct lsm6dsl_wake_up_ths_t
struct lsm6dsl_wake_up_dur_t
struct lsm6dsl_free_fall_t
struct lsm6dsl_md1_cfg_t
struct lsm6dsl_md2_cfg_t
struct lsm6dsl_master_cmd_code_t
struct lsm6dsl_sens_sync_spi_error_code_t
struct lsm6dsl_slv0_add_t
struct lsm6dsl_slv0_subadd_t
struct lsm6dsl_slave0_config_t
struct lsm6dsl_slv1_add_t
struct lsm6dsl_slv1_subadd_t
struct lsm6dsl_slave1_config_t
struct lsm6dsl_slv2_add_t
struct lsm6dsl_slv2_subadd_t
struct lsm6dsl_slave2_config_t
struct lsm6dsl_slv3_add_t
struct lsm6dsl_slv3_subadd_t
struct lsm6dsl_slave3_config_t
struct lsm6dsl_datawrite_src_mode_sub_slv0_t
struct lsm6dsl_config_pedo_ths_min_t
struct lsm6dsl_pedo_deb_reg_t
struct lsm6dsl_a_wrist_tilt_mask_t
struct lsm6dsl_all_sources_t
struct lsm6dsl_int1_route_t
struct lsm6dsl_int2_route_t
struct lsm6dsl_emb_sh_read_t
struct lsm6dsl_sh_cfg_write_t
struct lsm6dsl_sh_cfg_read_t
Macros
#define LSM6DSL_FUNC_CFG_ACCESS 0x01U
#define LSM6DSL_SENSOR_SYNC_TIME_FRAME 0x04U
#define LSM6DSL_SENSOR_SYNC_RES_RATIO 0x05U
#define LSM6DSL_FIFO_CTRL1 0x06U
#define LSM6DSL_FIFO_CTRL2 0x07U
#define LSM6DSL_FIFO_CTRL3 0x08U
#define LSM6DSL_FIFO_CTRL4 0x09U
#define LSM6DSL_FIFO_CTRL5 0x0AU
#define LSM6DSL_DRDY_PULSE_CFG_G 0x0BU
#define LSM6DSL_INT1_CTRL 0x0DU
#define LSM6DSL_INT2_CTRL 0x0EU
#define LSM6DSL_WHO_AM_I 0x0FU
#define LSM6DSL_CTRL1_XL 0x10U
#define LSM6DSL_CTRL2_G 0x11U
#define LSM6DSL_CTRL3_C 0x12U
#define LSM6DSL_CTRL4_C 0x13U
#define LSM6DSL_CTRL5_C 0x14U
#define LSM6DSL_CTRL6_C 0x15U
#define LSM6DSL_CTRL7_G 0x16U
#define LSM6DSL_CTRL8_XL 0x17U
#define LSM6DSL_CTRL9_XL 0x18U
#define LSM6DSL_CTRL10_C 0x19U
#define LSM6DSL_MASTER_CONFIG 0x1AU
#define LSM6DSL_WAKE_UP_SRC 0x1BU
#define LSM6DSL_TAP_SRC 0x1CU
#define LSM6DSL_D6D_SRC 0x1DU
#define LSM6DSL_STATUS_REG 0x1EU
#define LSM6DSL_OUT_TEMP_L 0x20U
#define LSM6DSL_OUT_TEMP_H 0x21U
#define LSM6DSL_OUTX_L_G 0x22U
#define LSM6DSL_OUTX_H_G 0x23U
#define LSM6DSL_OUTY_L_G 0x24U
#define LSM6DSL_OUTY_H_G 0x25U
#define LSM6DSL_OUTZ_L_G 0x26U
#define LSM6DSL_OUTZ_H_G 0x27U
#define LSM6DSL_OUTX_L_XL 0x28U
#define LSM6DSL_OUTX_H_XL 0x29U
#define LSM6DSL_OUTY_L_XL 0x2AU
#define LSM6DSL_OUTY_H_XL 0x2BU
#define LSM6DSL_OUTZ_L_XL 0x2CU
#define LSM6DSL_OUTZ_H_XL 0x2DU
#define LSM6DSL_SENSORHUB1_REG 0x2EU
#define LSM6DSL_SENSORHUB2_REG 0x2FU
#define LSM6DSL_SENSORHUB3_REG 0x30U
#define LSM6DSL_SENSORHUB4_REG 0x31U
#define LSM6DSL_SENSORHUB5_REG 0x32U
#define LSM6DSL_SENSORHUB6_REG 0x33U
#define LSM6DSL_SENSORHUB7_REG 0x34U
#define LSM6DSL_SENSORHUB8_REG 0x35U
#define LSM6DSL_SENSORHUB9_REG 0x36U
#define LSM6DSL_SENSORHUB10_REG 0x37U
#define LSM6DSL_SENSORHUB11_REG 0x38U
#define LSM6DSL_SENSORHUB12_REG 0x39U
#define LSM6DSL_FIFO_STATUS1 0x3AU
#define LSM6DSL_FIFO_STATUS2 0x3BU
#define LSM6DSL_FIFO_STATUS3 0x3CU
#define LSM6DSL_FIFO_STATUS4 0x3DU
#define LSM6DSL_FIFO_DATA_OUT_L 0x3EU
#define LSM6DSL_FIFO_DATA_OUT_H 0x3FU
#define LSM6DSL_TIMESTAMP0_REG 0x40U
#define LSM6DSL_TIMESTAMP1_REG 0x41U
#define LSM6DSL_TIMESTAMP2_REG 0x42U
#define LSM6DSL_STEP_TIMESTAMP_L 0x49U
#define LSM6DSL_STEP_TIMESTAMP_H 0x4AU
#define LSM6DSL_STEP_COUNTER_L 0x4BU
#define LSM6DSL_STEP_COUNTER_H 0x4CU
#define LSM6DSL_SENSORHUB13_REG 0x4DU
#define LSM6DSL_SENSORHUB14_REG 0x4EU
#define LSM6DSL_SENSORHUB15_REG 0x4FU
#define LSM6DSL_SENSORHUB16_REG 0x50U
#define LSM6DSL_SENSORHUB17_REG 0x51U
#define LSM6DSL_SENSORHUB18_REG 0x52U
#define LSM6DSL_FUNC_SRC1 0x53U
#define LSM6DSL_FUNC_SRC2 0x54U
#define LSM6DSL_WRIST_TILT_IA 0x55U
#define LSM6DSL_TAP_CFG 0x58U
#define LSM6DSL_TAP_THS_6D 0x59U
#define LSM6DSL_INT_DUR2 0x5AU
#define LSM6DSL_WAKE_UP_THS 0x5BU
#define LSM6DSL_WAKE_UP_DUR 0x5CU
#define LSM6DSL_FREE_FALL 0x5DU
#define LSM6DSL_MD1_CFG 0x5EU
#define LSM6DSL_MD2_CFG 0x5FU
#define LSM6DSL_MASTER_CMD_CODE 0x60U
#define LSM6DSL_SENS_SYNC_SPI_ERROR_CODE 0x61U
#define LSM6DSL_OUT_MAG_RAW_X_L 0x66U
#define LSM6DSL_OUT_MAG_RAW_X_H 0x67U
#define LSM6DSL_OUT_MAG_RAW_Y_L 0x68U
#define LSM6DSL_OUT_MAG_RAW_Y_H 0x69U
#define LSM6DSL_OUT_MAG_RAW_Z_L 0x6AU
#define LSM6DSL_OUT_MAG_RAW_Z_H 0x6BU
#define LSM6DSL_X_OFS_USR 0x73U
#define LSM6DSL_Y_OFS_USR 0x74U
#define LSM6DSL_Z_OFS_USR 0x75U
#define LSM6DSL_SLV0_ADD 0x02U
#define LSM6DSL_SLV0_SUBADD 0x03U
#define LSM6DSL_SLAVE0_CONFIG 0x04U
#define LSM6DSL_SLV1_ADD 0x05U
#define LSM6DSL_SLV1_SUBADD 0x06U
#define LSM6DSL_SLAVE1_CONFIG 0x07U
#define LSM6DSL_SLV2_ADD 0x08U
#define LSM6DSL_SLV2_SUBADD 0x09U
#define LSM6DSL_SLAVE2_CONFIG 0x0AU
#define LSM6DSL_SLV3_ADD 0x0BU
#define LSM6DSL_SLV3_SUBADD 0x0CU
#define LSM6DSL_SLAVE3_CONFIG 0x0DU
#define LSM6DSL_DATAWRITE_SRC_MODE_SUB_SLV0 0x0EU
#define LSM6DSL_CONFIG_PEDO_THS_MIN 0x0FU
#define LSM6DSL_SM_THS 0x13U
#define LSM6DSL_PEDO_DEB_REG 0x14U
#define LSM6DSL_STEP_COUNT_DELTA 0x15U
#define LSM6DSL_MAG_SI_XX 0x24U
#define LSM6DSL_MAG_SI_XY 0x25U
#define LSM6DSL_MAG_SI_XZ 0x26U
#define LSM6DSL_MAG_SI_YX 0x27U
#define LSM6DSL_MAG_SI_YY 0x28U
#define LSM6DSL_MAG_SI_YZ 0x29U
#define LSM6DSL_MAG_SI_ZX 0x2AU
#define LSM6DSL_MAG_SI_ZY 0x2BU
#define LSM6DSL_MAG_SI_ZZ 0x2CU
#define LSM6DSL_MAG_OFFX_L 0x2DU
#define LSM6DSL_MAG_OFFX_H 0x2EU
#define LSM6DSL_MAG_OFFY_L 0x2FU
#define LSM6DSL_MAG_OFFY_H 0x30U
#define LSM6DSL_MAG_OFFZ_L 0x31U
#define LSM6DSL_MAG_OFFZ_H 0x32U
#define LSM6DSL_A_WRIST_TILT_LAT 0x50U
#define LSM6DSL_A_WRIST_TILT_THS 0x54U
#define LSM6DSL_A_WRIST_TILT_MASK 0x59U
Enumerations
enum lsm6dsl_fs_xl_t {
LSM6DSL_2g = 0 , LSM6DSL_16g = 1 , LSM6DSL_4g = 2 , LSM6DSL_8g = 3 ,
LSM6DSL_XL_FS_ND = 4
}
enum lsm6dsl_odr_xl_t {
LSM6DSL_XL_ODR_OFF = 0 , LSM6DSL_XL_ODR_12Hz5 = 1 , LSM6DSL_XL_ODR_26Hz = 2 , LSM6DSL_XL_ODR_52Hz = 3 ,
LSM6DSL_XL_ODR_104Hz = 4 , LSM6DSL_XL_ODR_208Hz = 5 , LSM6DSL_XL_ODR_416Hz = 6 , LSM6DSL_XL_ODR_833Hz = 7 ,
LSM6DSL_XL_ODR_1k66Hz = 8 , LSM6DSL_XL_ODR_3k33Hz = 9 , LSM6DSL_XL_ODR_6k66Hz = 10 , LSM6DSL_XL_ODR_1Hz6 = 11 ,
LSM6DSL_XL_ODR_ND = 12
}
enum lsm6dsl_fs_g_t {
LSM6DSL_250dps = 0 , LSM6DSL_125dps = 1 , LSM6DSL_500dps = 2 , LSM6DSL_1000dps = 4 ,
LSM6DSL_2000dps = 6 , LSM6DSL_GY_FS_ND = 7
}
enum lsm6dsl_odr_g_t {
LSM6DSL_GY_ODR_OFF = 0 , LSM6DSL_GY_ODR_12Hz5 = 1 , LSM6DSL_GY_ODR_26Hz = 2 , LSM6DSL_GY_ODR_52Hz = 3 ,
LSM6DSL_GY_ODR_104Hz = 4 , LSM6DSL_GY_ODR_208Hz = 5 , LSM6DSL_GY_ODR_416Hz = 6 , LSM6DSL_GY_ODR_833Hz = 7 ,
LSM6DSL_GY_ODR_1k66Hz = 8 , LSM6DSL_GY_ODR_3k33Hz = 9 , LSM6DSL_GY_ODR_6k66Hz = 10 , LSM6DSL_GY_ODR_ND = 11
}
enum lsm6dsl_usr_off_w_t { LSM6DSL_LSb_1mg = 0 , LSM6DSL_LSb_16mg = 1 , LSM6DSL_WEIGHT_ND = 2 }
enum lsm6dsl_xl_hm_mode_t { LSM6DSL_XL_HIGH_PERFORMANCE = 0 , LSM6DSL_XL_NORMAL = 1 , LSM6DSL_XL_PW_MODE_ND = 2 }
enum lsm6dsl_rounding_status_t { LSM6DSL_STAT_RND_DISABLE = 0 , LSM6DSL_STAT_RND_ENABLE = 1 , LSM6DSL_STAT_RND_ND = 2 }
enum lsm6dsl_g_hm_mode_t { LSM6DSL_GY_HIGH_PERFORMANCE = 0 , LSM6DSL_GY_NORMAL = 1 , LSM6DSL_GY_PW_MODE_ND = 2 }
enum lsm6dsl_timer_hr_t { LSM6DSL_LSB_6ms4 = 0 , LSM6DSL_LSB_25us = 1 , LSM6DSL_TS_RES_ND = 2 }
enum lsm6dsl_rounding_t {
LSM6DSL_ROUND_DISABLE = 0 , LSM6DSL_ROUND_XL = 1 , LSM6DSL_ROUND_GY = 2 , LSM6DSL_ROUND_GY_XL = 3 ,
LSM6DSL_ROUND_SH1_TO_SH6 = 4 , LSM6DSL_ROUND_XL_SH1_TO_SH6 = 5 , LSM6DSL_ROUND_GY_XL_SH1_TO_SH12 = 6 , LSM6DSL_ROUND_GY_XL_SH1_TO_SH6 = 7 ,
LSM6DSL_ROUND_OUT_ND = 8
}
enum lsm6dsl_func_cfg_en_t { LSM6DSL_USER_BANK = 0 , LSM6DSL_BANK_A = 4 , LSM6DSL_BANK_B = 5 , LSM6DSL_BANK_ND = 6 }
enum lsm6dsl_drdy_pulsed_g_t { LSM6DSL_DRDY_LATCHED = 0 , LSM6DSL_DRDY_PULSED = 1 , LSM6DSL_DRDY_ND = 2 }
enum lsm6dsl_ble_t { LSM6DSL_LSB_AT_LOW_ADD = 0 , LSM6DSL_MSB_AT_LOW_ADD = 1 , LSM6DSL_DATA_FMT_ND = 2 }
enum lsm6dsl_st_xl_t { LSM6DSL_XL_ST_DISABLE = 0 , LSM6DSL_XL_ST_POSITIVE = 1 , LSM6DSL_XL_ST_NEGATIVE = 2 , LSM6DSL_XL_ST_ND = 3 }
enum lsm6dsl_st_g_t { LSM6DSL_GY_ST_DISABLE = 0 , LSM6DSL_GY_ST_POSITIVE = 1 , LSM6DSL_GY_ST_NEGATIVE = 3 , LSM6DSL_GY_ST_ND = 4 }
enum lsm6dsl_slope_fds_t { LSM6DSL_USE_SLOPE = 0 , LSM6DSL_USE_HPF = 1 , LSM6DSL_HP_PATH_ND = 2 }
enum lsm6dsl_bw0_xl_t { LSM6DSL_XL_ANA_BW_1k5Hz = 0 , LSM6DSL_XL_ANA_BW_400Hz = 1 , LSM6DSL_XL_ANA_BW_ND = 2 }
enum lsm6dsl_lpf1_bw_sel_t { LSM6DSL_XL_LP1_ODR_DIV_2 = 0 , LSM6DSL_XL_LP1_ODR_DIV_4 = 1 , LSM6DSL_XL_LP1_NA = 2 }
enum lsm6dsl_input_composite_t {
LSM6DSL_XL_LOW_LAT_LP_ODR_DIV_50 = 0x00 , LSM6DSL_XL_LOW_LAT_LP_ODR_DIV_100 = 0x01 , LSM6DSL_XL_LOW_LAT_LP_ODR_DIV_9 = 0x02 , LSM6DSL_XL_LOW_LAT_LP_ODR_DIV_400 = 0x03 ,
LSM6DSL_XL_LOW_NOISE_LP_ODR_DIV_50 = 0x10 , LSM6DSL_XL_LOW_NOISE_LP_ODR_DIV_100 = 0x11 , LSM6DSL_XL_LOW_NOISE_LP_ODR_DIV_9 = 0x12 , LSM6DSL_XL_LOW_NOISE_LP_ODR_DIV_400 = 0x13 ,
LSM6DSL_XL_LP_NA = 0x20
}
enum lsm6dsl_hpcf_xl_t {
LSM6DSL_XL_HP_ODR_DIV_4 = 0x00 , LSM6DSL_XL_HP_ODR_DIV_100 = 0x01 , LSM6DSL_XL_HP_ODR_DIV_9 = 0x02 , LSM6DSL_XL_HP_ODR_DIV_400 = 0x03 ,
LSM6DSL_XL_HP_NA = 0x10
}
enum lsm6dsl_lpf1_sel_g_t {
LSM6DSL_LP2_ONLY = 0x00 , LSM6DSL_HP_16mHz_LP2 = 0x80 , LSM6DSL_HP_65mHz_LP2 = 0x90 , LSM6DSL_HP_260mHz_LP2 = 0xA0 ,
LSM6DSL_HP_1Hz04_LP2 = 0xB0 , LSM6DSL_HP_DISABLE_LP1_LIGHT = 0x0A , LSM6DSL_HP_DISABLE_LP1_NORMAL = 0x09 , LSM6DSL_HP_DISABLE_LP_STRONG = 0x08 ,
LSM6DSL_HP_DISABLE_LP1_AGGRESSIVE = 0x0B , LSM6DSL_HP_16mHz_LP1_LIGHT = 0x8A , LSM6DSL_HP_65mHz_LP1_NORMAL = 0x99 , LSM6DSL_HP_260mHz_LP1_STRONG = 0xA8 ,
LSM6DSL_HP_1Hz04_LP1_AGGRESSIVE = 0xBB , LSM6DSL_HP_GY_BAND_NA = 0xFF
}
enum lsm6dsl_sim_t { LSM6DSL_SPI_4_WIRE = 0 , LSM6DSL_SPI_3_WIRE = 1 , LSM6DSL_SPI_MODE_ND = 2 }
enum lsm6dsl_i2c_disable_t { LSM6DSL_I2C_ENABLE = 0 , LSM6DSL_I2C_DISABLE = 1 , LSM6DSL_I2C_MODE_ND = 2 }
enum lsm6dsl_pp_od_t { LSM6DSL_PUSH_PULL = 0 , LSM6DSL_OPEN_DRAIN = 1 , LSM6DSL_PIN_MODE_ND = 2 }
enum lsm6dsl_h_lactive_t { LSM6DSL_ACTIVE_HIGH = 0 , LSM6DSL_ACTIVE_LOW = 1 , LSM6DSL_POLARITY_ND = 2 }
enum lsm6dsl_lir_t { LSM6DSL_INT_PULSED = 0 , LSM6DSL_INT_LATCHED = 1 , LSM6DSL_INT_MODE = 2 }
enum lsm6dsl_inact_en_t {
LSM6DSL_PROPERTY_DISABLE = 0 , LSM6DSL_XL_12Hz5_GY_NOT_AFFECTED = 1 , LSM6DSL_XL_12Hz5_GY_SLEEP = 2 , LSM6DSL_XL_12Hz5_GY_PD = 3 ,
LSM6DSL_ACT_MODE_ND = 4
}
enum lsm6dsl_single_double_tap_t { LSM6DSL_ONLY_SINGLE = 0 , LSM6DSL_BOTH_SINGLE_DOUBLE = 1 , LSM6DSL_TAP_MODE_ND = 2 }
enum lsm6dsl_low_pass_on_6d_t { LSM6DSL_ODR_DIV_2_FEED = 0 , LSM6DSL_LPF2_FEED = 1 , LSM6DSL_6D_FEED_ND = 2 }
enum lsm6dsl_sixd_ths_t {
LSM6DSL_DEG_80 = 0 , LSM6DSL_DEG_70 = 1 , LSM6DSL_DEG_60 = 2 , LSM6DSL_DEG_50 = 3 ,
LSM6DSL_6D_TH_ND = 4
}
enum lsm6dsl_ff_ths_t {
LSM6DSL_FF_TSH_156mg = 0 , LSM6DSL_FF_TSH_219mg = 1 , LSM6DSL_FF_TSH_250mg = 2 , LSM6DSL_FF_TSH_312mg = 3 ,
LSM6DSL_FF_TSH_344mg = 4 , LSM6DSL_FF_TSH_406mg = 5 , LSM6DSL_FF_TSH_469mg = 6 , LSM6DSL_FF_TSH_500mg = 7 ,
LSM6DSL_FF_TSH_ND = 8
}
enum lsm6dsl_trigger_fifo_t { LSM6DSL_TRG_XL_GY_DRDY = 0 , LSM6DSL_TRG_STEP_DETECT = 1 , LSM6DSL_TRG_SH_DRDY = 2 , LSM6DSL_TRG_SH_ND = 3 }
enum lsm6dsl_dec_fifo_xl_t {
LSM6DSL_FIFO_XL_DISABLE = 0 , LSM6DSL_FIFO_XL_NO_DEC = 1 , LSM6DSL_FIFO_XL_DEC_2 = 2 , LSM6DSL_FIFO_XL_DEC_3 = 3 ,
LSM6DSL_FIFO_XL_DEC_4 = 4 , LSM6DSL_FIFO_XL_DEC_8 = 5 , LSM6DSL_FIFO_XL_DEC_16 = 6 , LSM6DSL_FIFO_XL_DEC_32 = 7 ,
LSM6DSL_FIFO_XL_DEC_ND = 8
}
enum lsm6dsl_dec_fifo_gyro_t {
LSM6DSL_FIFO_GY_DISABLE = 0 , LSM6DSL_FIFO_GY_NO_DEC = 1 , LSM6DSL_FIFO_GY_DEC_2 = 2 , LSM6DSL_FIFO_GY_DEC_3 = 3 ,
LSM6DSL_FIFO_GY_DEC_4 = 4 , LSM6DSL_FIFO_GY_DEC_8 = 5 , LSM6DSL_FIFO_GY_DEC_16 = 6 , LSM6DSL_FIFO_GY_DEC_32 = 7 ,
LSM6DSL_FIFO_GY_DEC_ND = 8
}
enum lsm6dsl_dec_ds3_fifo_t {
LSM6DSL_FIFO_DS3_DISABLE = 0 , LSM6DSL_FIFO_DS3_NO_DEC = 1 , LSM6DSL_FIFO_DS3_DEC_2 = 2 , LSM6DSL_FIFO_DS3_DEC_3 = 3 ,
LSM6DSL_FIFO_DS3_DEC_4 = 4 , LSM6DSL_FIFO_DS3_DEC_8 = 5 , LSM6DSL_FIFO_DS3_DEC_16 = 6 , LSM6DSL_FIFO_DS3_DEC_32 = 7 ,
LSM6DSL_FIFO_DS3_DEC_ND = 8
}
enum lsm6dsl_dec_ds4_fifo_t {
LSM6DSL_FIFO_DS4_DISABLE = 0 , LSM6DSL_FIFO_DS4_NO_DEC = 1 , LSM6DSL_FIFO_DS4_DEC_2 = 2 , LSM6DSL_FIFO_DS4_DEC_3 = 3 ,
LSM6DSL_FIFO_DS4_DEC_4 = 4 , LSM6DSL_FIFO_DS4_DEC_8 = 5 , LSM6DSL_FIFO_DS4_DEC_16 = 6 , LSM6DSL_FIFO_DS4_DEC_32 = 7 ,
LSM6DSL_FIFO_DS4_DEC_ND = 8
}
enum lsm6dsl_fifo_mode_t {
LSM6DSL_BYPASS_MODE = 0 , LSM6DSL_FIFO_MODE = 1 , LSM6DSL_STREAM_TO_FIFO_MODE = 3 , LSM6DSL_BYPASS_TO_STREAM_MODE = 4 ,
LSM6DSL_STREAM_MODE = 6 , LSM6DSL_FIFO_MODE_ND = 8
}
enum lsm6dsl_odr_fifo_t {
LSM6DSL_FIFO_DISABLE = 0 , LSM6DSL_FIFO_12Hz5 = 1 , LSM6DSL_FIFO_26Hz = 2 , LSM6DSL_FIFO_52Hz = 3 ,
LSM6DSL_FIFO_104Hz = 4 , LSM6DSL_FIFO_208Hz = 5 , LSM6DSL_FIFO_416Hz = 6 , LSM6DSL_FIFO_833Hz = 7 ,
LSM6DSL_FIFO_1k66Hz = 8 , LSM6DSL_FIFO_3k33Hz = 9 , LSM6DSL_FIFO_6k66Hz = 10 , LSM6DSL_FIFO_RATE_ND = 11
}
enum lsm6dsl_den_lh_t { LSM6DSL_DEN_ACT_LOW = 0 , LSM6DSL_DEN_ACT_HIGH = 1 , LSM6DSL_DEN_POL_ND = 2 }
enum lsm6dsl_den_mode_t {
LSM6DSL_DEN_DISABLE = 0 , LSM6DSL_LEVEL_FIFO = 6 , LSM6DSL_LEVEL_LETCHED = 3 , LSM6DSL_LEVEL_TRIGGER = 2 ,
LSM6DSL_EDGE_TRIGGER = 4 , LSM6DSL_DEN_MODE_ND = 5
}
enum lsm6dsl_den_xl_en_t { LSM6DSL_STAMP_IN_GY_DATA = 0 , LSM6DSL_STAMP_IN_XL_DATA = 1 , LSM6DSL_STAMP_IN_GY_XL_DATA = 2 , LSM6DSL_DEN_STAMP_ND = 3 }
enum lsm6dsl_pedo_fs_t { LSM6DSL_PEDO_AT_2g = 0 , LSM6DSL_PEDO_AT_4g = 1 , LSM6DSL_PEDO_FS_ND = 2 }
enum lsm6dsl_rr_t {
LSM6DSL_RES_RATIO_2_11 = 0 , LSM6DSL_RES_RATIO_2_12 = 1 , LSM6DSL_RES_RATIO_2_13 = 2 , LSM6DSL_RES_RATIO_2_14 = 3 ,
LSM6DSL_RES_RATIO_ND = 4
}
enum lsm6dsl_pull_up_en_t { LSM6DSL_EXT_PULL_UP = 0 , LSM6DSL_INTERNAL_PULL_UP = 1 , LSM6DSL_SH_PIN_MODE = 2 }
enum lsm6dsl_start_config_t { LSM6DSL_XL_GY_DRDY = 0 , LSM6DSL_EXT_ON_INT2_PIN = 1 , LSM6DSL_SH_SYNCRO_ND = 2 }
enum lsm6dsl_aux_sens_on_t {
LSM6DSL_SLV_0 = 0 , LSM6DSL_SLV_0_1 = 1 , LSM6DSL_SLV_0_1_2 = 2 , LSM6DSL_SLV_0_1_2_3 = 3 ,
LSM6DSL_SLV_EN_ND = 4
}
enum lsm6dsl_slave0_rate_t {
LSM6DSL_SL0_NO_DEC = 0 , LSM6DSL_SL0_DEC_2 = 1 , LSM6DSL_SL0_DEC_4 = 2 , LSM6DSL_SL0_DEC_8 = 3 ,
LSM6DSL_SL0_DEC_ND = 4
}
enum lsm6dsl_write_once_t { LSM6DSL_EACH_SH_CYCLE = 0 , LSM6DSL_ONLY_FIRST_CYCLE = 1 , LSM6DSL_SH_WR_MODE_ND = 2 }
enum lsm6dsl_slave1_rate_t {
LSM6DSL_SL1_NO_DEC = 0 , LSM6DSL_SL1_DEC_2 = 1 , LSM6DSL_SL1_DEC_4 = 2 , LSM6DSL_SL1_DEC_8 = 3 ,
LSM6DSL_SL1_DEC_ND = 4
}
enum lsm6dsl_slave2_rate_t {
LSM6DSL_SL2_NO_DEC = 0 , LSM6DSL_SL2_DEC_2 = 1 , LSM6DSL_SL2_DEC_4 = 2 , LSM6DSL_SL2_DEC_8 = 3 ,
LSM6DSL_SL2_DEC_ND = 4
}
enum lsm6dsl_slave3_rate_t {
LSM6DSL_SL3_NO_DEC = 0 , LSM6DSL_SL3_DEC_2 = 1 , LSM6DSL_SL3_DEC_4 = 2 , LSM6DSL_SL3_DEC_8 = 3 ,
LSM6DSL_SL3_DEC_ND = 4
}
Functions
int32_t lsm6dsl_read_reg (stmdev_ctx_t *ctx, uint8_t reg, uint8_t *data, uint16_t len)
Read generic device register.
int32_t lsm6dsl_write_reg (stmdev_ctx_t *ctx, uint8_t reg, uint8_t *data, uint16_t len)
Write generic device register.
float_t lsm6dsl_from_fs2g_to_mg (int16_t lsb)
float_t lsm6dsl_from_fs4g_to_mg (int16_t lsb)
float_t lsm6dsl_from_fs8g_to_mg (int16_t lsb)
float_t lsm6dsl_from_fs16g_to_mg (int16_t lsb)
float_t lsm6dsl_from_fs125dps_to_mdps (int16_t lsb)
float_t lsm6dsl_from_fs250dps_to_mdps (int16_t lsb)
float_t lsm6dsl_from_fs500dps_to_mdps (int16_t lsb)
float_t lsm6dsl_from_fs1000dps_to_mdps (int16_t lsb)
float_t lsm6dsl_from_fs2000dps_to_mdps (int16_t lsb)
float_t lsm6dsl_from_lsb_to_celsius (int16_t lsb)
int32_t lsm6dsl_xl_full_scale_set (stmdev_ctx_t *ctx, lsm6dsl_fs_xl_t val)
Accelerometer full-scale selection.[set].
int32_t lsm6dsl_xl_full_scale_get (stmdev_ctx_t *ctx, lsm6dsl_fs_xl_t *val)
Accelerometer full-scale selection.[get].
int32_t lsm6dsl_xl_data_rate_set (stmdev_ctx_t *ctx, lsm6dsl_odr_xl_t val)
Accelerometer data rate selection.[set].
int32_t lsm6dsl_xl_data_rate_get (stmdev_ctx_t *ctx, lsm6dsl_odr_xl_t *val)
Accelerometer data rate selection.[get].
int32_t lsm6dsl_gy_full_scale_set (stmdev_ctx_t *ctx, lsm6dsl_fs_g_t val)
Gyroscope chain full-scale selection.[set].
int32_t lsm6dsl_gy_full_scale_get (stmdev_ctx_t *ctx, lsm6dsl_fs_g_t *val)
Gyroscope chain full-scale selection.[get].
int32_t lsm6dsl_gy_data_rate_set (stmdev_ctx_t *ctx, lsm6dsl_odr_g_t val)
Gyroscope data rate selection.[set].
int32_t lsm6dsl_gy_data_rate_get (stmdev_ctx_t *ctx, lsm6dsl_odr_g_t *val)
Gyroscope data rate selection.[get].
int32_t lsm6dsl_block_data_update_set (stmdev_ctx_t *ctx, uint8_t val)
Block data update.[set].
int32_t lsm6dsl_block_data_update_get (stmdev_ctx_t *ctx, uint8_t *val)
Block data update.[get].
int32_t lsm6dsl_xl_offset_weight_set (stmdev_ctx_t *ctx, lsm6dsl_usr_off_w_t val)
Weight of XL user offset bits of registers X_OFS_USR(73h), Y_OFS_USR(74h), Z_OFS_USR(75h).[set].
int32_t lsm6dsl_xl_offset_weight_get (stmdev_ctx_t *ctx, lsm6dsl_usr_off_w_t *val)
Weight of XL user offset bits of registers X_OFS_USR(73h), Y_OFS_USR(74h), Z_OFS_USR(75h).[get].
int32_t lsm6dsl_xl_power_mode_set (stmdev_ctx_t *ctx, lsm6dsl_xl_hm_mode_t val)
High-performance operating mode for accelerometer[set].
int32_t lsm6dsl_xl_power_mode_get (stmdev_ctx_t *ctx, lsm6dsl_xl_hm_mode_t *val)
High-performance operating mode for accelerometer.[get].
int32_t lsm6dsl_rounding_on_status_set (stmdev_ctx_t *ctx, lsm6dsl_rounding_status_t val)
Source register rounding function on WAKE_UP_SRC (1Bh), TAP_SRC (1Ch), D6D_SRC (1Dh), STATUS_REG (1Eh) and FUNC_SRC1 (53h) registers in the primary interface.[set].
int32_t lsm6dsl_rounding_on_status_get (stmdev_ctx_t *ctx, lsm6dsl_rounding_status_t *val)
Source register rounding function on WAKE_UP_SRC (1Bh), TAP_SRC (1Ch), D6D_SRC (1Dh), STATUS_REG (1Eh) and FUNC_SRC1 (53h) registers in the primary interface.[get].
int32_t lsm6dsl_gy_power_mode_set (stmdev_ctx_t *ctx, lsm6dsl_g_hm_mode_t val)
High-performance operating mode disable for gyroscope.[set].
int32_t lsm6dsl_gy_power_mode_get (stmdev_ctx_t *ctx, lsm6dsl_g_hm_mode_t *val)
High-performance operating mode disable for gyroscope.[get].
int32_t lsm6dsl_all_sources_get (stmdev_ctx_t *ctx, lsm6dsl_all_sources_t *val)
Read all the interrupt/status flag of the device.[get].
int32_t lsm6dsl_status_reg_get (stmdev_ctx_t *ctx, lsm6dsl_status_reg_t *val)
The STATUS_REG register is read by the primary interface[get].
int32_t lsm6dsl_xl_flag_data_ready_get (stmdev_ctx_t *ctx, uint8_t *val)
Accelerometer new data available.[get].
int32_t lsm6dsl_gy_flag_data_ready_get (stmdev_ctx_t *ctx, uint8_t *val)
Gyroscope new data available.[get].
int32_t lsm6dsl_temp_flag_data_ready_get (stmdev_ctx_t *ctx, uint8_t *val)
Temperature new data available.[get].
int32_t lsm6dsl_xl_usr_offset_set (stmdev_ctx_t *ctx, uint8_t *buff)
Accelerometer axis user offset correction expressed in two’s complement, weight depends on USR_OFF_W in CTRL6_C. The value must be in the range [-127 127].[set].
int32_t lsm6dsl_xl_usr_offset_get (stmdev_ctx_t *ctx, uint8_t *buff)
Accelerometer axis user offset correction xpressed in two’s complement, weight depends on USR_OFF_W in CTRL6_C. The value must be in the range [-127 127].[get].
int32_t lsm6dsl_timestamp_set (stmdev_ctx_t *ctx, uint8_t val)
Enable timestamp count. The count is saved in TIMESTAMP0_REG (40h), TIMESTAMP1_REG (41h) and TIMESTAMP2_REG (42h).[set].
int32_t lsm6dsl_timestamp_get (stmdev_ctx_t *ctx, uint8_t *val)
Enable timestamp count. The count is saved in TIMESTAMP0_REG (40h), TIMESTAMP1_REG (41h) and TIMESTAMP2_REG (42h).[get].
int32_t lsm6dsl_timestamp_res_set (stmdev_ctx_t *ctx, lsm6dsl_timer_hr_t val)
Timestamp register resolution setting. Configuration of this bit affects TIMESTAMP0_REG(40h), TIMESTAMP1_REG(41h), TIMESTAMP2_REG(42h), STEP_TIMESTAMP_L(49h), STEP_TIMESTAMP_H(4Ah) and STEP_COUNT_DELTA(15h) registers.[set].
int32_t lsm6dsl_timestamp_res_get (stmdev_ctx_t *ctx, lsm6dsl_timer_hr_t *val)
Timestamp register resolution setting. Configuration of this bit affects TIMESTAMP0_REG(40h), TIMESTAMP1_REG(41h), TIMESTAMP2_REG(42h), STEP_TIMESTAMP_L(49h), STEP_TIMESTAMP_H(4Ah) and STEP_COUNT_DELTA(15h) registers.[get].
int32_t lsm6dsl_rounding_mode_set (stmdev_ctx_t *ctx, lsm6dsl_rounding_t val)
Circular burst-mode (rounding) read from output registers through the primary interface.[set].
int32_t lsm6dsl_rounding_mode_get (stmdev_ctx_t *ctx, lsm6dsl_rounding_t *val)
Circular burst-mode (rounding) read from output registers through the primary interface.[get].
int32_t lsm6dsl_temperature_raw_get (stmdev_ctx_t *ctx, int16_t *val)
Temperature data output register (r). L and H registers together express a 16-bit word in two’s complement.[get].
int32_t lsm6dsl_angular_rate_raw_get (stmdev_ctx_t *ctx, int16_t *val)
Angular rate sensor. The value is expressed as a 16-bit word in two’s complement.[get].
int32_t lsm6dsl_acceleration_raw_get (stmdev_ctx_t *ctx, int16_t *val)
Linear acceleration output register. The value is expressed as a 16-bit word in two’s complement.[get].
int32_t lsm6dsl_mag_calibrated_raw_get (stmdev_ctx_t *ctx, int16_t *val)
External magnetometer raw data.[get].
int32_t lsm6dsl_fifo_raw_data_get (stmdev_ctx_t *ctx, uint8_t *buffer, uint8_t len)
Read data in FIFO.[get].
int32_t lsm6dsl_mem_bank_set (stmdev_ctx_t *ctx, lsm6dsl_func_cfg_en_t val)
Enable access to the embedded functions/sensor hub configuration registers[set].
int32_t lsm6dsl_mem_bank_get (stmdev_ctx_t *ctx, lsm6dsl_func_cfg_en_t *val)
Enable access to the embedded functions/sensor hub configuration registers[get].
int32_t lsm6dsl_data_ready_mode_set (stmdev_ctx_t *ctx, lsm6dsl_drdy_pulsed_g_t val)
Data-ready pulsed / letched mode[set].
int32_t lsm6dsl_data_ready_mode_get (stmdev_ctx_t *ctx, lsm6dsl_drdy_pulsed_g_t *val)
Data-ready pulsed / letched mode[get].
int32_t lsm6dsl_device_id_get (stmdev_ctx_t *ctx, uint8_t *buff)
DeviceWhoamI.[get].
int32_t lsm6dsl_reset_set (stmdev_ctx_t *ctx, uint8_t val)
Software reset. Restore the default values in user registers[set].
int32_t lsm6dsl_reset_get (stmdev_ctx_t *ctx, uint8_t *val)
Software reset. Restore the default values in user registers[get].
int32_t lsm6dsl_data_format_set (stmdev_ctx_t *ctx, lsm6dsl_ble_t val)
Big/Little Endian Data selection.[set].
int32_t lsm6dsl_data_format_get (stmdev_ctx_t *ctx, lsm6dsl_ble_t *val)
Big/Little Endian Data selection.[get].
int32_t lsm6dsl_auto_increment_set (stmdev_ctx_t *ctx, uint8_t val)
Register address automatically incremented during a multiple byte access with a serial interface.[set].
int32_t lsm6dsl_auto_increment_get (stmdev_ctx_t *ctx, uint8_t *val)
Register address automatically incremented during a multiple byte access with a serial interface.[get].
int32_t lsm6dsl_boot_set (stmdev_ctx_t *ctx, uint8_t val)
Reboot memory content. Reload the calibration parameters.[set].
int32_t lsm6dsl_boot_get (stmdev_ctx_t *ctx, uint8_t *val)
Reboot memory content. Reload the calibration parameters.[get].
int32_t lsm6dsl_xl_self_test_set (stmdev_ctx_t *ctx, lsm6dsl_st_xl_t val)
Linear acceleration sensor self-test enable.[set].
int32_t lsm6dsl_xl_self_test_get (stmdev_ctx_t *ctx, lsm6dsl_st_xl_t *val)
Linear acceleration sensor self-test enable.[get].
int32_t lsm6dsl_gy_self_test_set (stmdev_ctx_t *ctx, lsm6dsl_st_g_t val)
Angular rate sensor self-test enable.[set].
int32_t lsm6dsl_gy_self_test_get (stmdev_ctx_t *ctx, lsm6dsl_st_g_t *val)
Angular rate sensor self-test enable.[get].
int32_t lsm6dsl_filter_settling_mask_set (stmdev_ctx_t *ctx, uint8_t val)
Mask DRDY on pin (both XL & Gyro) until filter settling ends (XL and Gyro independently masked).[set].
int32_t lsm6dsl_filter_settling_mask_get (stmdev_ctx_t *ctx, uint8_t *val)
Mask DRDY on pin (both XL & Gyro) until filter settling ends (XL and Gyro independently masked).[get].
int32_t lsm6dsl_xl_hp_path_internal_set (stmdev_ctx_t *ctx, lsm6dsl_slope_fds_t val)
HPF or SLOPE filter selection on wake-up and Activity/Inactivity functions.[set].
int32_t lsm6dsl_xl_hp_path_internal_get (stmdev_ctx_t *ctx, lsm6dsl_slope_fds_t *val)
HPF or SLOPE filter selection on wake-up and Activity/Inactivity functions.[get].
int32_t lsm6dsl_xl_filter_analog_set (stmdev_ctx_t *ctx, lsm6dsl_bw0_xl_t val)
Accelerometer analog chain bandwidth selection (only for accelerometer ODR ≥ 1.67 kHz).[set].
int32_t lsm6dsl_xl_filter_analog_get (stmdev_ctx_t *ctx, lsm6dsl_bw0_xl_t *val)
Accelerometer analog chain bandwidth selection (only for accelerometer ODR ≥ 1.67 kHz).[get].
int32_t lsm6dsl_xl_lp1_bandwidth_set (stmdev_ctx_t *ctx, lsm6dsl_lpf1_bw_sel_t val)
Accelerometer digital LPF (LPF1) bandwidth selection LPF2 is not used.[set].
int32_t lsm6dsl_xl_lp1_bandwidth_get (stmdev_ctx_t *ctx, lsm6dsl_lpf1_bw_sel_t *val)
Accelerometer digital LPF (LPF1) bandwidth selection LPF2 is not used.[get].
int32_t lsm6dsl_xl_lp2_bandwidth_set (stmdev_ctx_t *ctx, lsm6dsl_input_composite_t val)
LPF2 on outputs[set].
int32_t lsm6dsl_xl_lp2_bandwidth_get (stmdev_ctx_t *ctx, lsm6dsl_input_composite_t *val)
LPF2 on outputs[get].
int32_t lsm6dsl_xl_reference_mode_set (stmdev_ctx_t *ctx, uint8_t val)
Enable HP filter reference mode.[set].
int32_t lsm6dsl_xl_reference_mode_get (stmdev_ctx_t *ctx, uint8_t *val)
Enable HP filter reference mode.[get].
int32_t lsm6dsl_xl_hp_bandwidth_set (stmdev_ctx_t *ctx, lsm6dsl_hpcf_xl_t val)
High pass/Slope on outputs.[set].
int32_t lsm6dsl_xl_hp_bandwidth_get (stmdev_ctx_t *ctx, lsm6dsl_hpcf_xl_t *val)
High pass/Slope on outputs.[get].
int32_t lsm6dsl_gy_band_pass_set (stmdev_ctx_t *ctx, lsm6dsl_lpf1_sel_g_t val)
Gyroscope low pass path bandwidth.[set].
int32_t lsm6dsl_gy_band_pass_get (stmdev_ctx_t *ctx, lsm6dsl_lpf1_sel_g_t *val)
Gyroscope low pass path bandwidth.[get].
int32_t lsm6dsl_spi_mode_set (stmdev_ctx_t *ctx, lsm6dsl_sim_t val)
SPI Serial Interface Mode selection.[set].
int32_t lsm6dsl_spi_mode_get (stmdev_ctx_t *ctx, lsm6dsl_sim_t *val)
SPI Serial Interface Mode selection.[get].
int32_t lsm6dsl_i2c_interface_set (stmdev_ctx_t *ctx, lsm6dsl_i2c_disable_t val)
Disable / Enable I2C interface.[set].
int32_t lsm6dsl_i2c_interface_get (stmdev_ctx_t *ctx, lsm6dsl_i2c_disable_t *val)
Disable / Enable I2C interface.[get].
int32_t lsm6dsl_pin_int1_route_set (stmdev_ctx_t *ctx, lsm6dsl_int1_route_t val)
Select the signal that need to route on int1 pad[set].
int32_t lsm6dsl_pin_int1_route_get (stmdev_ctx_t *ctx, lsm6dsl_int1_route_t *val)
Select the signal that need to route on int1 pad[get].
int32_t lsm6dsl_pin_int2_route_set (stmdev_ctx_t *ctx, lsm6dsl_int2_route_t val)
Select the signal that need to route on int2 pad[set].
int32_t lsm6dsl_pin_int2_route_get (stmdev_ctx_t *ctx, lsm6dsl_int2_route_t *val)
Select the signal that need to route on int2 pad[get].
int32_t lsm6dsl_pin_mode_set (stmdev_ctx_t *ctx, lsm6dsl_pp_od_t val)
Push-pull/open drain selection on interrupt pads.[set].
int32_t lsm6dsl_pin_mode_get (stmdev_ctx_t *ctx, lsm6dsl_pp_od_t *val)
Push-pull/open drain selection on interrupt pads.[get].
int32_t lsm6dsl_pin_polarity_set (stmdev_ctx_t *ctx, lsm6dsl_h_lactive_t val)
Interrupt active-high/low.[set].
int32_t lsm6dsl_pin_polarity_get (stmdev_ctx_t *ctx, lsm6dsl_h_lactive_t *val)
Interrupt active-high/low.[get].
int32_t lsm6dsl_all_on_int1_set (stmdev_ctx_t *ctx, uint8_t val)
All interrupt signals become available on INT1 pin.[set].
int32_t lsm6dsl_all_on_int1_get (stmdev_ctx_t *ctx, uint8_t *val)
All interrupt signals become available on INT1 pin.[get].
int32_t lsm6dsl_int_notification_set (stmdev_ctx_t *ctx, lsm6dsl_lir_t val)
Latched/pulsed interrupt.[set].
int32_t lsm6dsl_int_notification_get (stmdev_ctx_t *ctx, lsm6dsl_lir_t *val)
Latched/pulsed interrupt.[get].
int32_t lsm6dsl_wkup_threshold_set (stmdev_ctx_t *ctx, uint8_t val)
Threshold for wakeup.1 LSB = FS_XL / 64.[set].
int32_t lsm6dsl_wkup_threshold_get (stmdev_ctx_t *ctx, uint8_t *val)
Threshold for wakeup.1 LSB = FS_XL / 64.[get].
int32_t lsm6dsl_wkup_dur_set (stmdev_ctx_t *ctx, uint8_t val)
Wake up duration event.1LSb = 1 / ODR[set].
int32_t lsm6dsl_wkup_dur_get (stmdev_ctx_t *ctx, uint8_t *val)
Wake up duration event.1LSb = 1 / ODR[get].
int32_t lsm6dsl_gy_sleep_mode_set (stmdev_ctx_t *ctx, uint8_t val)
Enables gyroscope Sleep mode.[set].
int32_t lsm6dsl_gy_sleep_mode_get (stmdev_ctx_t *ctx, uint8_t *val)
Enables gyroscope Sleep mode.[get].
int32_t lsm6dsl_act_mode_set (stmdev_ctx_t *ctx, lsm6dsl_inact_en_t val)
Enable inactivity function.[set].
int32_t lsm6dsl_act_mode_get (stmdev_ctx_t *ctx, lsm6dsl_inact_en_t *val)
Enable inactivity function.[get].
int32_t lsm6dsl_act_sleep_dur_set (stmdev_ctx_t *ctx, uint8_t val)
Duration to go in sleep mode.1 LSb = 512 / ODR[set].
int32_t lsm6dsl_act_sleep_dur_get (stmdev_ctx_t *ctx, uint8_t *val)
Duration to go in sleep mode. 1 LSb = 512 / ODR[get].
int32_t lsm6dsl_tap_src_get (stmdev_ctx_t *ctx, lsm6dsl_tap_src_t *val)
Read the tap / double tap source register.[get].
int32_t lsm6dsl_tap_detection_on_z_set (stmdev_ctx_t *ctx, uint8_t val)
Enable Z direction in tap recognition.[set].
int32_t lsm6dsl_tap_detection_on_z_get (stmdev_ctx_t *ctx, uint8_t *val)
Enable Z direction in tap recognition.[get].
int32_t lsm6dsl_tap_detection_on_y_set (stmdev_ctx_t *ctx, uint8_t val)
Enable Y direction in tap recognition.[set].
int32_t lsm6dsl_tap_detection_on_y_get (stmdev_ctx_t *ctx, uint8_t *val)
Enable Y direction in tap recognition.[get].
int32_t lsm6dsl_tap_detection_on_x_set (stmdev_ctx_t *ctx, uint8_t val)
Enable X direction in tap recognition.[set].
int32_t lsm6dsl_tap_detection_on_x_get (stmdev_ctx_t *ctx, uint8_t *val)
Enable X direction in tap recognition.[get].
int32_t lsm6dsl_tap_threshold_x_set (stmdev_ctx_t *ctx, uint8_t val)
Threshold for tap recognition.[set].
int32_t lsm6dsl_tap_threshold_x_get (stmdev_ctx_t *ctx, uint8_t *val)
Threshold for tap recognition.[get].
int32_t lsm6dsl_tap_shock_set (stmdev_ctx_t *ctx, uint8_t val)
Maximum duration is the maximum time of an overthreshold signal detection to be recognized as a tap event. The default value of these bits is 00b which corresponds to 4*ODR_XL time. If the SHOCK[1:0] bits are set to a different value, 1LSB corresponds to 8*ODR_XL time.[set].
int32_t lsm6dsl_tap_shock_get (stmdev_ctx_t *ctx, uint8_t *val)
Maximum duration is the maximum time of an overthreshold signal detection to be recognized as a tap event. The default value of these bits is 00b which corresponds to 4*ODR_XL time. If the SHOCK[1:0] bits are set to a different value, 1LSB corresponds to 8*ODR_XL time.[get].
int32_t lsm6dsl_tap_quiet_set (stmdev_ctx_t *ctx, uint8_t val)
Quiet time is the time after the first detected tap in which there must not be any overthreshold event. The default value of these bits is 00b which corresponds to 2*ODR_XL time. If the QUIET[1:0] bits are set to a different value, 1LSB corresponds to 4*ODR_XL time.[set].
int32_t lsm6dsl_tap_quiet_get (stmdev_ctx_t *ctx, uint8_t *val)
Quiet time is the time after the first detected tap in which there must not be any overthreshold event. The default value of these bits is 00b which corresponds to 2*ODR_XL time. If the QUIET[1:0] bits are set to a different value, 1LSB corresponds to 4*ODR_XL time.[get].
int32_t lsm6dsl_tap_dur_set (stmdev_ctx_t *ctx, uint8_t val)
When double tap recognition is enabled, this register expresses the maximum time between two consecutive detected taps to determine a double tap event. The default value of these bits is 0000b which corresponds to 16*ODR_XL time. If the DUR[3:0] bits are set to a different value,1LSB corresponds to 32*ODR_XL time.[set].
int32_t lsm6dsl_tap_dur_get (stmdev_ctx_t *ctx, uint8_t *val)
When double tap recognition is enabled, this register expresses the maximum time between two consecutive detected taps to determine a double tap event. The default value of these bits is 0000b which corresponds to 16*ODR_XL time. If the DUR[3:0] bits are set to a different value,1LSB corresponds to 32*ODR_XL time.[get].
int32_t lsm6dsl_tap_mode_set (stmdev_ctx_t *ctx, lsm6dsl_single_double_tap_t val)
Single/double-tap event enable/disable.[set].
int32_t lsm6dsl_tap_mode_get (stmdev_ctx_t *ctx, lsm6dsl_single_double_tap_t *val)
Single/double-tap event enable/disable.[get].
int32_t lsm6dsl_6d_feed_data_set (stmdev_ctx_t *ctx, lsm6dsl_low_pass_on_6d_t val)
LPF2 feed 6D function selection.[set].
int32_t lsm6dsl_6d_feed_data_get (stmdev_ctx_t *ctx, lsm6dsl_low_pass_on_6d_t *val)
LPF2 feed 6D function selection.[get].
int32_t lsm6dsl_6d_threshold_set (stmdev_ctx_t *ctx, lsm6dsl_sixd_ths_t val)
Threshold for 4D/6D function.[set].
int32_t lsm6dsl_6d_threshold_get (stmdev_ctx_t *ctx, lsm6dsl_sixd_ths_t *val)
Threshold for 4D/6D function.[get].
int32_t lsm6dsl_4d_mode_set (stmdev_ctx_t *ctx, uint8_t val)
4D orientation detection enable.[set]
int32_t lsm6dsl_4d_mode_get (stmdev_ctx_t *ctx, uint8_t *val)
4D orientation detection enable.[get]
int32_t lsm6dsl_ff_dur_set (stmdev_ctx_t *ctx, uint8_t val)
Free-fall duration event. 1LSb = 1 / ODR[set].
int32_t lsm6dsl_ff_dur_get (stmdev_ctx_t *ctx, uint8_t *val)
Free-fall duration event. 1LSb = 1 / ODR[get].
int32_t lsm6dsl_ff_threshold_set (stmdev_ctx_t *ctx, lsm6dsl_ff_ths_t val)
Free fall threshold setting.[set].
int32_t lsm6dsl_ff_threshold_get (stmdev_ctx_t *ctx, lsm6dsl_ff_ths_t *val)
Free fall threshold setting.[get].
int32_t lsm6dsl_fifo_watermark_set (stmdev_ctx_t *ctx, uint16_t val)
FIFO watermark level selection.[set].
int32_t lsm6dsl_fifo_watermark_get (stmdev_ctx_t *ctx, uint16_t *val)
FIFO watermark level selection.[get].
int32_t lsm6dsl_fifo_data_level_get (stmdev_ctx_t *ctx, uint16_t *val)
FIFO data level.[get].
int32_t lsm6dsl_fifo_wtm_flag_get (stmdev_ctx_t *ctx, uint8_t *val)
FIFO watermark.[get].
int32_t lsm6dsl_fifo_pattern_get (stmdev_ctx_t *ctx, uint16_t *val)
FIFO pattern.[get].
int32_t lsm6dsl_fifo_temp_batch_set (stmdev_ctx_t *ctx, uint8_t val)
Batching of temperature data[set].
int32_t lsm6dsl_fifo_temp_batch_get (stmdev_ctx_t *ctx, uint8_t *val)
Batching of temperature data[get].
int32_t lsm6dsl_fifo_write_trigger_set (stmdev_ctx_t *ctx, lsm6dsl_trigger_fifo_t val)
Trigger signal for FIFO write operation.[set].
int32_t lsm6dsl_fifo_write_trigger_get (stmdev_ctx_t *ctx, lsm6dsl_trigger_fifo_t *val)
Trigger signal for FIFO write operation.[get].
int32_t lsm6dsl_fifo_pedo_and_timestamp_batch_set (stmdev_ctx_t *ctx, uint8_t val)
Enable pedometer step counter and timestamp as 4th FIFO data set.[set].
int32_t lsm6dsl_fifo_pedo_and_timestamp_batch_get (stmdev_ctx_t *ctx, uint8_t *val)
Enable pedometer step counter and timestamp as 4th FIFO data set.[get].
int32_t lsm6dsl_fifo_xl_batch_set (stmdev_ctx_t *ctx, lsm6dsl_dec_fifo_xl_t val)
Selects Batching Data Rate (writing frequency in FIFO) for accelerometer data.[set].
int32_t lsm6dsl_fifo_xl_batch_get (stmdev_ctx_t *ctx, lsm6dsl_dec_fifo_xl_t *val)
Selects Batching Data Rate (writing frequency in FIFO) for accelerometer data.[get].
int32_t lsm6dsl_fifo_gy_batch_set (stmdev_ctx_t *ctx, lsm6dsl_dec_fifo_gyro_t val)
Selects Batching Data Rate (writing frequency in FIFO) for gyroscope data.[set].
int32_t lsm6dsl_fifo_gy_batch_get (stmdev_ctx_t *ctx, lsm6dsl_dec_fifo_gyro_t *val)
Selects Batching Data Rate (writing frequency in FIFO) for gyroscope data.[get].
int32_t lsm6dsl_fifo_dataset_3_batch_set (stmdev_ctx_t *ctx, lsm6dsl_dec_ds3_fifo_t val)
Selects Batching Data Rate (writing frequency in FIFO) for third data set.[set].
int32_t lsm6dsl_fifo_dataset_3_batch_get (stmdev_ctx_t *ctx, lsm6dsl_dec_ds3_fifo_t *val)
Selects Batching Data Rate (writing frequency in FIFO) for third data set.[get].
int32_t lsm6dsl_fifo_dataset_4_batch_set (stmdev_ctx_t *ctx, lsm6dsl_dec_ds4_fifo_t val)
Selects Batching Data Rate (writing frequency in FIFO) for fourth data set.[set].
int32_t lsm6dsl_fifo_dataset_4_batch_get (stmdev_ctx_t *ctx, lsm6dsl_dec_ds4_fifo_t *val)
Selects Batching Data Rate (writing frequency in FIFO) for fourth data set.[get].
int32_t lsm6dsl_fifo_xl_gy_8bit_format_set (stmdev_ctx_t *ctx, uint8_t val)
8-bit data storage in FIFO.[set]
int32_t lsm6dsl_fifo_xl_gy_8bit_format_get (stmdev_ctx_t *ctx, uint8_t *val)
8-bit data storage in FIFO.[get]
int32_t lsm6dsl_fifo_stop_on_wtm_set (stmdev_ctx_t *ctx, uint8_t val)
Sensing chain FIFO stop values memorization at threshold level.[set].
int32_t lsm6dsl_fifo_stop_on_wtm_get (stmdev_ctx_t *ctx, uint8_t *val)
Sensing chain FIFO stop values memorization at threshold level.[get].
int32_t lsm6dsl_fifo_mode_set (stmdev_ctx_t *ctx, lsm6dsl_fifo_mode_t val)
FIFO mode selection.[set].
int32_t lsm6dsl_fifo_mode_get (stmdev_ctx_t *ctx, lsm6dsl_fifo_mode_t *val)
FIFO mode selection.[get].
int32_t lsm6dsl_fifo_data_rate_set (stmdev_ctx_t *ctx, lsm6dsl_odr_fifo_t val)
FIFO ODR selection, setting FIFO_MODE also.[set].
int32_t lsm6dsl_fifo_data_rate_get (stmdev_ctx_t *ctx, lsm6dsl_odr_fifo_t *val)
FIFO ODR selection, setting FIFO_MODE also.[get].
int32_t lsm6dsl_den_polarity_set (stmdev_ctx_t *ctx, lsm6dsl_den_lh_t val)
DEN active level configuration.[set].
int32_t lsm6dsl_den_polarity_get (stmdev_ctx_t *ctx, lsm6dsl_den_lh_t *val)
DEN active level configuration.[get].
int32_t lsm6dsl_den_mode_set (stmdev_ctx_t *ctx, lsm6dsl_den_mode_t val)
DEN functionality marking mode[set].
int32_t lsm6dsl_den_mode_get (stmdev_ctx_t *ctx, lsm6dsl_den_mode_t *val)
DEN functionality marking mode[get].
int32_t lsm6dsl_den_enable_set (stmdev_ctx_t *ctx, lsm6dsl_den_xl_en_t val)
Extend DEN functionality to accelerometer sensor.[set].
int32_t lsm6dsl_den_enable_get (stmdev_ctx_t *ctx, lsm6dsl_den_xl_en_t *val)
Extend DEN functionality to accelerometer sensor. [get].
int32_t lsm6dsl_den_mark_axis_z_set (stmdev_ctx_t *ctx, uint8_t val)
DEN value stored in LSB of Z-axis.[set].
int32_t lsm6dsl_den_mark_axis_z_get (stmdev_ctx_t *ctx, uint8_t *val)
DEN value stored in LSB of Z-axis.[get].
int32_t lsm6dsl_den_mark_axis_y_set (stmdev_ctx_t *ctx, uint8_t val)
DEN value stored in LSB of Y-axis.[set].
int32_t lsm6dsl_den_mark_axis_y_get (stmdev_ctx_t *ctx, uint8_t *val)
DEN value stored in LSB of Y-axis.[get].
int32_t lsm6dsl_den_mark_axis_x_set (stmdev_ctx_t *ctx, uint8_t val)
DEN value stored in LSB of X-axis.[set].
int32_t lsm6dsl_den_mark_axis_x_get (stmdev_ctx_t *ctx, uint8_t *val)
DEN value stored in LSB of X-axis.[get].
int32_t lsm6dsl_pedo_step_reset_set (stmdev_ctx_t *ctx, uint8_t val)
Reset pedometer step counter.[set].
int32_t lsm6dsl_pedo_step_reset_get (stmdev_ctx_t *ctx, uint8_t *val)
Reset pedometer step counter.[get].
int32_t lsm6dsl_pedo_sens_set (stmdev_ctx_t *ctx, uint8_t val)
Enable pedometer algorithm.[set].
int32_t lsm6dsl_pedo_sens_get (stmdev_ctx_t *ctx, uint8_t *val)
pedo_sens: Enable pedometer algorithm.[get]
int32_t lsm6dsl_pedo_threshold_set (stmdev_ctx_t *ctx, uint8_t val)
Minimum threshold to detect a peak. Default is 10h.[set].
int32_t lsm6dsl_pedo_threshold_get (stmdev_ctx_t *ctx, uint8_t *val)
Minimum threshold to detect a peak. Default is 10h.[get].
int32_t lsm6dsl_pedo_full_scale_set (stmdev_ctx_t *ctx, lsm6dsl_pedo_fs_t val)
pedo_full_scale: Pedometer data range.[set]
int32_t lsm6dsl_pedo_full_scale_get (stmdev_ctx_t *ctx, lsm6dsl_pedo_fs_t *val)
Pedometer data range.[get].
int32_t lsm6dsl_pedo_debounce_steps_set (stmdev_ctx_t *ctx, uint8_t val)
Pedometer debounce configuration register (r/w).[set].
int32_t lsm6dsl_pedo_debounce_steps_get (stmdev_ctx_t *ctx, uint8_t *val)
Pedometer debounce configuration register (r/w).[get].
int32_t lsm6dsl_pedo_timeout_set (stmdev_ctx_t *ctx, uint8_t val)
Debounce time. If the time between two consecutive steps is greater than DEB_TIME*80ms, the debouncer is reactivated. Default value: 01101[set].
int32_t lsm6dsl_pedo_timeout_get (stmdev_ctx_t *ctx, uint8_t *val)
Debounce time. If the time between two consecutive steps is greater than DEB_TIME*80ms, the debouncer is reactivated. Default value: 01101[get].
int32_t lsm6dsl_pedo_steps_period_set (stmdev_ctx_t *ctx, uint8_t *buff)
Time period register for step detection on delta time (r/w).[set].
int32_t lsm6dsl_pedo_steps_period_get (stmdev_ctx_t *ctx, uint8_t *buff)
Time period register for step detection on delta time (r/w).[get].
int32_t lsm6dsl_motion_sens_set (stmdev_ctx_t *ctx, uint8_t val)
Enable significant motion detection function.[set].
int32_t lsm6dsl_motion_sens_get (stmdev_ctx_t *ctx, uint8_t *val)
Enable significant motion detection function.[get].
int32_t lsm6dsl_motion_threshold_set (stmdev_ctx_t *ctx, uint8_t *buff)
Significant motion threshold.[set].
int32_t lsm6dsl_motion_threshold_get (stmdev_ctx_t *ctx, uint8_t *buff)
Significant motion threshold.[get].
int32_t lsm6dsl_tilt_sens_set (stmdev_ctx_t *ctx, uint8_t val)
Enable tilt calculation.[set].
int32_t lsm6dsl_tilt_sens_get (stmdev_ctx_t *ctx, uint8_t *val)
Enable tilt calculation.[get].
int32_t lsm6dsl_wrist_tilt_sens_set (stmdev_ctx_t *ctx, uint8_t val)
Enable tilt calculation.[set].
int32_t lsm6dsl_wrist_tilt_sens_get (stmdev_ctx_t *ctx, uint8_t *val)
Enable tilt calculation.[get].
int32_t lsm6dsl_tilt_latency_set (stmdev_ctx_t *ctx, uint8_t *buff)
Absolute Wrist Tilt latency register (r/w). Absolute wrist tilt latency parameters. 1 LSB = 40 ms. Default value: 0Fh (600 ms).[set].
int32_t lsm6dsl_tilt_latency_get (stmdev_ctx_t *ctx, uint8_t *buff)
Absolute Wrist Tilt latency register (r/w). Absolute wrist tilt latency parameters. 1 LSB = 40 ms. Default value: 0Fh (600 ms).[get].
int32_t lsm6dsl_tilt_threshold_set (stmdev_ctx_t *ctx, uint8_t *buff)
Absolute Wrist Tilt threshold register(r/w). Absolute wrist tilt threshold parameters. 1 LSB = 15.625 mg.Default value: 20h (500 mg).[set].
int32_t lsm6dsl_tilt_threshold_get (stmdev_ctx_t *ctx, uint8_t *buff)
Absolute Wrist Tilt threshold register(r/w). Absolute wrist tilt threshold parameters. 1 LSB = 15.625 mg.Default value: 20h (500 mg).[get].
int32_t lsm6dsl_tilt_src_set (stmdev_ctx_t *ctx, lsm6dsl_a_wrist_tilt_mask_t *val)
Absolute Wrist Tilt mask register (r/w).[set].
int32_t lsm6dsl_tilt_src_get (stmdev_ctx_t *ctx, lsm6dsl_a_wrist_tilt_mask_t *val)
Absolute Wrist Tilt mask register (r/w).[get].
int32_t lsm6dsl_mag_soft_iron_set (stmdev_ctx_t *ctx, uint8_t val)
Enable soft-iron correction algorithm for magnetometer.[set].
int32_t lsm6dsl_mag_soft_iron_get (stmdev_ctx_t *ctx, uint8_t *val)
Enable soft-iron correction algorithm for magnetometer.[get].
int32_t lsm6dsl_mag_hard_iron_set (stmdev_ctx_t *ctx, uint8_t val)
Enable hard-iron correction algorithm for magnetometer.[set].
int32_t lsm6dsl_mag_hard_iron_get (stmdev_ctx_t *ctx, uint8_t *val)
Enable hard-iron correction algorithm for magnetometer.[get].
int32_t lsm6dsl_mag_soft_iron_mat_set (stmdev_ctx_t *ctx, uint8_t *buff)
Soft iron 3x3 matrix. Value are expressed in sign-module format. (Es. SVVVVVVVb where S is the sign 0/+1/- and V is the value).[set].
int32_t lsm6dsl_mag_soft_iron_mat_get (stmdev_ctx_t *ctx, uint8_t *buff)
Soft iron 3x3 matrix. Value are expressed in sign-module format. (Es. SVVVVVVVb where S is the sign 0/+1/- and V is the value).[get].
int32_t lsm6dsl_mag_offset_set (stmdev_ctx_t *ctx, int16_t *val)
Offset for hard-iron compensation register (r/w). The value is expressed as a 16-bit word in two’s complement.[set].
int32_t lsm6dsl_mag_offset_get (stmdev_ctx_t *ctx, int16_t *val)
Offset for hard-iron compensation register(r/w). The value is expressed as a 16-bit word in two’s complement.[get].
int32_t lsm6dsl_func_en_set (stmdev_ctx_t *ctx, uint8_t val)
Enable function.[set].
int32_t lsm6dsl_sh_sync_sens_frame_set (stmdev_ctx_t *ctx, uint8_t val)
Sensor synchronization time frame with the step of 500 ms and full range of 5s. Unsigned 8-bit.[set].
int32_t lsm6dsl_sh_sync_sens_frame_get (stmdev_ctx_t *ctx, uint8_t *val)
Sensor synchronization time frame with the step of 500 ms and full range of 5s. Unsigned 8-bit.[get].
int32_t lsm6dsl_sh_sync_sens_ratio_set (stmdev_ctx_t *ctx, lsm6dsl_rr_t val)
Resolution ratio of error code for sensor synchronization.[set].
int32_t lsm6dsl_sh_sync_sens_ratio_get (stmdev_ctx_t *ctx, lsm6dsl_rr_t *val)
Resolution ratio of error code for sensor synchronization.[get].
int32_t lsm6dsl_sh_master_set (stmdev_ctx_t *ctx, uint8_t val)
Sensor hub I2C master enable.[set].
int32_t lsm6dsl_sh_master_get (stmdev_ctx_t *ctx, uint8_t *val)
Sensor hub I2C master enable.[get].
int32_t lsm6dsl_sh_pass_through_set (stmdev_ctx_t *ctx, uint8_t val)
I2C interface pass-through.[set].
int32_t lsm6dsl_sh_pass_through_get (stmdev_ctx_t *ctx, uint8_t *val)
I2C interface pass-through.[get].
int32_t lsm6dsl_sh_pin_mode_set (stmdev_ctx_t *ctx, lsm6dsl_pull_up_en_t val)
Master I2C pull-up enable/disable.[set].
int32_t lsm6dsl_sh_pin_mode_get (stmdev_ctx_t *ctx, lsm6dsl_pull_up_en_t *val)
Master I2C pull-up enable/disable.[get].
int32_t lsm6dsl_sh_syncro_mode_set (stmdev_ctx_t *ctx, lsm6dsl_start_config_t val)
Sensor hub trigger signal selection.[set].
int32_t lsm6dsl_sh_syncro_mode_get (stmdev_ctx_t *ctx, lsm6dsl_start_config_t *val)
Sensor hub trigger signal selection.[get].
int32_t lsm6dsl_sh_drdy_on_int1_set (stmdev_ctx_t *ctx, uint8_t val)
Manage the Master DRDY signal on INT1 pad.[set].
int32_t lsm6dsl_sh_drdy_on_int1_get (stmdev_ctx_t *ctx, uint8_t *val)
Manage the Master DRDY signal on INT1 pad.[get].
int32_t lsm6dsl_sh_read_data_raw_get (stmdev_ctx_t *ctx, lsm6dsl_emb_sh_read_t *val)
Sensor hub output registers.[get].
int32_t lsm6dsl_sh_cmd_sens_sync_set (stmdev_ctx_t *ctx, uint8_t val)
Master command code used for stamping for sensor sync.[set].
int32_t lsm6dsl_sh_cmd_sens_sync_get (stmdev_ctx_t *ctx, uint8_t *val)
Master command code used for stamping for sensor sync.[get].
int32_t lsm6dsl_sh_spi_sync_error_set (stmdev_ctx_t *ctx, uint8_t val)
Error code used for sensor synchronization.[set].
int32_t lsm6dsl_sh_spi_sync_error_get (stmdev_ctx_t *ctx, uint8_t *val)
Error code used for sensor synchronization.[get].
int32_t lsm6dsl_sh_num_of_dev_connected_set (stmdev_ctx_t *ctx, lsm6dsl_aux_sens_on_t val)
Number of external sensors to be read by the sensor hub.[set].
int32_t lsm6dsl_sh_num_of_dev_connected_get (stmdev_ctx_t *ctx, lsm6dsl_aux_sens_on_t *val)
Number of external sensors to be read by the sensor hub.[get].
int32_t lsm6dsl_sh_cfg_write (stmdev_ctx_t *ctx, lsm6dsl_sh_cfg_write_t *val)
Configure slave 0 for perform a write.[set].
int32_t lsm6dsl_sh_slv0_cfg_read (stmdev_ctx_t *ctx, lsm6dsl_sh_cfg_read_t *val)
Configure slave 0 for perform a read.[get].
int32_t lsm6dsl_sh_slv1_cfg_read (stmdev_ctx_t *ctx, lsm6dsl_sh_cfg_read_t *val)
Configure slave 1 for perform a read.[get].
int32_t lsm6dsl_sh_slv2_cfg_read (stmdev_ctx_t *ctx, lsm6dsl_sh_cfg_read_t *val)
Configure slave 2 for perform a read.[get].
int32_t lsm6dsl_sh_slv3_cfg_read (stmdev_ctx_t *ctx, lsm6dsl_sh_cfg_read_t *val)
Configure slave 3 for perform a read.[get].
int32_t lsm6dsl_sh_slave_0_dec_set (stmdev_ctx_t *ctx, lsm6dsl_slave0_rate_t val)
Decimation of read operation on Slave 0 starting from the sensor hub trigger.[set].
int32_t lsm6dsl_sh_slave_0_dec_get (stmdev_ctx_t *ctx, lsm6dsl_slave0_rate_t *val)
Decimation of read operation on Slave 0 starting from the sensor hub trigger.[get].
int32_t lsm6dsl_sh_write_mode_set (stmdev_ctx_t *ctx, lsm6dsl_write_once_t val)
Slave 0 write operation is performed only at the first sensor hub cycle. This is effective if the Aux_sens_on[1:0] field in SLAVE0_CONFIG(04h) is set to a value other than 00.[set].
int32_t lsm6dsl_sh_write_mode_get (stmdev_ctx_t *ctx, lsm6dsl_write_once_t *val)
Slave 0 write operation is performed only at the first sensor hub cycle. This is effective if the Aux_sens_on[1:0] field in SLAVE0_CONFIG(04h) is set to a value other than 00.[get].
int32_t lsm6dsl_sh_slave_1_dec_set (stmdev_ctx_t *ctx, lsm6dsl_slave1_rate_t val)
Decimation of read operation on Slave 1 starting from the sensor hub trigger.[set].
int32_t lsm6dsl_sh_slave_1_dec_get (stmdev_ctx_t *ctx, lsm6dsl_slave1_rate_t *val)
Decimation of read operation on Slave 1 starting from the sensor hub trigger.[get].
int32_t lsm6dsl_sh_slave_2_dec_set (stmdev_ctx_t *ctx, lsm6dsl_slave2_rate_t val)
Decimation of read operation on Slave 2 starting from the sensor hub trigger.[set].
int32_t lsm6dsl_sh_slave_2_dec_get (stmdev_ctx_t *ctx, lsm6dsl_slave2_rate_t *val)
Decimation of read operation on Slave 2 starting from the sensor hub trigger.[get].
int32_t lsm6dsl_sh_slave_3_dec_set (stmdev_ctx_t *ctx, lsm6dsl_slave3_rate_t val)
Decimation of read operation on Slave 3 starting from the sensor hub trigger.[set].
int32_t lsm6dsl_sh_slave_3_dec_get (stmdev_ctx_t *ctx, lsm6dsl_slave3_rate_t *val)
Decimation of read operation on Slave 3 starting from the sensor hub trigger.[get].
Detailed Description
This file provides a set of functions needed to drive the lsm6dsl enanced inertial module.
Function Documentation
lsm6dsl_4d_mode_get()
int32_t lsm6dsl_4d_mode_get (stmdev_ctx_t * ctx, uint8_t * val)
4D orientation detection enable.[get]
Parameters
ctx Read / write interface definitions
val Change the values of d4d_en in reg TAP_THS_6D
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_4d_mode_set()
int32_t lsm6dsl_4d_mode_set (stmdev_ctx_t * ctx, uint8_t val)
4D orientation detection enable.[set]
Parameters
ctx Read / write interface definitions
val Change the values of d4d_en in reg TAP_THS_6D
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_6d_feed_data_get()
int32_t lsm6dsl_6d_feed_data_get (stmdev_ctx_t * ctx, lsm6dsl_low_pass_on_6d_t * val)
LPF2 feed 6D function selection.[get].
Parameters
ctx Read / write interface definitions
val Get the values of low_pass_on_6d in reg CTRL8_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_6d_feed_data_set()
int32_t lsm6dsl_6d_feed_data_set (stmdev_ctx_t * ctx, lsm6dsl_low_pass_on_6d_t val)
LPF2 feed 6D function selection.[set].
Parameters
ctx Read / write interface definitions
val Change the values of low_pass_on_6d in reg CTRL8_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_6d_threshold_get()
int32_t lsm6dsl_6d_threshold_get (stmdev_ctx_t * ctx, lsm6dsl_sixd_ths_t * val)
Threshold for 4D/6D function.[get].
Parameters
ctx Read / write interface definitions
val Get the values of sixd_ths in reg TAP_THS_6D
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_6d_threshold_set()
int32_t lsm6dsl_6d_threshold_set (stmdev_ctx_t * ctx, lsm6dsl_sixd_ths_t val)
Threshold for 4D/6D function.[set].
Parameters
ctx Read / write interface definitions
val Change the values of sixd_ths in reg TAP_THS_6D
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Set_6D_Orientation_Threshold().
lsm6dsl_acceleration_raw_get()
int32_t lsm6dsl_acceleration_raw_get (stmdev_ctx_t * ctx, int16_t * val)
Linear acceleration output register. The value is expressed as a 16-bit word in two’s complement.[get].
Parameters
ctx Read / write interface definitions
buff Buffer that stores data read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_GetAxes(), and LSM6DSL_ACC_GetAxesRaw().
lsm6dsl_act_mode_get()
int32_t lsm6dsl_act_mode_get (stmdev_ctx_t * ctx, lsm6dsl_inact_en_t * val)
Enable inactivity function.[get].
Parameters
ctx Read / write interface definitions
val Get the values of inact_en in reg TAP_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_act_mode_set()
int32_t lsm6dsl_act_mode_set (stmdev_ctx_t * ctx, lsm6dsl_inact_en_t val)
Enable inactivity function.[set].
Parameters
ctx Read / write interface definitions
val Change the values of inact_en in reg TAP_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_act_sleep_dur_get()
int32_t lsm6dsl_act_sleep_dur_get (stmdev_ctx_t * ctx, uint8_t * val)
Duration to go in sleep mode. 1 LSb = 512 / ODR[get].
Parameters
ctx Read / write interface definitions
val Change the values of sleep_dur in reg WAKE_UP_DUR
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_act_sleep_dur_set()
int32_t lsm6dsl_act_sleep_dur_set (stmdev_ctx_t * ctx, uint8_t val)
Duration to go in sleep mode.1 LSb = 512 / ODR[set].
Parameters
ctx Read / write interface definitions
val Change the values of sleep_dur in reg WAKE_UP_DUR
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Set_Sleep_Duration().
lsm6dsl_all_on_int1_get()
int32_t lsm6dsl_all_on_int1_get (stmdev_ctx_t * ctx, uint8_t * val)
All interrupt signals become available on INT1 pin.[get].
Parameters
ctx Read / write interface definitions
val Change the values of int2_on_int1 in reg CTRL4_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_all_on_int1_set()
int32_t lsm6dsl_all_on_int1_set (stmdev_ctx_t * ctx, uint8_t val)
All interrupt signals become available on INT1 pin.[set].
Parameters
ctx Read / write interface definitions
val Change the values of int2_on_int1 in reg CTRL4_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_all_sources_get()
int32_t lsm6dsl_all_sources_get (stmdev_ctx_t * ctx, lsm6dsl_all_sources_t * val)
Read all the interrupt/status flag of the device.[get].
Parameters
ctx Read / write interface definitions
val WAKE_UP_SRC, TAP_SRC, D6D_SRC, STATUS_REG, FUNC_SRC1, FUNC_SRC2, WRIST_TILT_IA, A_WRIST_TILT_Mask
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_angular_rate_raw_get()
int32_t lsm6dsl_angular_rate_raw_get (stmdev_ctx_t * ctx, int16_t * val)
Angular rate sensor. The value is expressed as a 16-bit word in two’s complement.[get].
Parameters
ctx Read / write interface definitions
buff Buffer that stores data read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_GYRO_GetAxes(), and LSM6DSL_GYRO_GetAxesRaw().
lsm6dsl_auto_increment_get()
int32_t lsm6dsl_auto_increment_get (stmdev_ctx_t * ctx, uint8_t * val)
Register address automatically incremented during a multiple byte access with a serial interface.[get].
Parameters
ctx Read / write interface definitions
val Change the values of if_inc in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_auto_increment_set()
int32_t lsm6dsl_auto_increment_set (stmdev_ctx_t * ctx, uint8_t val)
Register address automatically incremented during a multiple byte access with a serial interface.[set].
Parameters
ctx Read / write interface definitions
val Change the values of if_inc in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_Init().
lsm6dsl_block_data_update_get()
int32_t lsm6dsl_block_data_update_get (stmdev_ctx_t * ctx, uint8_t * val)
Block data update.[get].
Parameters
ctx Read / write interface definitions
val Change the values of bdu in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_block_data_update_set()
int32_t lsm6dsl_block_data_update_set (stmdev_ctx_t * ctx, uint8_t val)
Block data update.[set].
Parameters
ctx Read / write interface definitions
val Change the values of bdu in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_boot_get()
int32_t lsm6dsl_boot_get (stmdev_ctx_t * ctx, uint8_t * val)
Reboot memory content. Reload the calibration parameters.[get].
Parameters
ctx Read / write interface definitions
val Change the values of boot in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_boot_set()
int32_t lsm6dsl_boot_set (stmdev_ctx_t * ctx, uint8_t val)
Reboot memory content. Reload the calibration parameters.[set].
Parameters
ctx Read / write interface definitions
val Change the values of boot in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_data_format_get()
int32_t lsm6dsl_data_format_get (stmdev_ctx_t * ctx, lsm6dsl_ble_t * val)
Big/Little Endian Data selection.[get].
Parameters
ctx Read / write interface definitions
val Get the values of ble in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_data_format_set()
int32_t lsm6dsl_data_format_set (stmdev_ctx_t * ctx, lsm6dsl_ble_t val)
Big/Little Endian Data selection.[set].
Parameters
ctx Read / write interface definitions
val Change the values of ble in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_data_ready_mode_get()
int32_t lsm6dsl_data_ready_mode_get (stmdev_ctx_t * ctx, lsm6dsl_drdy_pulsed_g_t * val)
Data-ready pulsed / letched mode[get].
Parameters
ctx Read / write interface definitions
val Get the values of drdy_pulsed in reg DRDY_PULSE_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_data_ready_mode_set()
int32_t lsm6dsl_data_ready_mode_set (stmdev_ctx_t * ctx, lsm6dsl_drdy_pulsed_g_t val)
Data-ready pulsed / letched mode[set].
Parameters
ctx Read / write interface definitions
val Change the values of drdy_pulsed in reg DRDY_PULSE_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_den_enable_get()
int32_t lsm6dsl_den_enable_get (stmdev_ctx_t * ctx, lsm6dsl_den_xl_en_t * val)
Extend DEN functionality to accelerometer sensor. [get].
Parameters
ctx Read / write interface definitions
val Get the values of den_xl_g in reg CTRL9_XL and den_xl_en in CTRL4_C.
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_den_enable_set()
int32_t lsm6dsl_den_enable_set (stmdev_ctx_t * ctx, lsm6dsl_den_xl_en_t val)
Extend DEN functionality to accelerometer sensor.[set].
Parameters
ctx Read / write interface definitions
val Change the values of den_xl_g in reg CTRL9_XL and den_xl_en in CTRL4_C.
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_den_mark_axis_x_get()
int32_t lsm6dsl_den_mark_axis_x_get (stmdev_ctx_t * ctx, uint8_t * val)
DEN value stored in LSB of X-axis.[get].
Parameters
ctx Read / write interface definitions
val Change the values of den_x in reg CTRL9_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_den_mark_axis_x_set()
int32_t lsm6dsl_den_mark_axis_x_set (stmdev_ctx_t * ctx, uint8_t val)
DEN value stored in LSB of X-axis.[set].
Parameters
ctx Read / write interface definitions
val Change the values of den_x in reg CTRL9_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_den_mark_axis_y_get()
int32_t lsm6dsl_den_mark_axis_y_get (stmdev_ctx_t * ctx, uint8_t * val)
DEN value stored in LSB of Y-axis.[get].
Parameters
ctx Read / write interface definitions
val Change the values of den_y in reg CTRL9_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_den_mark_axis_y_set()
int32_t lsm6dsl_den_mark_axis_y_set (stmdev_ctx_t * ctx, uint8_t val)
DEN value stored in LSB of Y-axis.[set].
Parameters
ctx Read / write interface definitions
val Change the values of den_y in reg CTRL9_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_den_mark_axis_z_get()
int32_t lsm6dsl_den_mark_axis_z_get (stmdev_ctx_t * ctx, uint8_t * val)
DEN value stored in LSB of Z-axis.[get].
Parameters
ctx Read / write interface definitions
val Change the values of den_z in reg CTRL9_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_den_mark_axis_z_set()
int32_t lsm6dsl_den_mark_axis_z_set (stmdev_ctx_t * ctx, uint8_t val)
DEN value stored in LSB of Z-axis.[set].
Parameters
ctx Read / write interface definitions
val Change the values of den_z in reg CTRL9_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_den_mode_get()
int32_t lsm6dsl_den_mode_get (stmdev_ctx_t * ctx, lsm6dsl_den_mode_t * val)
DEN functionality marking mode[get].
Parameters
ctx Read / write interface definitions
val Change the values of den_mode in reg CTRL6_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_den_mode_set()
int32_t lsm6dsl_den_mode_set (stmdev_ctx_t * ctx, lsm6dsl_den_mode_t val)
DEN functionality marking mode[set].
Parameters
ctx Read / write interface definitions
val Change the values of den_mode in reg CTRL6_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_den_polarity_get()
int32_t lsm6dsl_den_polarity_get (stmdev_ctx_t * ctx, lsm6dsl_den_lh_t * val)
DEN active level configuration.[get].
Parameters
ctx Read / write interface definitions
val Get the values of den_lh in reg CTRL5_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_den_polarity_set()
int32_t lsm6dsl_den_polarity_set (stmdev_ctx_t * ctx, lsm6dsl_den_lh_t val)
DEN active level configuration.[set].
Parameters
ctx Read / write interface definitions
val Change the values of den_lh in reg CTRL5_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_device_id_get()
int32_t lsm6dsl_device_id_get (stmdev_ctx_t * ctx, uint8_t * buff)
DeviceWhoamI.[get].
Parameters
ctx Read / write interface definitions
buff Buffer that stores data read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ReadID().
lsm6dsl_ff_dur_get()
int32_t lsm6dsl_ff_dur_get (stmdev_ctx_t * ctx, uint8_t * val)
Free-fall duration event. 1LSb = 1 / ODR[get].
Parameters
ctx Read / write interface definitions
val Change the values of ff_dur in reg WAKE_UP_DUR
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_ff_dur_set()
int32_t lsm6dsl_ff_dur_set (stmdev_ctx_t * ctx, uint8_t val)
Free-fall duration event. 1LSb = 1 / ODR[set].
Parameters
ctx Read / write interface definitions
val Change the values of ff_dur in reg WAKE_UP_DUR
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Set_Free_Fall_Duration().
lsm6dsl_ff_threshold_get()
int32_t lsm6dsl_ff_threshold_get (stmdev_ctx_t * ctx, lsm6dsl_ff_ths_t * val)
Free fall threshold setting.[get].
Parameters
ctx Read / write interface definitions
val Get the values of ff_ths in reg FREE_FALL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_ff_threshold_set()
int32_t lsm6dsl_ff_threshold_set (stmdev_ctx_t * ctx, lsm6dsl_ff_ths_t val)
Free fall threshold setting.[set].
Parameters
ctx Read / write interface definitions
val Change the values of ff_ths in reg FREE_FALL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Set_Free_Fall_Threshold().
lsm6dsl_fifo_data_level_get()
int32_t lsm6dsl_fifo_data_level_get (stmdev_ctx_t * ctx, uint16_t * val)
FIFO data level.[get].
Parameters
ctx Read / write interface definitions
val get the values of diff_fifo in reg FIFO_STATUS1 and FIFO_STATUS2(diff_fifo), it is recommended to set the BDU bit.
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_FIFO_Get_Num_Samples().
lsm6dsl_fifo_data_rate_get()
int32_t lsm6dsl_fifo_data_rate_get (stmdev_ctx_t * ctx, lsm6dsl_odr_fifo_t * val)
FIFO ODR selection, setting FIFO_MODE also.[get].
Parameters
ctx Read / write interface definitions
val Get the values of odr_fifo in reg FIFO_CTRL5
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_data_rate_set()
int32_t lsm6dsl_fifo_data_rate_set (stmdev_ctx_t * ctx, lsm6dsl_odr_fifo_t val)
FIFO ODR selection, setting FIFO_MODE also.[set].
Parameters
ctx Read / write interface definitions
val Change the values of odr_fifo in reg FIFO_CTRL5
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_dataset_3_batch_get()
int32_t lsm6dsl_fifo_dataset_3_batch_get (stmdev_ctx_t * ctx, lsm6dsl_dec_ds3_fifo_t * val)
Selects Batching Data Rate (writing frequency in FIFO) for third data set.[get].
Parameters
ctx Read / write interface definitions
val Get the values of dec_ds3_fifo in reg FIFO_CTRL4
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_dataset_3_batch_set()
int32_t lsm6dsl_fifo_dataset_3_batch_set (stmdev_ctx_t * ctx, lsm6dsl_dec_ds3_fifo_t val)
Selects Batching Data Rate (writing frequency in FIFO) for third data set.[set].
Parameters
ctx Read / write interface definitions
val Change the values of dec_ds3_fifo in reg FIFO_CTRL4
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_dataset_4_batch_get()
int32_t lsm6dsl_fifo_dataset_4_batch_get (stmdev_ctx_t * ctx, lsm6dsl_dec_ds4_fifo_t * val)
Selects Batching Data Rate (writing frequency in FIFO) for fourth data set.[get].
Parameters
ctx Read / write interface definitions
val Get the values of dec_ds4_fifo in reg FIFO_CTRL4
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_dataset_4_batch_set()
int32_t lsm6dsl_fifo_dataset_4_batch_set (stmdev_ctx_t * ctx, lsm6dsl_dec_ds4_fifo_t val)
Selects Batching Data Rate (writing frequency in FIFO) for fourth data set.[set].
Parameters
ctx Read / write interface definitions
val Change the values of dec_ds4_fifo in reg FIFO_CTRL4
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_gy_batch_get()
int32_t lsm6dsl_fifo_gy_batch_get (stmdev_ctx_t * ctx, lsm6dsl_dec_fifo_gyro_t * val)
Selects Batching Data Rate (writing frequency in FIFO) for gyroscope data.[get].
Parameters
ctx Read / write interface definitions
val Get the values of dec_fifo_gyro in reg FIFO_CTRL3
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_gy_batch_set()
int32_t lsm6dsl_fifo_gy_batch_set (stmdev_ctx_t * ctx, lsm6dsl_dec_fifo_gyro_t val)
Selects Batching Data Rate (writing frequency in FIFO) for gyroscope data.[set].
Parameters
ctx Read / write interface definitions
val Change the values of dec_fifo_gyro in reg FIFO_CTRL3
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_mode_get()
int32_t lsm6dsl_fifo_mode_get (stmdev_ctx_t * ctx, lsm6dsl_fifo_mode_t * val)
FIFO mode selection.[get].
Parameters
ctx Read / write interface definitions
val Get the values of fifo_mode in reg FIFO_CTRL5
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_mode_set()
int32_t lsm6dsl_fifo_mode_set (stmdev_ctx_t * ctx, lsm6dsl_fifo_mode_t val)
FIFO mode selection.[set].
Parameters
ctx Read / write interface definitions
val Change the values of fifo_mode in reg FIFO_CTRL5
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_pattern_get()
int32_t lsm6dsl_fifo_pattern_get (stmdev_ctx_t * ctx, uint16_t * val)
FIFO pattern.[get].
Parameters
ctx Read / write interface definitions
val get the values of fifo_pattern in reg FIFO_STATUS3 and FIFO_STATUS4, it is recommended to set the BDU bit
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_FIFO_Get_Pattern().
lsm6dsl_fifo_pedo_and_timestamp_batch_get()
int32_t lsm6dsl_fifo_pedo_and_timestamp_batch_get (stmdev_ctx_t * ctx, uint8_t * val)
Enable pedometer step counter and timestamp as 4th FIFO data set.[get].
Parameters
ctx Read / write interface definitions
val Change the values of timer_pedo_fifo_en in reg FIFO_CTRL2
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_pedo_and_timestamp_batch_set()
int32_t lsm6dsl_fifo_pedo_and_timestamp_batch_set (stmdev_ctx_t * ctx, uint8_t val)
Enable pedometer step counter and timestamp as 4th FIFO data set.[set].
Parameters
ctx Read / write interface definitions
val Change the values of timer_pedo_fifo_en in reg FIFO_CTRL2
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_raw_data_get()
int32_t lsm6dsl_fifo_raw_data_get (stmdev_ctx_t * ctx, uint8_t * buffer, uint8_t len)
Read data in FIFO.[get].
Parameters
ctx Read / write interface definitions
buffer Data buffer to store FIFO data.
len Number of data to read from FIFO.
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_stop_on_wtm_get()
int32_t lsm6dsl_fifo_stop_on_wtm_get (stmdev_ctx_t * ctx, uint8_t * val)
Sensing chain FIFO stop values memorization at threshold level.[get].
Parameters
ctx Read / write interface definitions
val Change the values of stop_on_fth in reg FIFO_CTRL4
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_stop_on_wtm_set()
int32_t lsm6dsl_fifo_stop_on_wtm_set (stmdev_ctx_t * ctx, uint8_t val)
Sensing chain FIFO stop values memorization at threshold level.[set].
Parameters
ctx Read / write interface definitions
val Change the values of stop_on_fth in reg FIFO_CTRL4
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_FIFO_Set_Stop_On_Fth().
lsm6dsl_fifo_temp_batch_get()
int32_t lsm6dsl_fifo_temp_batch_get (stmdev_ctx_t * ctx, uint8_t * val)
Batching of temperature data[get].
Parameters
ctx Read / write interface definitions
val Change the values of fifo_temp_en in reg FIFO_CTRL2
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_temp_batch_set()
int32_t lsm6dsl_fifo_temp_batch_set (stmdev_ctx_t * ctx, uint8_t val)
Batching of temperature data[set].
Parameters
ctx Read / write interface definitions
val Change the values of fifo_temp_en in reg FIFO_CTRL2
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_watermark_get()
int32_t lsm6dsl_fifo_watermark_get (stmdev_ctx_t * ctx, uint16_t * val)
FIFO watermark level selection.[get].
Parameters
ctx Read / write interface definitions
val Change the values of fth in reg FIFO_CTRL1
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_watermark_set()
int32_t lsm6dsl_fifo_watermark_set (stmdev_ctx_t * ctx, uint16_t val)
FIFO watermark level selection.[set].
Parameters
ctx Read / write interface definitions
val Change the values of fth in reg FIFO_CTRL1
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_FIFO_Set_Watermark_Level().
lsm6dsl_fifo_write_trigger_get()
int32_t lsm6dsl_fifo_write_trigger_get (stmdev_ctx_t * ctx, lsm6dsl_trigger_fifo_t * val)
Trigger signal for FIFO write operation.[get].
Parameters
ctx Read / write interface definitions
val act on FIFO_CTRL2(timer_pedo_fifo_drdy) and MASTER_CONFIG(data_valid_sel_fifo)
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_write_trigger_set()
int32_t lsm6dsl_fifo_write_trigger_set (stmdev_ctx_t * ctx, lsm6dsl_trigger_fifo_t val)
Trigger signal for FIFO write operation.[set].
Parameters
ctx Read / write interface definitions
val act on FIFO_CTRL2(timer_pedo_fifo_drdy) and MASTER_CONFIG(data_valid_sel_fifo)
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_wtm_flag_get()
int32_t lsm6dsl_fifo_wtm_flag_get (stmdev_ctx_t * ctx, uint8_t * val)
FIFO watermark.[get].
Parameters
ctx Read / write interface definitions
val get the values of watermark in reg FIFO_STATUS2 and
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_xl_batch_get()
int32_t lsm6dsl_fifo_xl_batch_get (stmdev_ctx_t * ctx, lsm6dsl_dec_fifo_xl_t * val)
Selects Batching Data Rate (writing frequency in FIFO) for accelerometer data.[get].
Parameters
ctx Read / write interface definitions
val Get the values of dec_fifo_xl in reg FIFO_CTRL3
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_xl_batch_set()
int32_t lsm6dsl_fifo_xl_batch_set (stmdev_ctx_t * ctx, lsm6dsl_dec_fifo_xl_t val)
Selects Batching Data Rate (writing frequency in FIFO) for accelerometer data.[set].
Parameters
ctx Read / write interface definitions
val Change the values of dec_fifo_xl in reg FIFO_CTRL3
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_xl_gy_8bit_format_get()
int32_t lsm6dsl_fifo_xl_gy_8bit_format_get (stmdev_ctx_t * ctx, uint8_t * val)
8-bit data storage in FIFO.[get]
Parameters
ctx Read / write interface definitions
val Change the values of only_high_data in reg FIFO_CTRL4
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_fifo_xl_gy_8bit_format_set()
int32_t lsm6dsl_fifo_xl_gy_8bit_format_set (stmdev_ctx_t * ctx, uint8_t val)
8-bit data storage in FIFO.[set]
Parameters
ctx Read / write interface definitions
val Change the values of only_high_data in reg FIFO_CTRL4
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_filter_settling_mask_get()
int32_t lsm6dsl_filter_settling_mask_get (stmdev_ctx_t * ctx, uint8_t * val)
Mask DRDY on pin (both XL & Gyro) until filter settling ends (XL and Gyro independently masked).[get].
Parameters
ctx Read / write interface definitions
val Change the values of drdy_mask in reg CTRL4_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_filter_settling_mask_set()
int32_t lsm6dsl_filter_settling_mask_set (stmdev_ctx_t * ctx, uint8_t val)
Mask DRDY on pin (both XL & Gyro) until filter settling ends (XL and Gyro independently masked).[set].
Parameters
ctx Read / write interface definitions
val Change the values of drdy_mask in reg CTRL4_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_func_en_set()
int32_t lsm6dsl_func_en_set (stmdev_ctx_t * ctx, uint8_t val)
Enable function.[set].
Parameters
ctx Read / write interface definitions
val Change the values func_en
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_gy_band_pass_get()
int32_t lsm6dsl_gy_band_pass_get (stmdev_ctx_t * ctx, lsm6dsl_lpf1_sel_g_t * val)
Gyroscope low pass path bandwidth.[get].
Parameters
ctx Read / write interface definitions
val gyroscope filtering chain
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_gy_band_pass_set()
int32_t lsm6dsl_gy_band_pass_set (stmdev_ctx_t * ctx, lsm6dsl_lpf1_sel_g_t val)
Gyroscope low pass path bandwidth.[set].
Parameters
ctx Read / write interface definitions
val gyroscope filtering chain configuration.
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_gy_data_rate_get()
int32_t lsm6dsl_gy_data_rate_get (stmdev_ctx_t * ctx, lsm6dsl_odr_g_t * val)
Gyroscope data rate selection.[get].
Parameters
ctx Read / write interface definitions
val Get the values of odr_g in reg CTRL2_G
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_gy_data_rate_set()
int32_t lsm6dsl_gy_data_rate_set (stmdev_ctx_t * ctx, lsm6dsl_odr_g_t val)
Gyroscope data rate selection.[set].
Parameters
ctx Read / write interface definitions
val Change the values of odr_g in reg CTRL2_G
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_gy_flag_data_ready_get()
int32_t lsm6dsl_gy_flag_data_ready_get (stmdev_ctx_t * ctx, uint8_t * val)
Gyroscope new data available.[get].
Parameters
ctx Read / write interface definitions
val Change the values of gda in reg STATUS_REG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_GYRO_Get_DRDY_Status().
lsm6dsl_gy_full_scale_get()
int32_t lsm6dsl_gy_full_scale_get (stmdev_ctx_t * ctx, lsm6dsl_fs_g_t * val)
Gyroscope chain full-scale selection.[get].
Parameters
ctx Read / write interface definitions
val Get the values of fs_g in reg CTRL2_G
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_gy_full_scale_set()
int32_t lsm6dsl_gy_full_scale_set (stmdev_ctx_t * ctx, lsm6dsl_fs_g_t val)
Gyroscope chain full-scale selection.[set].
Parameters
ctx Read / write interface definitions
val Change the values of fs_g in reg CTRL2_G
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_gy_power_mode_get()
int32_t lsm6dsl_gy_power_mode_get (stmdev_ctx_t * ctx, lsm6dsl_g_hm_mode_t * val)
High-performance operating mode disable for gyroscope.[get].
Parameters
ctx Read / write interface definitions
val Get the values of g_hm_mode in reg CTRL7_G
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_gy_power_mode_set()
int32_t lsm6dsl_gy_power_mode_set (stmdev_ctx_t * ctx, lsm6dsl_g_hm_mode_t val)
High-performance operating mode disable for gyroscope.[set].
Parameters
ctx Read / write interface definitions
val Change the values of g_hm_mode in reg CTRL7_G
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_gy_self_test_get()
int32_t lsm6dsl_gy_self_test_get (stmdev_ctx_t * ctx, lsm6dsl_st_g_t * val)
Angular rate sensor self-test enable.[get].
Parameters
ctx Read / write interface definitions
val Get the values of st_g in reg CTRL5_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_gy_self_test_set()
int32_t lsm6dsl_gy_self_test_set (stmdev_ctx_t * ctx, lsm6dsl_st_g_t val)
Angular rate sensor self-test enable.[set].
Parameters
ctx Read / write interface definitions
val Change the values of st_g in reg CTRL5_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_gy_sleep_mode_get()
int32_t lsm6dsl_gy_sleep_mode_get (stmdev_ctx_t * ctx, uint8_t * val)
Enables gyroscope Sleep mode.[get].
Parameters
ctx Read / write interface definitions
val Change the values of sleep in reg CTRL4_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_gy_sleep_mode_set()
int32_t lsm6dsl_gy_sleep_mode_set (stmdev_ctx_t * ctx, uint8_t val)
Enables gyroscope Sleep mode.[set].
Parameters
ctx Read / write interface definitions
val Change the values of sleep in reg CTRL4_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_i2c_interface_get()
int32_t lsm6dsl_i2c_interface_get (stmdev_ctx_t * ctx, lsm6dsl_i2c_disable_t * val)
Disable / Enable I2C interface.[get].
Parameters
ctx Read / write interface definitions
val Get the values of i2c_disable in reg CTRL4_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_i2c_interface_set()
int32_t lsm6dsl_i2c_interface_set (stmdev_ctx_t * ctx, lsm6dsl_i2c_disable_t val)
Disable / Enable I2C interface.[set].
Parameters
ctx Read / write interface definitions
val Change the values of i2c_disable in reg CTRL4_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_int_notification_get()
int32_t lsm6dsl_int_notification_get (stmdev_ctx_t * ctx, lsm6dsl_lir_t * val)
Latched/pulsed interrupt.[get].
Parameters
ctx Read / write interface definitions
val Get the values of lir in reg TAP_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_int_notification_set()
int32_t lsm6dsl_int_notification_set (stmdev_ctx_t * ctx, lsm6dsl_lir_t val)
Latched/pulsed interrupt.[set].
Parameters
ctx Read / write interface definitions
val Change the values of lir in reg TAP_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_mag_calibrated_raw_get()
int32_t lsm6dsl_mag_calibrated_raw_get (stmdev_ctx_t * ctx, int16_t * val)
External magnetometer raw data.[get].
Parameters
ctx Read / write interface definitions
buff Buffer that stores data read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_mag_hard_iron_get()
int32_t lsm6dsl_mag_hard_iron_get (stmdev_ctx_t * ctx, uint8_t * val)
Enable hard-iron correction algorithm for magnetometer.[get].
Parameters
ctx Read / write interface definitions
val Change the values of iron_en in reg MASTER_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_mag_hard_iron_set()
int32_t lsm6dsl_mag_hard_iron_set (stmdev_ctx_t * ctx, uint8_t val)
Enable hard-iron correction algorithm for magnetometer.[set].
Parameters
ctx Read / write interface definitions
val Change the values of iron_en in reg MASTER_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_mag_offset_get()
int32_t lsm6dsl_mag_offset_get (stmdev_ctx_t * ctx, int16_t * val)
Offset for hard-iron compensation register(r/w). The value is expressed as a 16-bit word in two’s complement.[get].
Parameters
ctx Read / write interface definitions
buff Buffer that stores data read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_mag_offset_set()
int32_t lsm6dsl_mag_offset_set (stmdev_ctx_t * ctx, int16_t * val)
Offset for hard-iron compensation register (r/w). The value is expressed as a 16-bit word in two’s complement.[set].
Parameters
ctx Read / write interface definitions
buff Buffer that contains data to write
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_mag_soft_iron_get()
int32_t lsm6dsl_mag_soft_iron_get (stmdev_ctx_t * ctx, uint8_t * val)
Enable soft-iron correction algorithm for magnetometer.[get].
Parameters
ctx Read / write interface definitions
val Change the values of soft_en in reg CTRL9_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_mag_soft_iron_mat_get()
int32_t lsm6dsl_mag_soft_iron_mat_get (stmdev_ctx_t * ctx, uint8_t * buff)
Soft iron 3x3 matrix. Value are expressed in sign-module format. (Es. SVVVVVVVb where S is the sign 0/+1/- and V is the value).[get].
Parameters
ctx Read / write interface definitions
buff Buffer that stores data read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_mag_soft_iron_mat_set()
int32_t lsm6dsl_mag_soft_iron_mat_set (stmdev_ctx_t * ctx, uint8_t * buff)
Soft iron 3x3 matrix. Value are expressed in sign-module format. (Es. SVVVVVVVb where S is the sign 0/+1/- and V is the value).[set].
Parameters
ctx Read / write interface definitions
buff Buffer that contains data to write
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_mag_soft_iron_set()
int32_t lsm6dsl_mag_soft_iron_set (stmdev_ctx_t * ctx, uint8_t val)
Enable soft-iron correction algorithm for magnetometer.[set].
Parameters
ctx Read / write interface definitions
val Change the values of soft_en in reg CTRL9_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_mem_bank_get()
int32_t lsm6dsl_mem_bank_get (stmdev_ctx_t * ctx, lsm6dsl_func_cfg_en_t * val)
Enable access to the embedded functions/sensor hub configuration registers[get].
Parameters
ctx Read / write interface definitions
val Get the values of func_cfg_en in reg FUNC_CFG_ACCESS
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_mem_bank_set()
int32_t lsm6dsl_mem_bank_set (stmdev_ctx_t * ctx, lsm6dsl_func_cfg_en_t val)
Enable access to the embedded functions/sensor hub configuration registers[set].
Parameters
ctx Read / write interface definitions
val Change the values of func_cfg_en in reg FUNC_CFG_ACCESS
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by lsm6dsl_mag_offset_get(), lsm6dsl_mag_offset_set(), lsm6dsl_mag_soft_iron_mat_get(), lsm6dsl_mag_soft_iron_mat_set(), lsm6dsl_motion_threshold_get(), lsm6dsl_motion_threshold_set(), lsm6dsl_pedo_debounce_steps_get(), lsm6dsl_pedo_debounce_steps_set(), lsm6dsl_pedo_full_scale_get(), lsm6dsl_pedo_full_scale_set(), lsm6dsl_pedo_steps_period_get(), lsm6dsl_pedo_steps_period_set(), lsm6dsl_pedo_threshold_get(), lsm6dsl_pedo_threshold_set(), lsm6dsl_pedo_timeout_get(), lsm6dsl_pedo_timeout_set(), lsm6dsl_sh_cfg_write(), lsm6dsl_sh_num_of_dev_connected_get(), lsm6dsl_sh_num_of_dev_connected_set(), lsm6dsl_sh_slave_0_dec_get(), lsm6dsl_sh_slave_0_dec_set(), lsm6dsl_sh_slave_1_dec_get(), lsm6dsl_sh_slave_1_dec_set(), lsm6dsl_sh_slave_2_dec_get(), lsm6dsl_sh_slave_2_dec_set(), lsm6dsl_sh_slave_3_dec_get(), lsm6dsl_sh_slave_3_dec_set(), lsm6dsl_sh_slv0_cfg_read(), lsm6dsl_sh_slv1_cfg_read(), lsm6dsl_sh_slv2_cfg_read(), lsm6dsl_sh_slv3_cfg_read(), lsm6dsl_sh_write_mode_get(), lsm6dsl_sh_write_mode_set(), lsm6dsl_tilt_latency_get(), lsm6dsl_tilt_latency_set(), lsm6dsl_tilt_src_get(), lsm6dsl_tilt_src_set(), lsm6dsl_tilt_threshold_get(), and lsm6dsl_tilt_threshold_set().
lsm6dsl_motion_sens_get()
int32_t lsm6dsl_motion_sens_get (stmdev_ctx_t * ctx, uint8_t * val)
Enable significant motion detection function.[get].
Parameters
ctx Read / write interface definitions
val Change the values of sign_motion_en in reg CTRL10_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_motion_sens_set()
int32_t lsm6dsl_motion_sens_set (stmdev_ctx_t * ctx, uint8_t val)
Enable significant motion detection function.[set].
Parameters
ctx Read / write interface definitions
val Change the values of sign_motion_en in reg CTRL10_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_motion_threshold_get()
int32_t lsm6dsl_motion_threshold_get (stmdev_ctx_t * ctx, uint8_t * buff)
Significant motion threshold.[get].
Parameters
ctx Read / write interface definitions
buff Buffer that store significant motion threshold.
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_motion_threshold_set()
int32_t lsm6dsl_motion_threshold_set (stmdev_ctx_t * ctx, uint8_t * buff)
Significant motion threshold.[set].
Parameters
ctx Read / write interface definitions
buff Buffer that store significant motion threshold.
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_pedo_debounce_steps_get()
int32_t lsm6dsl_pedo_debounce_steps_get (stmdev_ctx_t * ctx, uint8_t * val)
Pedometer debounce configuration register (r/w).[get].
Parameters
ctx Read / write interface definitions
val Change the values of deb_step in reg PEDO_DEB_REG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_pedo_debounce_steps_set()
int32_t lsm6dsl_pedo_debounce_steps_set (stmdev_ctx_t * ctx, uint8_t val)
Pedometer debounce configuration register (r/w).[set].
Parameters
ctx Read / write interface definitions
val Change the values of deb_step in reg PEDO_DEB_REG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_pedo_full_scale_get()
int32_t lsm6dsl_pedo_full_scale_get (stmdev_ctx_t * ctx, lsm6dsl_pedo_fs_t * val)
Pedometer data range.[get].
Parameters
ctx Read / write interface definitions
val Get the values of pedo_fs in reg CONFIG_PEDO_THS_MIN
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_pedo_full_scale_set()
int32_t lsm6dsl_pedo_full_scale_set (stmdev_ctx_t * ctx, lsm6dsl_pedo_fs_t val)
pedo_full_scale: Pedometer data range.[set]
Parameters
ctx Read / write interface definitions
val Change the values of pedo_fs in reg CONFIG_PEDO_THS_MIN
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_pedo_sens_get()
int32_t lsm6dsl_pedo_sens_get (stmdev_ctx_t * ctx, uint8_t * val)
pedo_sens: Enable pedometer algorithm.[get]
Parameters
ctx Read / write interface definitions
val Change the values of pedo_en in reg CTRL10_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_pedo_sens_set()
int32_t lsm6dsl_pedo_sens_set (stmdev_ctx_t * ctx, uint8_t val)
Enable pedometer algorithm.[set].
Parameters
ctx Read / write interface definitions
val Change the values of pedo_en in reg CTRL10_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_pedo_step_reset_get()
int32_t lsm6dsl_pedo_step_reset_get (stmdev_ctx_t * ctx, uint8_t * val)
Reset pedometer step counter.[get].
Parameters
ctx Read / write interface definitions
val Change the values of pedo_rst_step in reg CTRL10_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_pedo_step_reset_set()
int32_t lsm6dsl_pedo_step_reset_set (stmdev_ctx_t * ctx, uint8_t val)
Reset pedometer step counter.[set].
Parameters
ctx Read / write interface definitions
val Change the values of pedo_rst_step in reg CTRL10_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Disable_Step_Counter_Reset(), and LSM6DSL_ACC_Enable_Step_Counter_Reset().
lsm6dsl_pedo_steps_period_get()
int32_t lsm6dsl_pedo_steps_period_get (stmdev_ctx_t * ctx, uint8_t * buff)
Time period register for step detection on delta time (r/w).[get].
Parameters
ctx Read / write interface definitions
buff Buffer that stores data read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_pedo_steps_period_set()
int32_t lsm6dsl_pedo_steps_period_set (stmdev_ctx_t * ctx, uint8_t * buff)
Time period register for step detection on delta time (r/w).[set].
Parameters
ctx Read / write interface definitions
buff Buffer that contains data to write
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_pedo_threshold_get()
int32_t lsm6dsl_pedo_threshold_get (stmdev_ctx_t * ctx, uint8_t * val)
Minimum threshold to detect a peak. Default is 10h.[get].
Parameters
ctx Read / write interface definitions
val Change the values of ths_min in reg CONFIG_PEDO_THS_MIN
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_pedo_threshold_set()
int32_t lsm6dsl_pedo_threshold_set (stmdev_ctx_t * ctx, uint8_t val)
Minimum threshold to detect a peak. Default is 10h.[set].
Parameters
ctx Read / write interface definitions
val Change the values of ths_min in reg CONFIG_PEDO_THS_MIN
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
Referenced by LSM6DSL_ACC_Set_Pedometer_Threshold().
lsm6dsl_pedo_timeout_get()
int32_t lsm6dsl_pedo_timeout_get (stmdev_ctx_t * ctx, uint8_t * val)
Debounce time. If the time between two consecutive steps is greater than DEB_TIME*80ms, the debouncer is reactivated. Default value: 01101[get].
Parameters
ctx Read / write interface definitions
val Change the values of deb_time in reg PEDO_DEB_REG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_pedo_timeout_set()
int32_t lsm6dsl_pedo_timeout_set (stmdev_ctx_t * ctx, uint8_t val)
Debounce time. If the time between two consecutive steps is greater than DEB_TIME*80ms, the debouncer is reactivated. Default value: 01101[set].
Parameters
ctx Read / write interface definitions
val Change the values of deb_time in reg PEDO_DEB_REG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_pin_int1_route_get()
int32_t lsm6dsl_pin_int1_route_get (stmdev_ctx_t * ctx, lsm6dsl_int1_route_t * val)
Select the signal that need to route on int1 pad[get].
Parameters
ctx Read / write interface definitions
val read INT1_CTRL, MD1_CFG, CTRL4_C(den_drdy_int1), MASTER_CONFIG(drdy_on_int1)
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Disable_6D_Orientation(), LSM6DSL_ACC_Disable_Double_Tap_Detection(), LSM6DSL_ACC_Disable_Free_Fall_Detection(), LSM6DSL_ACC_Disable_Inactivity_Detection(), LSM6DSL_ACC_Disable_Pedometer(), LSM6DSL_ACC_Disable_Single_Tap_Detection(), LSM6DSL_ACC_Disable_Tilt_Detection(), LSM6DSL_ACC_Disable_Wake_Up_Detection(), LSM6DSL_ACC_Set_INT1_DRDY(), and LSM6DSL_GYRO_Set_INT1_DRDY().
lsm6dsl_pin_int1_route_set()
int32_t lsm6dsl_pin_int1_route_set (stmdev_ctx_t * ctx, lsm6dsl_int1_route_t val)
Select the signal that need to route on int1 pad[set].
Parameters
ctx Read / write interface definitions
val configure INT1_CTRL, MD1_CFG, CTRL4_C(den_drdy_int1), MASTER_CONFIG(drdy_on_int1)
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_pin_int2_route_get()
int32_t lsm6dsl_pin_int2_route_get (stmdev_ctx_t * ctx, lsm6dsl_int2_route_t * val)
Select the signal that need to route on int2 pad[get].
Parameters
ctx Read / write interface definitions
val INT2_CTRL, DRDY_PULSE_CFG(int2_wrist_tilt), MD2_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_pin_int2_route_set()
int32_t lsm6dsl_pin_int2_route_set (stmdev_ctx_t * ctx, lsm6dsl_int2_route_t val)
Select the signal that need to route on int2 pad[set].
Parameters
ctx Read / write interface definitions
val INT2_CTRL, DRDY_PULSE_CFG(int2_wrist_tilt), MD2_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_pin_mode_get()
int32_t lsm6dsl_pin_mode_get (stmdev_ctx_t * ctx, lsm6dsl_pp_od_t * val)
Push-pull/open drain selection on interrupt pads.[get].
Parameters
ctx Read / write interface definitions
val Get the values of pp_od in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_pin_mode_set()
int32_t lsm6dsl_pin_mode_set (stmdev_ctx_t * ctx, lsm6dsl_pp_od_t val)
Push-pull/open drain selection on interrupt pads.[set].
Parameters
ctx Read / write interface definitions
val Change the values of pp_od in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_pin_polarity_get()
int32_t lsm6dsl_pin_polarity_get (stmdev_ctx_t * ctx, lsm6dsl_h_lactive_t * val)
Interrupt active-high/low.[get].
Parameters
ctx Read / write interface definitions
val Get the values of h_lactive in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_pin_polarity_set()
int32_t lsm6dsl_pin_polarity_set (stmdev_ctx_t * ctx, lsm6dsl_h_lactive_t val)
Interrupt active-high/low.[set].
Parameters
ctx Read / write interface definitions
val Change the values of h_lactive in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_read_reg()
int32_t lsm6dsl_read_reg (stmdev_ctx_t * ctx, uint8_t reg, uint8_t * data, uint16_t len)
Read generic device register.
Parameters
ctx read / write interface definitions(ptr)
reg register to read
data pointer to buffer that store the data read(ptr)
len number of consecutive register to read
Return values
interface status (MANDATORY: return 0 -> no Error)
References stmdev_ctx_t::handle.
Referenced by lsm6dsl_4d_mode_get(), lsm6dsl_4d_mode_set(), lsm6dsl_6d_feed_data_get(), lsm6dsl_6d_feed_data_set(), lsm6dsl_6d_threshold_get(), lsm6dsl_6d_threshold_set(), LSM6DSL_ACC_Get_6D_Orientation_XH(), LSM6DSL_ACC_Get_6D_Orientation_XL(), LSM6DSL_ACC_Get_6D_Orientation_YH(), LSM6DSL_ACC_Get_6D_Orientation_YL(), LSM6DSL_ACC_Get_6D_Orientation_ZH(), LSM6DSL_ACC_Get_6D_Orientation_ZL(), LSM6DSL_ACC_Get_Event_Status(), LSM6DSL_ACC_Get_Step_Count(), lsm6dsl_acceleration_raw_get(), lsm6dsl_act_mode_get(), lsm6dsl_act_mode_set(), lsm6dsl_act_sleep_dur_get(), lsm6dsl_act_sleep_dur_set(), lsm6dsl_all_on_int1_get(), lsm6dsl_all_on_int1_set(), lsm6dsl_all_sources_get(), lsm6dsl_angular_rate_raw_get(), lsm6dsl_auto_increment_get(), lsm6dsl_auto_increment_set(), lsm6dsl_block_data_update_get(), lsm6dsl_block_data_update_set(), lsm6dsl_boot_get(), lsm6dsl_boot_set(), lsm6dsl_data_format_get(), lsm6dsl_data_format_set(), lsm6dsl_data_ready_mode_get(), lsm6dsl_data_ready_mode_set(), lsm6dsl_den_enable_get(), lsm6dsl_den_enable_set(), lsm6dsl_den_mark_axis_x_get(), lsm6dsl_den_mark_axis_x_set(), lsm6dsl_den_mark_axis_y_get(), lsm6dsl_den_mark_axis_y_set(), lsm6dsl_den_mark_axis_z_get(), lsm6dsl_den_mark_axis_z_set(), lsm6dsl_den_mode_get(), lsm6dsl_den_mode_set(), lsm6dsl_den_polarity_get(), lsm6dsl_den_polarity_set(), lsm6dsl_device_id_get(), lsm6dsl_ff_dur_get(), lsm6dsl_ff_dur_set(), lsm6dsl_ff_threshold_get(), lsm6dsl_ff_threshold_set(), lsm6dsl_fifo_data_level_get(), lsm6dsl_fifo_data_rate_get(), lsm6dsl_fifo_data_rate_set(), lsm6dsl_fifo_dataset_3_batch_get(), lsm6dsl_fifo_dataset_3_batch_set(), lsm6dsl_fifo_dataset_4_batch_get(), lsm6dsl_fifo_dataset_4_batch_set(), LSM6DSL_FIFO_Get_Data(), LSM6DSL_FIFO_Get_Full_Status(), lsm6dsl_fifo_gy_batch_get(), lsm6dsl_fifo_gy_batch_set(), lsm6dsl_fifo_mode_get(), lsm6dsl_fifo_mode_set(), lsm6dsl_fifo_pattern_get(), lsm6dsl_fifo_pedo_and_timestamp_batch_get(), lsm6dsl_fifo_pedo_and_timestamp_batch_set(), lsm6dsl_fifo_raw_data_get(), LSM6DSL_FIFO_Set_INT1_FIFO_Full(), lsm6dsl_fifo_stop_on_wtm_get(), lsm6dsl_fifo_stop_on_wtm_set(), lsm6dsl_fifo_temp_batch_get(), lsm6dsl_fifo_temp_batch_set(), lsm6dsl_fifo_watermark_get(), lsm6dsl_fifo_watermark_set(), lsm6dsl_fifo_write_trigger_get(), lsm6dsl_fifo_write_trigger_set(), lsm6dsl_fifo_wtm_flag_get(), lsm6dsl_fifo_xl_batch_get(), lsm6dsl_fifo_xl_batch_set(), lsm6dsl_fifo_xl_gy_8bit_format_get(), lsm6dsl_fifo_xl_gy_8bit_format_set(), lsm6dsl_filter_settling_mask_get(), lsm6dsl_filter_settling_mask_set(), lsm6dsl_func_en_set(), lsm6dsl_gy_band_pass_get(), lsm6dsl_gy_band_pass_set(), lsm6dsl_gy_data_rate_get(), lsm6dsl_gy_data_rate_set(), lsm6dsl_gy_flag_data_ready_get(), lsm6dsl_gy_full_scale_get(), lsm6dsl_gy_full_scale_set(), lsm6dsl_gy_power_mode_get(), lsm6dsl_gy_power_mode_set(), lsm6dsl_gy_self_test_get(), lsm6dsl_gy_self_test_set(), lsm6dsl_gy_sleep_mode_get(), lsm6dsl_gy_sleep_mode_set(), lsm6dsl_i2c_interface_get(), lsm6dsl_i2c_interface_set(), lsm6dsl_int_notification_get(), lsm6dsl_int_notification_set(), lsm6dsl_mag_calibrated_raw_get(), lsm6dsl_mag_hard_iron_get(), lsm6dsl_mag_hard_iron_set(), lsm6dsl_mag_soft_iron_get(), lsm6dsl_mag_soft_iron_set(), lsm6dsl_mem_bank_get(), lsm6dsl_mem_bank_set(), lsm6dsl_motion_sens_get(), lsm6dsl_motion_sens_set(), lsm6dsl_pedo_sens_get(), lsm6dsl_pedo_sens_set(), lsm6dsl_pedo_step_reset_get(), lsm6dsl_pedo_step_reset_set(), lsm6dsl_pin_int1_route_get(), lsm6dsl_pin_int1_route_set(), lsm6dsl_pin_int2_route_get(), lsm6dsl_pin_int2_route_set(), lsm6dsl_pin_mode_get(), lsm6dsl_pin_mode_set(), lsm6dsl_pin_polarity_get(), lsm6dsl_pin_polarity_set(), LSM6DSL_Read_Reg(), lsm6dsl_reset_get(), lsm6dsl_reset_set(), lsm6dsl_rounding_mode_get(), lsm6dsl_rounding_mode_set(), lsm6dsl_rounding_on_status_get(), lsm6dsl_rounding_on_status_set(), lsm6dsl_sh_cmd_sens_sync_get(), lsm6dsl_sh_cmd_sens_sync_set(), lsm6dsl_sh_drdy_on_int1_get(), lsm6dsl_sh_drdy_on_int1_set(), lsm6dsl_sh_master_get(), lsm6dsl_sh_master_set(), lsm6dsl_sh_pass_through_get(), lsm6dsl_sh_pass_through_set(), lsm6dsl_sh_pin_mode_get(), lsm6dsl_sh_pin_mode_set(), lsm6dsl_sh_read_data_raw_get(), lsm6dsl_sh_spi_sync_error_get(), lsm6dsl_sh_spi_sync_error_set(), lsm6dsl_sh_sync_sens_frame_get(), lsm6dsl_sh_sync_sens_frame_set(), lsm6dsl_sh_sync_sens_ratio_get(), lsm6dsl_sh_sync_sens_ratio_set(), lsm6dsl_sh_syncro_mode_get(), lsm6dsl_sh_syncro_mode_set(), lsm6dsl_spi_mode_get(), lsm6dsl_spi_mode_set(), lsm6dsl_status_reg_get(), lsm6dsl_tap_detection_on_x_get(), lsm6dsl_tap_detection_on_x_set(), lsm6dsl_tap_detection_on_y_get(), lsm6dsl_tap_detection_on_y_set(), lsm6dsl_tap_detection_on_z_get(), lsm6dsl_tap_detection_on_z_set(), lsm6dsl_tap_dur_get(), lsm6dsl_tap_dur_set(), lsm6dsl_tap_mode_get(), lsm6dsl_tap_mode_set(), lsm6dsl_tap_quiet_get(), lsm6dsl_tap_quiet_set(), lsm6dsl_tap_shock_get(), lsm6dsl_tap_shock_set(), lsm6dsl_tap_src_get(), lsm6dsl_tap_threshold_x_get(), lsm6dsl_tap_threshold_x_set(), lsm6dsl_temp_flag_data_ready_get(), lsm6dsl_temperature_raw_get(), lsm6dsl_tilt_sens_get(), lsm6dsl_tilt_sens_set(), lsm6dsl_timestamp_get(), lsm6dsl_timestamp_res_get(), lsm6dsl_timestamp_res_set(), lsm6dsl_timestamp_set(), lsm6dsl_wkup_dur_get(), lsm6dsl_wkup_dur_set(), lsm6dsl_wkup_threshold_get(), lsm6dsl_wkup_threshold_set(), lsm6dsl_wrist_tilt_sens_get(), lsm6dsl_wrist_tilt_sens_set(), lsm6dsl_xl_data_rate_get(), lsm6dsl_xl_data_rate_set(), lsm6dsl_xl_filter_analog_get(), lsm6dsl_xl_filter_analog_set(), lsm6dsl_xl_flag_data_ready_get(), lsm6dsl_xl_full_scale_get(), lsm6dsl_xl_full_scale_set(), lsm6dsl_xl_hp_bandwidth_get(), lsm6dsl_xl_hp_bandwidth_set(), lsm6dsl_xl_hp_path_internal_get(), lsm6dsl_xl_hp_path_internal_set(), lsm6dsl_xl_lp1_bandwidth_get(), lsm6dsl_xl_lp1_bandwidth_set(), lsm6dsl_xl_lp2_bandwidth_get(), lsm6dsl_xl_lp2_bandwidth_set(), lsm6dsl_xl_offset_weight_get(), lsm6dsl_xl_offset_weight_set(), lsm6dsl_xl_power_mode_get(), lsm6dsl_xl_power_mode_set(), lsm6dsl_xl_reference_mode_get(), lsm6dsl_xl_reference_mode_set(), lsm6dsl_xl_self_test_get(), lsm6dsl_xl_self_test_set(), and lsm6dsl_xl_usr_offset_get().
lsm6dsl_reset_get()
int32_t lsm6dsl_reset_get (stmdev_ctx_t * ctx, uint8_t * val)
Software reset. Restore the default values in user registers[get].
Parameters
ctx Read / write interface definitions
val Change the values of sw_reset in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_reset_set()
int32_t lsm6dsl_reset_set (stmdev_ctx_t * ctx, uint8_t val)
Software reset. Restore the default values in user registers[set].
Parameters
ctx Read / write interface definitions
val Change the values of sw_reset in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_rounding_mode_get()
int32_t lsm6dsl_rounding_mode_get (stmdev_ctx_t * ctx, lsm6dsl_rounding_t * val)
Circular burst-mode (rounding) read from output registers through the primary interface.[get].
Parameters
ctx Read / write interface definitions
val Get the values of rounding in reg CTRL5_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_rounding_mode_set()
int32_t lsm6dsl_rounding_mode_set (stmdev_ctx_t * ctx, lsm6dsl_rounding_t val)
Circular burst-mode (rounding) read from output registers through the primary interface.[set].
Parameters
ctx Read / write interface definitions
val Change the values of rounding in reg CTRL5_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_rounding_on_status_get()
int32_t lsm6dsl_rounding_on_status_get (stmdev_ctx_t * ctx, lsm6dsl_rounding_status_t * val)
Source register rounding function on WAKE_UP_SRC (1Bh), TAP_SRC (1Ch), D6D_SRC (1Dh), STATUS_REG (1Eh) and FUNC_SRC1 (53h) registers in the primary interface.[get].
Parameters
ctx Read / write interface definitions
val Get the values of rounding_status in reg CTRL7_G
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_rounding_on_status_set()
int32_t lsm6dsl_rounding_on_status_set (stmdev_ctx_t * ctx, lsm6dsl_rounding_status_t val)
Source register rounding function on WAKE_UP_SRC (1Bh), TAP_SRC (1Ch), D6D_SRC (1Dh), STATUS_REG (1Eh) and FUNC_SRC1 (53h) registers in the primary interface.[set].
Parameters
ctx Read / write interface definitions
val Change the values of rounding_status in reg CTRL7_G
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_cfg_write()
int32_t lsm6dsl_sh_cfg_write (stmdev_ctx_t * ctx, lsm6dsl_sh_cfg_write_t * val)
Configure slave 0 for perform a write.[set].
Parameters
ctx Read / write interface definitions
val Structure that contain:
uint8_t slv_add; 8 bit i2c device address
uint8_t slv_subadd; 8 bit register device address
uint8_t slv_data; 8 bit data to write
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_cmd_sens_sync_get()
int32_t lsm6dsl_sh_cmd_sens_sync_get (stmdev_ctx_t * ctx, uint8_t * val)
Master command code used for stamping for sensor sync.[get].
Parameters
ctx Read / write interface definitions
val Change the values of master_cmd_code in reg MASTER_CMD_CODE
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_cmd_sens_sync_set()
int32_t lsm6dsl_sh_cmd_sens_sync_set (stmdev_ctx_t * ctx, uint8_t val)
Master command code used for stamping for sensor sync.[set].
Parameters
ctx Read / write interface definitions
val Change the values of master_cmd_code in reg MASTER_CMD_CODE
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_drdy_on_int1_get()
int32_t lsm6dsl_sh_drdy_on_int1_get (stmdev_ctx_t * ctx, uint8_t * val)
Manage the Master DRDY signal on INT1 pad.[get].
Parameters
ctx Read / write interface definitions
val Change the values of drdy_on_int1 in reg MASTER_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_drdy_on_int1_set()
int32_t lsm6dsl_sh_drdy_on_int1_set (stmdev_ctx_t * ctx, uint8_t val)
Manage the Master DRDY signal on INT1 pad.[set].
Parameters
ctx Read / write interface definitions
val Change the values of drdy_on_int1 in reg MASTER_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_master_get()
int32_t lsm6dsl_sh_master_get (stmdev_ctx_t * ctx, uint8_t * val)
Sensor hub I2C master enable.[get].
Parameters
ctx Read / write interface definitions
val Change the values of master_on in reg MASTER_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_master_set()
int32_t lsm6dsl_sh_master_set (stmdev_ctx_t * ctx, uint8_t val)
Sensor hub I2C master enable.[set].
Parameters
ctx Read / write interface definitions
val Change the values of master_on in reg MASTER_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_num_of_dev_connected_get()
int32_t lsm6dsl_sh_num_of_dev_connected_get (stmdev_ctx_t * ctx, lsm6dsl_aux_sens_on_t * val)
Number of external sensors to be read by the sensor hub.[get].
Parameters
ctx Read / write interface definitions
val Get the values of aux_sens_on in reg SLAVE0_CONFIG.
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_num_of_dev_connected_set()
int32_t lsm6dsl_sh_num_of_dev_connected_set (stmdev_ctx_t * ctx, lsm6dsl_aux_sens_on_t val)
Number of external sensors to be read by the sensor hub.[set].
Parameters
ctx Read / write interface definitions
val Change the values of aux_sens_on in reg SLAVE0_CONFIG.
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_pass_through_get()
int32_t lsm6dsl_sh_pass_through_get (stmdev_ctx_t * ctx, uint8_t * val)
I2C interface pass-through.[get].
Parameters
ctx Read / write interface definitions
val Change the values of pass_through_mode in reg MASTER_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_pass_through_set()
int32_t lsm6dsl_sh_pass_through_set (stmdev_ctx_t * ctx, uint8_t val)
I2C interface pass-through.[set].
Parameters
ctx Read / write interface definitions
val Change the values of pass_through_mode in reg MASTER_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_pin_mode_get()
int32_t lsm6dsl_sh_pin_mode_get (stmdev_ctx_t * ctx, lsm6dsl_pull_up_en_t * val)
Master I2C pull-up enable/disable.[get].
Parameters
ctx Read / write interface definitions
val Get the values of pull_up_en in reg MASTER_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_pin_mode_set()
int32_t lsm6dsl_sh_pin_mode_set (stmdev_ctx_t * ctx, lsm6dsl_pull_up_en_t val)
Master I2C pull-up enable/disable.[set].
Parameters
ctx Read / write interface definitions
val Change the values of pull_up_en in reg MASTER_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_read_data_raw_get()
int32_t lsm6dsl_sh_read_data_raw_get (stmdev_ctx_t * ctx, lsm6dsl_emb_sh_read_t * val)
Sensor hub output registers.[get].
Parameters
ctx Read / write interface definitions
val Structure of registers from SENSORHUB1_REG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_slave_0_dec_get()
int32_t lsm6dsl_sh_slave_0_dec_get (stmdev_ctx_t * ctx, lsm6dsl_slave0_rate_t * val)
Decimation of read operation on Slave 0 starting from the sensor hub trigger.[get].
Parameters
ctx Read / write interface definitions
val Get the values of slave0_rate in reg SLAVE0_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_slave_0_dec_set()
int32_t lsm6dsl_sh_slave_0_dec_set (stmdev_ctx_t * ctx, lsm6dsl_slave0_rate_t val)
Decimation of read operation on Slave 0 starting from the sensor hub trigger.[set].
Parameters
ctx Read / write interface definitions
val Change the values of slave0_rate in reg SLAVE0_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_slave_1_dec_get()
int32_t lsm6dsl_sh_slave_1_dec_get (stmdev_ctx_t * ctx, lsm6dsl_slave1_rate_t * val)
Decimation of read operation on Slave 1 starting from the sensor hub trigger.[get].
Parameters
ctx Read / write interface definitions reg SLAVE1_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_slave_1_dec_set()
int32_t lsm6dsl_sh_slave_1_dec_set (stmdev_ctx_t * ctx, lsm6dsl_slave1_rate_t val)
Decimation of read operation on Slave 1 starting from the sensor hub trigger.[set].
Parameters
ctx Read / write interface definitions
val Change the values of slave1_rate in reg SLAVE1_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_slave_2_dec_get()
int32_t lsm6dsl_sh_slave_2_dec_get (stmdev_ctx_t * ctx, lsm6dsl_slave2_rate_t * val)
Decimation of read operation on Slave 2 starting from the sensor hub trigger.[get].
Parameters
ctx Read / write interface definitions
val Get the values of slave2_rate in reg SLAVE2_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_slave_2_dec_set()
int32_t lsm6dsl_sh_slave_2_dec_set (stmdev_ctx_t * ctx, lsm6dsl_slave2_rate_t val)
Decimation of read operation on Slave 2 starting from the sensor hub trigger.[set].
Parameters
ctx Read / write interface definitions
val Change the values of slave2_rate in reg SLAVE2_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_slave_3_dec_get()
int32_t lsm6dsl_sh_slave_3_dec_get (stmdev_ctx_t * ctx, lsm6dsl_slave3_rate_t * val)
Decimation of read operation on Slave 3 starting from the sensor hub trigger.[get].
Parameters
ctx Read / write interface definitions
val Get the values of slave3_rate in reg SLAVE3_CONFIG.
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_slave_3_dec_set()
int32_t lsm6dsl_sh_slave_3_dec_set (stmdev_ctx_t * ctx, lsm6dsl_slave3_rate_t val)
Decimation of read operation on Slave 3 starting from the sensor hub trigger.[set].
Parameters
ctx Read / write interface definitions
val Change the values of slave3_rate in reg SLAVE3_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_slv0_cfg_read()
int32_t lsm6dsl_sh_slv0_cfg_read (stmdev_ctx_t * ctx, lsm6dsl_sh_cfg_read_t * val)
Configure slave 0 for perform a read.[get].
Parameters
ctx Read / write interface definitions
val Structure that contain:
uint8_t slv_add; 8 bit i2c device address
uint8_t slv_subadd; 8 bit register device address
uint8_t slv_len; num of bit to read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_slv1_cfg_read()
int32_t lsm6dsl_sh_slv1_cfg_read (stmdev_ctx_t * ctx, lsm6dsl_sh_cfg_read_t * val)
Configure slave 1 for perform a read.[get].
Parameters
ctx Read / write interface definitions
val Structure that contain:
uint8_t slv_add; 8 bit i2c device address
uint8_t slv_subadd; 8 bit register device address
uint8_t slv_len; num of bit to read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_slv2_cfg_read()
int32_t lsm6dsl_sh_slv2_cfg_read (stmdev_ctx_t * ctx, lsm6dsl_sh_cfg_read_t * val)
Configure slave 2 for perform a read.[get].
Parameters
ctx Read / write interface definitions
val Structure that contain:
uint8_t slv_add; 8 bit i2c device address
uint8_t slv_subadd; 8 bit register device address
uint8_t slv_len; num of bit to read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_slv3_cfg_read()
int32_t lsm6dsl_sh_slv3_cfg_read (stmdev_ctx_t * ctx, lsm6dsl_sh_cfg_read_t * val)
Configure slave 3 for perform a read.[get].
Parameters
ctx Read / write interface definitions
val Structure that contain:
uint8_t slv_add; 8 bit i2c device address
uint8_t slv_subadd; 8 bit register device address
uint8_t slv_len; num of bit to read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_spi_sync_error_get()
int32_t lsm6dsl_sh_spi_sync_error_get (stmdev_ctx_t * ctx, uint8_t * val)
Error code used for sensor synchronization.[get].
Parameters
ctx Read / write interface definitions
val Change the values of error_code in reg SENS_SYNC_SPI_ERROR_CODE.
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_spi_sync_error_set()
int32_t lsm6dsl_sh_spi_sync_error_set (stmdev_ctx_t * ctx, uint8_t val)
Error code used for sensor synchronization.[set].
Parameters
ctx Read / write interface definitions
val Change the values of error_code in reg SENS_SYNC_SPI_ERROR_CODE.
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_sync_sens_frame_get()
int32_t lsm6dsl_sh_sync_sens_frame_get (stmdev_ctx_t * ctx, uint8_t * val)
Sensor synchronization time frame with the step of 500 ms and full range of 5s. Unsigned 8-bit.[get].
Parameters
ctx Read / write interface definitions
val Change the values of tph in reg SENSOR_SYNC_TIME_FRAME
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_sync_sens_frame_set()
int32_t lsm6dsl_sh_sync_sens_frame_set (stmdev_ctx_t * ctx, uint8_t val)
Sensor synchronization time frame with the step of 500 ms and full range of 5s. Unsigned 8-bit.[set].
Parameters
ctx Read / write interface definitions
val Change the values of tph in reg SENSOR_SYNC_TIME_FRAME
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_sync_sens_ratio_get()
int32_t lsm6dsl_sh_sync_sens_ratio_get (stmdev_ctx_t * ctx, lsm6dsl_rr_t * val)
Resolution ratio of error code for sensor synchronization.[get].
Parameters
ctx Read / write interface definitions
val Get the values of rr in reg SENSOR_SYNC_RES_RATIO
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_sync_sens_ratio_set()
int32_t lsm6dsl_sh_sync_sens_ratio_set (stmdev_ctx_t * ctx, lsm6dsl_rr_t val)
Resolution ratio of error code for sensor synchronization.[set].
Parameters
ctx Read / write interface definitions
val Change the values of rr in reg SENSOR_SYNC_RES_RATIO
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_syncro_mode_get()
int32_t lsm6dsl_sh_syncro_mode_get (stmdev_ctx_t * ctx, lsm6dsl_start_config_t * val)
Sensor hub trigger signal selection.[get].
Parameters
ctx Read / write interface definitions
val Get the values of start_config in reg MASTER_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_syncro_mode_set()
int32_t lsm6dsl_sh_syncro_mode_set (stmdev_ctx_t * ctx, lsm6dsl_start_config_t val)
Sensor hub trigger signal selection.[set].
Parameters
ctx Read / write interface definitions
val Change the values of start_config in reg MASTER_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_sh_write_mode_get()
int32_t lsm6dsl_sh_write_mode_get (stmdev_ctx_t * ctx, lsm6dsl_write_once_t * val)
Slave 0 write operation is performed only at the first sensor hub cycle. This is effective if the Aux_sens_on[1:0] field in SLAVE0_CONFIG(04h) is set to a value other than 00.[get].
Parameters
ctx Read / write interface definitions
val Get the values of write_once in reg SLAVE1_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_sh_write_mode_set()
int32_t lsm6dsl_sh_write_mode_set (stmdev_ctx_t * ctx, lsm6dsl_write_once_t val)
Slave 0 write operation is performed only at the first sensor hub cycle. This is effective if the Aux_sens_on[1:0] field in SLAVE0_CONFIG(04h) is set to a value other than 00.[set].
Parameters
ctx Read / write interface definitions
val Change the values of write_once in reg SLAVE1_CONFIG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_spi_mode_get()
int32_t lsm6dsl_spi_mode_get (stmdev_ctx_t * ctx, lsm6dsl_sim_t * val)
SPI Serial Interface Mode selection.[get].
Parameters
ctx Read / write interface definitions
val Get the values of sim in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_spi_mode_set()
int32_t lsm6dsl_spi_mode_set (stmdev_ctx_t * ctx, lsm6dsl_sim_t val)
SPI Serial Interface Mode selection.[set].
Parameters
ctx Read / write interface definitions
val Change the values of sim in reg CTRL3_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_status_reg_get()
int32_t lsm6dsl_status_reg_get (stmdev_ctx_t * ctx, lsm6dsl_status_reg_t * val)
The STATUS_REG register is read by the primary interface[get].
Parameters
ctx Read / write interface definitions
val Registers STATUS_REG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_detection_on_x_get()
int32_t lsm6dsl_tap_detection_on_x_get (stmdev_ctx_t * ctx, uint8_t * val)
Enable X direction in tap recognition.[get].
Parameters
ctx Read / write interface definitions
val Change the values of tap_x_en in reg TAP_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_detection_on_x_set()
int32_t lsm6dsl_tap_detection_on_x_set (stmdev_ctx_t * ctx, uint8_t val)
Enable X direction in tap recognition.[set].
Parameters
ctx Read / write interface definitions
val Change the values of tap_x_en in reg TAP_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_detection_on_y_get()
int32_t lsm6dsl_tap_detection_on_y_get (stmdev_ctx_t * ctx, uint8_t * val)
Enable Y direction in tap recognition.[get].
Parameters
ctx Read / write interface definitions
val Change the values of tap_y_en in reg TAP_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_detection_on_y_set()
int32_t lsm6dsl_tap_detection_on_y_set (stmdev_ctx_t * ctx, uint8_t val)
Enable Y direction in tap recognition.[set].
Parameters
ctx Read / write interface definitions
val Change the values of tap_y_en in reg TAP_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_detection_on_z_get()
int32_t lsm6dsl_tap_detection_on_z_get (stmdev_ctx_t * ctx, uint8_t * val)
Enable Z direction in tap recognition.[get].
Parameters
ctx Read / write interface definitions
val Change the values of tap_z_en in reg TAP_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_detection_on_z_set()
int32_t lsm6dsl_tap_detection_on_z_set (stmdev_ctx_t * ctx, uint8_t val)
Enable Z direction in tap recognition.[set].
Parameters
ctx Read / write interface definitions
val Change the values of tap_z_en in reg TAP_CFG
References lsm6dsl_read_reg().
lsm6dsl_tap_dur_get()
int32_t lsm6dsl_tap_dur_get (stmdev_ctx_t * ctx, uint8_t * val)
When double tap recognition is enabled, this register expresses the maximum time between two consecutive detected taps to determine a double tap event. The default value of these bits is 0000b which corresponds to 16*ODR_XL time. If the DUR[3:0] bits are set to a different value,1LSB corresponds to 32*ODR_XL time.[get].
Parameters
ctx Read / write interface definitions
val Change the values of dur in reg INT_DUR2
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_dur_set()
int32_t lsm6dsl_tap_dur_set (stmdev_ctx_t * ctx, uint8_t val)
When double tap recognition is enabled, this register expresses the maximum time between two consecutive detected taps to determine a double tap event. The default value of these bits is 0000b which corresponds to 16*ODR_XL time. If the DUR[3:0] bits are set to a different value,1LSB corresponds to 32*ODR_XL time.[set].
Parameters
ctx Read / write interface definitions
val Change the values of dur in reg INT_DUR2
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Set_Tap_Duration_Time().
lsm6dsl_tap_mode_get()
int32_t lsm6dsl_tap_mode_get (stmdev_ctx_t * ctx, lsm6dsl_single_double_tap_t * val)
Single/double-tap event enable/disable.[get].
Parameters
ctx Read / write interface definitions
val Get the values of single_double_tap in reg WAKE_UP_THS
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_mode_set()
int32_t lsm6dsl_tap_mode_set (stmdev_ctx_t * ctx, lsm6dsl_single_double_tap_t val)
Single/double-tap event enable/disable.[set].
Parameters
ctx Read / write interface definitions
val Change the values of single_double_tap in reg WAKE_UP_THS
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_quiet_get()
int32_t lsm6dsl_tap_quiet_get (stmdev_ctx_t * ctx, uint8_t * val)
Quiet time is the time after the first detected tap in which there must not be any overthreshold event. The default value of these bits is 00b which corresponds to 2*ODR_XL time. If the QUIET[1:0] bits are set to a different value, 1LSB corresponds to 4*ODR_XL time.[get].
Parameters
ctx Read / write interface definitions
val Change the values of quiet in reg INT_DUR2
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_quiet_set()
int32_t lsm6dsl_tap_quiet_set (stmdev_ctx_t * ctx, uint8_t val)
Quiet time is the time after the first detected tap in which there must not be any overthreshold event. The default value of these bits is 00b which corresponds to 2*ODR_XL time. If the QUIET[1:0] bits are set to a different value, 1LSB corresponds to 4*ODR_XL time.[set].
Parameters
ctx Read / write interface definitions
val Change the values of quiet in reg INT_DUR2
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Set_Tap_Quiet_Time().
lsm6dsl_tap_shock_get()
int32_t lsm6dsl_tap_shock_get (stmdev_ctx_t * ctx, uint8_t * val)
Maximum duration is the maximum time of an overthreshold signal detection to be recognized as a tap event. The default value of these bits is 00b which corresponds to 4*ODR_XL time. If the SHOCK[1:0] bits are set to a different value, 1LSB corresponds to 8*ODR_XL time.[get].
Parameters
ctx Read / write interface definitions
val Change the values of shock in reg INT_DUR2
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_shock_set()
int32_t lsm6dsl_tap_shock_set (stmdev_ctx_t * ctx, uint8_t val)
Maximum duration is the maximum time of an overthreshold signal detection to be recognized as a tap event. The default value of these bits is 00b which corresponds to 4*ODR_XL time. If the SHOCK[1:0] bits are set to a different value, 1LSB corresponds to 8*ODR_XL time.[set].
Parameters
ctx Read / write interface definitions
val Change the values of shock in reg INT_DUR2
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Set_Tap_Shock_Time().
lsm6dsl_tap_src_get()
int32_t lsm6dsl_tap_src_get (stmdev_ctx_t * ctx, lsm6dsl_tap_src_t * val)
Read the tap / double tap source register.[get].
Parameters
ctx Read / write interface definitions
val Structure of registers from TAP_SRC
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_threshold_x_get()
int32_t lsm6dsl_tap_threshold_x_get (stmdev_ctx_t * ctx, uint8_t * val)
Threshold for tap recognition.[get].
Parameters
ctx Read / write interface definitions
val Change the values of tap_ths in reg TAP_THS_6D
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tap_threshold_x_set()
int32_t lsm6dsl_tap_threshold_x_set (stmdev_ctx_t * ctx, uint8_t val)
Threshold for tap recognition.[set].
Parameters
ctx Read / write interface definitions
val Change the values of tap_ths in reg TAP_THS_6D
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Set_Tap_Threshold().
lsm6dsl_temp_flag_data_ready_get()
int32_t lsm6dsl_temp_flag_data_ready_get (stmdev_ctx_t * ctx, uint8_t * val)
Temperature new data available.[get].
Parameters
ctx Read / write interface definitions
val Change the values of tda in reg STATUS_REG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_temperature_raw_get()
int32_t lsm6dsl_temperature_raw_get (stmdev_ctx_t * ctx, int16_t * val)
Temperature data output register (r). L and H registers together express a 16-bit word in two’s complement.[get].
Parameters
ctx Read / write interface definitions
buff Buffer that stores data read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tilt_latency_get()
int32_t lsm6dsl_tilt_latency_get (stmdev_ctx_t * ctx, uint8_t * buff)
Absolute Wrist Tilt latency register (r/w). Absolute wrist tilt latency parameters. 1 LSB = 40 ms. Default value: 0Fh (600 ms).[get].
Parameters
ctx Read / write interface definitions
buff Buffer that stores data read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_tilt_latency_set()
int32_t lsm6dsl_tilt_latency_set (stmdev_ctx_t * ctx, uint8_t * buff)
Absolute Wrist Tilt latency register (r/w). Absolute wrist tilt latency parameters. 1 LSB = 40 ms. Default value: 0Fh (600 ms).[set].
Parameters
ctx Read / write interface definitions
buff Buffer that contains data to write
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_tilt_sens_get()
int32_t lsm6dsl_tilt_sens_get (stmdev_ctx_t * ctx, uint8_t * val)
Enable tilt calculation.[get].
Parameters
ctx Read / write interface definitions
val Change the values of tilt_en in reg CTRL10_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tilt_sens_set()
int32_t lsm6dsl_tilt_sens_set (stmdev_ctx_t * ctx, uint8_t val)
Enable tilt calculation.[set].
Parameters
ctx Read / write interface definitions
val Change the values of tilt_en in reg CTRL10_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_tilt_src_get()
int32_t lsm6dsl_tilt_src_get (stmdev_ctx_t * ctx, lsm6dsl_a_wrist_tilt_mask_t * val)
Absolute Wrist Tilt mask register (r/w).[get].
Parameters
ctx Read / write interface definitions
val Registers A_WRIST_TILT_MASK
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_tilt_src_set()
int32_t lsm6dsl_tilt_src_set (stmdev_ctx_t * ctx, lsm6dsl_a_wrist_tilt_mask_t * val)
Absolute Wrist Tilt mask register (r/w).[set].
Parameters
ctx Read / write interface definitions
val Registers A_WRIST_TILT_MASK
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_tilt_threshold_get()
int32_t lsm6dsl_tilt_threshold_get (stmdev_ctx_t * ctx, uint8_t * buff)
Absolute Wrist Tilt threshold register(r/w). Absolute wrist tilt threshold parameters. 1 LSB = 15.625 mg.Default value: 20h (500 mg).[get].
Parameters
ctx Read / write interface definitions
buff Buffer that stores data read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_tilt_threshold_set()
int32_t lsm6dsl_tilt_threshold_set (stmdev_ctx_t * ctx, uint8_t * buff)
Absolute Wrist Tilt threshold register(r/w). Absolute wrist tilt threshold parameters. 1 LSB = 15.625 mg.Default value: 20h (500 mg).[set].
Parameters
ctx Read / write interface definitions
buff Buffer that contains data to write
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_mem_bank_set().
lsm6dsl_timestamp_get()
int32_t lsm6dsl_timestamp_get (stmdev_ctx_t * ctx, uint8_t * val)
Enable timestamp count. The count is saved in TIMESTAMP0_REG (40h), TIMESTAMP1_REG (41h) and TIMESTAMP2_REG (42h).[get].
Parameters
ctx Read / write interface definitions
val Change the values of timer_en in reg CTRL10_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_timestamp_res_get()
int32_t lsm6dsl_timestamp_res_get (stmdev_ctx_t * ctx, lsm6dsl_timer_hr_t * val)
Timestamp register resolution setting. Configuration of this bit affects TIMESTAMP0_REG(40h), TIMESTAMP1_REG(41h), TIMESTAMP2_REG(42h), STEP_TIMESTAMP_L(49h), STEP_TIMESTAMP_H(4Ah) and STEP_COUNT_DELTA(15h) registers.[get].
Parameters
ctx Read / write interface definitions
val Get the values of timer_hr in reg WAKE_UP_DUR
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_timestamp_res_set()
int32_t lsm6dsl_timestamp_res_set (stmdev_ctx_t * ctx, lsm6dsl_timer_hr_t val)
Timestamp register resolution setting. Configuration of this bit affects TIMESTAMP0_REG(40h), TIMESTAMP1_REG(41h), TIMESTAMP2_REG(42h), STEP_TIMESTAMP_L(49h), STEP_TIMESTAMP_H(4Ah) and STEP_COUNT_DELTA(15h) registers.[set].
Parameters
ctx Read / write interface definitions
val Change the values of timer_hr in reg WAKE_UP_DUR
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_timestamp_set()
int32_t lsm6dsl_timestamp_set (stmdev_ctx_t * ctx, uint8_t val)
Enable timestamp count. The count is saved in TIMESTAMP0_REG (40h), TIMESTAMP1_REG (41h) and TIMESTAMP2_REG (42h).[set].
Parameters
ctx Read / write interface definitions
val Change the values of timer_en in reg CTRL10_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_wkup_dur_get()
int32_t lsm6dsl_wkup_dur_get (stmdev_ctx_t * ctx, uint8_t * val)
Wake up duration event.1LSb = 1 / ODR[get].
Parameters
ctx Read / write interface definitions
val Change the values of wake_dur in reg WAKE_UP_DUR
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_wkup_dur_set()
int32_t lsm6dsl_wkup_dur_set (stmdev_ctx_t * ctx, uint8_t val)
Wake up duration event.1LSb = 1 / ODR[set].
Parameters
ctx Read / write interface definitions
val Change the values of wake_dur in reg WAKE_UP_DUR
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Set_Wake_Up_Duration().
lsm6dsl_wkup_threshold_get()
int32_t lsm6dsl_wkup_threshold_get (stmdev_ctx_t * ctx, uint8_t * val)
Threshold for wakeup.1 LSB = FS_XL / 64.[get].
Parameters
ctx Read / write interface definitions
val Change the values of wk_ths in reg WAKE_UP_THS
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_wkup_threshold_set()
int32_t lsm6dsl_wkup_threshold_set (stmdev_ctx_t * ctx, uint8_t val)
Threshold for wakeup.1 LSB = FS_XL / 64.[set].
Parameters
ctx Read / write interface definitions
val Change the values of wk_ths in reg WAKE_UP_THS
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Set_Wake_Up_Threshold().
lsm6dsl_wrist_tilt_sens_get()
int32_t lsm6dsl_wrist_tilt_sens_get (stmdev_ctx_t * ctx, uint8_t * val)
Enable tilt calculation.[get].
Parameters
ctx Read / write interface definitions
val Change the values of tilt_en in reg CTRL10_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_wrist_tilt_sens_set()
int32_t lsm6dsl_wrist_tilt_sens_set (stmdev_ctx_t * ctx, uint8_t val)
Enable tilt calculation.[set].
Parameters
ctx Read / write interface definitions
val Change the values of tilt_en in reg CTRL10_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_write_reg()
int32_t lsm6dsl_write_reg (stmdev_ctx_t * ctx, uint8_t reg, uint8_t * data, uint16_t len)
Write generic device register.
Parameters
ctx read / write interface definitions(ptr)
reg register to write
data pointer to data to write in register reg(ptr)
len number of consecutive register to write
Return values
interface status (MANDATORY: return 0 -> no Error)
References stmdev_ctx_t::handle, and stmdev_ctx_t::write_reg.
Referenced by LSM6DSL_Write_Reg(), and lsm6dsl_xl_usr_offset_set().
lsm6dsl_xl_data_rate_get()
int32_t lsm6dsl_xl_data_rate_get (stmdev_ctx_t * ctx, lsm6dsl_odr_xl_t * val)
Accelerometer data rate selection.[get].
Parameters
ctx Read / write interface definitions
val Get the values of odr_xl in reg CTRL1_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_data_rate_set()
int32_t lsm6dsl_xl_data_rate_set (stmdev_ctx_t * ctx, lsm6dsl_odr_xl_t val)
Accelerometer data rate selection.[set].
Parameters
ctx Read / write interface definitions
val Change the values of odr_xl in reg CTRL1_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_filter_analog_get()
int32_t lsm6dsl_xl_filter_analog_get (stmdev_ctx_t * ctx, lsm6dsl_bw0_xl_t * val)
Accelerometer analog chain bandwidth selection (only for accelerometer ODR ≥ 1.67 kHz).[get].
Parameters
ctx Read / write interface definitions
val Get the values of bw0_xl in reg CTRL1_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_filter_analog_set()
int32_t lsm6dsl_xl_filter_analog_set (stmdev_ctx_t * ctx, lsm6dsl_bw0_xl_t val)
Accelerometer analog chain bandwidth selection (only for accelerometer ODR ≥ 1.67 kHz).[set].
Parameters
ctx Read / write interface definitions
val Change the values of bw0_xl in reg CTRL1_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_flag_data_ready_get()
int32_t lsm6dsl_xl_flag_data_ready_get (stmdev_ctx_t * ctx, uint8_t * val)
Accelerometer new data available.[get].
Parameters
ctx Read / write interface definitions
val Change the values of xlda in reg STATUS_REG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
Referenced by LSM6DSL_ACC_Get_DRDY_Status().
lsm6dsl_xl_full_scale_get()
int32_t lsm6dsl_xl_full_scale_get (stmdev_ctx_t * ctx, lsm6dsl_fs_xl_t * val)
Accelerometer full-scale selection.[get].
Parameters
ctx Read / write interface definitions
val Get the values of fs_xl in reg CTRL1_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_full_scale_set()
int32_t lsm6dsl_xl_full_scale_set (stmdev_ctx_t * ctx, lsm6dsl_fs_xl_t val)
Accelerometer full-scale selection.[set].
Parameters
ctx Read / write interface definitions
val Change the values of fs_xl in reg CTRL1_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_hp_bandwidth_get()
int32_t lsm6dsl_xl_hp_bandwidth_get (stmdev_ctx_t * ctx, lsm6dsl_hpcf_xl_t * val)
High pass/Slope on outputs.[get].
Parameters
ctx Read / write interface definitions
val Get the values of hpcf_xl in reg CTRL8_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_hp_bandwidth_set()
int32_t lsm6dsl_xl_hp_bandwidth_set (stmdev_ctx_t * ctx, lsm6dsl_hpcf_xl_t val)
High pass/Slope on outputs.[set].
Parameters
ctx Read / write interface definitions
val Change the values of hpcf_xl in reg CTRL8_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_hp_path_internal_get()
int32_t lsm6dsl_xl_hp_path_internal_get (stmdev_ctx_t * ctx, lsm6dsl_slope_fds_t * val)
HPF or SLOPE filter selection on wake-up and Activity/Inactivity functions.[get].
Parameters
ctx Read / write interface definitions
val Get the values of slope_fds in reg TAP_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_hp_path_internal_set()
int32_t lsm6dsl_xl_hp_path_internal_set (stmdev_ctx_t * ctx, lsm6dsl_slope_fds_t val)
HPF or SLOPE filter selection on wake-up and Activity/Inactivity functions.[set].
Parameters
ctx Read / write interface definitions
val Change the values of slope_fds in reg TAP_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_lp1_bandwidth_get()
int32_t lsm6dsl_xl_lp1_bandwidth_get (stmdev_ctx_t * ctx, lsm6dsl_lpf1_bw_sel_t * val)
Accelerometer digital LPF (LPF1) bandwidth selection LPF2 is not used.[get].
Parameters
ctx Read / write interface definitions
val Get the values of lpf1_bw_sel in reg CTRL1_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_lp1_bandwidth_set()
int32_t lsm6dsl_xl_lp1_bandwidth_set (stmdev_ctx_t * ctx, lsm6dsl_lpf1_bw_sel_t val)
Accelerometer digital LPF (LPF1) bandwidth selection LPF2 is not used.[set].
Parameters
ctx Read / write interface definitions
val Change the values of lpf1_bw_sel in reg CTRL1_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_lp2_bandwidth_get()
int32_t lsm6dsl_xl_lp2_bandwidth_get (stmdev_ctx_t * ctx, lsm6dsl_input_composite_t * val)
LPF2 on outputs[get].
Parameters
ctx Read / write interface definitions
val Get the values of input_composite in reg CTRL8_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_lp2_bandwidth_set()
int32_t lsm6dsl_xl_lp2_bandwidth_set (stmdev_ctx_t * ctx, lsm6dsl_input_composite_t val)
LPF2 on outputs[set].
Parameters
ctx Read / write interface definitions
val Change the values of input_composite in reg CTRL8_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_offset_weight_get()
int32_t lsm6dsl_xl_offset_weight_get (stmdev_ctx_t * ctx, lsm6dsl_usr_off_w_t * val)
Weight of XL user offset bits of registers X_OFS_USR(73h), Y_OFS_USR(74h), Z_OFS_USR(75h).[get].
Parameters
ctx Read / write interface definitions
val Get the values of usr_off_w in reg CTRL6_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_offset_weight_set()
int32_t lsm6dsl_xl_offset_weight_set (stmdev_ctx_t * ctx, lsm6dsl_usr_off_w_t val)
Weight of XL user offset bits of registers X_OFS_USR(73h), Y_OFS_USR(74h), Z_OFS_USR(75h).[set].
Parameters
ctx Read / write interface definitions
val Change the values of usr_off_w in reg CTRL6_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_power_mode_get()
int32_t lsm6dsl_xl_power_mode_get (stmdev_ctx_t * ctx, lsm6dsl_xl_hm_mode_t * val)
High-performance operating mode for accelerometer.[get].
Parameters
ctx Read / write interface definitions
val Get the values of xl_hm_mode in reg CTRL6_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_power_mode_set()
int32_t lsm6dsl_xl_power_mode_set (stmdev_ctx_t * ctx, lsm6dsl_xl_hm_mode_t val)
High-performance operating mode for accelerometer[set].
Parameters
ctx Read / write interface definitions
val Change the values of xl_hm_mode in reg CTRL6_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_reference_mode_get()
int32_t lsm6dsl_xl_reference_mode_get (stmdev_ctx_t * ctx, uint8_t * val)
Enable HP filter reference mode.[get].
Parameters
ctx Read / write interface definitions
val Change the values of hp_ref_mode in reg CTRL8_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_reference_mode_set()
int32_t lsm6dsl_xl_reference_mode_set (stmdev_ctx_t * ctx, uint8_t val)
Enable HP filter reference mode.[set].
Parameters
ctx Read / write interface definitions
val Change the values of hp_ref_mode in reg CTRL8_XL
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_self_test_get()
int32_t lsm6dsl_xl_self_test_get (stmdev_ctx_t * ctx, lsm6dsl_st_xl_t * val)
Linear acceleration sensor self-test enable.[get].
Parameters
ctx Read / write interface definitions
val Get the values of st_xl in reg CTRL5_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_self_test_set()
int32_t lsm6dsl_xl_self_test_set (stmdev_ctx_t * ctx, lsm6dsl_st_xl_t val)
Linear acceleration sensor self-test enable.[set].
Parameters
ctx Read / write interface definitions
val Change the values of st_xl in reg CTRL5_C
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_usr_offset_get()
int32_t lsm6dsl_xl_usr_offset_get (stmdev_ctx_t * ctx, uint8_t * buff)
Accelerometer axis user offset correction xpressed in two’s complement, weight depends on USR_OFF_W in CTRL6_C. The value must be in the range [-127 127].[get].
Parameters
ctx Read / write interface definitions
buff Buffer that stores data read
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_read_reg().
lsm6dsl_xl_usr_offset_set()
int32_t lsm6dsl_xl_usr_offset_set (stmdev_ctx_t * ctx, uint8_t * buff)
Accelerometer axis user offset correction expressed in two’s complement, weight depends on USR_OFF_W in CTRL6_C. The value must be in the range [-127 127].[set].
Parameters
ctx Read / write interface definitions
buff Buffer that contains data to write
Return values
Interface status (MANDATORY: return 0 -> no Error).
References lsm6dsl_write_reg().