Multifunction Safety Relay WEG: http_util.h File Reference
http_util.h File Reference
Helper functions for building HTTP GET and POST requests, and stream reading. Header for http_util.c.
#include <stdint.h>
#include <stdbool.h>
Data Structures
struct http_range_status_t
Macros
#define HTTP_OK 0
#define HTTP_ERR -1
#define HTTP_ERR_HTTP -2
#define HTTP_ERR_CLOSED -3
#define FWVERSION_NAME_SIZE 20
#define FWVERSION_DATE_SIZE 16
#define FWVERSION_TIME_SIZE 9
Typedefs
typedef void * http_handle_t
typedef void * http_sock_handle_t
Enumerations
enum http_proto_t {
HTTP_PROTO_NONE = 0 , HTTP_PROTO_HTTP , HTTP_PROTO_HTTPS , HTTP_PROTO_NONE = 0 ,
HTTP_PROTO_HTTP , HTTP_PROTO_HTTPS
}
Functions
int http_open (http_handle_t *const pHnd, const char *url)
Open an HTTP progressive download session.
int http_close (const http_handle_t hnd)
Close an HTTP session.
bool http_is_open (const http_handle_t hnd)
Tells whether an HTTP session is still open, or has been closed by the server.
int http_read (uint8_t *const readbuffer, http_range_status_t *const status, const size_t offset, const size_t size, const char *const extra_headers, const uint8_t *const post_buf, const size_t post_buf_size, const http_handle_t hnd)
Read from an HTTP progressive download session.
int http_url_parse (char *const host, const int host_max_len, int *const port, bool *tls, char *const query, const int query_max_len, const char *url)
Parse and split an http url into hostname/port number/query string.
int http_req_create (char **const req_buf, const char *const query, const char *const hostname, const size_t offset, const size_t size, const char *const extra_headers, const size_t post_buf_size)
Create an HTTP request string from the parameter list.
void http_req_destroy (const char *req_buf)
Destroy an HTTP request string created by http_req_create();.
int http_sock_open (http_sock_handle_t *const http_sock_hnd, const char *url)
Open a socket-like connection over the passed HTTP progressive download session.
int http_sock_close (const http_sock_handle_t http_sock_hnd)
Close a socket-like connection.
int http_sock_rcv (uint8_t *const readbuffer, const int size, const http_sock_handle_t http_sock_hnd)
Receive data from an socket-like connection.
int http_sock_get_resource_size (const http_sock_handle_t http_sock_hnd)
Detailed Description
Helper functions for building HTTP GET and POST requests, and stream reading. Header for http_util.c.
Author
MCD Application Team
Attention
© Copyright (c) 2017 STMicroelectronics International N.V. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted, provided that the following conditions are met:
Redistribution of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of STMicroelectronics nor the names of other contributors to this software may be used to endorse or promote products derived from this software without specific written permission.
This software, including modifications and/or derivative works of this software, must execute solely and exclusively on microcontroller or microprocessor devices manufactured by or for STMicroelectronics.
Redistribution and use of this software other than as permitted under this license is void and will automatically terminate your rights under this license.
THIS SOFTWARE IS PROVIDED BY STMICROELECTRONICS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS, IMPLIED OR STATUTORY WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT OF THIRD PARTY INTELLECTUAL PROPERTY RIGHTS ARE DISCLAIMED TO THE FULLEST EXTENT PERMITTED BY LAW. IN NO EVENT SHALL STMICROELECTRONICS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Macro Definition Documentation
HTTP_ERR_CLOSED
#define HTTP_ERR_CLOSED -3
The HTTP connection was closed by the server.
HTTP_ERR_HTTP
#define HTTP_ERR_HTTP -2
HTTP error
Function Documentation
http_close()
int http_close (const http_handle_t hnd)
Close an HTTP session.
Note
The internal session context is freed by the callee.
Parameters
In hnd Session handle.
Return values
Error code HTTP_OK (0) Success HTTP_ERR (<0) Failure
Close an HTTP session.
Note
The internal session context is freed by the callee.
Parameters
In hnd Session handle.
Return values
Error code HTTP_OK (0) Success HTTP_ERR (<0) Failure
References HTTP_ERR, HTTP_OK, msg_error, NET_OK, net_sock_close(), net_sock_destroy(), and http_context_t::sock.
Referenced by http_sock_close(), and http_sock_rcv().
http_is_open()
bool http_is_open (const http_handle_t hnd)
Tells whether an HTTP session is still open, or has been closed by the server.
check if a connection is open.
Parameters
In hnd Session handle.
Return values
true The session is open. false: The session is closed: the handle should be freed by calling http_close().
Tells whether an HTTP session is still open, or has been closed by the server.
check if a connection is open.
Parameters
In hnd Session handle.
Return values
true The session is open. false: The session is closed: the handle should be freed by calling http_close().
References http_context_t::connection_is_open.
Referenced by http_delete(), http_get(), http_post(), http_put(), and http_sock_rcv().
http_open()
int http_open (http_handle_t *const pHnd, const char * url)
Open an HTTP progressive download session.
Note
The internal session context is allocated by the callee.
Parameters
In pHnd Pointer on the session handle.
In url Source of the progressive download. e.g. http://john.doe:80/foo.bar
Return values
Error code HTTP_OK (0) Success HTTP_ERR (<0) Failure
References http_context_t::connection_is_open, http_context_t::hostname, HTTP_MAX_HOST_SIZE, HTTP_MAX_QUERY_SIZE, HTTP_OK, http_url_parse(), net_sock_create(), http_context_t::query, and http_context_t::sock.
Referenced by http_sock_open(), and http_sock_rcv().
http_read()
int http_read (uint8_t *const readbuffer, http_range_status_t *const status, const size_t offset, const size_t size, const char *const extra_headers, const uint8_t *const post_buf, const size_t post_buf_size, const http_handle_t hnd)
Read from an HTTP progressive download session.
Parameters
Out readbuffer Output buffer.
Out status HTTP range download status.
In offset Offset (in bytes) from the start of the remote resource to read from. (Supported only with GET requests).
In size Size of the chunk to read.
In extra_headers String containing additional HTTP headers to send. Each line must end with \r
. "" for no header at all.
In post_buf Payload of the POST request. If NULL, the call is translated into a GET request.
In post_buf_size Size of the POST payload.
In hnd Session handle.
Return values
>=0 Success: Number of bytes copied to readbuffer. <0 Error: HTTP_ERR Bad input parameter. Or allocation error. HTTP_ERR_HTTP Connection error, or unexpected response from the HTTP server. HTTP_ERR_CLOSED The connection was closed by the server during the previous http_read(). It is allowed by the protocol.
References http_context_t::connection_is_open, http_context_t::hostname, HTTP_ERR, HTTP_ERR_CLOSED, HTTP_ERR_HTTP, HTTP_OK, HTTP_READ_BUFFER_SIZE, http_req_create(), msg_error, net_sock_recv(), net_sock_send(), http_context_t::query, and http_context_t::sock.
Referenced by http_sock_rcv().
http_req_create()
int http_req_create (char **const req_buf, const char *const query, const char *const hostname, const size_t offset, const size_t size, const char *const extra_headers, const size_t post_buf_size)
Create an HTTP request string from the parameter list.
Note
The request buffer is allocated by the callee and must be released by calling http_req_destroy() after usage.
Parameters
Out req_buf Output buffer, allocated by the callee.
In query HTTP query string.
In hostname Remote hostname.
In offset Offset to the first byte to be read from the requested document in case of a partial content request. Must be set to 0 otherwise.
In size Maximum length of the chunk of the requested document to be read.
In extra_headers HTTP headers to be appended to the request header. Single buffer. Each line must be ended by \r
.
In post_buf_size Size of the document body to be sent, in case of a POST request. Must be 0 for a GET request.
Return values
Error code >0 Success, length of the request string written to req_buf. HTTP_ERR (<0) Failure
References HTTP_ERR, HTTP_OK, and msg_error.
Referenced by http_read().
http_req_destroy()
void http_req_destroy (const char * req_buf)
Destroy an HTTP request string created by http_req_create();.
Parameters
In req_buf Buffer to be freed.
http_sock_close()
int http_sock_close (const http_sock_handle_t http_sock_hnd)
Close a socket-like connection.
Parameters
In http_sock_hnd HTTP socket-like handle.
Return values
Error code HTTP_OK (0) Success HTTP_ERR (<0) Failure
References http_close(), HTTP_ERR, http_sock_context_t::http_hnd, HTTP_OK, and http_sock_context_t::pUrl.
http_sock_open()
int http_sock_open (http_sock_handle_t *const http_sock_hnd, const char * url)
Open a socket-like connection over the passed HTTP progressive download session.
Parameters
Out http_sock_hnd HTTP socket-like handle.
In url Source of the progressive download. e.g. http://john.doe:80/foo.bar
Return values
Error code HTTP_OK (0) Success HTTP_ERR (<0) Failure
References HTTP_ERR, http_sock_context_t::http_hnd, HTTP_OK, http_open(), http_sock_context_t::pUrl, http_sock_context_t::read_pos, and http_sock_context_t::res_size.
http_sock_rcv()
int http_sock_rcv (uint8_t *const readbuffer, const int size, const http_sock_handle_t http_sock_hnd)
Receive data from an socket-like connection.
Parameters
Out readbuffer Destination buffer. Allocated by the caller.
In size Maximum length of the read data.
In http_sock_hnd HTTP socket-like handle.
Return values
>=0 Success: Number of bytes copied to the destination buffer. <0 Error: HTTP_ERR Bad input parameter. HTTP_ERR_HTTP HTTP progressive download error.
References http_close(), HTTP_ERR, HTTP_ERR_HTTP, http_sock_context_t::http_hnd, http_is_open(), HTTP_MAX_TRY, HTTP_OK, http_open(), http_read(), msg_error, msg_info, http_sock_context_t::pUrl, http_sock_context_t::read_pos, http_sock_context_t::res_size, and http_range_status_t::resource_size.
http_url_parse()
int http_url_parse (char *const host, const int host_max_len, int *const port, bool * tls, char *const query, const int query_max_len, const char * url)
Parse and split an http url into hostname/port number/query string.
Parameters
Out host Hostname. Allocated by the caller.
In host_max_len Maximum length of the hostname.
Out proto Application protocol (HTTP or HTTPS).
Out port Port number.
Out query HTTP query. Allocated by the caller.
Out tls This is an HTTPS URL.
In query_max_len Maximum length of the query.
In url URL to be parsed.
Return values
Error code HTTP_OK (0) Success HTTP_ERR (<0) Failure
References msg_debug.
Referenced by http_open().