Multifunction Safety Relay WEG: http_lib.h File Reference
http_lib.h File Reference
Helper functions for sending HTTP requests Header for http_lib.c.
#include <stdint.h>
#include <stdbool.h>
Macros
#define HTTP_OK 0
#define HTTP_ERR -1
#define HTTP_PARAM -2
#define HTTP_TIMEOUT -3
#define HTTP_EOF -4
#define HTTP_NOT_FOUND -5
#define HTTP_AUTH -6
Typedefs
typedef void * http_handle_t
typedef void * http_sock_handle_t
Enumerations
enum http_proto_t {
HTTP_PROTO_NONE = 0 , HTTP_PROTO_HTTP , HTTP_PROTO_HTTPS , HTTP_PROTO_NONE = 0 ,
HTTP_PROTO_HTTP , HTTP_PROTO_HTTPS
}
enum http_request_t {
HTTP_REQUEST_NONE = 0 , HTTP_REQUEST_GET , HTTP_REQUEST_POST , HTTP_REQUEST_PUT ,
HTTP_REQUEST_DELETE
}
Functions
int http_create_session (http_handle_t *const pHnd, const char *host, int port, http_proto_t protocol)
Create an HTTP session.
int http_connect (http_handle_t Hnd)
Open an HTTP session.
int http_close (const http_handle_t hnd)
Close an HTTP session.
int http_create_request (http_request_t request_type, char *host, char *resource, uint8_t *buffer, uint32_t length)
Write begining of a request in the provided buffer. It will be sent with http_send(). It can be followed to calls to http_add_header() and http_add_body()
int http_add_header (uint8_t *buffer, uint32_t buffer_length, char *header, char *value)
Add an HTTP header to a request created in the provided buffer.
int http_add_body (uint8_t *buffer, uint32_t buffer_length, uint8_t *body, uint32_t body_length)
Add body part to a request created in the provided buffer.
int http_send (http_handle_t hnd, uint8_t *buffer, uint32_t buffer_length)
Send a request.
int http_recv (http_handle_t hnd, uint8_t *buffer, uint32_t length)
Receive data from server.
int http_recv_response (http_handle_t hnd, uint8_t *buffer, uint32_t buffer_length)
Receive full response to a request. This loops until it has received the amount of data indicated in Content-Length: header or the supplied response buffer is full.
int http_sock_setopt (http_handle_t Hnd, const char *optname, const uint8_t *optbuf, size_t optlen)
Set network socket option for an HTTP session. Used mainly for TLS options ("tls_ca_certs"). Must be done after create_session() and before connect().
int http_get (const http_handle_t hnd, const char *query, const char *additional_headers, uint8_t *readbuffer, uint32_t readbuffer_size)
Send an HTTP GET request.
int http_post (const http_handle_t hnd, const char *query, const char *additional_headers, const uint8_t *postbuffer, uint32_t postbuffer_size, uint8_t *responsebuffer, uint32_t responsebuffer_size)
Send an HTTP POST request.
int http_put (const http_handle_t hnd, const char *query, const char *additional_headers, const uint8_t *putbuffer, uint32_t putbuffer_size, uint8_t *responsebuffer, uint32_t responsebuffer_size)
Send an HTTP PUT request.
int http_delete (const http_handle_t hnd, const char *resource, const char *additional_headers, uint8_t *responsebuffer, uint32_t responsebuffer_size)
Send an HTTP DELETE request.
bool http_is_open (const http_handle_t hnd)
check if a connection is open.
uint8_t * http_find_body (uint8_t *http_message, uint32_t *length)
Find the start of body data in HTTP buffer.
uint32_t http_response_status (uint8_t *http_response, uint32_t length)
Get the HTTP response status in headers.
int http_response_validate (uint8_t *http_response, uint32_t length)
Validate the HTTP response.
uint32_t http_content_length (uint8_t *buffer, uint32_t length)
Get the value of Content-Length: in headers.
Detailed Description
Helper functions for sending HTTP requests Header for http_lib.c.
Author
MCD Application Team
Attention
© Copyright (c) 2017 STMicroelectronics International N.V. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted, provided that the following conditions are met:
Redistribution of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of STMicroelectronics nor the names of other contributors to this software may be used to endorse or promote products derived from this software without specific written permission.
This software, including modifications and/or derivative works of this software, must execute solely and exclusively on microcontroller or microprocessor devices manufactured by or for STMicroelectronics.
Redistribution and use of this software other than as permitted under this license is void and will automatically terminate your rights under this license.
THIS SOFTWARE IS PROVIDED BY STMICROELECTRONICS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS, IMPLIED OR STATUTORY WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT OF THIRD PARTY INTELLECTUAL PROPERTY RIGHTS ARE DISCLAIMED TO THE FULLEST EXTENT PERMITTED BY LAW. IN NO EVENT SHALL STMICROELECTRONICS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Macro Definition Documentation
HTTP_AUTH
#define HTTP_AUTH -6
The remote host cound not be authentified.
HTTP_EOF
#define HTTP_EOF -4
Connection dropped during the operation.
HTTP_ERR
#define HTTP_ERR -1
Internal error
HTTP_NOT_FOUND
#define HTTP_NOT_FOUND -5
The remote host could not be reached.
HTTP_OK
#define HTTP_OK 0
Success
HTTP_PARAM
#define HTTP_PARAM -2
Wrong parameters, or wrong state.
HTTP_TIMEOUT
#define HTTP_TIMEOUT -3
Timeout rearched during a blocking operation.
Function Documentation
http_add_body()
int http_add_body (uint8_t * buffer, uint32_t buffer_length, uint8_t * body, uint32_t body_length)
Add body part to a request created in the provided buffer.
Note
All the headers must have been added before calling this function.
Can be called zero or one time.
Parameters
In buffer full buffer provided by user (with header).
In buffer length buffer size (large enough for headers and body).
In body pointer to body part to be copied in buffer.
In body length body size.
Return values
returns total length (header+body) or HTTP_ERR (<0) in case of error
References HTTP_ERR, and http_find_body().
http_add_header()
int http_add_header (uint8_t * buffer, uint32_t buffer_length, char * header, char * value)
Add an HTTP header to a request created in the provided buffer.
Note
Must be called before http_add_body()
Can be called several times
Parameters
In buffer HTTP buffer provided by user. Must contain header and end with double CR-LF.
In length buffer size.
In header name
In header value
Return values
Error code HTTP_OK (0) Success HTTP_ERR (<0) Failure
References HTTP_ERR, and http_find_body().
http_close()
int http_close (const http_handle_t hnd)
Close an HTTP session.
Note
The internal session context is freed by the callee.
Parameters
In hnd Session handle.
Return values
Error code HTTP_OK (0) Success HTTP_ERR (<0) Failure
Close an HTTP session.
Note
The internal session context is freed by the callee.
Parameters
In hnd Session handle.
Return values
Error code HTTP_OK (0) Success HTTP_ERR (<0) Failure
References http_context_t::connection_is_open, HTTP_ERR, HTTP_OK, NET_OK, net_sock_close(), net_sock_destroy(), and http_context_t::sock.
http_connect()
int http_connect (http_handle_t Hnd)
Open an HTTP session.
Note
The internal session context is allocated by the callee.
Parameters
In Hnd session handle.
Return values
Error code HTTP_OK (0) Success HTTP_ERR (<0) Failure
References http_context_t::connection_is_open, http_context_t::hostname, HTTP_ERR, HTTP_OK, msg_error, NET_OK, net_sock_open(), http_context_t::port, and http_context_t::sock.
http_content_length()
uint32_t http_content_length (uint8_t * buffer, uint32_t length)
Get the value of Content-Length: in headers.
Parameters
In buffer buffer containing headers.
In length buffer size.
Return values
Error code >0 content length. HTTP_ERR (<0) Failure
Referenced by http_recv_response().
http_create_request()
int http_create_request (http_request_t request_type, char * host, char * resource, uint8_t * buffer, uint32_t length)
Write begining of a request in the provided buffer. It will be sent with http_send(). It can be followed to calls to http_add_header() and http_add_body()
Parameters
In type request type (GET, POST ...)
In host target host name (it will be used as HTTP header Host: hostname.com)
In resource resource (path with leading slash. Ex: "/path/to/resource.html")
In buffer buffer provided by user.
In length buffer size.
Return values
>0 Header size <0 Error
http_create_session()
int http_create_session (http_handle_t *const pHnd, const char * host, int port, http_proto_t protocol)
Create an HTTP session.
Note
The internal session context is allocated by the callee.
Parameters
In pHnd Pointer on the session handle.
In host target host. Ex: www.host.com
In port target port. Ex: 80
In protocol plain or secure connection (TLS)
Return values
Error code HTTP_OK (0) Success HTTP_ERR (<0) Failure
http_delete()
int http_delete (const http_handle_t hnd, const char * resource, const char * additional_headers, uint8_t * responsebuffer, uint32_t responsebuffer_size)
Send an HTTP DELETE request.
Parameters
In hnd HTTP Handle created by http_open().
In query HTTP resource path ("/path/to/resource.html"). Must beging with '/'.
In additional_headers HTTP headers (each line ending with \r
)
In responsebuffer pointer to buffer for POST response
In responsebuffer_size max size of data of POST response.
Return values
Error code >0 Success, length of the received data. HTTP_ERR (<0) Failure
References http_context_t::buffer, HTTP_ERR, http_is_open(), and msg_error.
http_find_body()
uint8_t * http_find_body (uint8_t * http_message, uint32_t * len)
Find the start of body data in HTTP buffer.
Parameters
In buffer HTTP buffer.
In/Out length In: buffer size. Out: body size.
Return values
!=NULL pointer to body part of HTTP buffer. NULL Body part was not found.
Find the start of body data in HTTP buffer.
http_message: pointer to full HTTP message
len: pointer to HTTP message length. It will contain body length in return.
Return values
pointer to body in HTTP message
Referenced by http_add_body(), http_add_header(), and http_recv_response().
http_get()
int http_get (const http_handle_t hnd, const char * query, const char * additional_headers, uint8_t * readbuffer, uint32_t readbuffer_size)
Send an HTTP GET request.
Parameters
In hnd Handle created by http_create_session().
In query HTTP query string ("/path/to/request.html"). Must beging with '/'.
In additional_headers HTTP headers (each line ending with CRLF)
In readbuffer pointer to read buffer filled with server response to GET request (with header and body).
In size size of read buffer.
Return values
Error code >=0 Success, length of the received data. HTTP_ERR (<0) Failure
References http_context_t::buffer, HTTP_ERR, http_is_open(), HTTP_OK, and msg_error.
http_is_open()
bool http_is_open (const http_handle_t hnd)
check if a connection is open.
Parameters
In hnd HTTP Handle created by http_open().
Return values
bool >0 true, connection is open. 0 False, connection is not open
check if a connection is open.
Parameters
In hnd Session handle.
Return values
true The session is open. false: The session is closed: the handle should be freed by calling http_close().
References http_context_t::connection_is_open.
http_post()
int http_post (const http_handle_t hnd, const char * query, const char * additional_headers, const uint8_t * postbuffer, uint32_t postbuffer_size, uint8_t * responsebuffer, uint32_t responsebuffer_size)
Send an HTTP POST request.
Parameters
In hnd HTTP Handle created by http_open().
In query HTTP query string ("/path/to/request.html"). Must beging with '/'.
In additional_headers HTTP headers ("name: value", each line ending with \r
)
In postbuffer pointer to data to be sent with POST request
In postbuffer_size length of data of POST request.
In responsebuffer pointer to buffer for POST response
In responsebuffer_size max size of data of POST response.
Return values
Error code >0 Success, length of the received data. HTTP_ERR (<0) Failure
References http_context_t::buffer, HTTP_ERR, http_is_open(), and msg_error.
http_put()
int http_put (const http_handle_t hnd, const char * query, const char * additional_headers, const uint8_t * putbuffer, uint32_t putbuffer_size, uint8_t * responsebuffer, uint32_t responsebuffer_size)
Send an HTTP PUT request.
Parameters
In hnd HTTP Handle created by http_open().
In resource HTTP resource string ("/path/to/resource.html"). Must beging with '/'.
In additional_headers HTTP headers (each line ending with \r
)
In putbuffer pointer to data to be sent with PUT request
In putbuffer_size length of data of PUT request.
In responsebuffer pointer to buffer for response
In responsebuffer_size max size of response.
Return values
Error code >0 Success, length of the received data. HTTP_ERR (<0) Failure
References http_context_t::buffer, HTTP_ERR, http_is_open(), and msg_error.
http_recv()
int http_recv (http_handle_t hnd, uint8_t * buffer, uint32_t length)
Receive data from server.
Parameters
In Handle Session handle
In/Out buffer buffer to receive data from server.
In length buffer size.
Return values
size of received data HTTP_OK (0) Success HTTP_ERR (<0) Failure
References HTTP_OK, msg_debug, net_sock_recv(), and http_context_t::sock.
http_recv_response()
int http_recv_response (http_handle_t hnd, uint8_t * buffer, uint32_t buffer_length)
Receive full response to a request. This loops until it has received the amount of data indicated in Content-Length: header or the supplied response buffer is full.
Parameters
In Handle
Out buffer response buffer (empty).
In buffer_length buffer size.
Return values
size of received data HTTP_OK (0) Success HTTP_ERR (<0) Failure
References http_content_length(), http_find_body(), msg_debug, net_sock_recv(), and http_context_t::sock.
http_response_status()
uint32_t http_response_status (uint8_t * http_response, uint32_t length)
Get the HTTP response status in headers.
Parameters
In buffer buffer containing headers.
In length buffer size.
Return values
Error code >0 HTTP status (200 == OK, 404 == not found, ...). HTTP_ERR (<0) Failure
Get the HTTP response status in headers.
http_response: pointer to full HTTP response
len: HTTP response length.
Return values
HTTP status code (200 = success, 404 = not found ...)
http_response_validate()
int http_response_validate (uint8_t * http_response, uint32_t length)
Validate the HTTP response.
Parameters
In buffer buffer containing headers.
In length buffer size.
Return values
Error code >0 ok. HTTP_ERR (<0) Failure
Validate the HTTP response.
http_response: pointer to full HTTP response
len: HTTP response length.
Return values
References HTTP_OK.
http_send()
int http_send (http_handle_t hnd, uint8_t * buffer, uint32_t buffer_length)
Send a request.
Parameters
In Handle handle to session created and connected.
In buffer full buffer provided by user (prepared with header and body).
In buffer buffer size.
Return values
Error code HTTP_OK (0) Success HTTP_ERR (<0) Failure
References HTTP_OK, msg_debug, net_sock_send(), and http_context_t::sock.
http_sock_setopt()
int http_sock_setopt (http_handle_t Hnd, const char * optname, const uint8_t * optbuf, size_t optlen)
Set network socket option for an HTTP session. Used mainly for TLS options ("tls_ca_certs"). Must be done after create_session() and before connect().
Parameters
In hnd Session handle.
Return values
Error code HTTP_OK (0) Success HTTP_ERR (<0) Failure
References net_sock_setopt(), and http_context_t::sock.