Sensor de vibração MQTT - Trabalho de conclusão de curso: iot_flash_config.c File Reference
iot_flash_config.c File Reference
configuration in flash memory.
#include <string.h>
#include <stdio.h>
#include <stdbool.h>
#include "main.h"
#include "rfu.h"
#include "flash.h"
#include "iot_flash_config.h"
#include "msg.h"
Macros
#define PEM_READ_LINE_SIZE 120
#define PEM_READ_BUFFER_SIZE 8192
#define TRACE_FLASH(...)
Functions
int CaptureAndFlashPem (char *pem_name, char const *flash_addr, bool restricted_area)
Ask user and write the TLS certificates and key to the Flash memory.
int getInputString (char *inputString, size_t len)
Get a line from the console (user input).
int enterPemString (char *read_buffer, size_t max_len)
Get one PEM string (ASCII format of TLS certificates and keys) from the console (user input).
int updateTLSCredentials (void)
int checkTLSRootCA ()
Check if TLS root CA certificates are present in Flash memory.
int checkTLSDeviceConfig ()
Check if the device TLS credentials (device certificate and device private key) are present in Flash memory.
int setIoTDeviceConfig (iot_config_t *config)
Store the IoT device configuration in Flash.
int getIoTDeviceConfig (const char **const name)
Get the device configuration from Flash.
int checkIoTDeviceConfig ()
Check if an IoT device configuration is present in Flash memory.
int getTLSKeys (const char **const root_ca_cert, const char **const device_cert, const char **const private_key)
Get the TLS certificates and private key addresses in the Flash memory.
Detailed Description
configuration in flash memory.
Author
MCD Application Team
Attention
© Copyright (c) 2017 STMicroelectronics International N.V. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted, provided that the following conditions are met:
Redistribution of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of STMicroelectronics nor the names of other contributors to this software may be used to endorse or promote products derived from this software without specific written permission.
This software, including modifications and/or derivative works of this software, must execute solely and exclusively on microcontroller or microprocessor devices manufactured by or for STMicroelectronics.
Redistribution and use of this software other than as permitted under this license is void and will automatically terminate your rights under this license.
THIS SOFTWARE IS PROVIDED BY STMICROELECTRONICS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS, IMPLIED OR STATUTORY WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT OF THIRD PARTY INTELLECTUAL PROPERTY RIGHTS ARE DISCLAIMED TO THE FULLEST EXTENT PERMITTED BY LAW. IN NO EVENT SHALL STMICROELECTRONICS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Macro Definition Documentation
PEM_READ_BUFFER_SIZE
#define PEM_READ_BUFFER_SIZE 8192
Max size which can be got from the terminal in a single getInputString().
Function Documentation
CaptureAndFlashPem()
int CaptureAndFlashPem (char * pem_name, char const * flash_addr, bool restricted_area)
Ask user and write the TLS certificates and key to the Flash memory.
Do not zero-initialize the static user configuration. Otherwise, it must be entered manually each time the device FW is updated by STLink.
Parameters
none
Return values
Error code 0 Success <0 Unrecoverable error
References enterPemString(), and PEM_READ_BUFFER_SIZE.
checkIoTDeviceConfig()
int checkIoTDeviceConfig ()
Check if an IoT device configuration is present in Flash memory.
Return values
0 Configuration present. -1: No configuration.
checkTLSDeviceConfig()
int checkTLSDeviceConfig ()
Check if the device TLS credentials (device certificate and device private key) are present in Flash memory.
Parameters
void
Return values
0 Configured, -1 Not configured.
checkTLSRootCA()
int checkTLSRootCA ()
Check if TLS root CA certificates are present in Flash memory.
Parameters
void
Return values
0 Configured, -1 Not configured.
enterPemString()
int enterPemString (char * read_buffer, size_t max_len)
Get one PEM string (ASCII format of TLS certificates and keys) from the console (user input).
Parameters
Out key_read_buffer Destination buffer.
In max_len Maximum length to be written to the destination buffer.
Return values
Number of characters read into the output buffer.
References getInputString().
Referenced by CaptureAndFlashPem().
getInputString()
int getInputString (char * inputString, size_t len)
Get a line from the console (user input).
Parameters
Out inputString Pointer to buffer for input line.
In len Max length for line.
Return values
Number of bytes read from the terminal.
Referenced by enterPemString().
getIoTDeviceConfig()
int getIoTDeviceConfig (const char **const name)
Get the device configuration from Flash.
Parameters
Out name Pointer to the location of the device configuration. NULL if absent.
Return values
0 Success: The device configuration is configured and returned to the caller. -1 Error: Device configuration absent.
getTLSKeys()
int getTLSKeys (const char **const root_ca_cert, const char **const device_cert, const char **const private_key)
Get the TLS certificates and private key addresses in the Flash memory.
Parameters
Out ca_cert CA certificate / trust chain (PEM format: string)
Out device_cert Device certificate (PEM format: string)
Out private_key Device private key (PEM format: string)
Return values
0 TLS credentials found, and passed back to the caller. -1: TLS credentials not found.
setIoTDeviceConfig()
int setIoTDeviceConfig (iot_config_t * config)
Store the IoT device configuration in Flash.
Parameters
In config Configuration data.
Return values
0 Success -1 Error
References FLASH_update().