Multifunction Safety Relay WEG: iot_flash_config.h File Reference
iot_flash_config.h File Reference
Header for configuration.
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
Data Structures
struct c2c_config_t
struct wifi_config_t
struct iot_config_t
struct user_config_t
Macros
#define USER_CONF_C2C_SOAPC_MAX_LENGTH 16
#define USER_CONF_C2C_USERID_MAX_LENGTH 16
#define USER_CONF_C2C_PSW_MAX_LENGTH 16
#define USER_CONF_WIFI_SSID_MAX_LENGTH 32
#define USER_CONF_WIFI_PSK_MAX_LENGTH 64
#define USER_CONF_DEVICE_NAME_LENGTH 300
#define USER_CONF_SERVER_NAME_LENGTH 128
#define USER_CONF_TLS_OBJECT_MAX_SIZE 2048
#define USER_CONF_MAGIC 0x0123456789ABCDEFuLL
#define QUICK_START_REG_NAME "QuickStart"
#define SIMPLE_REG_NAME "SimpleReg"
#define ORG_ID_KEY "OrgId"
#define DEVICE_TYPE_KEY "DeviceType"
#define DEVICE_ID_KEY "DeviceId"
#define TOKEN_KEY "Token"
#define IBM_IOT_URL "internetofthings.ibmcloud.com"
Functions
int enterPemString (char *read_buffer, size_t max_len)
Get one PEM string (ASCII format of TLS certificates and keys) from the console (user input).
int getInputString (char *inputString, size_t len)
Get a line from the console (user input).
int checkC2cCredentials (const char **const oper_ap_code, const char **const username, const char **const password, bool *use_internal_sim)
int updateC2cCredentials (void)
int checkWiFiCredentials (const char **const ssid, const char **const psk, uint8_t *const security_mode)
int updateWiFiCredentials (void)
int updateTLSCredentials (void)
int checkTLSRootCA (void)
Check if TLS root CA certificates are present in Flash memory.
int checkTLSDeviceConfig (void)
Check if the device TLS credentials (device certificate and device private key) are present in Flash memory.
int getTLSKeys (const char **const ca_cert, const char **const device_cert, const char **const private_key)
Get the TLS certificates and private key addresses in the Flash memory.
int setIoTDeviceConfig (iot_config_t *config)
Store the IoT device configuration in Flash.
int getIoTDeviceConfig (const char **const name)
Get the device configuration from Flash.
int checkIoTDeviceConfig (void)
Check if an IoT device configuration is present in Flash memory.
int updateFirmwareVersion (void)
Detailed Description
Header for configuration.
Author
MCD Application Team
Attention
© Copyright (c) 2017 STMicroelectronics International N.V. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted, provided that the following conditions are met:
Redistribution of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of STMicroelectronics nor the names of other contributors to this software may be used to endorse or promote products derived from this software without specific written permission.
This software, including modifications and/or derivative works of this software, must execute solely and exclusively on microcontroller or microprocessor devices manufactured by or for STMicroelectronics.
Redistribution and use of this software other than as permitted under this license is void and will automatically terminate your rights under this license.
THIS SOFTWARE IS PROVIDED BY STMICROELECTRONICS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS, IMPLIED OR STATUTORY WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT OF THIRD PARTY INTELLECTUAL PROPERTY RIGHTS ARE DISCLAIMED TO THE FULLEST EXTENT PERMITTED BY LAW. IN NO EVENT SHALL STMICROELECTRONICS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Macro Definition Documentation
USER_CONF_DEVICE_NAME_LENGTH
#define USER_CONF_DEVICE_NAME_LENGTH 300
Must be large enough to hold a complete connection string
Function Documentation
checkIoTDeviceConfig()
int checkIoTDeviceConfig (void)
Check if an IoT device configuration is present in Flash memory.
Return values
0 Configuration present. -1: No configuration.
References iot_config_t::magic.
checkTLSDeviceConfig()
int checkTLSDeviceConfig (void)
Check if the device TLS credentials (device certificate and device private key) are present in Flash memory.
Parameters
void
Return values
0 Configured, -1 Not configured.
References user_config_t::device_tls_magic.
checkTLSRootCA()
int checkTLSRootCA (void)
Check if TLS root CA certificates are present in Flash memory.
Parameters
void
Return values
0 Configured, -1 Not configured.
References user_config_t::ca_tls_magic.
enterPemString()
int enterPemString (char * read_buffer, size_t max_len)
Get one PEM string (ASCII format of TLS certificates and keys) from the console (user input).
Parameters
Out key_read_buffer Destination buffer.
In max_len Maximum length to be written to the destination buffer.
Return values
Number of characters read into the output buffer.
References getInputString(), and msg_error.
Referenced by CaptureAndFlashPem().
getInputString()
int getInputString (char * inputString, size_t len)
Get a line from the console (user input).
Parameters
Out inputString Pointer to buffer for input line.
In len Max length for line.
Return values
Number of bytes read from the terminal.
Referenced by enterPemString().
getIoTDeviceConfig()
int getIoTDeviceConfig (const char **const name)
Get the device configuration from Flash.
Parameters
Out name Pointer to the location of the device configuration. NULL if absent.
Return values
0 Success: The device configuration is configured and returned to the caller. -1 Error: Device configuration absent.
References iot_config_t::magic.
getTLSKeys()
int getTLSKeys (const char **const root_ca_cert, const char **const device_cert, const char **const private_key)
Get the TLS certificates and private key addresses in the Flash memory.
Parameters
Out ca_cert CA certificate / trust chain (PEM format: string)
Out device_cert Device certificate (PEM format: string)
Out private_key Device private key (PEM format: string)
Return values
0 TLS credentials found, and passed back to the caller. -1: TLS credentials not found.
References user_config_t::ca_tls_magic.
setIoTDeviceConfig()
int setIoTDeviceConfig (iot_config_t * config)
Store the IoT device configuration in Flash.
Parameters
In config Configuration data.
Return values
0 Success -1 Error
References iot_config_t::magic.