Multifunction Safety Relay WEG: net.h File Reference
net.h File Reference
Network API.
#include <stdint.h>
#include <stdlib.h>
Data Structures
struct net_macaddr_t
struct net_ipaddr_t
Macros
#define NET_OK 0
#define NET_ERR -1
#define NET_PARAM -2
#define NET_TIMEOUT -3
#define NET_EOF -4
#define NET_NOT_FOUND -5
#define NET_AUTH -6
Typedefs
typedef int32_t * net_hnd_t
typedef int32_t * net_sockhnd_t
typedef int net_if_init_t(void *if_ctxt)
Callback type: initialize the network interface and connect to the LAN.
typedef int net_if_deinit_t(void *if_ctxt)
Callback type: de-initialize the network interface.
typedef int net_if_reinit_t(void *if_ctxt)
Callback type: re-initialize the network interface.
Enumerations
enum net_if_t {
NET_IF_NONE = 0 , NET_IF_WLAN , NET_IF_ETH , NET_IF_C2C ,
NET_IF_BNEP
}
enum net_proto_t { NET_PROTO_NONE = 0 , NET_PROTO_TCP , NET_PROTO_TLS , NET_PROTO_UDP }
enum net_ip_version_t { NET_IP_V4 , NET_IP_V6 }
Functions
int net_init (net_hnd_t *nethnd, net_if_t interface, net_if_init_t *f_netinit)
Initialize a network interface..
int net_deinit (net_hnd_t nethnd, net_if_deinit_t *f_netdeinit)
De-initialize a network interface.
int net_reinit (net_hnd_t nethnd, net_if_reinit_t *f_netreinit)
Re-initialize a network interface.
int net_get_ip_address (net_hnd_t nethnd, net_ipaddr_t *ipAddress)
Retrieve the IP address from an initialized network interface.
int net_get_mac_address (net_hnd_t nethnd, net_macaddr_t *macAddress)
Retrieve the MAC address from a network interface.
int net_get_hostaddress (net_hnd_t nethnd, net_ipaddr_t *ipAddress, const char *host)
Retrieve the (an) IP address of a remote host.
int net_sock_create (net_hnd_t nethnd, net_sockhnd_t *sockhnd, net_proto_t proto)
Create a socket and attach it to a network interface.
int net_sock_open (net_sockhnd_t sockhnd, const char *hostname, int remoteport, int localport)
Open a socket and connect to the destination..
int net_sock_setopt (net_sockhnd_t sockhnd, const char *optname, const uint8_t *optbuf, size_t optlen)
Set a socket option.
int net_sock_recv (net_sockhnd_t sockhnd, uint8_t *const buf, size_t len)
Read from a socket.
int net_sock_recvfrom (net_sockhnd_t sockhnd, uint8_t *const buf, size_t len, net_ipaddr_t *remoteaddress, int *remoteport)
int net_sock_send (net_sockhnd_t sockhnd, const uint8_t *buf, size_t len)
Send through a socket.
int net_sock_sendto (net_sockhnd_t sockhnd, const uint8_t *buf, size_t len, net_ipaddr_t *remoteaddress, int remoteport)
int net_sock_close (net_sockhnd_t sockhnd)
Close a socket. Or do nothing if the socket was not open.
int net_sock_destroy (net_sockhnd_t sockhnd)
Destroy a socket.
Detailed Description
Network API.
Author
MCD Application Team
Attention
© Copyright (c) 2017 STMicroelectronics International N.V. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted, provided that the following conditions are met:
Redistribution of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of STMicroelectronics nor the names of other contributors to this software may be used to endorse or promote products derived from this software without specific written permission.
This software, including modifications and/or derivative works of this software, must execute solely and exclusively on microcontroller or microprocessor devices manufactured by or for STMicroelectronics.
Redistribution and use of this software other than as permitted under this license is void and will automatically terminate your rights under this license.
THIS SOFTWARE IS PROVIDED BY STMICROELECTRONICS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS, IMPLIED OR STATUTORY WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT OF THIRD PARTY INTELLECTUAL PROPERTY RIGHTS ARE DISCLAIMED TO THE FULLEST EXTENT PERMITTED BY LAW. IN NO EVENT SHALL STMICROELECTRONICS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Macro Definition Documentation
NET_AUTH
#define NET_AUTH -6
The remote host cound not be authentified.
NET_EOF
#define NET_EOF -4
Connection dropped during the operation.
NET_ERR
#define NET_ERR -1
Internal error
NET_NOT_FOUND
#define NET_NOT_FOUND -5
The remote host could not be reached.
NET_OK
#define NET_OK 0
Function return codes. Success
NET_PARAM
#define NET_PARAM -2
Wrong parameters, or wrong state.
NET_TIMEOUT
#define NET_TIMEOUT -3
Timeout rearched during a blocking operation.
Typedef Documentation
net_hnd_t
typedef int32_t* net_hnd_t
Network interface handle.
net_if_deinit_t
typedef int net_if_deinit_t(void *if_ctxt)
Callback type: de-initialize the network interface.
Parameters
In if_ctxt Pointer to the interface-specific native context.
Return values
The callback must return a non-zero error code in case of failure.
net_if_init_t
typedef int net_if_init_t(void *if_ctxt)
Callback type: initialize the network interface and connect to the LAN.
Parameters
In if_ctxt Pointer to the interface-specific native context.
Return values
The callback must return a non-zero error code in case of failure.
net_if_reinit_t
typedef int net_if_reinit_t(void *if_ctxt)
Callback type: re-initialize the network interface.
Parameters
In if_ctxt Pointer to the interface-specific native context.
Return values
The callback must return a non-zero error code in case of failure.
net_sockhnd_t
typedef int32_t* net_sockhnd_t
Socket handle.
Enumeration Type Documentation
net_if_t
enum net_if_t
Network interface identifier. Restriction: One interface of each type at max.
net_ip_version_t
enum net_ip_version_t
IP protocol version.
net_proto_t
enum net_proto_t
Socket protocol.
Function Documentation
net_deinit()
int net_deinit (net_hnd_t nethnd, net_if_deinit_t * f_netdeinit)
De-initialize a network interface.
Parameters
In nethnd Network interface.
In f_netdeinit Callback to a platform/application specific de-initialization of the network interface.
Return values
Status NET_OK Success. NET_PARAM State error: Some sockets are still open on this interface. NET_ERR Internal error.
References NET_ERR, NET_PARAM, and net_ctxt_s::sock_list.
net_get_hostaddress()
int net_get_hostaddress (net_hnd_t nethnd, net_ipaddr_t * ipAddress, const char * host)
Retrieve the (an) IP address of a remote host.
Parameters
In nethnd Network interface.
Out ipAddress IP address. Allocated by the caller.
Return values
Status NET_OK Success. NET_PARAM Invalid parameter. NET_ERR Internal error. NET_NOT_FOUND The remote host name could not be resolved.
References NET_ERR, and NET_PARAM.
net_get_ip_address()
int net_get_ip_address (net_hnd_t nethnd, net_ipaddr_t * ipAddress)
Retrieve the IP address from an initialized network interface.
Parameters
In nethnd Network interface.
Out ipAddress IP address. Allocated by the caller.
Return values
Status NET_OK Success. NET_PARAM State error: The interface is not initialized, or a NULL pointer is passed. NET_ERR Internal error.
References NET_ERR, and NET_PARAM.
net_get_mac_address()
int net_get_mac_address (net_hnd_t nethnd, net_macaddr_t * macAddress)
Retrieve the MAC address from a network interface.
Parameters
In nethnd Network interface.
Out macAddress MAC address. Allocated by the caller.
Return values
Status NET_OK Success. NET_PARAM Invalid parameter. NET_ERR Internal error.
References NET_ERR.
net_init()
int net_init (net_hnd_t * nethnd, net_if_t interface, net_if_init_t * f_netinit)
Initialize a network interface..
Parameters
Out nethnd Handle to the new interface.
In interface Interface identifier.
In f_netinit Callback to a platform/application specific initialization of the network interface.
Return values
Status NET_OK Success. NET_PARAM The specified interface is not supported. NET_ERR Error.
References NET_ERR, and NET_PARAM.
net_reinit()
int net_reinit (net_hnd_t nethnd, net_if_reinit_t * f_netreinit)
Re-initialize a network interface.
Parameters
In nethnd Network interface.
In f_netreinit Callback to a platform/application specific re-initialization of the network interface.
Return values
Status NET_OK Success. NET_ERR Internal error.
References NET_ERR, NET_PARAM, and net_ctxt_s::sock_list.
net_sock_close()
int net_sock_close (net_sockhnd_t sockhnd)
Close a socket. Or do nothing if the socket was not open.
Note
A closed socket may be re-configured thanks to net_sock_setopt() and re-opened.
Parameters
In sockhnd Socket.
Return values
Status NET_OK Success. NET_ERR Internal error. NET_PARAM Invalid parameter passed.
References net_sock_ctxt_s::methods, and NET_PARAM.
Referenced by http_close().
net_sock_create()
int net_sock_create (net_hnd_t nethnd, net_sockhnd_t * sockhnd, net_proto_t proto)
Create a socket and attach it to a network interface.
Parameters
In nethnd Network interface.
Out sockhnd New socket. Allocated by the caller.
In proto Socket protocol.
Return values
Status NET_OK Success. NET_ERR Internal error. NET_PARAM Protocol not supported.
Referenced by http_open().
net_sock_destroy()
int net_sock_destroy (net_sockhnd_t sockhnd)
Destroy a socket.
Parameters
In sockhnd Socket.
Return values
Status NET_OK Success. NET_ERR Internal error.
References net_sock_ctxt_s::methods, and NET_PARAM.
Referenced by http_close().
net_sock_open()
int net_sock_open (net_sockhnd_t sockhnd, const char * hostname, int remoteport, int localport)
Open a socket and connect to the destination..
Parameters
In sockhnd Socket.
In hostname Destination host. Hostname or IP address string.
In dstport Destination port.
Return values
Status NET_OK Success. NET_ERR Internal error. NET_NOT_FOUND The remote host could not be reached, or its name could not be resolved.
References net_sock_ctxt_s::methods.
Referenced by http_connect().
net_sock_recv()
int net_sock_recv (net_sockhnd_t sockhnd, uint8_t *const buf, size_t len)
Read from a socket.
Note
If the "sock_blocking" option was set, the function will not return until the requested length is received, or the "sock_read_timeout" is reached. If the "sock_noblocking" option was set, the function will return immediately up to the requested length.
Parameters
In sockhnd Socket.
Out buf Destination buffer. Allocated by the caller.
In len Length to be read.
Return values
Status >=0 Success. Number of bytes read. NET_TIMEOUT In "sock_blocking" mode, the read timeout was reached. NET_EOF The connection was closed. NET_ERR Internal error. NET_PARAM Invalid parameter passed.
References net_sock_ctxt_s::methods, and NET_PARAM.
Referenced by http_read(), http_recv(), and http_recv_response().
net_sock_send()
int net_sock_send (net_sockhnd_t sockhnd, const uint8_t * buf, size_t len)
Send through a socket.
Parameters
In sockhnd Socket.
In buf Source buffer.
In len Length to be sent.
Return values
Status >=0 Success, number of bytes written. NET_TIMEOUT In "sock_blocking" mode, the send timeout was reached. NET_EOF The connection was closed. NET_ERR Internal error. NET_PARAM Invalid parameter passed.
References net_sock_ctxt_s::methods, and NET_PARAM.
Referenced by http_read(), and http_send().
net_sock_setopt()
int net_sock_setopt (net_sockhnd_t sockhnd, const char * optname, const uint8_t * optbuf, size_t optlen)
Set a socket option.
Note
May be called before the socket is opened.
The function does not copy the option contents to the context storage: The caller must keep the data available at their passed location until the socket is closed.
Parameters
In sockhnd Socket.
In optname Option name.
In optbuf Option payload.
In optlen Option payload length. If the data is an ASCII string, the length must include the \0 termination char.
Return values
Status NET_OK Success. NET_PARAM The option is not supported, or the contents are inconsistent with the option. NET_ERR Internal error. NET_AUTH The remote host cound not be authentified. (Applicable to NET_PROTO_TLS sockets).
References NET_PARAM, and net_sock_ctxt_s::proto.
Referenced by http_sock_setopt().