################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q7.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q7.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q7.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q7.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q7.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q7.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q7.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q31.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q15.c \
../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q7.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q7.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q7.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q7.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q7.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q7.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q7.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q31.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q15.o \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q31.o 

C_DEPS += \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_opt_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q7.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q7.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q7.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q7.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q7.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q7.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q7.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q7.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q7.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q31.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q15.d \
./Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q31.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/%.o: ../Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/%.c Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32L475xx -DUSE_HAL_DRIVER '-DMBEDTLS_CONFIG_FILE=<genmqtt_mbedtls_config.h>' '-DMQTTCLIENT_PLATFORM_HEADER=paho_mqtt_platform.h' -DENABLE_IOT_INFO -DENABLE_IOT_ERROR -DENABLE_IOT_WARNING -DGENERICMQTT -DUSE_MBED_TLS -DUSE_WIFI -DARM_MATH_CM4 -D__FPU_PRESENT=1U -c -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I"D:/TCC/B-L475E-IOT01A/TCC_estudo_vibracao/Projects/B-L475E-IOT01/Applications/Cloud/GenericMQTT/SW4STM32/B-L475E-IOT01_GenericMQTT/Drivers/BSP/Components/LSM6DSL" -I"D:/TCC/B-L475E-IOT01A/STM32CubeExpansion_Cloud_CLD_GEN_V1.0.0/Projects/B-L475E-IOT01/Applications/Cloud/GenericMQTT/SW4STM32/B-L475E-IOT01_GenericMQTT/Drivers/BSP/B-L475E-IOT01/Inc" -I"D:/TCC/B-L475E-IOT01A/TCC_estudo_vibracao/Projects/B-L475E-IOT01/Applications/Cloud/GenericMQTT/SW4STM32/B-L475E-IOT01_GenericMQTT/Middlewares/STM32_MotionSP_Library/Inc" -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../Inc -I../../../../../../../Common/GenericMQTT/Inc -I../../../../../../../Common/Shared/Inc -I../../../../../../../../Middlewares/Third_Party/paho.mqtt.embedded-c/MQTTClient-C/src -I../../../../../../../../Middlewares/Third_Party/paho.mqtt.embedded-c/MQTTPacket/src -I../../../../../../../../Middlewares/Third_Party/mbedTLS/include -I../../../../../../../../Middlewares/Third_Party/cJSON -I../../../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../Drivers/BSP/Components/lps22hb -I../../../../../../../../Drivers/BSP/Components/lsm6dsl -I../../../../../../../../Drivers/BSP/Components/vl53l0x -I"D:/TCC/B-L475E-IOT01A/STM32CubeExpansion_Cloud_CLD_GEN_V1.0.0/Drivers/CMSIS/Include" -I"D:/TCC/B-L475E-IOT01A/TCC_estudo_vibracao/Projects/B-L475E-IOT01/Applications/Cloud/GenericMQTT/SW4STM32/B-L475E-IOT01_GenericMQTT/Middlewares/STM32_MotionSP_Library" -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

