var searchData=
[
  ['sau_20functions_0',['SAU Functions',['../group___c_m_s_i_s___core___s_a_u_functions.html',1,'']]],
  ['sensors_20common_20types_1',['sensors common types',['../group___s_t_microelectronics.html',1,'']]],
  ['shift_20to_20apply_20to_20retrieve_20polarity_20information_20from_20pwr_5fwakeup_5fpiny_5fxxx_20constants_2',['Shift to apply to retrieve polarity information from PWR_WAKEUP_PINy_xxx constants',['../group___p_w_r_ex___w_u_p___polarity.html',1,'']]],
  ['sine_3',['Sine',['../group__sin.html',1,'']]],
  ['sine_20cosine_20_20_20_3cbr_3e_4',['Sine Cosine   &lt;br&gt;',['../group___sin_cos.html',1,'']]],
  ['six_5fposition_5fdetection_286d_2f4d_29_5',['Six_position_detection(6D/4D)',['../group___l_s_m6_d_s_l__.html',1,'']]],
  ['spi_6',['SPI',['../group___s_p_i.html',1,'']]],
  ['spi_20baudrate_20prescaler_7',['SPI BaudRate Prescaler',['../group___s_p_i___baud_rate___prescaler.html',1,'']]],
  ['spi_20clock_20phase_8',['SPI Clock Phase',['../group___s_p_i___clock___phase.html',1,'']]],
  ['spi_20clock_20polarity_9',['SPI Clock Polarity',['../group___s_p_i___clock___polarity.html',1,'']]],
  ['spi_20crc_20calculation_10',['SPI CRC Calculation',['../group___s_p_i___c_r_c___calculation.html',1,'']]],
  ['spi_20crc_20length_11',['SPI CRC Length',['../group___s_p_i___c_r_c__length.html',1,'']]],
  ['spi_20data_20size_12',['SPI Data Size',['../group___s_p_i___data___size.html',1,'']]],
  ['spi_20direction_20mode_13',['SPI Direction Mode',['../group___s_p_i___direction.html',1,'']]],
  ['spi_20error_20code_14',['SPI Error Code',['../group___s_p_i___error___code.html',1,'']]],
  ['spi_20exported_20constants_15',['SPI Exported Constants',['../group___s_p_i___exported___constants.html',1,'']]],
  ['spi_20exported_20macros_16',['SPI Exported Macros',['../group___s_p_i___exported___macros.html',1,'']]],
  ['spi_20exported_20types_17',['SPI Exported Types',['../group___s_p_i___exported___types.html',1,'']]],
  ['spi_20fifo_20reception_20threshold_18',['SPI FIFO Reception Threshold',['../group___s_p_i___f_i_f_o__reception__threshold.html',1,'']]],
  ['spi_20flags_20definition_19',['SPI Flags Definition',['../group___s_p_i___flags__definition.html',1,'']]],
  ['spi_20interrupt_20definition_20',['SPI Interrupt Definition',['../group___s_p_i___interrupt__definition.html',1,'']]],
  ['spi_20mode_21',['SPI Mode',['../group___s_p_i___mode.html',1,'']]],
  ['spi_20msb_20lsb_20transmission_22',['SPI MSB LSB Transmission',['../group___s_p_i___m_s_b___l_s_b__transmission.html',1,'']]],
  ['spi_20nss_20pulse_20mode_23',['SPI NSS Pulse Mode',['../group___s_p_i___n_s_s_p___mode.html',1,'']]],
  ['spi_20private_20macros_24',['SPI Private Macros',['../group___s_p_i___private___macros.html',1,'']]],
  ['spi_20reception_20fifo_20status_20level_25',['SPI Reception FIFO Status Level',['../group___s_p_i__reception__fifo__status__level.html',1,'']]],
  ['spi_20slave_20select_20management_26',['SPI Slave Select Management',['../group___s_p_i___slave___select__management.html',1,'']]],
  ['spi_20ti_20mode_27',['SPI TI Mode',['../group___s_p_i___t_i__mode.html',1,'']]],
  ['spi_20transmission_20fifo_20status_20level_28',['SPI Transmission FIFO Status Level',['../group___s_p_i__transmission__fifo__status__level.html',1,'']]],
  ['spi_5fexported_5ffunctions_29',['SPI_Exported_Functions',['../group___s_p_i___exported___functions.html',1,'']]],
  ['spi_5fexported_5ffunctions_5fgroup1_30',['SPI_Exported_Functions_Group1',['../group___s_p_i___exported___functions___group1.html',1,'']]],
  ['spi_5fexported_5ffunctions_5fgroup2_31',['SPI_Exported_Functions_Group2',['../group___s_p_i___exported___functions___group2.html',1,'']]],
  ['spi_5fexported_5ffunctions_5fgroup3_32',['SPI_Exported_Functions_Group3',['../group___s_p_i___exported___functions___group3.html',1,'']]],
  ['spiex_33',['SPIEx',['../group___s_p_i_ex.html',1,'']]],
  ['spiex_5fexported_5ffunctions_34',['SPIEx_Exported_Functions',['../group___s_p_i_ex___exported___functions.html',1,'']]],
  ['spiex_5fexported_5ffunctions_5fgroup1_35',['SPIEx_Exported_Functions_Group1',['../group___s_p_i_ex___exported___functions___group1.html',1,'']]],
  ['sram2_20page_20write_20protection_20_280_20to_2031_29_36',['SRAM2 Page Write protection (0 to 31)',['../group___s_y_s_c_f_g___s_r_a_m2_w_r_p.html',1,'']]],
  ['standard_20deviation_20_20_20_20_3cbr_3e_37',['Standard deviation    &lt;br&gt;',['../group___s_t_d.html',1,'']]],
  ['status_20and_20control_20registers_38',['Status and Control Registers',['../group___c_m_s_i_s___c_o_r_e.html',1,'']]],
  ['stm32l475xx_39',['Stm32l475xx',['../group__stm32l475xx.html',1,'']]],
  ['stm32l4xx_40',['Stm32l4xx',['../group__stm32l4xx.html',1,'']]],
  ['stm32l4xx_5fhal_5fdriver_41',['STM32L4xx_HAL_Driver',['../group___s_t_m32_l4xx___h_a_l___driver.html',1,'']]],
  ['stm32l4xx_5fsystem_42',['Stm32l4xx_system',['../group__stm32l4xx__system.html',1,'']]],
  ['stm32l4xx_5fsystem_5fexported_5fconstants_43',['STM32L4xx_System_Exported_Constants',['../group___s_t_m32_l4xx___system___exported___constants.html',1,'']]],
  ['stm32l4xx_5fsystem_5fexported_5ffunctions_44',['STM32L4xx_System_Exported_Functions',['../group___s_t_m32_l4xx___system___exported___functions.html',1,'']]],
  ['stm32l4xx_5fsystem_5fexported_5fmacros_45',['STM32L4xx_System_Exported_Macros',['../group___s_t_m32_l4xx___system___exported___macros.html',1,'']]],
  ['stm32l4xx_5fsystem_5fexported_5fvariables_46',['STM32L4xx_System_Exported_Variables',['../group___s_t_m32_l4xx___system___exported___variables.html',1,'']]],
  ['stm32l4xx_5fsystem_5fincludes_47',['STM32L4xx_System_Includes',['../group___s_t_m32_l4xx___system___includes.html',1,'']]],
  ['syscfg_20exported_20constants_48',['SYSCFG Exported Constants',['../group___s_y_s_c_f_g___exported___constants.html',1,'']]],
  ['syscfg_20exported_20macros_49',['SYSCFG Exported Macros',['../group___s_y_s_c_f_g___exported___macros.html',1,'']]],
  ['syscfg_20private_20macros_50',['SYSCFG Private Macros',['../group___s_y_s_c_f_g___private___macros.html',1,'']]],
  ['system_20clock_20source_51',['System Clock Source',['../group___r_c_c___system___clock___source.html',1,'']]],
  ['system_20clock_20source_20status_52',['System Clock Source Status',['../group___r_c_c___system___clock___source___status.html',1,'']]],
  ['system_20clock_20type_53',['System Clock Type',['../group___r_c_c___system___clock___type.html',1,'']]],
  ['system_20control_20block_20_28scb_29_54',['System Control Block (SCB)',['../group___c_m_s_i_s___s_c_b.html',1,'']]],
  ['system_20controls_20not_20in_20scb_20_28scnscb_29_55',['System Controls not in SCB (SCnSCB)',['../group___c_m_s_i_s___s_cn_s_c_b.html',1,'']]],
  ['system_20tick_20timer_20_28systick_29_56',['System Tick Timer (SysTick)',['../group___c_m_s_i_s___sys_tick.html',1,'']]],
  ['systick_20functions_57',['SysTick Functions',['../group___c_m_s_i_s___core___sys_tick_functions.html',1,'']]]
];
