var searchData=
[
  ['cache_20functions_0',['Cache Functions',['../group___c_m_s_i_s___core___cache_functions.html',1,'']]],
  ['cmsis_1',['CMSIS',['../group___c_m_s_i_s.html',1,'']]],
  ['cmsis_20core_20instruction_20interface_2',['CMSIS Core Instruction Interface',['../group___c_m_s_i_s___core___instruction_interface.html',1,'']]],
  ['cmsis_20core_20register_20access_20functions_3',['CMSIS Core Register Access Functions',['../group___c_m_s_i_s___core___reg_acc_functions.html',1,'']]],
  ['cmsis_20global_20defines_4',['CMSIS Global Defines',['../group___c_m_s_i_s__glob__defs.html',1,'']]],
  ['cmsis_20simd_20intrinsics_5',['CMSIS SIMD Intrinsics',['../group___c_m_s_i_s___s_i_m_d__intrinsics.html',1,'']]],
  ['cmsis_5fdevice_6',['CMSIS_Device',['../group___c_m_s_i_s___device.html',1,'']]],
  ['complex_20conjugate_20_20_20_20_20_20_20_20_3cbr_3e_7',['Complex Conjugate        &lt;br&gt;',['../group__cmplx__conj.html',1,'']]],
  ['complex_20dot_20product_20_20_20_20_3cbr_3e_8',['Complex Dot Product    &lt;br&gt;',['../group__cmplx__dot__prod.html',1,'']]],
  ['complex_20fft_20functions_20_20_20_3cbr_3e_9',['Complex FFT Functions   &lt;br&gt;',['../group___complex_f_f_t.html',1,'']]],
  ['complex_20fft_20tables_20_20_3cbr_3e_10',['Complex FFT Tables  &lt;br&gt;',['../group___c_f_f_t___c_i_f_f_t.html',1,'']]],
  ['complex_20magnitude_20_20_20_20_3cbr_3e_11',['Complex Magnitude    &lt;br&gt;',['../group__cmplx__mag.html',1,'']]],
  ['complex_20magnitude_20squared_20_20_20_20_20_20_20_20_3cbr_3e_12',['Complex Magnitude Squared        &lt;br&gt;',['../group__cmplx__mag__squared.html',1,'']]],
  ['complex_20matrix_20multiplication_20_20_20_20_20_3cbr_3e_13',['Complex Matrix Multiplication     &lt;br&gt;',['../group___cmplx_matrix_mult.html',1,'']]],
  ['complex_2dby_2dcomplex_20multiplication_20_20_20_20_20_20_20_20_3cbr_3e_14',['Complex-by-Complex Multiplication        &lt;br&gt;',['../group___cmplx_by_cmplx_mult.html',1,'']]],
  ['complex_2dby_2dreal_20multiplication_20_20_20_20_20_20_20_20_3cbr_3e_15',['Complex-by-Real Multiplication        &lt;br&gt;',['../group___cmplx_by_real_mult.html',1,'']]],
  ['component_16',['Component',['../group___component.html',1,'']]],
  ['configuration_20functions_17',['Configuration functions',['../group___e_x_t_i___exported___functions___group1.html',1,'']]],
  ['configuration_5fsection_5ffor_5fcmsis_18',['Configuration_section_for_CMSIS',['../group___configuration__section__for___c_m_s_i_s.html',1,'']]],
  ['convert_2016_2dbit_20integer_20value_20_20_20_20_3cbr_3e_19',['Convert 16-bit Integer value    &lt;br&gt;',['../group__q15__to__x.html',1,'']]],
  ['convert_2032_2dbit_20floating_20point_20value_20_20_20_20_3cbr_3e_20',['Convert 32-bit floating point value    &lt;br&gt;',['../group__float__to__x.html',1,'']]],
  ['convert_2032_2dbit_20integer_20value_20_20_20_20_3cbr_3e_21',['Convert 32-bit Integer value    &lt;br&gt;',['../group__q31__to__x.html',1,'']]],
  ['convert_208_2dbit_20integer_20value_20_20_20_20_3cbr_3e_22',['Convert 8-bit Integer value    &lt;br&gt;',['../group__q7__to__x.html',1,'']]],
  ['convolution_20_20_20_20_3cbr_3e_23',['Convolution    &lt;br&gt;',['../group___conv.html',1,'']]],
  ['core_20debug_20registers_20_28coredebug_29_24',['Core Debug Registers (CoreDebug)',['../group___c_m_s_i_s___core_debug.html',1,'']]],
  ['core_20definitions_25',['Core Definitions',['../group___c_m_s_i_s__core__base.html',1,'']]],
  ['core_20register_20bit_20field_20macros_26',['Core register bit field macros',['../group___c_m_s_i_s__core__bitfield.html',1,'']]],
  ['correlation_20_20_20_20_3cbr_3e_27',['Correlation    &lt;br&gt;',['../group___corr.html',1,'']]],
  ['cortex_28',['CORTEX',['../group___c_o_r_t_e_x.html',1,'']]],
  ['cortex_20exported_20constants_29',['CORTEX Exported Constants',['../group___c_o_r_t_e_x___exported___constants.html',1,'']]],
  ['cortex_20exported_20functions_30',['CORTEX Exported Functions',['../group___c_o_r_t_e_x___exported___functions.html',1,'']]],
  ['cortex_20exported_20macros_31',['CORTEX Exported Macros',['../group___c_o_r_t_e_x___exported___macros.html',1,'']]],
  ['cortex_20exported_20types_32',['CORTEX Exported Types',['../group___c_o_r_t_e_x___exported___types.html',1,'']]],
  ['cortex_20preemption_20priority_20group_33',['CORTEX Preemption Priority Group',['../group___c_o_r_t_e_x___preemption___priority___group.html',1,'']]],
  ['cortex_20private_20macros_34',['CORTEX Private Macros',['../group___c_o_r_t_e_x___private___macros.html',1,'']]],
  ['cortex_20systick_20clock_20source_35',['CORTEX SysTick clock source',['../group___c_o_r_t_e_x___sys_tick__clock__source.html',1,'']]],
  ['cosine_36',['Cosine',['../group__cos.html',1,'']]]
];
